### ISSUE TITLE
Running demo on Debian errors?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/qwc2-demo-app#10]
Trying the dummy startup here on a fresh Debian testing box.
Installed yarn, and try to start, I get the following output.
As a green node/nodejs person, I do not know how to proceed.
Any hints?

richard@west/tmp/qwc2-demo-app (stable)$ yarn start
yarn start v0.18.1
$ npm run themesconfig && webpack-dev-server --progress --colors --port 8081 

> QWC2App@0.1.0 themesconfig /tmp/qwc2-demo-app
> node themesConfig.js

/tmp/qwc2-demo-app/themesConfig.js:42
    let bboxw = extent[2] - extent[0];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! QWC2App@0.1.0 themesconfig: `node themesConfig.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the QWC2App@0.1.0 themesconfig script.
npm ERR! This is most likely a problem with the QWC2App package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node themesConfig.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls QWC2App
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.8.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "themesconfig"
npm ERR! cwd /tmp/qwc2-demo-app
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/qwc2-demo-app/npm-debug.log
npm ERR! not ok code 0
error Command failed with exit code 1.

**Comment by manisandro** [comment]
I suppose you are using an older node version? Googling around adding

    use strict;

at the start of `themesConfig.js` might help?

**Comment by rduivenvoorde** [comment]
Nope :-(

/tmp/qwc2-demo-app/themesConfig.js:11
use strict;
    ^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by manisandro** [comment]
ah maybe the quotes are actually part of the syntax?

    'use strict';

**Comment by rduivenvoorde** [comment]
Apparently Node 4.6.1 which is in Debian testing is very 'old' ... :-(

Now installed Node 7.* 
via https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions and

running...

**Comment by manisandro** [comment]
ok cool
