### ISSUE TITLE
crash when getfeatureinfo returns multisurface geometry

### ISSUE THREAD

**Issue by tobias-brunner** [qgis/qwc2-demo-app#101]
The app crashes (unhandled error), when getfeatureinfo returns a multisurface geometry.

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/f04e543afc483f92b3af9c61f00c94fb4fb101b1 (and https://github.com/qgis/qwc2/commit/ea0df8a70731d1ce63a2f7a695cb729d861e1cbf).
