### ISSUE TITLE
GetLegendGraphic locales bug

### ISSUE THREAD

**Issue by novikov-alexander** [qgis/qwc2-demo-app#102]
The qwc2 app always looks for style called "default" while requesting legend but for example in russian localization of QGIS it is called "По умолчанию".

qwc2 uses this code for loading legend:

`let request = layer.legendUrl + (layer.legendUrl.indexOf('?') === -1 ? '?' : '&') + "SERVICE=WMS&REQUEST=GetLegendGraphic&VERSION=" + (layer.version || "1.3.0") + "&FORMAT=image/png&LAYER=" + sublayer.name + "&STYLE=default";`

But there should be something like:

```let request = layer.legendUrl + (layer.legendUrl.indexOf('?') === -1 ? '?' : '&') + "SERVICE=WMS&REQUEST=GetLegendGraphic&VERSION=" + (layer.version || "1.3.0") + "&FORMAT=image/png&LAYER=" + sublayer.name + "&STYLE=" + sublayer.defaultStyle;```

It is interesting that qgis server returns right info about legend url. In my case it is 
```
<LegendURL>
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://mysite.ru:42080/qgis/qgis_mapserv.fcgi.exe?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=Main_Basins&FORMAT=image/png&STYLE=По умолчанию&SLD_VERSION=1.1.0"/>
</LegendURL>
```

I can fix that if somebody expirienced prompt me how to do it

**Comment by manisandro** [comment]
Actually the `STYLE` query parameter is optional, and defaults to the default style if omitted, so I've pushed a change which just omits `STYLE` from the `GetLegendGraphic` requests.

**Comment by novikov-alexander** [comment]
@manisandro thank you!
