### ISSUE TITLE
Is there any way to identify feature with many relationships?

### ISSUE THREAD

**Issue by novikov-alexander** [qgis/qwc2-demo-app#103]
It would be great to have an opportunity to be able to watch connected tables in one-to-many relationships. Something like forms in Identity tool

**Comment by manisandro** [comment]
Unless it is something that can be set up at QGIS project level in such way that WMS GetFeatureInfo delivers the expected response, you'll need to write a custom service and a custom client-side component to handle this.

**Comment by novikov-alexander** [comment]
@manisandro , are you sure that qgis server handles it?
I've tried both qgis 2.18 and 3.0.3.
In the first case after adding a relationship a corresponding form appered in the desktop app but GetFeatureInfo returns me nothing about joined table. 
In the second case a corresponding form didn't even appear in the desktop app.

What I'm doing wrong?

**Comment by manisandro** [comment]
I have no idea whether QGIS Server handles this, you should probably ask on the QGIS users list.

**Comment by andreasneumann** [comment]
No - it is not supported in QGIS server yet
It also should be discussed how this should be best handled.
I agree that it would be a very nice (and needed) feature to have in a web client

**Comment by novikov-alexander** [comment]
@andreasneumann thank you for your answer.
How could I follow a discussion?

**Comment by manisandro** [comment]
Server-side issue.

**Comment by lperozzi** [comment]
I can use `FeatureForm` for many to many relations?

**Comment by manisandro** [comment]
No, just key-value relations and 1:N relations are supported at this time.

**Comment by lperozzi** [comment]
Ok, I understand many thanks

**Comment by lperozzi** [comment]
Still exploring `FeatureForm` I have a question. When I have a `Drag and Drop designer` form which is used in a 1:N relation, the `form.ui` is well generated, but it seems not to be used in the QWC2 `FeatureForm` (see image below for clarity). I've added both layers as data resources and given public (read only) permissions.

![image](https://github.com/qgis/qwc2-demo-app/assets/6198369/a51a9deb-c79d-494a-86f2-4882427d3754)

**Comment by manisandro** [comment]
Looks correct to me, resp. the table view is currently the expected result for 1:N relations.

**Comment by lperozzi** [comment]
That means that is not possible to customize the fields in the Points tab (i.e. the Points.ui form is not taken into account)?

**Comment by manisandro** [comment]
Currently it is only possible if you provide a custom designer form and provide a custom `nrel` widget, see https://qwc-services.github.io/topics/Editing/

**Comment by lperozzi** [comment]
OK, understood. Thanks for your help, will test this way

**Comment by lperozzi** [comment]
If I understand well from https://qwc-services.github.io/topics/Editing/, I should create a custom designer form 
with a `QGroupBox` widgets which the `ObjectName` is `nrel__Relation_test__k_Afr` and each field are named `Relation_test__<fieldname>` ?

![image](https://github.com/qgis/qwc2-demo-app/assets/6198369/dac72fde-c264-4886-b8c5-f007570a20ab)

**Comment by manisandro** [comment]
Yes that sounds right.
