### ISSUE TITLE
How to access the map object?

### ISSUE THREAD

**Issue by madalinul** [qgis/qwc2-demo-app#106]
So I have an application that is built on Openlayers 3 and I would like to add it to the qwc2 demo. Because it's an older app it needs the map object to work, but I can't figure out how to get it.
Can you point me in the right direction?

**Comment by manisandro** [comment]
You'll need to implement a map plugin, for example [1], and register it in js/appConfig.js. Such plugins will then receive the ol map object as a prop.

[1] https://github.com/qgis/qwc2/blob/master/QWC2Components/plugins/map/RedliningSupport.jsx

**Comment by madalinul** [comment]
I think this should do it. Thanks for the help!

**Comment by manisandro** [comment]
Welcome!
