### ISSUE TITLE
Layer not showing in map -> ServiceException code="LayerNotDefined">

### ISSUE THREAD

**Issue by sebner19** [qgis/qwc2-demo-app#108]
Hello,
it seems that the qgis web client has problems with some data while working just fine with other.
A few days ago I created some test data (a quick and dirty point layer with some european cities) which works just fine in the web client. But creating a new project and using a one year old shapefile (with japanese cities - once again a point layer) fails.
I'm testing everything locally (xampp, qgis server). The strange thing though is that both my test cases work fine when using them in QGIS via WMS.
My minimalistic themesConfig looks like this:
```
{
  "themes": {
    "items": [
      {
        "url": "http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=Ecities.qgz",
        "attribution": "Europe cities",
        "default": true,
        "backgroundLayers": [
          {
            "name": "mapnik",
            "printLayer": "osm_farbig",
            "visibility": true
          }
        ],
        "mapCrs": "EPSG:3857"
      },
      {
        "url": "http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=Jcities.qgz",
        "attribution": "Japan cities",
        "backgroundLayers": [
          {
            "name": "mapnik",
            "visibility": true
          },
          {
            "name": "opentopomap"
          }
        ],
        "mapCrs": "EPSG:4326"
      }
    ],
    "backgroundLayers": [
      {
        "name": "mapnik",
        "title": "Open Street Map",
        "type": "osm",
        "source": "osm",
        "thumbnail": "mapnik.jpg",
        "attribution": "OpenStreetMap contributors",
        "attributionUrl": "https://www.openstreetmap.org/copyright"
      }
    ]
  },
  "defaultScales": [8000000, 4000000, 2000000, 1000000, 400000, 200000, 80000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000, 500, 250, 100],
  "defaultPrintGrid": [{"s": 10000, "x": 1000, "y": 1000}, {"s": 1000, "x": 100, "y": 100}, {"s": 100, "x": 10, "y": 10}],
  "defaultWMSVersion":"1.3.0"
}
```

Looking at the first map (cities in Europe) works just fine but the Japan map won't work. It shows me the country but not the layer on the map (it shows up on the legend though). Debugging the website shows 
`qgis_mapserv.fcgi.exe:1 GET http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=jcities&STYLES=&SRS=EPSG%3A4326&CRS=EPSG%3A4326&TILED=false&DPI=96&OPACITIES=255&WIDTH=1366&HEIGHT=975&BBOX=31.394545139397014%2C129.5185600293814%2C40.674424330214684%2C142.51990872133726 400 (Bad Request)`

Opening the path tells me that it can't find the layer which contains the points.
```
(<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
<ServiceException code="LayerNotDefined">Layer "jcities" does not exist</ServiceException>
</ServiceExceptionReport>)
```
Has anyone an idea? From my point of view there has to be something wrong with either the shapefile or the qgis project file. As far as I can tell the settings are exactly the same though.

PS.: I added the files in question as zip archive.

[QGIS.zip](https://github.com/qgis/qwc2-demo-app/files/2216094/QGIS.zip)

Edit: Added Server request XML files.

Ecities (working without a problem):
`<WMS_Capabilities xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd http://www.qgis.org/wms http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&SERVICE=WMS&REQUEST=GetSchemaExtension" version="1.3.0"><Service><Name>WMS</Name><Title>European Cities</Title><KeywordList><Keyword vocabulary="ISO">infoMapAccessService</Keyword></KeywordList><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz"/><Fees>conditions unknown</Fees><AccessConstraints>None</AccessConstraints></Service><Capability><Request><GetCapabilities><Format>text/xml</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&"/></Get></HTTP></DCPType></GetCapabilities><GetMap><Format>image/jpeg</Format><Format>image/png</Format><Format>image/png; mode=16bit</Format><Format>image/png; mode=8bit</Format><Format>image/png; mode=1bit</Format><Format>application/dxf</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&"/></Get></HTTP></DCPType></GetMap><GetFeatureInfo><Format>text/plain</Format><Format>text/html</Format><Format>text/xml</Format><Format>application/vnd.ogc.gml</Format><Format>application/vnd.ogc.gml/3.1.1</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&"/></Get></HTTP></DCPType></GetFeatureInfo><sld:GetLegendGraphic><Format>image/jpeg</Format><Format>image/png</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&"/></Get></HTTP></DCPType></sld:GetLegendGraphic><sld:DescribeLayer><Format>text/xml</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&"/></Get></HTTP></DCPType></sld:DescribeLayer><qgs:GetStyles><Format>text/xml</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&"/></Get></HTTP></DCPType></qgs:GetStyles></Request><Exception><Format>XML</Format></Exception><sld:UserDefinedSymbolization UserLayer="0" SupportSLD="1" RemoteWFS="0" UserStyle="1" InlineFeature="0" RemoteWCS="0"/><Layer><Name>Ecities</Name><KeywordList><Keyword vocabulary="ISO">infoMapAccessService</Keyword></KeywordList><CRS>CRS:84</CRS><CRS>EPSG:3857</CRS><EX_GeographicBoundingBox><westBoundLongitude>4.83073</westBoundLongitude><eastBoundLongitude>24.4284</eastBoundLongitude><southBoundLatitude>42.8681</southBoundLatitude><northBoundLatitude>50.9184</northBoundLatitude></EX_GeographicBoundingBox><BoundingBox miny="5.29192e+6" CRS="EPSG:3857" maxx="2.71936e+6" maxy="6.60688e+6" minx="537754"/><Layer queryable="1"><Name>Cities</Name><Title>Cities</Title><CRS>CRS:84</CRS><CRS>EPSG:3857</CRS><EX_GeographicBoundingBox><westBoundLongitude>9.12881</westBoundLongitude><eastBoundLongitude>17.0892</eastBoundLongitude><southBoundLatitude>45.4399</southBoundLatitude><northBoundLatitude>50.0905</northBoundLatitude></EX_GeographicBoundingBox><BoundingBox miny="5.69104e+6" CRS="EPSG:3857" maxx="1.90236e+6" maxy="6.46196e+6" minx="1.01621e+6"/><Style><Name>default</Name><Title>default</Title><LegendURL><Format>image/png</Format><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Ecities.qgz&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=Cities&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0"/></LegendURL></Style></Layer></Layer></Capability></WMS_Capabilities>`

Jcities:
`<WMS_Capabilities version="1.3.0" xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd http://www.qgis.org/wms http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&SERVICE=WMS&REQUEST=GetSchemaExtension"><Service><Name>WMS</Name><Title>Japan Cities</Title><KeywordList><Keyword vocabulary="ISO">infoMapAccessService</Keyword></KeywordList><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz"/><Fees>conditions unknown</Fees><AccessConstraints>None</AccessConstraints></Service><Capability><Request><GetCapabilities><Format>text/xml</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&"/></Get></HTTP></DCPType></GetCapabilities><GetMap><Format>image/jpeg</Format><Format>image/png</Format><Format>image/png; mode=16bit</Format><Format>image/png; mode=8bit</Format><Format>image/png; mode=1bit</Format><Format>application/dxf</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&"/></Get></HTTP></DCPType></GetMap><GetFeatureInfo><Format>text/plain</Format><Format>text/html</Format><Format>text/xml</Format><Format>application/vnd.ogc.gml</Format><Format>application/vnd.ogc.gml/3.1.1</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&"/></Get></HTTP></DCPType></GetFeatureInfo><sld:GetLegendGraphic><Format>image/jpeg</Format><Format>image/png</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&"/></Get></HTTP></DCPType></sld:GetLegendGraphic><sld:DescribeLayer><Format>text/xml</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&"/></Get></HTTP></DCPType></sld:DescribeLayer><qgs:GetStyles><Format>text/xml</Format><DCPType><HTTP><Get><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&"/></Get></HTTP></DCPType></qgs:GetStyles></Request><Exception><Format>XML</Format></Exception><sld:UserDefinedSymbolization RemoteWFS="0" RemoteWCS="0" UserLayer="0" UserStyle="1" InlineFeature="0" SupportSLD="1"/><Layer><Name>Jcities</Name><KeywordList><Keyword vocabulary="ISO">infoMapAccessService</Keyword></KeywordList><CRS>CRS:84</CRS><CRS>EPSG:4326</CRS><EX_GeographicBoundingBox><westBoundLongitude>129.631</westBoundLongitude><eastBoundLongitude>139.978</eastBoundLongitude><southBoundLatitude>31.5449</southBoundLatitude><northBoundLatitude>37.7816</northBoundLatitude></EX_GeographicBoundingBox><BoundingBox maxy="139.978" miny="129.631" minx="31.5449" CRS="EPSG:4326" maxx="37.7816"/><Layer queryable="1"><Name>jcities</Name><Title>jcities</Title><CRS>CRS:84</CRS><CRS>EPSG:4326</CRS><EX_GeographicBoundingBox><westBoundLongitude>129.878</westBoundLongitude><eastBoundLongitude>139.732</eastBoundLongitude><southBoundLatitude>32.6066</southBoundLatitude><northBoundLatitude>36.7199</northBoundLatitude></EX_GeographicBoundingBox><BoundingBox maxy="139.732" miny="129.878" minx="32.6066" CRS="EPSG:4326" maxx="36.7199"/><Style><Name>default</Name><Title>default</Title><LegendURL><Format>image/png</Format><OnlineResource xlink:type="simple" xlink:href="http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?map=Jcities.qgz&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=jcities&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0"/></LegendURL></Style></Layer></Layer></Capability></WMS_Capabilities>`

**Comment by hbruch** [comment]
Running into the same issue here. However, is this really a qwc2 issue, if the server responds with LayerNotDefined? What is the version of your qgis-server?

**Comment by hbruch** [comment]
In my case, the undefined Layer was caused by an exceeded postgres connection pool. Is there any hint in your QGIS_SERVER_LOGFILE? Or the QGIS_DEBUG_FILE? To get more clues you might need to compile qgis with QGISDEBUG flag.

**Comment by sebner19** [comment]
Hi, sorry for the late answer.

the server logfile doesn't reveal anything as far as I can see. Any idea why the exceeded postgres connection pool? Two simple point layers, same project settings, very weird.

[qgislog.txt](https://github.com/qgis/qwc2-demo-app/files/2460625/qgislog.txt)

**Comment by manisandro** [comment]
Yes, this is not related to QWC.
