### ISSUE TITLE
CoordinateDisplayer changing from toFixed(digits)  to  toLocaleFixed(number, digits)

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#109]
@manisandro  is there any reason for this change? 
because we use EPSG:3844 and the coordinates are like  400396.54 452280.21
now they are displayed 400.396,54 452.280,21 in the bottom bar and also in context menu.
If we want to copy them and use in others places, even in search coordinates we have to change them.
I changed the locale settings but did not look good in any one.

**Comment by tudorbarascu** [comment]
If using the ``en`` locale instead of ``ro`` it's still not good with ``400,396.54`` (notice the thousands separator).

**Comment by manisandro** [comment]
I've added a `localeAwareNumbers` setting to `config.json`. Default is `false`.

**Comment by luciman** [comment]
Thank you!
