### ISSUE TITLE
Print panel: Scale and Resolution widget should be a combobox

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#11]
It would be more user friendly if the widgets for scale and resolution would be comboboxes.

The scale should have the same values as the combobox in the bottom bar - if possible with the ability to override the scale.

The resolution should be configurable in a global option, perhaps with 96, 150, 300 (default), 600 as built-in default values.

**Comment by karl-magnus** [comment]
I think it's important to have more options for scale when printing compared to the main map. In the main map you want to resrict the number of scales so tiled maps won't have to render in too many scales and not having too many steps in the zoom tools. When you print you have demands for a specific scale for certain products and it's also important for the users to fit an area into the print composer as big as possible.

**Comment by andreasneumann** [comment]
Good point. Makes sense to have separate scale value lists for screen vs. print.

**Comment by manisandro** [comment]
Combobox for scales is implemented in qgis/qwc2@fbfd8323a6ed13a34cb6b210620e762cbb60d3b9. Similar could be done for resolutions.

**Comment by andreasneumann** [comment]
Sounds fine.

**Comment by manisandro** [comment]
Combobox for resolutions implemented in qgis/qwc2@6f63419
