### ISSUE TITLE
Mapbox Vector Tiles as Background Layer

### ISSUE THREAD

**Issue by Benni5K** [qgis/qwc2-demo-app#110]
Is mapbox vector tiles supported as a source for background maps? Case it is, an example for themesConfig.json would be helpful. Thanks a lot!

**Comment by Benni5K** [comment]
Thanks @manisandro. I looked around a bit at [MapStore2](https://github.com/geosolutions-it/MapStore2). There's actually a layer type 'tileprovider' (see [doc](https://dev.mapstore2.geo-solutions.it/mapstore/docs/maps-configuration) wich supports several types of tile maps, even MapBox. But I was a bit unprecice in my initial question, what I want to do is using a XYZ vector source (pbf) with MapBox GL Style. Unfortunately it seems that's not supportet by MapStore2. I will come back to this in case we put some dev effort into this.

**Comment by pka** [comment]
MVT support should be relatively easy. MapBox GL Styles can be converted to OL styling with https://github.com/boundlessgeo/ol-mapbox-style
