### ISSUE TITLE
Layers caching

### ISSUE THREAD

**Issue by novikov-alexander** [qgis/qwc2-demo-app#111]
I've found that qgiscloud.com loads all layers on site load. 
When I reopen a layer it is loaded immedeately from the cache.
How can I achive the same behaviour in my own project?

**Comment by manisandro** [comment]
Are you using `tiled: true`?

**Comment by novikov-alexander** [comment]
@manisandro I didn't used this option but I just enabled it. An image appears by parts not simultaniously.
Is it right behaviour?

**Comment by manisandro** [comment]
Yeah, that's what tiled does. Plus side of tiled is that tiles can be cached, but downside is that you see them appearing.

**Comment by novikov-alexander** [comment]
@manisandro 
I tried to check/uncheck layer several times. Each time tiles was reloaded from server. 
My browser is Chrome. Cache is enabled. What the problem could be?
![image](https://user-images.githubusercontent.com/8073853/45673613-d5d48100-bb33-11e8-9f40-bfe9045e9ab1.png)

**Comment by novikov-alexander** [comment]
@manisandro 
Meanwhile a background is loaded from cache.
![image](https://user-images.githubusercontent.com/8073853/45673899-8b9fcf80-bb34-11e8-8cf1-3eeb61626eda.png)

**Comment by novikov-alexander** [comment]
I don't know why but after upgrading on the latest master branch tiles loading works very quick 👍 
So, the issue may be closed.
