### ISSUE TITLE
Initially show theme/bounding box configurable?

### ISSUE THREAD

**Issue by hbruch** [qgis/qwc2-demo-app#113]
Is the initially shown theme / bounding box configurable, and if yes, how? I looked into config.json, themesconfig.json and js/appConfig.json but could not find any settings for this.

And is there a qwc2 forum where I should post such questions instead of opening an issue?

**Comment by andreasneumann** [comment]
There is a mailing list: see the last entry at https://www.qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists 

Documentation is found at https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md  - see "extent" parameter next to "mapCrs"
