### ISSUE TITLE
getfeature info window should be horizontally scrollable

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#115]
Currently if there is a "remarks" field with enough text.. the user cannot see the remarks unless the window is enlarged which is cumbersome on small screens.

**Comment by manisandro** [comment]
Hmm, you can't really have both the current text-overflow handling in the attributes table and horizontal scrolling - the result would be that you'd always have to scroll and that text-overflow handling never comes into play.

**Comment by tudorbarascu** [comment]
Indeed. This is solved anyway by using ``"longAttributesDisplay": "wrap",``. Thank you.
