### ISSUE TITLE
Make BottomBar configurable

### ISSUE THREAD

**Issue by bstroebl** [qgis/qwc2-demo-app#116]
The BottomBar should be as configurable as the top bar, because not all tools are useful for all cases. Furthermore on mobile devices there is currently no bottom bar possible at all because tools to the right are not visible.
A good addon would be a bottom_logo.

**Comment by manisandro** [comment]
> Furthermore on mobile devices there is currently no bottom bar possible at all because tools to the right are not visible.

Can you clarify what you mean with this?

**Comment by manisandro** [comment]
The bottombar is configuarble to the extent that the coordinate and scale elements can be disabled, see [1].

To further customize the bottombar, it makes more sense to write a custom bottombar component.

[1] https://github.com/qgis/qwc2-demo-app/blob/218c210e04d1e59afd4d7e61d21f2e288a63e602/config.json#L146
