### ISSUE TITLE
Locate feature by search string, layer dropdown and field dropdown

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#117]
Similar to the Search Layers plugin, a way to type in a search string, choose a search layer from a dropdown list and then choose a search field.  Or, a way to specify in themes.json which layers/fields in the current theme are allowed to be searched, and use the existing QWC2 search bar.  Ideally the search would work off of shapefiles in the QGIS Server project.

![clipboard01](https://user-images.githubusercontent.com/3105035/47155938-3f3be100-d2e6-11e8-8dd6-074a654734ba.png)

![clipboard02](https://user-images.githubusercontent.com/3105035/47156532-9bebcb80-d2e7-11e8-9f37-ea16c97f9b1f.png)

**Comment by manisandro** [comment]
Admittedly undocumented, but you can already specify fields in the search provider entry in `SearchProviders.js`, example:

    module.exports = {
        "address": {
            label: "Address",
            fields: [{
                id: "loc",
                label: "Locality",
                wildcard: true
            }, {
                id: "str",
                label: "Street",
                wildcard: true
            }, {
                id: "nr",
                label: "Number",
                wildcard: false
            }],
            onSearch: addressSearch
        }
    };

at which QWC will show a corresponding complex search form with the specified fields.

If you want to make the fields configured via themes.json, you can use a searchProviderFactory:

    module.exports = {
        searchProviderFactory: (cfg) => {
            if(!cfg.key) {
                return null;
            }
            return {
                label: cfg.label,
                fields: cfg.fields,
                onSearch: (text, requestId, searchOptions, dispatch) => search(cfg.key, text, requestId, searchOptions, dispatch, cfg)
            };
        }
    };

where `cfg` is an entry in the `searchProviders` array in `themesConfig.json`, i.e.

    "searchProviders": [
        {
            "key": "address",
            "label": "Address",
            "fields": [
                <as above>
            ]
        },
        ...
    ]

You could also add a `layer` field to the `cfg` to specify which layer the search provider should search, and possibly have multiple entries in `searchProviders`, one for each layer. If you then have `showProviderSelection: true` in `config.json`, you will see a search provider selection menu next to the search field, from which you can choose which configuration to use.

You are free to add any other information to `cfg` as you require, if you then pass it to the `search` function, which you can implement according to your needs, you can alter the search behavior according to whatever information you add to `cfg`.

I think this should cover all the points you have raised.

**Comment by catalinmiraute** [comment]
Hello Mani, I am new in using QWC2 and I am not a technical person.
I have succeeded to setup a project and now I am trying to understand how to adapt function layersearch.
Can you help me?

**Comment by manisandro** [comment]
You'll need to be more specific what you mean by adapt.

**Comment by catalinmiraute** [comment]
I am trying to implement a search into the layers of may project.

**Comment by catalinmiraute** [comment]
For example, I have a layer of streets and I want to search using the name of the street.

**Comment by manisandro** [comment]
This sounds more like a feature search than a layer search. Basically as indicated in my reply above, you'll probably want a server side component actually peforms the search on your dataset. I'm afraid you'll need some technical knowhow for this, it also depends on the format of your data etc so there is no off-the-shelf solution.

**Comment by catalinmiraute** [comment]
Ok, the data o my map project are ina MS SQL DB.
From your reply I understand that I need to develop a server side service ?

**Comment by manisandro** [comment]
Yes

**Comment by catalinmiraute** [comment]
The CSV export form Identify does not get also the WKT of geometry?

**Comment by manisandro** [comment]
If the featureinfo response in QGIS Server is configured to return also the geometry, it should yes. But please don't post unrelated questions in tickets, use the mailing list instead for general questions.

**Comment by catalinmiraute** [comment]
I found this https://github.com/qgis/qwc2-demo-app/issues/171
I am interested to make the search looking through the layers contained by the themes.json loaded by the client.

**Comment by catalinmiraute** [comment]
> featureinfo response in QGIS Server

It is configured to return the geom:
<GetFeatureInfo>
<Format>text/plain</Format>
<Format>text/html</Format>
<Format>text/xml</Format>
<Format>application/vnd.ogc.gml</Format>
<Format>application/vnd.ogc.gml/3.1.1</Format>
<Format>application/json</Format>
<Format>application/geo+json</Format>

**Comment by catalinmiraute** [comment]
Solved.

**Comment by carlosluissb** [comment]
> Solved.

Hi, I need to do the same thing you posed, look for information within fields of a layer. Could you give me some advice on how you did it?
