### ISSUE TITLE
Sublayer order corrupted after reload/permant url restore

### ISSUE THREAD

**Issue by hbruch** [qgis/qwc2-demo-app#118]
When I reload the qwc2 client in the browser, the order of sublayers is corrupted. The formerly selected sublayer appears separated from the remaining layers:

* Grouplayer
  * Sublayer A
* Another Layer
* Grouplayer
  * Sublayer B
  * Sublayer C

Though the sublayers should be mutually exclusive, Sublayer A and B are selected and as A has higher precedence, B and C are hidden unless the first Grouplayer is deselected.

EDIT: Worked around this issue by setting allowReorderingLayers=false as LayerUtils.restoreReorderedVisibleLayers splits layer groups to sort all selected layers before unselected ones (resulting in additional selection of a mutually exclusive layergroup).
I think sublayers should only be able to reordered inside their layer group (at least if it is mutually exclusive).

**Comment by manisandro** [comment]
This should be resolved as now all layers are listed in the URL.
