### ISSUE TITLE
Print request: needs to send GRID_INTERVAL parameters

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#12]
QGIS server has a GRID_INTERVAL_X, GRID_INTERVAL_Y parameter that needs to be sent along with the GetPrint Request.

QGIS web client I had a hard coded mapping of scale to GRID_INTERVAL - see https://github.com/qgis/QGIS-Web-Client/blob/master/site/js/QGISExtensions.js#L370

Here the GRID_INTERVAL_X/Y is concatenated in the URL:
https://github.com/qgis/QGIS-Web-Client/blob/master/site/js/QGISExtensions.js#L443

Obviously, this hard-coded way is not very elegant. Perhaps the grid interval could be calculated from the map width/height - or, we could have an associative array in themesConfig.json, where one can specify the interval along with the scales in the setting "defaultScales".

To be discussed.

**Comment by manisandro** [comment]
The gridIntervals along with defaultScales would be a feasible option. Shall I implement that approach?

**Comment by andreasneumann** [comment]
fine with me. Thanks.

**Comment by manisandro** [comment]
Implemented in qgis/qwc2@6bb4a94
