### ISSUE TITLE
tiled WMS Background Layer

### ISSUE THREAD

**Issue by stephaschu** [qgis/qwc2-demo-app#123]
When using "tiled": true in themesConfig.json for WMS Backgroundlayers an error is thrown: 
`Uncaught TypeError: Cannot read property 'bounds' of undefined`

The error leads to this line:
https://github.com/qgis/qwc2/blob/5079576768e8a642397dc5957248c03a9e4d7c10/MapStore2Components/components/map/openlayers/plugins/WMSLayer.js#L58

This could be fixed in themesConfig.json if a bbox is added to the Backgroundlayer.
`"boundingBox": {"bounds": [...], "crs": "EPSG:25832"}`

But i'm not sure if this should be done this way.

**Comment by manisandro** [comment]
For the moment looks like the best solution. Possibly though I need to have another look at the tile grid thing because of https://github.com/qgis/qwc2-demo-app/issues/122

**Comment by manisandro** [comment]
Looking into it again, I see no better solution. But I made the code fall-back gracefully to non-tiled WMS in these cases: https://github.com/qgis/qwc2/commit/43fa2c25da285bf0b94f8d31f2fbb4e9c0c2ac63
