### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by UserGis** [qgis/qwc2-demo-app#124]
Hi, I am trying to install this on Windows. I install node and npm. When I run **yarn start**, i get this message 
_```
C:\Apache24\apache\www\qwc2-demo-app-master>yarn start
yarn run v1.12.3
$ npm run tsupdate && npm run themesconfig && npm run iconfont && webpack-dev-server --pro
gress --colors --host 0.0.0.0 --port 8081

> QWC2App@0.3.0 tsupdate C:\Apache24\apache\www\qwc2-demo-app-master
> node qwc2/scripts/updateTranslations.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Apache24\apache\www\qwc2-demo-app-master\qwc2\scripts\update
Translations.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QWC2App@0.3.0 tsupdate: `node qwc2/scripts/updateTranslations.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the QWC2App@0.3.0 tsupdate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging outpu
t above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-15T11_12_44_39
5Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```_

**Comment by manisandro** [comment]
Looks like you didn't do a recursive clone (i.e. qwc2 folder is likely empty).
