### ISSUE TITLE
Editing problem

### ISSUE THREAD

**Issue by Abelon38** [qgis/qwc2-demo-app#125]
Hi! 

First of all thank you for a wonderful webmap! I am new to QWC2 and I am having problems with the Editing plugin. I am getting this error when saving after created a polygon: 

Add to layer redigera:
EditingInterface.js:19 {type: "Feature", id: "079bd7d4-b2c4-4c57-b06b-956a5f4f0e29", geometry: {…}, properties: {…}}

It seams that something is meesing in EditingInterface.js I guess this js field show remain as it is, or..?
I cannot pick and edit a layer neither..

Does anyone have an idea of what is go8ing wrong?

Thanks and best regards!
Abel

**Comment by manisandro** [comment]
The EditingInterface in the demo-app ist just a stub which you need to properly implement depending on whatever editing backend you want to use, see

https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#implementing-the-editing-interface-in-jseditinginterfacejs

**Comment by manisandro** [comment]
Again, the `js/EditingInterface.js` is just a skeleton showing the interface, you need to implement the actual logic your self depending on your backend. It really depends what backend you have for updating your datasets what a working example looks like. (A backend could for instance be a REST service which accepts GeoJSON geometries and writes them to the database).

**Comment by Abelon38** [comment]
Hi! 

My layer looks like this:
{
  "punto": {
   "layerName": "punto",
    "geomType": "Point",
        "fields": [
             {
              "id": "id",
               "name": "id",
                "type": "number",
                "constraints": {
                "required": true
              }
              },{
                "id": "namn",
                "name": "namn",
                "type": "text",
                "constraints": {
                "readOnly": false
              }
            }
        ]
    }
      
}
My js/EditingInterface.js for adding a new object looks like this: 

function addFeature(layerId, layerName, geomType, feature, mapCrs) {
    console.log("Add to layer " + layerId + layerName + geomType + ":");
    console.log(feature);
    let success = false;
    let errorMsg = "Commit failed";
    setTimeout(() => callback(success, errorMsg), 500);
}

This is a simple point layer with 2 attributs only. Can you say what it may be wrong? I
Thanks for your time. 

BR/
Abel

**Comment by manisandro** [comment]
Did you even read my reply?

**The js/EditingInterface.js is just a skeleton showing the interface, you need to implement the actual logic your self depending on your backend.**

**Comment by Abelon38** [comment]
Yes I did and that is what I am doing, but without a good descrption is very difficult to archive. The documentation doesnt say much if there is not a working example where people can see.. Thanks anyway!

BR/Abel

**Comment by manisandro** [comment]
Since the method used to write edit changes to the data is application specific, there is not much that can be documented beyond the interface. Again, it really depends on how you handle edit operations in your backend.

**Comment by Abelon38** [comment]
Hi Sandro!

I still dont understand what do mean with backend? QWC only has a frontend,
or do I am missing something? Sorry, but I am till fighting with
configuration and learning on QWC.

Thanks for your time!

BR
Abel

Den tors 22 nov. 2018 kl 15:34 skrev Sandro Mani <notifications@github.com>:

**Comment by andreasneumann** [comment]
Hi Abel,

Yes, QWC2 is a frontend. The fact that almost every GDI is slightly different, led to the decision not to provide a serverside part for editing in QWC2. You need to implement a counterpart on your GDI/server infrastructure, if you want to use editing in QWC2. Currently, as I understand it, you would have to implement a serverside counterpart that can write back GeoJSON to your data sources (often a database).

So, when editing, QWC2 sends back GeoJSON to the serverside part you would have to implement.

Greetings,
Andreas

**Comment by Abelon38** [comment]
Thanks Sandro!

Is there a guide on how to implement that? I really dont have an idea on
how to proceed from here.

Thanks a lot for your time!
 /Abel

Den fre 23 nov. 2018 kl 07:51 skrev Andreas Neumann <
notifications@github.com>:
