### ISSUE TITLE
Please provide rovide the .qgs of the demos to help trace out  display problems

### ISSUE THREAD

**Issue by g-vidal** [qgis/qwc2-demo-app#127]
Hi all,
many thanks for the recent huge work on v3 and on the whole software.
In some cases it is difficult to trace out why  the display in qwc2 isnot what the user expect to be. Some problems may arise from the parameters and configuration expressed in the .qgs. Would it be possible in the doc to have the qgs file used to build the qwc2 app of the demo to facilitate investigations.
It seems also that more parameters than those listed in the doc and used in the demo are available would it be possible to have a more complete reference or explain howto introduce extra parameters properly.

**Comment by groschialeux** [comment]
I would like that too.  The map tips are not working in my map and after a week I still haven't been able to figure out why.  They work in the QGIS Demo Map.  If the project was file was available I could probably fix my issue in just a few minutes.

**Comment by manisandro** [comment]
So the problem here is having a decent stand-alone project (meaning, which does not pull data from a database) and which can be redistributed.

**Comment by groschialeux** [comment]
I created my site and modified the sample themesConfig.json file to replace one of the demo maps with my own wms but I kept the 3 maps in the dev test section.

When I click somewhere in the QGIS Demo map I get the information in the feature info window so I know my qgis server and web client are properly installed but with my own map, I always get an empty window.  The strange thing though is that if I connect to my WMS with QGIS Desktop and click on a feature, I do get the info. I cannot figure out why it's not working with the web client.  

Having a fully functional stand-alone projects, even a very small one would be a valuable tool to debug issues like mine.  I could compare all the projects settings to help me find what I might be missing in my project.

**Comment by manisandro** [comment]
This looks more like a CORS issue than an issue with the project file. Look at the browser console (typically you open it by pressing F12), and see whether any errors are printed to the console, respectively look in the network inspector pane to see what's happening with your request.

**Comment by groschialeux** [comment]
You're right, it is a CORS issue.  I didn't think of that because everything is running on the same server but then it just occured to me that same physical machine is not necessarily same server.

My web clients is on expedimaps.com but my wms is at maps.expedimaps.com so I guess technically it's not the same server.

I still think a fully functional stand alone project could be usefull to some people though and I would be more than happy to contribute by creating it along with a write up on how to set it up.

**Comment by manisandro** [comment]
Sure, I'd be happy to publish it.
