### ISSUE TITLE
Feature Info window doesn't scroll in Firefox when layer has lots of fields

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#128]
When viewing attributes in the Feature Info window and there are many fields, Firefox doesn't let you scroll down to see more.  It works fine in Chrome.

**Comment by manisandro** [comment]
Please post a screenshot

**Comment by raynerhoward** [comment]
![chrome](https://user-images.githubusercontent.com/3105035/49442866-076ff680-f7cb-11e8-977d-25400ca236df.png)

![firefox](https://user-images.githubusercontent.com/3105035/49442876-0f2f9b00-f7cb-11e8-955d-7590e88a48ea.png)

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/7b1725c9df91fc1dc2266d4dbe25b06b35349352
