### ISSUE TITLE
Ability to utilize Nominatum search engine for OSM data

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#129]
The Nominatum search engine for OpenStreetMap data is very useful for locating names or addresses.  This capability is available in QGIS via the Nominatum Location Filter plugin.  Would be beneficial to have this search capability in QWC2.

**Comment by manisandro** [comment]
Search providers are application specific (since they mostly differ from user to user), but you should be able to implement it easily in js/SearchProviders.js. It is not something I'll add to the core modules.
