### ISSUE TITLE
Printing panel: label with IDs need to be exposed

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#13]
The printing panel needs to be enhanced to allow set an alternative text:

If the GetProjectSettings contains one or more "ComposerLabel" elements - see snippet below:

```
<ComposerTemplate width="210" height="297" name="A4-Hoch">
<ComposerMap width="189" height="233.5" name="map0"/>
<ComposerLabel name="Titel"/>
</ComposerTemplate>
```
the printing panel nees to have an additional line widget per ComposerLabel element and send the alternative string along with the GetPrint request. See http://blog.sourcepole.ch/2011/02/03/web-based-printing-with-qgis-server/

The line widget should be labelled with the ID of the ComposerLabel element.

**Comment by manisandro** [comment]
Already implemented in qgis/qwc2@8d15a609043a7d25b6128ee32306cf33d8954bb7
