### ISSUE TITLE
Exclude project layers in themes

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2-demo-app#131]
Let's say I have layer1 and layer2 in my QGIS project. And I don't want layer2 in my QWC2 application, for example because I want to use layer2 as a background layer. It looks to me that excluding layers isn't currently supported. Am I correct? Would it make sense to add support for that? What do you think?

**Comment by manisandro** [comment]
In general, you are free to post-process your themes.json as desired. Specifically for background layers, if you mark a layer as a `printLayer` (see https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#configuring-the-themes-in-themesconfigjson), it won't get listed in the layertree.

**Comment by elemoine** [comment]
> In general, you are free to post-process your themes.json as desired.

Yes, right, that's an option. But this would mean having another config file, where I'd list the layers to exclude. I don't like this too much but I may have to live with it.

> Specifically for background layers, if you mark a layer as a printLayer (see https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#configuring-the-themes-in-themesconfigjson), it won't get listed in the layertree.

Hmm ok I haden't realized that. That could actually be an option in my case. But that I still think offering a way to exclude layers would provide for a general mechanism.

Thanks for your response. Feel free to close this issue if you're not interested in that feature. If you're interested I may be able to contribute it.

**Comment by elemoine** [comment]
I tried this in theme item:

```
      "backgroundLayers": [{
        "name": "commune",
        "visibility": true,
        "printLayer": "commune"
      }],
```

But that did not prevent the "commune" layer from being added to the layer tree. Maybe I misunderstood what you told me.

Thanks.

**Comment by manisandro** [comment]
Btw you can also choose to exclude layers in the WMS capabilities in the QGIS Project Settings. Otherwise, sure, one could also add a blacklist option to themesConfig.json.

**Comment by elemoine** [comment]
Thank you Sandro. Closing this for now.
