### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2-demo-app#132]
I've noticed that QWC2 includes an Authentication plugin, and that qwc2-demo-app includes login and logout SVG icons. AFAICT this plugin is not mentioned in the docs. Are there public examples/demos using this plugin? Is anyone aware of authentication methods/servers that are compatible with this plugin? Thanks.

**Comment by manisandro** [comment]
See https://github.com/qwc-services/qwc-db-auth

**Comment by elemoine** [comment]
I'll have a look. Thank you very much.
