### ISSUE TITLE
Resolution on Hidpi

### ISSUE THREAD

**Issue by bstroebl** [qgis/qwc2-demo-app#133]
Hi,
my application suffers from the following problem: When called from a mobile device (hidpi device) the requested resolution of the map is like 5 times larger resulting in a larger map being sent (1.2 MB versus 250 KB) compared  to when called from a desktop PC. This behaviour creates long loading times (initial loading time ~ 10 seconds) when mobile data (slow connection, no wifi) is used.
I would like to be able to configure my base theme in a way that just sufficient resolution is requested no matter what the screen resolution of the device. I would create another base theme with higher resolution for users that sport sufficient band width.
Looking at [OpenLayers api docs](https://openlayers.org/en/latest/apidoc/module-ol_source_ImageWMS.html) I found the hidpi parameter and hope that setting it to false resolves my problem. How can I use it?

**Comment by manisandro** [comment]
@bstroebl Sorry for the late reply. Can you try adding `hidpi: false` after this line [1] and see whether it fixes the issue? If yes, I can add the possibility to configure it via `config.json`.

[1] https://github.com/qgis/qwc2/blob/master/MapStore2Components/components/map/openlayers/plugins/WMSLayer.js#L54

**Comment by bstroebl** [comment]
@manisandro 
thank you for looking into this. It does indeed fix the problem: when setting hidpi: false the map is requested with 96 dpi and appropriate WIDTH and HEIGHT
I would appreciate if you added this to config.

**Comment by manisandro** [comment]
Done, you can now set `wmsHidpi` in config.json, see [sample config](https://github.com/qgis/qwc2-demo-app/blob/master/config.json)
