### ISSUE TITLE
Firefox doesn't display the centerline of the layer's transparent slider

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#135]
Hi,

the Firefox (65.0.1) browser doesn‘t display the centerline of the layer's transparent slider in the layer tree window. It's fine in Chrome and IE.

![qwc2_fehler_transparenz_schieberegler_firefox](https://user-images.githubusercontent.com/20335953/53080004-fb592280-34f7-11e9-8b9c-061ce4c22827.png)

**Comment by manisandro** [comment]
Thanks for reporting, fixed in https://github.com/qgis/qwc2/commit/f5410094765ec1d7e9bd4de503e82ce9de0d4907
