### ISSUE TITLE
The list of map topics is too long on some browser

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#136]
Hi,

with many topics the list of map topics is too long on an iPad (iOS 12.1.3) and on mobile android devices with Chrome browser. Because of this the list is not scrollable to the end and the last topic image is clipped. In addition, the button of the overview map overlays the list.

The first picture shows the error in the Chrome (72.0.3626.105) browser: 
![qwc2_fehler_themen_chrome](https://user-images.githubusercontent.com/20335953/53080202-6c003f00-34f8-11e9-88a3-6c394d158269.png)

The second picture shows the correct version in the Firefox browser:
![qwc2_fehler_themen_firefox](https://user-images.githubusercontent.com/20335953/53080218-73274d00-34f8-11e9-84d1-e9dbdcb6494d.png)

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/a134f56a296659fd46a1a776b3bf001dfa1363bf, thanks for reporting.
