### ISSUE TITLE
location service does not work with Firefox (Android)

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#139]
With Firefox for Android the location service does not work on mobile devices. The permission request pops up briefly and then disappears immediately. The location button is grayed out. With Chrome or Safari under iOS the positioning works. It's fine in Chrome (Android) and Safari (iOS).

**Comment by bstroebl** [comment]
I think I can confirm this problem, at least my tests point in that direction. No way with FF under Android, Chrome works fine, no problems on iOS. It works alright with FF on Desktop (tested on Ubuntu and Win7).

**Comment by manisandro** [comment]
Confirmed but currently no idea if there is anything that can be done by QWC2.

**Comment by manisandro** [comment]
This works now AFAICS.
