### ISSUE TITLE
Error: project with just one composer temlate

### ISSUE THREAD

**Issue by karl-magnus** [qgis/qwc2-demo-app#14]
If the QGIS project just contains one composer template the deployment fails.
![bild](https://cloud.githubusercontent.com/assets/4749245/22473195/599d6e9c-e7d8-11e6-9204-a26f6d64b054.png)

**Comment by manisandro** [comment]
Can you provide the capabilities document?

**Comment by karl-magnus** [comment]
Quite sure that this is the problem. I've removed and added a layot so the project have one or two layots. One layot doesn't work. Two works. Nothing else changed.
[GetProjectSettings_one_composer.txt](https://github.com/qgis/qwc2-demo-app/files/744617/GetProjectSettings_one_composer.txt)

**Comment by manisandro** [comment]
Should be fixed in 90135fd6909579674e76dd4067463120464afa00, thanks for reporting.
