### ISSUE TITLE
It's not possible to run `yarn run themesconfig` if the qgis-server is behind a per user http basic authentication. 

### ISSUE THREAD

**Issue by autra** [qgis/qwc2-demo-app#141]
# Description

Here is our context : I have a qgis-server behind an http Basic authentication. This authentication is different for every user of our plateform.

If we provide an url of the form `http://login:pass@server/` into our `themesConfig.json`, this url will end up in themes.json when building the sources. Then all our users will use these credentials instead of theirs. We would like qwc2 to support alternate credentials during the configuration phase. 

# Possible solution

I was thinking about supporting an env var  `QWC2_WMS_BASIC_AUTH` of the form `login:pass` that would get passed to axios in `qwc2/scripts/themesConfig.js` when querying capabilities. I plan to open a PR but I wanted to have inputs of qwc2 maintainers before working on it. 

Thank you.

**Comment by tudorbarascu** [comment]
Hi,

You can use a proxy for this.. I think that's how you should be doing it, I think you can see in the config where to put it.
Or you can allow connections without authentication from the IP of your server in your nginx or apache config, in nginx something like this would do it in your location directive:

```
satisfy any;

# List holding friendly IPs
allow 192.168.1.0/24;     #  your lan IP
allow 5.2.200.100;          # or your qwc2 IP
deny  all;

auth_basic "Restricted access..";
auth_basic_user_file /etc/nginx/.htpasswd;  # For Basic Auth
```

**Comment by autra** [comment]
Thanks for your answer tudorbarascu.

> You can use a proxy for this.. I think that's how you should be doing it, I think you can see in the config where to put it.

Having to configure a proxy *just* to generate a static site is too much in my opinion.

> Or you can allow connections without authentication from the IP of your server in your nginx or apache config

This does not really scale... Beside, developers are not always able to change this configuration if they build their front on an external service.

To make things clearer: in my case I can perfectly workaround this issue in a lot of different ways including disabling the authent (or running a regex on the generated themes.json, or setting a proxy or...), but I do think it's not an optimal developer experience, especially when using an external service.

I think my proposal (or a similar one) would improve this experience.

**Comment by autra** [comment]
Hi! 

I opened a MR with a possible implementation: https://github.com/qgis/qwc2/pull/73

**Comment by tudorbarascu** [comment]
@autra Thanks a lot! Sorry for misunderstanding in the beginning, I read in diagonal and I quickly responded. All the best.

**Comment by manisandro** [comment]
Since addressed by https://github.com/qgis/qwc2/pull/73
