### ISSUE TITLE
GetFeatureInfo broken?

### ISSUE THREAD

**Issue by dkippo** [qgis/qwc2-demo-app#143]
Testing qwc2 master and trying to identify map features but always returning "No information available for the selected point".  I ran the same GetFeatureInfo request (taken from apache log) direct in the browser and appears to return a valid xml response.

Looks like the same problem when I run the demo project in the development application.  Works correctly when using branch stable.

**Comment by manisandro** [comment]
Cross-origin issue perhaps? Look at the browser console if there are any related error messages.

**Comment by dkippo** [comment]
Thanks, that was it.
