### ISSUE TITLE
Add a theme pointing to qgis4.qgis.org:8081/qgisserver_demo

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2-demo-app#144]
As [discussed](https://lists.osgeo.org/pipermail/qgis-psc/2019-March/007203.html) on the QGIS PSC mailing list we have set up a qwc2-demo-app instance on the qgis4.qgis.org server. It's available at http://qgis4.qgis.org:8081/qwc2_demo/. This is the standard qwc2-demo-app with no modification/customization.

Now we're thinking at adding a new theme/map to qwc2-demo-app pointing to the QGIS Server demo instance also available on that server (http://qgis4.qgis.org:8081/qgisserver_demo/). We could do that in a specific themesConfig.json, but we'd rather extend qwc2-demo-app's official themesConfig.json. In this way anyone setting up qwc2-demo-app with the default themesConfig.json will see a map pointing to the official QGIS Server demo.

What do you think? I can submit a PR if you agree with the proposal.

**Comment by andreasneumann** [comment]
Hi @elemoine 

Very much agreed. The current examples are really ugly. Not good advertising for QGIS Server and QWC2.

If you can add nicer examples, it would be much appreciated, I think.

Andreas

**Comment by manisandro** [comment]
Sure, fine for me! Thanks.

**Comment by elemoine** [comment]
@andreasneumann, you're right that the current maps are inelegant :) And the /qgisserver_demo map I am proposing to add is actually not better; it's based on data and a QGIS project used for the QGIS Server performance tests. But this is just a first step, and I hope that we can have a better /qgisserver_demo map in the future.

**Comment by elemoine** [comment]
@manisandro thank you for your response. I've started working on a PR: #145.

**Comment by elemoine** [comment]
Done. http://qgis4.qgis.org:8081/qwc2_demo

Thank you all!
