### ISSUE TITLE
Documentation is not clear where to add new projection

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#146]
The documentation states:

```
The js/appConfig.js file controls the following:
Which projections are known to the application. Every projection used (as map or data projection) needs to be registered by adding a corresponding
  Proj4js.defs(<EPSG Code>, <proj definition>);
line
```

I added the 25832 projection:
`Proj4js.defs["EPSG:25832"] = "+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs";`
at the end of the appConfig.js file, but when I open the page it throws me an error in the Javascript console:

`ReferenceError: Proj4js is not defined`

**Comment by stephaschu** [comment]
Adding projections was moved from js/appConfig.js to config.json (see https://github.com/qgis/qwc2-demo-app/blob/master/config.json#L31)

**Comment by manisandro** [comment]
Both still work, but you need to import proj4

    const Proj4js = require('proj4').default;

in `appConfig.js` if you do it there.

**Comment by lucamanga** [comment]
Thank you @manisandro and @stephaschu , now it's more clear 😀

**Comment by beerockxs** [comment]
The documentation https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md still says to just add that line to appConfig.js, it should be updated to reflect this change.
