### ISSUE TITLE
IdentifyRegion bug

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#147]
When the user end drawing the IdentifyRegion polygon a simple Identify request get over the IdentifyRegion request

**Comment by luciman** [comment]
@manisandro could you please take a look?

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/f3264c60d888fd4fa96d57fe557f89f42d2ef22d, thanks for reporting!
