### ISSUE TITLE
QWC2 stop running

### ISSUE THREAD

**Issue by mibalas** [qgis/qwc2-demo-app#149]
Hi, I'm new to QWC2

So, I installed QWC2 on Ubuntu Server 16 and I published a Qgis Project (.qgs) with QGIS Server and used "yarn start", its working.

But sometimes the application stops working and I have to tap "yarn start" again, is there a way to start automatically when the service is idle?

Thank you

**Comment by manisandro** [comment]
You need to be more specific for anyone to be able to help you.

**Comment by mibalas** [comment]
Hi, 
I dont know what exactly is happening, but after a while, my QWC2 stops running, I try to enter http://localhost:8081 and receive "ERR_CONNECTION_REFUSED", so I enter the QWC2 folder by terminal and send "yarn start" and QWC2 work again, but after a while, it stops working again :/

I dont know nodejs very well, I dont know what may be killing the application

**Comment by manisandro** [comment]
Look at the output in the terminal where you previously ran `yarn start`, it might contain information regarding why the process ended.

In any event, this is most likely not a QWC2 issue.
