### ISSUE TITLE
Projection choice in status bar should have alias names

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#15]
In the bottom status bar one can choose a CRS system for the display of the coordinates.

Our average Web-GIS users are not familiar with EPSG codes. For them it would be beneficial if we could display an alias name instead of the EPSG code, e.g.

EPSG:2056 --> CH1903/LV95
EPSG:21781 --> CH1903/LV03
EPSG:4326 --> WGS84
etc.

The combobox would display the Alias names, but internally use the EPSG codes.

**Comment by manisandro** [comment]
Implemented in 53f4165
