### ISSUE TITLE
Blank page when geolocation in Firefox is disabled

### ISSUE THREAD

**Issue by mrtwister3142** [qgis/qwc2-demo-app#150]
When geolocation in Firefox 67.0.2 is disabled ("geo.enabled" = false) then QWC2 returns a blank page, e.g. at https://geo.so.ch/map or https://map.geo.gl.ch/

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/4237783e486676939c26f8441c5a767e7ec4e610, thanks for reporting!
