### ISSUE TITLE
Issue with getting project to load

### ISSUE THREAD

**Issue by TheVidar** [qgis/qwc2-demo-app#151]
Hi,

We've been trying to adopt the web client however having a lot of issues getting a themesConfig file to work and produce our expected results. 

I'm by no means seasoned to QGIS but have followed instructions given to no avail, attached is the project file and the themesConfig file that I'm attempting to load.

Currently it produces an error as specified:

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at eval (Search.jsx:859)
    at eval (index.js:75)
    at eval (index.js:35)
    at eval (index.js:89)
    at eval (index.js:35)
    at eval (index.js:85)
    at Function.eval [as mapToProps] (index.js:35)
    at mapToPropsProxy (wrapMapToProps.js:46)
    at handleNewState (selectorFactory.js:50)
    at handleSubsequentCalls (selectorFactory.js:64)

---
themesConfig

{
  "themes": {
    "items": [
      {
        "url": "http://10.253.4.101/cgi-bin/qgis_mapserv.fcgi?MAP=/home/qgis/projects/cma2/thatch.qgs",
        "attribution": "admin_line"
      }
    ],
    "groups": [
      {
        "title": "group",
        "items": [
          {
            "title": "admin_line",
            "url": "http://10.253.4.101/cgi-bin/qgis_mapserv.fcgi?MAP=/home/qgis/projects/cma2/thatch.qgs"
          }
        ]
        }
        ],
    "backgroundLayers": [
      {
        "name": "admin_line",
        "title": "admin_line"
      }
    ]
  }
}

Any help would be great.

**Comment by TheVidar** [comment]
[Example.zip](https://github.com/qgis/qwc2-demo-app/files/3324122/Example.zip)

**Comment by manisandro** [comment]
Might be related to the fact that you have no search providers configured.

**Comment by manisandro** [comment]
Closing, feel free to reopen if you still encounter issues.
