### ISSUE TITLE
Updating my project throws an error

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#152]
Hello, following your documentation on updating my qwc2 app, the console states this:

```
# git pull

Updating bf49843..b310ce6
error: Your local changes to the following files would be overwritten by merge:
	themesConfig.json
	translations/data.it-IT
Please commit your changes or stash them before you merge.
Aborting
```

how can I fix it?

**Comment by tudorbarascu** [comment]
This is because you already edited those two files.
It's a git problem, not a qwc2 one.
You should copy those files somewhere to make a backup, then do a a `git checkout themesConfig.json translations/data.it-IT` to reset your changes to those files, then do the pull request.
Good luck!

**Comment by lucamanga** [comment]
Thank you for the info!
