### ISSUE TITLE
Browser caching issue

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#153]
Hello,

I discovered that if I do these steps:

1. load my qwc2 site with my browser
1. update my project
1. run `yarn run prod`
1. re-load the qwc2 site with my browser

the layer list is always the same; I must to a browser clean cache. There's any way to automatically to do this after a `yarn run prod`?

**Comment by manisandro** [comment]
You cannot flush the browser cache programmatically. What you can do is configure the webserver which runs your production deployment to serve `themes.json` with various no-cache headers.

**Comment by lucamanga** [comment]
Thank you for kind reply!
I've added this to my apache2 config and now it works perfectly!
```
<FilesMatch "themes.json$">
    FileEtag None
    <ifModule mod_headers.c>
        Header Unset ETag
        Header Set Cache-Control "max-age=0, no-store, no-cache, must-revalidate"
        Header Set Pragma "no-cache"
        Header Set Expires "Thu, 1 Jan 1970 00:00:00 GMT"
    </ifModule>
</FilesMatch>
```
