### ISSUE TITLE
Insert a XYZ Layer as Background Layer

### ISSUE THREAD

**Issue by zanollim** [qgis/qwc2-demo-app#155]
I'm developing my new WEBGIS site using the amazing QWC2 project.

My goal is to migrate from the old, actually very well working, QWC1 client to the new QWC2 client.

In my old QWC1 I am loading a static tile layer as background layer, here the portion of code in the Customizations.js file:

`var webmapp = new OpenLayers.Layer.XYZ( "Webmapp",
        ["https://path/to/tile/server/${z}/${x}/${y}.png"],
        {
            minScale: 577791,
            serverResolutions: [156543.03390000001, 78271.516950000005, 39135.758475000002, 19567.879237500001, 9783.9396187500006, 4891.9698093750003, 2445.9849046875001, 1222.9924523437501, 611.49622617187504, 305.74811308593752, 152.87405654296876, 76.43702827148438, 38.21851413574219, 19.109257067871095, 9.5546285339355475, 4.7773142669677737, 2.3886571334838869,],
            attribution: "&copy; Webmapp.it under CC BY-NC-SA",
            transitionEffect: "resize",
            sphericalMercator: true,
            visibiltiy: false,
        }
    );`

Is there a way to load the same XYZ layer as background layer in QWC2 client?
I'm not able to find the way, or any existing example.
Thanks

**Comment by manisandro** [comment]
This is currently not implemented, but should be rather easy:

- Create a `qwc2/components/map/openlayers/plugins/XYZLayer.js`, taking i.e. `WMTSLayer.js` as a template
- Implement the `create` function accordingly
- Add your new layer to the `LayerRegistry` in `qwc2/components/map/openlayers/plugins/index.js`

You can then add the background layer with `"type": "xyz"` (if that's the key name you choose in `LayerRegistry`), and all the options you need for the `create` function.

**Comment by zanollim** [comment]
Thanks Sandro,

following your precious instructions I found a more simple solution:

add my XYZ layer as type "tileprovider" in qwc2/utils/ConfigProvider.js

it works as a charm!
