### ISSUE TITLE
Feature remains selected after Feature Info window is closed if displayResultTree is true and you click a feature in the top pane of the Feature Info window 

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#156]
Hello,

When displayResultTree is true and you click on a feature in the top pane of the Feature Info window, the selection graphic does not go away when you close the Feature Info window.  Happens in both Chrome and Firefox.

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/47f2a65b4b6c0175fd21db809935ef9da51772d9, thanks for reporting!
