### ISSUE TITLE
Config option to disable marker pin during Identify and Search Result

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#157]
Hello,

It would be useful if there was an easy way (via config.json perhaps) to prevent the marker pin from being drawn during Identify and/or Search.  In many cases, it's enough that the identified feature is selected/highlighted without also having a marker pin on top of the feature.  Same thing with clicking on a feature in the drop-down Search results.  A marker pin on top of the selected/highlighted feature can be redundant.  Also, if features are labeled, an additional label from Search results can also be redundant.  Would be great if there was an option to disable Search result labels.

Just recently found out about the option to enable select/highlight of features simply by checking the box next to "Add geometry to feature response" under Project Properties → QGIS Server → WMS Capabilities.  Very cool.  This had been on my QWC2 wish list for a while.

Thanks.

**Comment by manisandro** [comment]
> It would be useful if there was an easy way (via config.json perhaps) to prevent the marker pin from being drawn during Identify and/or Search.

As for identify, adding a prop to the `Identify` class in `Identify.jsx` and then depeding on the value of the prop omitting the call to `addMarker` in `Identify::componentWillReceiveProps` should do (and then you can set the prop value in config.json).

Pin search results: a possibility would be to allow specifying `marker: false` in the search result entries, and accordingly omit the call to `addMarker` in `Search.jsx`.

> Would be great if there was an option to disable Search result labels.

You can already achieve this by setting `label: ""` in the search result entry you construct in `SearchProviders.js`.

**Comment by manisandro** [comment]
Closing, feel free to submit a PR with the changes outlined above.
