### ISSUE TITLE
Remove and Export icons don't line up vertically in Feature Info window top pane when multiple features are listed and displayResultTree is true

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#159]
As I move the mouse down over the list of feature IDs in the top pane of the Feature Info window (with displayResultTree = true), the Remove and Export icons shift to the left.  This causes the text of one (or more) of the feature IDs to wrap to the next line if there are lots of feature IDs shown (more pronounced when the window is narrowed).

Not a terribly huge issue, but I've noticed it doing this since I started messing around with QWC2 about a year ago.

Regards

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/c50b9f83051601f3506acf7d9be4e2f58cf33e35, thanks for reporting!
