### ISSUE TITLE
Allow WMTS only themes

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#16]
For some themes (like Orthoimage or base maps) it would be useful being able to have a theme without a WMS. These are typically used as the startup theme and would accelerate the speed of the initial topic that is loaded.

We need, however, the ability to specify a WMS printing layer for such WMTS-only layer.

Needs discussion.

Perhaps best solved by enhancing QGIS server to also accept WMS printing layers that could either be external to the project or from an entirely different source.

**Comment by manisandro** [comment]
QWC2 now correctly handles blank theme WMS layers (i.e. with `"sublayers": [],` in the respective 
`themes.json` theme entry). Print layers can still be specified in the underlying QGIS project. Does this address this issue?

**Comment by andreasneumann** [comment]
That issue is back from the time where I was still involved with the project - which unfortunately I am not currently. I think what you describe would be ok to solve this issue. We can close the issue now.
