### ISSUE TITLE
Print provides xml output

### ISSUE THREAD

**Issue by jmarsac** [qgis/qwc2-demo-app#162]
Hi,
I added a theme to qwc2-demo-app. It works fine but I can't print: PDF file is generated but it contains XML only (see attachment)

    <?xml version="1.0"?>
    <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0"> 
    <ServiceException code="OperationNotSupported">Please check the value of the REQUEST parameter</ServiceException>
    </ServiceExceptionReport>

I guess a component is missing but which one ?
[SIGEP88.pdf](https://github.com/qgis/qwc2-demo-app/files/3608730/SIGEP88.pdf)

**Comment by andreasneumann** [comment]
Are you running an XServer? Is QGIS Server on Linux or Windows?

PDF printing requires an XServer and also an FCGI configuration pointing to the correct DISPLAY port.

See https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/getting_started.html#xvfb

**Comment by jmarsac** [comment]
Yes Xvfb is running (started by systemd)

    [Unit]
    Description=X Virtual Frame Buffer Service
    After=network.target
    
    [Service]
    ExecStart=/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset
    
    [Install]
    WantedBy=multi-user.target

and DISPLAY is set for nginx

    location /qgis {
    if ($request_method = 'OPTIONS') {
    add_header 'Access-Control-Max-Age' 1728000;
    add_header 'Content-Type' 'text/plain charset=UTF-8';
    add_header 'Content-Length' 0;
    return 204;
    }

    gzip off;
    include fastcgi_params;
    fastcgi_param DISPLAY                     ":99";

    fastcgi_pass unix:/var/run/qgis-server.sock;
    }

**Comment by jmarsac** [comment]
QGIS server is running on Debian Stretch ( Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux)

**Comment by manisandro** [comment]
This is not a QWC2 issue, please seek help in the QGIS user list [1].

[1] https://lists.osgeo.org/mailman/listinfo/qgis-user

**Comment by jmarsac** [comment]
I come back since I don't understand...
If I manually build GetPrint request and send it to QGIS Server with
https://devmaps.azimut.fr:8443/qgis/88252/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&TEMPLATE=A4-PAYSAGE&map0:EXTENT=679592.3458333332%2C6127796.0874999985%2C680676.0791666666%2C6128523.112499999&FORMAT=pdf&DPI=150&SRS=EPSG:3857&MAP=/data/src/clients/sdev/extranet/data/88252/88252.qgs 
I get a valid PDF.
When I want to use qwc2 interface (https://devmaps.azimut.fr) printing fais and I get following error .

    <?xml version="1.0"?>
    <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
    <ServiceException code="OperationNotSupported">Please check the value of the REQUEST parameter</ServiceException>
    </ServiceExceptionReport>

themesConfig.json and qgis-server logs are joined in attachment.
Thanks for your help
[qgis-server.log](https://github.com/qgis/qwc2-demo-app/files/3620832/qgis-server.log)
[themesConfig.json.pdf](https://github.com/qgis/qwc2-demo-app/files/3620866/themesConfig.json.pdf)

**Comment by manisandro** [comment]
Looks to me as if the post parameters are not being forwarded to the qgis server. If you clear the qgis-server.log and then perform a single print from the client, do you see qgis server logging the requests with all parameters?

**Comment by jmarsac** [comment]
It seems to be no.
[qgis-server.log](https://github.com/qgis/qwc2-demo-app/files/3621421/qgis-server.log)

**Comment by manisandro** [comment]
Not sure what you mean by "it seems to be no". I see a GetPrint request in the log which looks fairly complete. What I see however is that LAYERS contains `osm_farbig`, which is a client-side background layer and likely does not exist in your qgis project. In this case I'd expect you'd receive an XML error output concerning a non-existing layer, and not about the REQUEST parameter though. If this is the case, you need to define a print-layer for your background layer.

**Comment by jmarsac** [comment]
I deleted previous comment since didn't restart qgis-mapserv.fcgi before testing. Here is new log after cleaning.
[qgis-server2.log](https://github.com/qgis/qwc2-demo-app/files/3621574/qgis-server2.log)

**Comment by manisandro** [comment]
Again, same observation as before.

    15:20:43 INFO Server[8716]: ******************** New request ***************
    15:20:43 INFO Server[8716]: SERVER_NAMEdevmaps.azimut.fr
    15:20:43 INFO Server[8716]: REQUEST_URI/qgis/88252?MAP=%2Fdata%2Fsrc%2Fclients%2Fsdev%2Fextranet%2Fdata%2F88252%2F88252.qgs&
    15:20:43 INFO Server[8716]: REMOTE_ADDR192.168.5.16
    15:20:43 INFO Server[8716]: CONTENT_TYPEapplication/x-www-form-urlencoded
    15:20:43 INFO Server[8716]: HTTP_USER_AGENTMozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
    15:20:43 WARNING [8716]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
    15:20:43 WARNING [8716]: formatString is: pdf
    15:20:43 INFO Server[8716]: COLORS:,,
    15:20:43 INFO Server[8716]: DPI:300
    15:20:43 INFO Server[8716]: FORMAT:pdf
    15:20:43 INFO Server[8716]: LAYERS:osm_farbig,Cables,Armoires
    15:20:43 INFO Server[8716]: MAP:/data/src/clients/sdev/extranet/data/88252/88252.qgs
    15:20:43 INFO Server[8716]: MAP0:EXTENT:679908.3928401842,6127787.273506121,680396.8603401842,6128181.107511341
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_GEOM:
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_LABELBUFFERCOLOR:
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_LABELBUFFERSIZE:
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_LABELCOLOR:
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_LABELSIZE:
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_LABELSTRING:
    15:20:43 INFO Server[8716]: MAP0:HIGHLIGHT_SYMBOL:
    15:20:43 INFO Server[8716]: MAP0:LAYERS:osm_farbig,Cables,Armoires
    15:20:43 INFO Server[8716]: MAP0:ROTATION:0
    15:20:43 INFO Server[8716]: MAP0:SCALE:2500
    15:20:43 INFO Server[8716]: OPACITIES:255,255,255
    15:20:43 INFO Server[8716]: REQUEST:GetPrint
    15:20:43 INFO Server[8716]: SERVICE:WMS
    15:20:43 INFO Server[8716]: SRS:EPSG:3857
    15:20:43 INFO Server[8716]: TEMPLATE:A4-PAYSAGE
    15:20:43 INFO Server[8716]: TRANSPARENT:true
    15:20:43 INFO Server[8716]: VERSION:1.3.0
    15:20:43 INFO Server[8716]: Request finished in 4 ms

**Comment by jmarsac** [comment]
Thank you @manisandro 
According to documentation, if "printLayer" is missing no background is printed(_If omitted, no background is printed._). Does it mean that nothing is printed ?

**Comment by manisandro** [comment]
No, it means that the background is not printed if `printLayer` is not defined. Looking at your themesConfig.json, you have `"printLayer": "osm_farbig",`, but `osm_farbig` is not a layer which exists in your project according to the GetProjectSettings output.

**Comment by jmarsac** [comment]
Ok. But when removing all backgrounds from my theme definition, I get same error. Why ?

**Comment by manisandro** [comment]
Hard to say without seeing your themes.json. Either you updated themesConfig.json without regenerating themes.json, or you are attempting to print a theme without any layer at all.

**Comment by jmarsac** [comment]
I remove qgis-server.log, restart qgis_mapserv.fcgi and rerun "yarn start" after each change on themesConfig.json. Last used below

    {
      "themes": {
        "items": [
              {
                "title": "88252",
                "url": "https://devmaps.azimut.fr:8443/qgis/88252?MAP=/data/src/clients/sdev/extranet/data/88252/88252.qgs",
                "attribution": "Syndicat Départemental d'Electricité des Vosges",
                "attributionUrl": "https://www.smdev88.fr",
                "format": "image/png; mode=8bit",
                "tiled": false,
                "default": true,
                "scales": [1000000,500000,200000, 100000,50000, 25000, 20000, 10000, 7500, 5000, 2500, 2000, 1000, 500, 200, 100],
                "printScales": [500000, 200000, 100000,50000, 25000, 20000, 10000, 7500, 5000, 2500, 2000, 1000, 500, 200, 100],
                "printResolutions": [72, 150, 300, 600],
                "backgroundLayers": [
                ],
                "searchProviders": ["coordinates"],
                "mapCrs": "EPSG:3857",
                "additionalMouseCrs": ["EPSG:2154"],
                "config": {
                  "preserveExtentOnThemeSwitch": false
                }
              }
        ],
        "groups": [
          {
            "title": "Communes",
            "items": [
            ],
            "groups": [
    
            ]
          }
        ],
        "backgroundLayers": [
          {
            "name": "mapnik",
            "title": "Open Street Map",
            "type": "osm",
            "source": "osm",
            "thumbnail": "mapnik.jpg",
            "attribution": "OpenStreetMap contributors",
            "attributionUrl": "https://www.openstreetmap.org/copyright"
          },
          {
            "name": "Night2012",
            "title": "NASAGIBS Night 2012",
            "type": "tileprovider",
            "source": "nasagibs",
            "provider": "NASAGIBS.ViirsEarthAtNight2012",
            "thumbnail": "Night2012.jpg",
            "attribution": "Suomi NPP / VIIRS via NASA Earth Observatory"
          },
          {
            "name": "StamenWatercolor",
            "title": "Stamen Watercolor/OSM",
            "type": "tileprovider",
            "source": "stamen",
            "provider": "Stamen.Watercolor"
          },
          {
            "name": "StamenToner",
            "title": "Stamen Toner/OSM",
            "type": "tileprovider",
            "source": "stamen",
            "provider": "Stamen.Toner"
          },
          {
            "name": "Gemeindegrenzen",
            "title": "Gemeindegrenzen",
            "type": "wms",
            "url": "http://wms.geo.admin.ch/",
            "params": {
              "LAYERS": "ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill",
              "STYLES": "default"
            }
          },
          {
            "type": "wmts",
            "url": "http://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_ShadedRelief/default/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.jpeg",
            "title": "Blue Marble",
            "name": "bluemarble",
            "tileMatrixPrefix": "",
            "tileMatrixSet": "GoogleMapsCompatible_Level8",
            "originX": -20037508.34278925,
            "originY": 20037508.34278925,
            "projection:": "EPSG:3857",
            "resolutions": [
              156543.03390625,
              78271.516953125,
              39135.7584765625,
              19567.87923828125,
              9783.939619140625,
              4891.9698095703125,
              2445.9849047851562,
              1222.9924523925781
            ],
            "tileSize": [
              256,
              256
            ],
            "thumbnail": "img/mapthumbs/default.jpg"
          },
          {
            "type": "wms",
            "url": "https://maps.omniscale.net/v2/swl-33d96aa8/style.default/map",
            "title": "osm",
            "name": "osm",
            "srs": "EPSG:25832",
            "params": {
              "LAYERS": "osm",
              "STYLES": "",
              "VERSION": "1.1.1"
            },
            "thumbnail": "img/mapthumbs/default2.jpg"
          },
          {
            "type": "wmts",
            "url":"https://wmts20.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/2056/{TileMatrix}/{TileCol}/{TileRow}.jpeg",
            "title": "Landeskarte",
            "name": "pixelkarte",
            "tileMatrixPrefix": "",
            "tileMatrixSet": "2056_27",
            "originX": 2420000.0,
            "originY": 1350000.0,
            "projection:": "EPSG:2056",
            "resolutions": [4000,3750,3500,3250,3000,2750,2500,2250,2000,1750,1500,1250,1000,750,650,500,250,100,50,20,10,5,2.5,2,1.5,1,0.5,0.25],
            "tileSize": [256, 256],
            "thumbnail": "img/mapthumbs/default.jpg"
          },
          {
            "type": "tileprovider",
            "provider": "OpenTopoMap",
            "title": "OpenTopoMap",
            "name": "opentopomap",
            "thumbnail": "img/mapthumbs/default.jpg",
            "attribution": "Map data: &copy; <a href=\"https://openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors, SRTM | Map style: &copy; <a href=\"https://opentopomap.org\" target=\"_blank\">OpenTopoMap</a> (<a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\">CC-BY-SA</a>)"
          },
          {
            "type": "wmts",
            "url": "https://wxs.ign.fr/pratique/geoportail/wmts",
            "title": "IGN",
            "name": "GEOGRAPHICALGRIDSYSTEMS.MAPS",
            "format": "image/jpeg",
            "style": "normal",
            "originX": -20037508,
            "originY": 20037508,
            "projection": "EPSG:3857",
            "resolutions": [
              156543.03392804097,
              78271.51696402048,
              39135.75848201024,
              19567.87924100512,
              9783.93962050256,
              4891.96981025128,
              2445.98490512564,
              1222.99245256282,
              611.49622628141,
              305.748113140705,
              152.8740565703525,
              76.43702828517625,
              38.21851414258813,
              19.109257071294063,
              9.554628535647032,
              4.777314267823516,
              2.388657133911758,
              1.194328566955879
            ],
            "tileSize": [256, 256],
            "requestEncoding": "KVP",
            "tileMatrixSet": "PM",
            "tileMatrixPrefix": "",
            "thumbnail": "ign.png",
            "attribution": "<a href=\"http://www.geoportail.fr/\" target=\"_blank\"><img src=\"https://api.ign.fr/geoportail/api/js/latest/theme/geoportal/img/logo_gp.gif\"></a>"
          }
        ]
      },
      "defaultScales": [4000000, 2000000, 1000000, 400000, 200000, 80000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000, 500, 250, 100],
      "defaultPrintGrid": [{"s": 10000, "x": 1000, "y": 1000}, {"s": 1000, "x": 100, "y": 100}, {"s": 100, "x": 10, "y": 10}],
      "defaultWMSVersion":"1.3.0"
    }

**Comment by manisandro** [comment]
Assuming https://devmaps.azimut.fr is what you are currently testing with - this is again the

    Please check the value of the REQUEST parameter

error, not the one about the missing layer. The same error appears with

    <html>
    <body>
    <form action="https://devmaps.azimut.fr:8443/qgis/88252" method="POST">
    <div>
    <input name="TEMPLATE" value="A4-PAYSAGE" />
    <input name="map0:scale" value="2500" />
    <input name="DPI" value="300" />
    <input name="map0:rotation" value="0" />
    <input name="map0:extent" value="679908.76625,6127787.08299739,680397.23375,6128180.91700261" />
    <input name="SERVICE" value="WMS" />
    <input name="VERSION" value="1.3.0" />
    <input name="REQUEST" value="GetPrint" />
    <input name="FORMAT" value="pdf" />
    <input name="TRANSPARENT" value="true" />
    <input name="SRS" value="EPSG:3857" />
    <input name="MAP" value="/data/src/clients/sdev/extranet/data/88252/88252.qgs" />
    <input name="OPACITIES" value="255,255,255" />
    <input name="LAYERS" value="Communes,Cables,Armoires" />
    <input name="COLORS" value=",," />
    <input name="map0:LAYERS" value="Communes,Cables,Armoires" />
    <input name="map0:HIGHLIGHT_GEOM" value="" />
    <input name="map0:HIGHLIGHT_SYMBOL" value="" />
    <input name="map0:HIGHLIGHT_LABELSTRING" value="" />
    <input name="map0:HIGHLIGHT_LABELCOLOR" value="" />
    <input name="map0:HIGHLIGHT_LABELBUFFERCOLOR" value="" />
    <input name="map0:HIGHLIGHT_LABELBUFFERSIZE" value="" />
    <input name="map0:HIGHLIGHT_LABELSIZE" value="" /></div>
    <div><input type="submit" value="Submit" /></div>
    </form>
    </body>
    </html>

so again, I believe your post requests are not getting properly delivered to the QGIS server.

**Comment by jmarsac** [comment]
Thank you Sandro. I'm going to keep looking for.
