### ISSUE TITLE
Identify tool click radius

### ISSUE THREAD

**Issue by mibalas** [qgis/qwc2-demo-app#164]
Hi, I'm have some difficulties using the identify tool in feature point layers.

How to increase the radius of mouse click?

**Comment by manisandro** [comment]
Hi, you can set the `FI_POINT_TOLERANCE`, `FI_LINE_TOLERANCE`, `FI_POLYGON_TOLERANCE` params in config.json see [1].

[1] https://github.com/qgis/qwc2-demo-app/blob/master/config.json#L345

**Comment by mibalas** [comment]
Hi, thank you for answer.

I changed the values and restart qwc2 ​​but nothing happened.

Is there any other setting I have to do?
