### ISSUE TITLE
How to use maptips ?

### ISSUE THREAD

**Issue by groschialeux** [qgis/qwc2-demo-app#165]
I don't understand how maptips work exactly.   The only way I could make it work is by adding a "maptip" attribute to my tables and populating it with some text.    I did that after reading some post on stack exchange because I could not get it to work any other way.

I thought QWC2 would use the Display Name or the HTML Map Tip from the Display tab in the project layer's properties.   

What is the right way to display maptip ?  Is having a "maptip" attribute actually the only way ?

**Comment by manisandro** [comment]
If you set a HTML Maptip in your layer properties in QGIS, QGIS server should automatically add a corresponding maptip attribute to the GetFeatureInfo response. This is then picked up by QWC2.

**Comment by groschialeux** [comment]
That's what I thought.  For some reason my qgis server does not do it but at least now you gave me confirmation that it supposed to so I can dig the issue.

Thanks Sandro.

**Comment by groschialeux** [comment]
Sandro,

I fixed my issue.  I know the issue is closed but if you don't mind I am going to post about the fix, maybe it can help others in the future.

In a nutshell, I was running qgis server 2.18 on Ubuntu 18.04 but on my Linux Mint desktop I am using QGIS 3.8.

It appears the projects are not compatible.  I upgraded qgis-server to 3.x and not I see maptips.

**Comment by manisandro** [comment]
Yeah QGIS 3.x projects are definitely not backwards compatible to 2.x. Thanks for posting back.
