### ISSUE TITLE
http://qgis4.qgis.org:8081/qgisserver_demo is down again!!

### ISSUE THREAD

**Issue by lucianor1979** [qgis/qwc2-demo-app#166]
http://qgis4.qgis.org:8081/qgisserver_demo is Down again

**Comment by pblottiere** [comment]
Hi @lucianor1979,

> http://qgis4.qgis.org:8081/qgisserver_demo is Down again

It's the adress of QGIS Server and it seems online:

``` bash
$ curl http://qgis4.qgis.org:8081/qgisserver_demo
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException>
</ServiceExceptionReport>
```

And QWC2 demo on QGIS4 seems online too: http://qgis4.qgis.org:8081/qwc2_demo/

What difficulties did you meet?

**Comment by manisandro** [comment]
Closing since everything seems working normally.
