### ISSUE TITLE
Printing: preview doesn't match effective print extent

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#17]
It seems like the print preview in the web client does not match the effective printing area. It shows a bigger area than the print result in the PDF file.

I assume that the preview shows the area as if the map would not have a header and margins. The GetProjectSettings command delivers the correct frame size:

`<ComposerTemplates>
   <ComposerTemplate width="210" height="297" name="A4-Hoch">
     <ComposerMap width="189" height="233.5" name="map0"/>
  </ComposerTemplate>
  <ComposerTemplate width="297" height="210" name="A4-Quer">
    <ComposerMap width="276" height="147" name="map0"/>
  </ComposerTemplate>
   <ComposerTemplate width="297" height="420" name="A3-Hoch">
       <ComposerMap width="276" height="356.5" name="map0"/>
   </ComposerTemplate>
   <ComposerTemplate width="420" height="297" name="A3-Quer">
       <ComposerMap width="399" height="234" name="map0"/>
   </ComposerTemplate>
</ComposerTemplates>
`

QWC2 has to use the smaller size as defined in the <ComposerMap> element. It seems like currently it uses the width and height of the <ComposerTemplate> element.

**Comment by manisandro** [comment]
Hm the size is the one of the first ComposerMap element:

                        // use first map from GetProjectSettings
                        var composerMap = toArray(composerTemplate.ComposerMap)[0];
                        printTemplate.map = {
                            name: composerMap.$.name,
                            width: parseFloat(composerMap.$.width),
                            height: parseFloat(composerMap.$.height)
                        };

**Comment by andreasneumann** [comment]
did you work on that recently?

You can see at https://services.geo.zg.ch/qwc2/ that the preview definitely does not match the result in the PDF.

**Comment by andreasneumann** [comment]
![print_preview](https://cloud.githubusercontent.com/assets/884476/22556895/f5e8010e-e968-11e6-9cd9-e4c53978ae25.png)
Print Preview

![print_result](https://cloud.githubusercontent.com/assets/884476/22556894/f5e7b488-e968-11e6-8cc6-61a85ba3c39a.png)
Result in PDF

**Comment by andreasneumann** [comment]
So it seems there is an issue that the extent is not delivered correctly. The width/heigh ratio looks similar.

I also double checked that is not an issue with the WMS extents.

Same issue appears when I am zoomed in quite far. Extents do not match.

**Comment by manisandro** [comment]
Mh a possible issue is that the extent is passed in EPSG:3857 and not in the map projection.

**Comment by manisandro** [comment]
Please try with https://github.com/qgis/qwc2/commit/f4cda8ff7c69bb73eecf283a339aa2f947d4d4e8

**Comment by andreasneumann** [comment]
ok - that would explain it. Stupid EPSG:3857 - why is everyone assuming that this the one and only coordinate system in the world?

Will try your fix tomorrow. About to leave office. Thanks!

**Comment by manisandro** [comment]
@andreasneumann Did the fix work?

**Comment by andreasneumann** [comment]
Looks good - thanks a lot!
