### ISSUE TITLE
Error no such file install when running yarn install

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/qwc2-demo-app#170]
# Problem

Just following the instructions I get the error:

![no-file](https://user-images.githubusercontent.com/2510900/68672710-d8c1da80-055a-11ea-9211-e7c793cc9015.png)

**Comment by manisandro** [comment]
Looks like your `yarn` command isn't the package manager, but some other tool.

**Comment by NyakudyaA** [comment]
> Looks like your `yarn` command isn't the package manager, but some other tool.

So is it more an OS error than not finding the file. I did `sudo apt-get install yarn`

**Comment by NyakudyaA** [comment]
Thanks saw the problem being referenced here https://github.com/yarnpkg/yarn/issues/3189
