### ISSUE TITLE
Search layers & zoom to extent

### ISSUE THREAD

**Issue by bdus-dev** [qgis/qwc2-demo-app#171]
Hello,
I'm much interested in implementing a layers search following the `layerSearch()` function of SearchProviders.js. In the provided example there is a hardcoded example of the search of the term `bahnhof`.

It would be very interesting if the names of the WM- provided layers could be searched and if selected the map could be centred and zoomed to the layer extent. Is it possible to have the list of the layers in `layerSearch`, and for each of them the bbox.

**Comment by manisandro** [comment]
Zooming etc should already be the case (see [1]). What you need to do is implement the part which gathers the list of searchable layers and then filter that list. The implementation of this really depends on your use-case, and also the choice whether you do it entirely client-side (i.e. by looking through the layers contained by the themes.json loaded by the client), or whether you want to do it in a dedicated search service.

[1] https://github.com/qgis/qwc2/blob/master/components/Search.jsx#L393

**Comment by bdus-dev** [comment]
Thank you for the reply, it was very useful.
I could easily add the search functionality, but I'm not able to get the zoom to layer function. It would be great to have an activate & zoom to layer function on layer select. 

Any help will be much appreciated; follows my implementation of SearchProviders.

Thank you again!

    const Themes = require('../themes.json');
    ...
    const recursiveSearchLayer = function(string, searchIn, found, path) {

    if (!found){
        found = {
            id: "layers",
            title: "Layers",
            items: []
        };
    }
    
    searchIn.forEach(lay => {
        if (lay.sublayers){
            found = recursiveSearchLayer(string, lay.sublayers, found, lay.name + ' > ');
        } else {
            if ( lay.title.toLowerCase().includes(string.toLowerCase()) ){
                found.items.push({
                        type: SearchResultType.THEMELAYER,
                        id: lay.name,
                        text: path + '' + lay.title,
                        layer: lay
                    });
             }
         }
      });
      return found;
    }

    function layerSearch(text, requestId, searchOptions, dispatch) {
        const results = recursiveSearchLayer(text, Themes.themes.items[0].sublayers);
        dispatch(addSearchResults({data: [results], provider: "layers", reqId: requestId}, true));
    }

**Comment by bdus-dev** [comment]
I think I got it: I have to  enable `zoomToLayers` option in `config.json`:
`"zoomToLayers": true,`

**Comment by manisandro** [comment]
> I see there should be an alert in [1] to ask users if they want to turn on the layer, but I'm not sure ho to trigger it.

This is currently implemented for place results, i.e. if such a result is marked as being related to a specific layer, and that layer is invisible, then the notification is shown.

**Comment by lperozzi** [comment]
Hi @bdus-dev,

could you share your working example of a working layersearch?

**Comment by danceb** [comment]
@bdus-dev I would be interested in this, too!
