### ISSUE TITLE
Use layers group as "printLayer"

### ISSUE THREAD

**Issue by jmarsac** [qgis/qwc2-demo-app#174]
Hi,
I wish to use several layers as background *printLayer*. I tried using layers group but group name is directly sent to qgis-server instead of layers list. Is there any way to group some project layers for printing background ?

**Comment by stephaschu** [comment]
You can either use an array as printLayer: ` "printLayer": ["layer1", "layer2"] `
or in QGIS Desktop adding a WMS shortname for that group and use the shortname as printLayer.

**Comment by jmarsac** [comment]
Thank you @stephaschu for your help.

Unfortunately I tried the two solutions unsuccessfully
`
        "backgroundLayers": [
          
{
            "name": "mapnik",
            "printLayer": [
              "roads",
              "buildings"
            ],
            "visibility": true
          },
          {
            "name": "GEOGRAPHICALGRIDSYSTEMS.MAPS",
            "printLayer": "osmvosges"
          },
          {
            "name": "opentopomap",
            "printLayer": "buildings"
          }
        ],
`
"printLayer": ["roads","buildings"] for "mapnik" background prints no background layer and doesn't request it to qgis-server (see [mapnik.log](https://github.com/qgis/qwc2-demo-app/files/4019856/mapnik.log) )

"printLayer": "osmvosges" for "GEOGRAPHICALGRIDSYSTEMS.MAPS" background  prints no background layer but requests it to qgis-server (see [GEOGRAPHICALGRIDSYSTEMS.MAPS.log](https://github.com/qgis/qwc2-demo-app/files/4019855/GEOGRAPHICALGRIDSYSTEMS.MAPS.log) ).

"printLayer": "buildings" for "opentopomap" works fine. (see [opentopomap.log](https://github.com/qgis/qwc2-demo-app/files/4019852/opentopomap.log) )

If I remove "printLayer" field in themes.json, I can print these layers correctly.

All concerned layers are defined in QGIS project file (GetProjectSettings request result: [getprojectsettings.xml.txt](https://github.com/qgis/qwc2-demo-app/files/4019848/getprojectsettings.xml.txt) )

**Comment by manisandro** [comment]
Creating a layer group in QGIS and specifying the group name as the printLayer should work. `printLayer` does currently not support an array of layers. Closing, feel free to reopen if still relevant.
