### ISSUE TITLE
Allow user to specify the CRS of st (search text) coordinates in URL and Search Bar

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#178]
Mabye this is already an option in config.json or SearchProviders.js but I'd like to specify a different CRS than the current map CRS in the search bar along with the coordinates.  Something like

`http://localhost/index.html?st=2173539,262375&crs=EPSG:2274&s=1200`

The goal is to construct a URL that passes the coordinates along with the CRS (EPSG:2274 in my case) and have it place a small circle at that location on the map at startup.

Regards,

Rayner

**Comment by manisandro** [comment]
That should be doable with the recently added StartupMarker plugin [1][2], see also `hc` parameter as documented here [3].

[1] https://github.com/qgis/qwc2-demo-app/blob/master/js/appConfig.js#L61
[2] https://github.com/qgis/qwc2-demo-app/blob/master/config.json#L440
[3] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#url-parameters

**Comment by raynerhoward** [comment]
Thanks, had tried that before:

http://localhost/index.html?hc=true&c=2173539,262375&crs=EPSG:2274&s=1200

But it didn't work until I changed config.json to show:

  "projections": [
    {
      "code": "EPSG:2274",
      "proj": "+proj=lcc +lat_1=36.41666666666666 +lat_2=35.25 +lat_0=34.33333333333334 +lon_0=-86 +x_0=600000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs",
      "label": "NAD83 / TN-SP FT-US"
    }
  ],

Now to figure out how to change the marker to something a little more subtle, like a small semi-transparent circle . . .

Thanks,

Rayner

**Comment by manisandro** [comment]
Believe the original issue here is addressed.
