### ISSUE TITLE
Adding custom item to menu

### ISSUE THREAD

**Issue by TCM5** [qgis/qwc2-demo-app#180]
Hi guys

I already implemented a custom plugin that I want to be invoked as an menu item from Map & Tools. The item already shows on the menu because I already added to the config.json, but when the menu item is clicked noting occurs.

What's the steps to create a custom plugin and add to the menu?

I already tryied making a clong of Help.jsx plugin using an Help2.jsx but occurs the same result, the item is not invoked...

**Comment by manisandro** [comment]
If you add `debug=true` when running your QWC2 in development mode (so say `http://localhost:8081?debug=true`), you'll see that a click on a menu item (which is not an external link) results in a `setCurrentTask` action with task id equal to the key of the menu entry. Your plugin will then need to pick up whether the current application state is equal to that task id, and react accordingly. See i.e. [1] and all the logic dependent on the `currentTask` there.

[1] https://github.com/qgis/qwc2/blob/c698d6c9525bcc379739b12fa1fa23b1666f3682/components/SideBar.jsx#L43

**Comment by TCM5** [comment]
Thanks for the tips @manisandro.

Using the param for debug the output is what you said. The plugin key/name appears as the current taks but nothing occurs. The plugin I'm using for try this doesn't have any complex logic, just a output's a div like Help.jsx plugin

```
const React = require('react');

function renderHelp2() {
    return (<div>HELP2</div>);
}

module.exports = renderHelp2;
```

I compared with the core login for the Help.jsx and all the configurations and it's equal. What am i missing?

**Comment by manisandro** [comment]
As stated above, your plugin will then need to pick up whether the current application state is equal to that task id, and react accordingly.

You'll probably want to familiarize yourself a bit with react/redux to properly understand the mechanism.

**Comment by TCM5** [comment]
You are right! I must confess i'm not familiar with the redux mechanism (I'm still doing things in React without using redux in other project's). 

Thanks for the help, I will investigate a little bit more about this.
