### ISSUE TITLE
Layer Labels

### ISSUE THREAD

**Issue by elias-abou-hamad** [qgis/qwc2-demo-app#182]
Dear All,

I'm trying to add Layer Labels form the attribute table. it not feasible or there is a solution ?

Regards,
Elias

**Comment by manisandro** [comment]
Hi, it's not clear what you are asking here. There is no attribute table in QWC2.

**Comment by elias-abou-hamad** [comment]
hi all what i need to show the labels on the maps. please find attached picture.
![Capture](https://user-images.githubusercontent.com/61179100/74734487-55014380-5257-11ea-8e55-963732515500.PNG)

**Comment by manisandro** [comment]
If your project is set up to render labels, then QGIS Server will render them and QWC2 will display whatever map QGIS Server returns. QWC2 does not do any rendering of QGIS layers himself.
