### ISSUE TITLE
Label attribute

### ISSUE THREAD

**Issue by elias-abou-hamad** [qgis/qwc2-demo-app#183]
Hello,
I need to show a label attribute on a QWc2 map. As an example, i need to label points with their ID or polygons with their areas. 
I am not able to do the proper configuration or coding. 

I appreciate if anyone can help with this or can share a sample code for a similar case.
Thanks,
Elias

**Comment by manisandro** [comment]
Please don't open duplicate tickets, as I explained in #182, you need to do this in QGIS.

**Comment by elias-abou-hamad** [comment]
Hi ,
Thanks for your prompt reply.
Please advise how to do it in QGIS. since the labels are already shown in qgis but are not displayed on the map.
I need more insights please.

Thanks

**Comment by manisandro** [comment]
You'll want to ask on the QGIS users mailing list (https://lists.osgeo.org/mailman/listinfo/qgis-user)

**Comment by Poldy1705** [comment]
Which Label Rendering method do you use? Rule based Rendering is not yet supported by QGIS Server....

**Comment by elias-abou-hamad** [comment]
No it is not a rule based label. it is just an attribute label that i need to show on the map.
Is it a rendering issue that could be specified on the project?
