### ISSUE TITLE
Enable QGIS Server parallel rendering?

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#185]
Hello,

I'm using the QGIS Mapserver 3LIZ docker as WMS Server. Seeing in its debug log, it seems that the parallel rendering is disabled. Is there any way to enable it?

**Comment by lucamanga** [comment]
The QGIS Server documentation states:

**QGIS_SERVER_PARALLEL_RENDERING**
Activates parallel rendering for WMS GetMap requests. _**It’s disabled (false) by default**_. Available values are:

    0 or false (case insensitive)
    1 or true (case insensitive)

**Comment by manisandro** [comment]
Sorry but this is not related to qwc2.
