### ISSUE TITLE
Add a legend sidebar

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#186]
Hi,

it would be nice to have a sepearate legend sidebar, and not integrated into layers tree.
For example, try to search a legend item in a tree with over 100 layers (common in projects for Urban planning, for example) and you find that it is not too comfortable.

Also, it could enable content based legend (supported in QGIS Server)

**Comment by manisandro** [comment]
@lucamanga There is now a new eye-icon in the LayerTree panel titlebar which filters all invisible layers from the layertree. Does that help?

**Comment by lucamanga** [comment]
Interesting. Does it has support for content-based legend?

**Comment by manisandro** [comment]
That's an interesting point, currently it only honours the active/inactive checkbox state, but it might be desireable to also honour whether a layer is actually visible due to minScale/maxScale.

**Comment by manisandro** [comment]
Implemented: https://github.com/qgis/qwc2/commit/f4cd163ef58cb96e924cd62dbd78456db622ee15
