### ISSUE TITLE
Wrong opacity in themes.json

### ISSUE THREAD

**Issue by sigmoe** [qgis/qwc2-demo-app#187]
The themes.json is created automatically thanks to 'yarn run prod' command, but the themes.json resulting doesn't take into account the opacity of the layer (the opacity is always 255 for all the layers in themes.json whereas in my qgz project, I have some layers with 50% of opacity).

**Comment by manisandro** [comment]
This is due to QGIS server until very recently not exposing the transparency in the project settings. You'll need to use a QGIS Server version which contains [1].

[1] https://github.com/qgis/QGIS/commit/07b64aaa188cd2c47f8bf5b04fb868a6d7984aff#diff-be5b1592dd6f3dfe11fd6f648158ffee
