### ISSUE TITLE
Wrong interpretation of HTML tooltip

### ISSUE THREAD

**Issue by sigmoe** [qgis/qwc2-demo-app#188]
I have an HTML tooltip on a layer, and QWC display it with a wrong interpretation of the width.
The HTML code is:
```
<style> 
div
{
	font-family: verdana;
	font-size: 12px;
	width: 250px;
	text-align: center;
}
.sgmtitre 
{ 
     	color: #ffffff; 
     	font-weight: BOLD;
	border-style: solid; 
	border-width: 1px;
	background-color: #fa9383;
	line-height: 20px;
} 
.sgmligne 
{ 
     	color: #aa2606; 
	line-height: 15px;
	margin-top: 10px;
} 
</style> 
<div class="sgmtitre">Client SIGMOÉ</div>
<div class="sgmligne">[% "raisonsoc" %]</div>
```
Two lines are displayed, and the problem is that the first line (`<div class="sgmtitre">`) exceeds the shape of the tooltip.

**Comment by manisandro** [comment]
The `div` style declarations are interfering with the ones set internally by QWC2. You can wrap your divs in an extra container element to which you can then apply your style, i.e.

    <style>
    div.maptipcontainer
    {
            font-family: verdana;
            font-size: 12px;
            width: 350px;
            text-align: center;
    }
    .sgmtitre
    {
            color: #ffffff;
            font-weight: BOLD;
            border-style: solid;
            border-width: 1px;
            background-color: #fa9383;
            line-height: 20px;
    }
    .sgmligne
    {
            color: #aa2606;
            line-height: 15px;
            margin-top: 10px;
    }
    </style>
    <div class=\"maptipcontainer\">
    <div class=\"sgmtitre\">Client SIGMOÉ</div>
    <div class=\"sgmligne\">Test</div>
    </div>
