### ISSUE TITLE
Demo app 'Wolfsburg' seems to be dead

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#191]
It seems to be that the demo app on the server <http://qwc2.sourcepole.ch/wms/wolfsburg/qwc2_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings> is dead.

It would be great to have a bundle of a working instance - the parameter files themesConfig.json, config.json, etc. and a working demo app, or the corresponding .qgs file. The demos at Kanton Glarus and Kanton Solothurn make a lot of appetite, but are not helpful to set up a demo app :-((

**Comment by manisandro** [comment]
Right, I was hoping it might be a transient thing - but looks like we need to replace that one.

**Comment by manisandro** [comment]
Removed
