### ISSUE TITLE
Could QWC2 edit and save PostGIS polygon data?

### ISSUE THREAD

**Issue by kimtaedoo** [qgis/qwc2-demo-app#195]
Hello everyone.

I searching new tool, replaceable our existing system.
Existing system is running QGIS desktop client + PostGIS on PostgreSQL, and edit vector polygon data.

I checking QWC2 demo site.
https://map.geo.gl.ch/

I think, if Redlining polygon can view and save with PosGIS, it is matching our needs.
But I can't understanding with reading any official document.

Where document read can I get this answer?
Is it possible? And how do I this?

Regards.

**Comment by manisandro** [comment]
Redlining is client-side only (though you can export it as GeoJSON and reimport it if you want).

There is an editing module which works in conjunction with the data service [1], the idea is that you have a postgis table as datasource for a qgis layer which is displayed in the client, with the data service you can edit the features in the respective table. You can also use any custom server side editing backend, you just need to adapt the EditingInterface.js accordingly.


[1] https://github.com/qwc-services/qwc-data-service/

**Comment by kimtaedoo** [comment]
@manisandro 
Thanks a lot information.
I understood, and once more think our system update.
