### ISSUE TITLE
is there a way to disable ``startupMode`` when adding a permalink so that the map stays..

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#196]
If the startup mode is enabled with ``FOLLOWING``.. the location given in permalinks is quickly changed with that of the GPS. Is there a way to disable this other than passing a search text?

From docs:
Set ``startupMode`` in the ``LocateSupport`` options of the Map configuration in ``config.json``. Possible values are ``DISABLED``, ``ENABLED`` or ``FOLLOWING``. If a search text is passed via st URL parameter, the ``startupMode`` is ignored.

**Comment by manisandro** [comment]
Uhm, what's the use case? Following by default unless a position is specified?

**Comment by tudorbarascu** [comment]
Basically, when someone on the field (mobile device) receives a permalink and the Default mode is set on following.. that person is unable to see the map as it should as the map quickly goes to the GPS position.  So basically, something like creating a permalink with a gps enabled off would be great.
Otherwise, we need to turn off Following by default in order to make permalinks usable. Hope it's clear. Thank you for considering.

**Comment by manisandro** [comment]
startupMode is also ignored if `hc=1` is passed in the URL (hc meaning "highlight coordinate", which results in a pin added to the position specified by `c` if the StartupMarker plugin is enabled).

**Comment by manisandro** [comment]
Closing, feel free to reopen if the `hc=1` approach does not meet your needs.
