### ISSUE TITLE
Add different export format 

### ISSUE THREAD

**Issue by FlavBd** [qgis/qwc2-demo-app#198]
Hello, 

Currently there are two formats to export data : json and csv. We can configure it in the application by setting _exportFormat_ attribute in config.json.
It could be nice for the user to choose the format in a drop-down list before exporting data.

Also I suggest others formats like kml, geopackage or geojson. 

We have already talked about this feature in [the mailing list](http://osgeo-org.1560.x6.nabble.com/New-features-in-QWC2-td5434695.html).

**Comment by manisandro** [comment]
Geojson support was merged, happy to accept other PRs if additional formats are desired.
