### ISSUE TITLE
Highlight geometry at feature info requests do not work on EPSG other than EPSG:3857

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#2]
Seems like when doing a feature info request, the hightlight geometry fails, if the main applications EPSG is not EPSG:3857.

Perhaps the WKT string needs to be attached with the proper SRID?

**Comment by manisandro** [comment]
Can you post the XML reply from the identify request?

**Comment by andreasneumann** [comment]
<GetFeatureInfoResponse>
<Layer name="Grundnutzung">
<Feature id="4401">
<Attribute value="1705" name="BFS-Nr"/>
<Attribute value="Neuheim" name="Gemeinde"/>
<Attribute value="12126" name="Fläche"/>
<Attribute value="Bauzonen" name="Grundnutzung PBG Kanton"/>
<Attribute value="Wohnzonen" name="Grundnutzung Kanton"/>
<Attribute value="Wohnzone 2" name="Grundnutzung Gemeinde"/>
<Attribute value="W2" name="Zonencode Gemeinde"/>
<Attribute value="Genehmigung Regierungsrat" name="Rechtsstatus"/>
<Attribute value="2" name="Geschosszahl"/>
<Attribute value="10.7" name="Firsthöhe"/>
<Attribute value="0.40" name="Ausnützungsziffer"/>
<Attribute value="0.00" name="Baumassenziffer"/>
<Attribute value="ES II" name="Lärmempfindlichkeitsstufe"/>
<Attribute value="AV gerechnet" name="Herkunft"/>
<Attribute value="1994-02-28" name="Datum"/>
<Attribute value="" name="Bemerkung"/>
<Attribute value="W2" name="Zonenbeschrieb"/>
<BoundingBox CRS="EPSG:2056" maxx="2685997.49" minx="2685863.773" maxy="1228207.707" miny="1228028.402"/>
<Attribute value="Polygon ((2685979.128 1228100.738, 2685987.334 1228130.386, 2685995.137 1228158.556, 2685997.49 1228166.93, 2685980.898 1228177.714, 2685961.747 1228190.158, 2685956.515 1228193.569, 2685936.481 1228206.626, 2685934.795 1228207.707, 2685932.053 1228203.775, 2685931.455 1228202.937, 2685929.242 1228199.891, 2685928.014 1228198.238, 2685928.014 1228198.238, 2685925.066 1228194.469, 2685922.997 1228191.903, 2685922.052 1228190.751, 2685918.973 1228187.087, 2685917.795 1228185.718, 2685917.795 1228185.718, 2685914.845 1228182.274, 2685914.745 1228182.159, 2685911.837 1228178.88, 2685911.837 1228178.88, 2685908.542 1228175.364, 2685905.186 1228171.905, 2685903.039 1228169.755, 2685901.77 1228168.506, 2685898.295 1228165.166, 2685894.762 1228161.888, 2685893.83 1228161.042, 2685890.197 1228157.822, 2685873.983 1228143.228, 2685863.773 1228135.044, 2685864.892 1228133.789, 2685885.968 1228110.151, 2685900.886 1228093.383, 2685959.128 1228028.402, 2685979.128 1228100.738))" type="derived" name="geometry"/>
</Feature>
</Layer>
<Layer name="Überlagernde Bestimmungen"/>
<Layer name="Überlagernde Zone"/>
<Layer name="Überlagernde Linie"/>
<Layer name="Überlagernde Punkt"/>
</GetFeatureInfoResponse>

**Comment by andreasneumann** [comment]
Seems like the actual geometry comes without EPSG code, but the BoundingBox element contains the correct EPSG code.

Either we use the global EPSG setting from "config.json" by default, or we parse the `<BoundingBox/>` elements EPSG, which is probably safer, in case QGIS server delivers a different EPSG compared to what is set in config.json

**Comment by manisandro** [comment]
We already rely on the BoundingBox for the CRS. Digging into the MapStore2 code it looks like their vectorlayer needs the CRS to be explicitly defined or else it will fall back to EPSG:3857. Working on it.

**Comment by manisandro** [comment]
Fixed in
https://github.com/sourcepole/MapStore2/commit/5bc35493dc5f054093d8a0b68bc3aae081f3726e
https://github.com/qgis/qwc2/commit/ebc3f3e6488f42156c3814b4392ccb214636a887
