### ISSUE TITLE
Add zoom to layer also for imported layers

### ISSUE THREAD

**Issue by Poldy1705** [qgis/qwc2-demo-app#200]
Is it possible to add the zoom to layer function also for imported layers?

**Comment by stephaschu** [comment]
As are there are several ways to import layers. How do you import layers? Do you have an example?
This should work out of the box if your imported layer has a bbox object:

```
bbox: {
  bounds: [ -180, -90, 180, 90],
  crs: "EPSG:4326"
}
```

**Comment by Poldy1705** [comment]
I import the layer by importing al local geojson file. There is no bbox object.
![import_local_geojson](https://user-images.githubusercontent.com/29286915/80999525-1e45cd00-8e45-11ea-9a0a-ba540ecfb418.png)

![import_local_geojson_2](https://user-images.githubusercontent.com/29286915/80999717-6bc23a00-8e45-11ea-9a03-54a9ad88c45d.png)


[armaturen.geojson.txt](https://github.com/qgis/qwc2-demo-app/files/4576517/armaturen.geojson.txt)

It's also the same when you export your redlining layer as json and re-import it. There is no bbox object by default.

**Comment by manisandro** [comment]
Done in https://github.com/qgis/qwc2/commit/45ba9df1a9a891d8299a1bbdf766947bb1caed18
