### ISSUE TITLE
Style Icon „Zoom to feature“ on mobile devices

### ISSUE THREAD

**Issue by Poldy1705** [qgis/qwc2-demo-app#203]
The Styling for the Icon „Zoom to Feature“ in the Identity viewer on mobile devices (IOS) is not correct.

![35C41A1F-4A3F-4B30-951B-522AC529E1A2](https://user-images.githubusercontent.com/29286915/81001290-cceb0d00-8e47-11ea-8ca4-01eb7d5589e9.jpeg)
![8C204654-C0F4-4FEB-B8A8-4FDD4A8FC142](https://user-images.githubusercontent.com/29286915/81001296-cf4d6700-8e47-11ea-9374-42b066c875b7.jpeg)

**Comment by manisandro** [comment]
@stephaschu Can you look into this?

**Comment by stephaschu** [comment]
Sorry, I dont have access to IOS. 
I just checked with emulated iPad/iPhone on Firefox and a long layer name but no issues here

![zoomtofeature](https://user-images.githubusercontent.com/30912074/82813801-1c948580-9e96-11ea-9b1a-52e4fa355e9c.png)

**Comment by stephaschu** [comment]
hmm just tested with chrome 81 on android 9, seems ok:

![Screenshot-20200527-092234-Chrome](https://user-images.githubusercontent.com/30912074/82991357-d5290900-9ffd-11ea-9518-69277cf8b2a9.jpg)

**Comment by stephaschu** [comment]
thx for the call @StefanNiemeier, I could reproduce this now and should be fixed in https://github.com/qgis/qwc2/pull/109

@manisandro does this break anything else?
