### ISSUE TITLE
WSGI for MS SQL

### ISSUE THREAD

**Issue by catalinmiraute** [qgis/qwc2-demo-app#204]
Hello, I a new user of QWC2 and I am trying to implement a feature search.
My DB is MS SQL.
I see that WSGI (https://github.com/qgis/QGIS-Web-Client/tree/master/wsgi) is created only for PostgreSQL.
Is there any chance to have something similar for project with data on MS SQL?
Tks!

**Comment by lucamanga** [comment]
Have you installed the MS SQL driver?
See here
https://docs.microsoft.com/en-us/sql/connect/python/python-driver-for-sql-server?view=sql-server-ver15

**Comment by catalinmiraute** [comment]
No, I am newbie in this area :) so you need to have patience with me.
After I install this what is the next step?

**Comment by lucamanga** [comment]
there are plenty of tutorials on web.
One example:

https://datatofish.com/how-to-connect-python-to-sql-server-using-pyodbc/

**Comment by catalinmiraute** [comment]
And the scripts from here https://github.com/qgis/QGIS-Web-Client/tree/master/wsgi are remaining the same?

**Comment by lucamanga** [comment]
obviously not. Those files are only examples. Read the comments. It's not
easy as 1-2-3, though.

-- 





Comune di Trento 

via Belenzani, 19 - 38122 Trento | C.F e P. IVA: 
00355870221

tel. +39 0461.884111 | www.comune.trento.it 
<http://www.comune.trento.it>

**Comment by lucamanga** [comment]
Moreover, those examples are functional only for Postgres

**Comment by catalinmiraute** [comment]
I have an Postgres DB and I want to adapt those scripts.

**Comment by lucamanga** [comment]
Well, the documentation is here, read the paragraph **Implementing search providers in js/SearchProviders.js**

https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md

and the linked sample js/SearchProviders.js

**Comment by manisandro** [comment]
Closing since this is not really a QWC2 issue - documentation for the client side interfaces is there, rest is backend specific.
