### ISSUE TITLE
Import WMS/WFS 

### ISSUE THREAD

**Issue by catalinmiraute** [qgis/qwc2-demo-app#205]
Hello, when I am trying to add via the import function a WMS into the QWC2 map, there are some issues with the "drawing" of it.
The WMS permits EPSG 3844 and 4326.
Since I am using the Romanian CRS EPSG 3844, I know about the axis orientation and I made the following change in the CoordinatesUtils.js:
return axis || 'neu'  (northing, easting, up - useful for “lat/long” geographic coordinates, or south orientated transverse mercator)
The default value was 'enu' (easting, northing, elevation).
I also added 3844 in config.json file:
    {
      "code": "EPSG:3844",
      "proj": "+proj=sterea +lat_0=46 +lon_0=25 +k=0.99975 +x_0=500000 +y_0=500000 +ellps=krass +towgs84=2.329,-147.042,-92.08,-0.309,0.325,0.497,5.69 +units=m +no_defs",
      "label": "Stereo 70 / Pulkovo 42(58)"
    }
This happens only if I am trying to add this WMS service by import.
If I am putting the WMS into the QGIS map project, as a layer, it is ok.

**Comment by manisandro** [comment]
According to [1] you should be using the proj string

    +proj=sterea +lat_0=46 +lon_0=25 +k=0.99975 +x_0=500000 +y_0=500000 +ellps=krass +towgs84=33.4,-146.6,-76.3,-0.359,-0.053,0.844,-0.84 +units=m +no_defs

[1] https://epsg.io/3844
