### ISSUE TITLE
enable searching on WMS/WFS layers, with no micro-service?

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#206]
Hello,

it would be nice to have this feature: to able to search inside WMS/WFS layers, without writing the micro-service for searching.
For example, I have a WMS layer and then QWC2 does a WMS searching.

I didn't found it in documentation if is possible without the micro-service.

**Comment by manisandro** [comment]
Uhm how would this work, at least concerning WMS? You need something with access to the dataset behind the WMS suppling the feature info, so either a micro-service of the WMS server via GetFeatureInfo?

**Comment by lucamanga** [comment]
I see that QGIS Server has FILTER for WMS searches:

https://docs.qgis.org/3.10/en/docs/training_manual/qgis_server/wms.html#moderate-fa-use-filter-opacities-and-styles-parameters

**Comment by manisandro** [comment]
Assuming GetFeatureInfo also takes the Filter parameter, you should be able to write a custom search provider which returns features matching your filter.
