### ISSUE TITLE
How to setup proxy service to avoid CORS error on QWC2 Test 2056?

### ISSUE THREAD

**Issue by dmestudent** [qgis/qwc2-demo-app#208]
Hello QWC2 Dev Team, 

first of all I want to say thank you for developing such a great QGIS webclient on top of a modern software stack. 

I have a question regarding the proxy service. I downloaded and setup the qwc2-demo-app. I also installed python, pip and flask on my elementaryOS machine (ubuntu) and exported + started the proxy.py service as described here https://flask.palletsprojects.com/en/1.1.x/quickstart/. 

```
 * Serving Flask app "proxy.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
I also edited the config.json 
```
  "proxyServiceUrl": "http://127.0.0.1:5000/",
```
afterwards I started the qwc2-demo-app using "yarn start".

The app is up and running but if I open the QWC2 Test 2056 Theme and click on a brown bulding for example,  I still receive the following error: 
```
Access to XMLHttpRequest at 'http://qwc2.sourcepole.ch/wms/themes/test?service=WMS&version=1.3.0&request=GetFeatureInfo&id=387afe7c-859c-4ff0-b9ea-4cb995ef5586&layers=a,c,b,Orthofoto_2015_stdzh_0.5_jpeg&query_layers=a,c,b,Orthofoto_2015_stdzh_0.5_jpeg&x=51&y=51&i=51&j=51&height=101&width=101&srs=EPSG:2056&crs=EPSG:2056&bbox=2682654.525799538,1247168.9456867238,2684227.5539849196,1248741.9738721058&info_format=text%2Fxml&with_geometry=true&with_maptip=false&feature_count=20&FI_POINT_TOLERANCE=16&FI_LINE_TOLERANCE=8&FI_POLYGON_TOLERANCE=4' from origin 'http://0.0.0.0:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Am I missing or misunderstanding something here? 

My second question is, is there any platform like a forum or a discord server where people using this project can communicate and help each other? I would love to share my experience and questions regarding this great project with other people. 

Best regards
dmeStudent

**Comment by manisandro** [comment]
So usage of the proxy service has never been complete in qwc2, so I've gone ahead and removed it completely.

* For development, it's easier to just use a CORS plugin (i.e. https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/)
* For production, you should ensure that all services run on the same origin, or have the services add the headers as necessary. Using a proxy service is also a security risk because it can be abused for other purposes.

**Comment by tony-dwire-paradigm** [comment]
Just in case anyone ends up here, and you want to be able to reach the services on another origin, you can edit the nginx configuration for the api gateway and add the header. For me this meant adding the `Access-Control-Allow-Origin: *` header to the ows locatoin in the nginx config (under api-gateway folder):

```nginx
server {
    listen       80;
    server_name  localhost;
    ...
    location /ows {
        proxy_pass http://qwc-ogc-service:9090;
        add_header Access-Control-Allow-Origin *; # THIS LINE HERE
    }
    ...
```
