### ISSUE TITLE
Raster image export needs a DPI parameter

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#21]
The old QWC1 had a dpi parameter for the export to allow the export of higher-dpi rasters. This is important for printed publications, like reports, etc.

Similar to the image format combobox there should be a second combobox with the dpi choice, taken from the defaultPrintResolutions parameter.

**Comment by manisandro** [comment]
Done in https://github.com/qgis/qwc2/commit/35bc34ff97c1c1cf4924a02c2e2bea7782c07bc2
