### ISSUE TITLE
edit form problems

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#210]
Hi @manisandro I have updated my qwc2.
The problem is that the edit feature doesn't work anymore. I use edit an editConfig like the test2056_edit.json config without qt ui. The problem is if I try to pick a feature nothing happens even if the respons from getFeature is ok. From my investigations the problem is from this commit https://github.com/qgis/qwc2/commit/362646b3194b84bc5efd4d63f38fa135d0d56563
If I comment the if from here https://github.com/qgis/qwc2/blob/405fd0c9cd59adf1439fb97ffa9ec2a715009866/plugins/Editing.jsx#L96 to L101 it works.
Can you help me.

Thank you

**Comment by manisandro** [comment]
Ups sorry I forgot to commit the update to the EditingInterface, see [1].

[1] https://github.com/qgis/qwc2-demo-app/commit/fbedeb7cc32497d8642ccc507a89e6f3aac4ae84

**Comment by luciman** [comment]
It works, but you forgot to export the new modules. I made a pull request.
Thank you
