### ISSUE TITLE
Problem Updating a qgis web map. 

### ISSUE THREAD

**Issue by eduardojsilvajr** [qgis/qwc2-demo-app#219]
Hello, i have a QWC2 serving a WMS.

this WMS is posting a shp that has some attributes that need daily updating but if a just change the shapefile the npm crashes with the error bellow and because of this i've been updating manually the data.

` Reading themesConfig.json
ERROR reading WMS GetProjectSettings of http://10.1.183.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=/home/dgeo/Projeto_qgis/projeto.qgz:
 { Error: Request failed with status code 500
    at createError (/home/dgeo/qwc2-demo-app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/dgeo/qwc2-demo-app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/dgeo/qwc2-demo-app/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config: 
   { url: 'http://10.1.183.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz',
     method: 'get',
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.19.0' },
     proxy: null,
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     data: undefined },
  request: 
   ClientRequest {
     domain: null,
     _events: 
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 251,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 9,
        [Symbol(bytesRead)]: 271 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 251,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 9,
        [Symbol(bytesRead)]: 271 },
     _header: 'GET /cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: 10.1.183.45\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz',
     _ended: true,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://10.1.183.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz',
        redirects: [],
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable: 
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://10.1.183.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz' },
     [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response: 
   { status: 500,
     statusText: 'Internal Server Error',
     headers: 
      { date: 'Thu, 25 Jun 2020 17:07:11 GMT',
        server: 'Apache/2.4.29 (Ubuntu)',
        'content-length': '54',
        'access-control-allow-origin': '*',
        connection: 'close',
        'content-type': 'text/xml; charset=utf-8' },
     config: 
      { url: 'http://10.1.183.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz',
        method: 'get',
        headers: [Object],
        proxy: null,
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        data: undefined },
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: 10.1.183.45\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings&map=%2Fhome%2Fdgeo%2FProjeto_qgis%2Fprojeto.qgz',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: '<ServerException>Layer(s) not valid</ServerException>\n' },
  isAxiosError: true,
  toJSON: [Function] }
ERROR: Could not read GetProjectSettings

npm ERR! Linux 5.3.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "themesconfig"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! QWC2App@1.1.0 themesconfig: `node qwc2/scripts/themesConfig.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the QWC2App@1.1.0 themesconfig script 'node qwc2/scripts/themesConfig.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the QWC2App package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node qwc2/scripts/themesConfig.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs QWC2App
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls QWC2App
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dgeo/qwc2-demo-app/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. `

i searched npm ERR! code ELIFECYCLE on google and have tried:

`npm cache clean --force, 
 rm -rf node_modules package-lock.json
 npm install
 yarn upgrade`

this is my npm-debug:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'themesconfig' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prethemesconfig', 'themesconfig', 'postthemesconfig' ]
5 info lifecycle QWC2App@1.1.0~prethemesconfig: QWC2App@1.1.0
6 silly lifecycle QWC2App@1.1.0~prethemesconfig: no script for prethemesconfig, continuing
7 info lifecycle QWC2App@1.1.0~themesconfig: QWC2App@1.1.0
8 verbose lifecycle QWC2App@1.1.0~themesconfig: unsafe-perm in lifecycle true
9 verbose lifecycle QWC2App@1.1.0~themesconfig: PATH: /usr/share/npm/bin/node-gyp-bin:/home/dgeo/qwc2-demo-app/node_modules/.bin:/tmp/yarn--1593105336417-0.6685744916298275:/home/dgeo/qwc2-demo-app/node_modules/.bin:/home/dgeo/.config/yarn/link/node_modules/.bin:/home/dgeo/qwc2-demo-app/node_modules/.bin:/home/dgeo/.yarn/bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle QWC2App@1.1.0~themesconfig: CWD: /home/dgeo/qwc2-demo-app
11 silly lifecycle QWC2App@1.1.0~themesconfig: Args: [ '-c', 'node qwc2/scripts/themesConfig.js' ]
12 silly lifecycle QWC2App@1.1.0~themesconfig: Returned: code: 1  signal: null
13 info lifecycle QWC2App@1.1.0~themesconfig: Failed to exec themesconfig script
14 verbose stack Error: QWC2App@1.1.0 themesconfig: `node qwc2/scripts/themesConfig.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid QWC2App@1.1.0
16 verbose cwd /home/dgeo/qwc2-demo-app
17 error Linux 5.3.0-46-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "themesconfig"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error QWC2App@1.1.0 themesconfig: `node qwc2/scripts/themesConfig.js`
22 error Exit status 1
23 error Failed at the QWC2App@1.1.0 themesconfig script 'node qwc2/scripts/themesConfig.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the QWC2App package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node qwc2/scripts/themesConfig.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs QWC2App
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls QWC2App
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

some help, pls?

**Comment by lucamanga** [comment]
If you go to that URL: http://10.1.183.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=/home/dgeo/Projeto_qgis/projeto.qgz 
what happens?

**Comment by manisandro** [comment]
The 500 response code indicates a QGIS Server issue. You might want to enable logging to get more info [1].

Closing as not a QWC2 issue.

[1] https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/config.html
