### ISSUE TITLE
GetCapabilities and themesConfig.json

### ISSUE THREAD

**Issue by sggreener** [qgis/qwc2-demo-app#220]
The guide says that themes.json is generated from themesConfig.json.

So we am trying to build a themesConfig.json for our qGIS Server WMS. 

The example json file is helpful but nothing (as far as we can see) fully documents the json file, so we have no idea which items  need to be filled in, which not, and what filling in an item produces in the client.

Given that we want to do nothing more than configure QWC2 to serve all our qGIS Server WMS layers, is there a tool around that takes a WMS GetCapabilities XML and generates a base themesConfig.json document? 

regards
Simon

**Comment by manisandro** [comment]
The themesConfig.json file is documented here [1]

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#configuring-the-themes-in-themesconfigjson

**Comment by sggreener** [comment]
I have seen the document you reference and, with a closer reading, can now see how to use the python script to generate themes.json from themesConfig.json.

However, other than  a general pointer to the idea of generating a themes.json from themesConfig.json, there is no actual example of a themsConfig.json that references a WMS server so that the generations script can extract and build a themes.json that can be used to configure QWC2 for my WMS.

The referenced sample themesConfig.json simply has a tag structure and does not contain the GetCapabilities example I am after.

https://github.com/qgis/qwc2-demo-app/blob/master/themesConfig.json

This seems to me to be so fundamental that it warrants a more detailed description and worked example..

**Comment by manisandro** [comment]
Not sure what you mean, the structure of the themesConfig.json and the fields of the individual sections is documented, i.e. the part

![image](https://user-images.githubusercontent.com/1298852/86446241-f8895700-bd13-11ea-86db-f2c986617f34.png)

The example gives you a complete example. In themesConfig.json you specify the URL of the WMS service, the themes.json generator script then downloads the capabilities and builds the full theme configuration.

**Comment by sggreener** [comment]
No, I disagree that what we needed was clearly documented. 

The sample themesConfig.json was of no use.

If the GetCapabilities example was as clear as you claim why did it take us 4 days to create a json document that was clear and worked?

But, here's the thing:  that example came from someone who worked it out over a 2 week period.

We would all like that time back.

Your documentation is highly technical from the dev team's perspective but lacks end user focus. 

QWC2 appears to be the best client around which is why we persevered. I hope that improved documentation with an end user focus can be created which will increase its uptake.

Regards
Simon

⁣Get BlueMail for Android ​

**Comment by bstroebl** [comment]
@sggreener feel free to improve the documentation in a manner usable for end users and make a pull request, I am convinced the devs will happily merge it.
