### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by sggreener** [qgis/qwc2-demo-app#222]
The main documentation talks about being able to add in new projections.

All our data is in ESPG:28356.

I have read the doco and I cannot work out how to change appConfig.js to add in a new projection, and then how to push that projection through to the client.

Can you provide an example?

Simon Greener

**Comment by manisandro** [comment]
Just specify them in config.json, see [1]

[1] https://github.com/qgis/qwc2-demo-app/blob/master/config.json#L34
