### ISSUE TITLE
Qwc2 documentary suggestion

### ISSUE THREAD

**Issue by kirui-max** [qgis/qwc2-demo-app#226]

**Comment by kirui-max** [comment]
There is no documentation on how to begin from scratch, get the qwc2 and create a qwc2 considering not every person is familiar with how to do it based on operating system be it windows or Ubuntu or etc. I would like to bring a documentation to better the documentation on how to. I have been trying to install qgis server and succeeded and get the qwc2 but in vain on getting qwc2. I used lubuntu.
The documentation has to be better, can anyone please respond

**Comment by tudorbarascu** [comment]
@kirui-max The documentation is at https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md The examples in the code are good enough to get you going..
