### ISSUE TITLE
Printing issue?

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#228]
Hello, I need help on printing support. I have done these steps:

1) In QGIS desktop I have created a Print Layout named "A4" with a map and saved the project;
2) I have added this to themsConfig.json:
```
        "defaultPrintScales": [80000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000, 500],
        "defaultPrintResolutions": [150, 75],
```
3) I have run this command: ```yarn run themes config```
4) reloaded the webpage, when I click on the print button the page becomes blank and in the Console I see this error:
```Uncaught TypeError: n.props.theme.params is undefined```
at the row of ```Print.jsx:264:80```:
```
                        <input readOnly={true} name="MAP" type={formvisibility} value={this.props.theme.params.MAP || ""} />
```

**Comment by lucamanga** [comment]
Addendum: in the compiled ```themes.json``` there are these rows:

```
        "print": [
          {
            "name": "A4",
            "map": {
              "name": "map0",
              "width": 297,
              "height": 210
            }
          }
        ],
```

**Comment by lucamanga** [comment]
I'll attach the themes.config:

```https://cartografia.comunelavis.it/themes.json```

and the map is visible from:

```https://cartografia.comunelavis.it/```

**Comment by manisandro** [comment]
Uhm this is working fine as far as I can see?

![image](https://user-images.githubusercontent.com/1298852/89776144-950bf980-db09-11ea-85ee-215199c43cb1.png)

**Comment by lucamanga** [comment]
can you explain me the steps on how did you show that Print options?

**Comment by manisandro** [comment]
I just took the current qwc2 master and directly used your themes.json, nothing else actually.

**Comment by lucamanga** [comment]
Ok, with your method is all working, now.
