### ISSUE TITLE
[Question] Theme Switch on SearchResult Select

### ISSUE THREAD

**Issue by dmestudent** [qgis/qwc2-demo-app#229]
Hello, 

I wrote my own SearchProviders and their working as intended. My question is, if it is supported or would be possible to switch the theme if the selected search results location is on another theme. So in my case I have a building with multiple floors split into multiple themes. 

When I now search for a room that is for example part of the ground floor, but I am currently on the upper floor theme, I would like to switch to the ground floor themeand mark the room on the map once the search result is clicked. 

Is something like that possible or maybe already supported? 

Thanks in advance 👍 

Greetings dmestudent

**Comment by manisandro** [comment]
Hello
No there is no support for this currently, but one could extend the result structure to contain a "theme" field, and then extend the search component to honor that field if specified.

**Comment by dmestudent** [comment]
Hello @manisandro and thank you for the quick response. So I followed your idea of adding a theme field and I also realized the theme switch once a search result from another theme is clicked. My current problem atm is getting the "map marker logic" working again.

I guess after the theme is switched it completely resets the viewport, removes the current search and therefore has no reference anymore on how and where to place the marker.

Greetings

**Comment by manisandro** [comment]
In Search.jsx there is logic which causes the search to get cleared if the theme changes. You could add a field to the search state which blocks this behaviour.

**Comment by dmestudent** [comment]
Thank you @manisandro it works like charm 👍 Just added a field to my backend entity so that I can pass the targetThemeId. I intercept within the SearchResultType.PLACE conditional check and execute my theme switch code. 

I also modified componentWillReceiveProps for the Search.jsx by commenting out the first if condition which was removing the searchresult layer. 

At the moment I can no see any unwanted behavior and everything seems to work as intended in my usecase. 

Thank you for your time and this great software in general.

Best regards,
dmestudent

**Comment by manisandro** [comment]
Glad it works - if you feel like this is also interesting for other users, please consider proposing your extensions in a pull request. Thanks.
