### ISSUE TITLE
by searching a linesting the result marker ins in center of gravity

### ISSUE THREAD

**Issue by tomep** [qgis/qwc2-demo-app#23]
when i searching e feature like linesting the result show me e marker in center of gravity and not on the line selb.
![suche](https://cloud.githubusercontent.com/assets/26709746/24354975/5f7bcbb4-12f4-11e7-8152-47476f1d82fd.png)

regards
tom

**Comment by andreasneumann** [comment]
I agree - this is an issue for LineString search results.

It may also be an issue with results for banana shaped polygons.

My suggestion is to add a bit of intelligence to the search provider. The search result list could contain an additional point geometry (wkt) for the result marker. The serverside database / script could generate this geometry, e.g. for linestrings at the 50% point of the line along the line, or at a centroid guaranteed to be on the polygon. Postgis provides such functions.

I will add this to our discussion about harmonizing search services scheduled on April 18.

Tom - would you like to join our QWC2 meeting in Zurich on April 18?
