### ISSUE TITLE
pdf not working

### ISSUE THREAD

**Issue by davidebz** [qgis/qwc2-demo-app#230]
Hi,

we are using qwc2-demo-app, we like to print a pdf but we got an error. The first problem we got is that layer osm_farbig does not exists. We have removed printLayer from themesConfig.json but now it say that print is failed. In this case it's look like a core dump of the cgi.

How we can understand where the problem is? Can we activate a log function?

Thanks in advance for any help!

**Comment by manisandro** [comment]
The coredump is a QGIS Server issue, and not related to QWC2. You can find information here how to enable logging: https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/config.html
