### ISSUE TITLE
t (theme) parameter is deleted from url

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#231]
@manisandro The problem seems to come from here [https://github.com/qgis/qwc2/commit/93575f2913261cbc65fa0ca7390bec3d94269475](https://github.com/qgis/qwc2/commit/93575f2913261cbc65fa0ca7390bec3d94269475)
even if it is `setTimeout` `0` there is a delay and there it is set the `t` parameter and immediately after it is set the `e` parameter, but when the `e` parameter is set the `window.location.href` is without `t` parameter

If run without  [https://github.com/qgis/qwc2/commit/93575f2913261cbc65fa0ca7390bec3d94269475](https://github.com/qgis/qwc2/commit/93575f2913261cbc65fa0ca7390bec3d94269475) it works perfect.

**Comment by manisandro** [comment]
Argh. I'll need to find another workaround for the firefox bug then... Thanks for reporting

**Comment by manisandro** [comment]
Should be fixed by https://github.com/qgis/qwc2/commit/06afca4eb43dd4061c9aaeeb1635e270aedd216f
