### ISSUE TITLE
Print function doesn´t work

### ISSUE THREAD

**Issue by earth-design** [qgis/qwc2-demo-app#237]
On the WebGIS http://www.sarmap.ch:8081/cropix/?k=c086b7c5c there is a print function included in the menu. No matter which theme I open the message box retrieves: "The selected theme does not support printing".
So I wonder if this function is not activated or specified, or if all our themes do not fulfill certain conditions to enable them for printing.

**Comment by manisandro** [comment]
This is a client-specific issue, please create these issues in the appropriate tracker.
