### ISSUE TITLE
Function "Show layer map tips" doesn´t work 

### ISSUE THREAD

**Issue by earth-design** [qgis/qwc2-demo-app#238]
In the WebGIS http://www.sarmap.ch:8081/cropix/?k=c086b7c5c there is a function in the menu with the name "Show layer map tips". This function doesn´t show any change in the map. Neither with right nor with left click, neither on raster nor on vector data.
A feature info can be retrieved from by clicking on single features, but independently if the function "Show layer map tips" is checked or not.

**Comment by manisandro** [comment]
I've created an issue in the appropriate tracker (same with #237).
