### ISSUE TITLE
Enhancement for link sharing

### ISSUE THREAD

**Issue by earth-design** [qgis/qwc2-demo-app#239]
In the WebGIS http://www.sarmap.ch:8081/cropix/?k=c086b7c5c there is tool for Link sharing. The selection of third party social networks is linkedin, twitter and facebook. Would be a gadget, not a must to have whatsapp there as well, since it is quite popular.

**Comment by manisandro** [comment]
Done https://github.com/qgis/qwc2/commit/49e794c23123a93071bc1c5c63e236b38a507167
