### ISSUE TITLE
Configurable legend image

### ISSUE THREAD

**Issue by karl-magnus** [qgis/qwc2-demo-app#24]
I think the ability to customize the legend image would be a good enhancement. And not so tricky. Someting like The layer image is the output of the WMS GetLegendGraphic request.
	{
          "name": "LayerTree",
          "cfg": {
            "showLegendIcons": true,
             "appendToGetLegendGraphic":"&ICONLABELSPACE=2&LAYERTITLE=FALSE&ITEMFONTSIZE=9&LAYERSPACE=1&SYMBOLSPACE=1"

in the config.json file

**Comment by manisandro** [comment]
I suppose this would be more flexible if done per-theme? (i.e. in themesConfig.json?)

**Comment by karl-magnus** [comment]
Yes, suppose it's better. Thougt of having it per-layer but then it would be a more complex thing somehow adding it to the getProjectSettings. I think per theme would be good for now.

**Comment by manisandro** [comment]
You can now specify a `extraLegendParameters` in `themesConfig.json`.
