### ISSUE TITLE
Overview map loads satellite data as background layer

### ISSUE THREAD

**Issue by earth-design** [qgis/qwc2-demo-app#240]
In the WebGIS http://www.sarmap.ch:8081/cropix/?k=c086b7c5c there is in the lower right corner a double-arrow. If you click it an overview map appears. The overview map should show the Open-street-map background layer as wms service. This gives the user orientation about the surrounding area. As at today the background layer loads the Open-street-map background layer and then it takes a while until it loaded the raster layer from the map products. It would be better to load the OSM layer only. 
Second issue here is, that on the left side of the double arrow is written "Terms of use". "Terms of use" is linked with an external web-site, which is okay, but there should be written Overview map without a link, so that the user understands, that the double arrow opens the overview map.

**Comment by manisandro** [comment]
Client specific issue, tracked in the appropriate tracker.
