### ISSUE TITLE
custom map click

### ISSUE THREAD

**Issue by rodrigotuisla** [qgis/qwc2-demo-app#241]
Hi,

Is there a way to change the map click behavior from a custom React component without changing the openlayers Map.jsx component? If so, how can I do it?

Thank you very much!

**Comment by manisandro** [comment]
You can override which tool acts as identify tool (i.e. is triggered by default when left-clicking in the map) globally [1] and you can also override it per theme.

You can then implement a custom tool which activates if the identify tool state matches [2], and handle the click event state change, i.e. [3].


[1] https://github.com/qgis/qwc2-demo-app/blob/master/config.json#L25
[2] https://github.com/qgis/qwc2/blob/c7143d989be1d28a76c633833315c641c2b7a987/plugins/Identify.jsx#L175
[3] https://github.com/qgis/qwc2/blob/c7143d989be1d28a76c633833315c641c2b7a987/plugins/Identify.jsx#L110

**Comment by rodrigotuisla** [comment]
Thank you very much for your quick reply.
I can't seem to get it work because my state map object does not have any clickPoint or clickFeature function.

`point: state.map && state.map.clickPoint || {},
 clickFeature: state.map.clickFeature || {},`

Always got an empty object from this. What am I missing?

Thanks again!

**Comment by manisandro** [comment]
Run your viewer with adding the `debug=true` query in the URL. In the browser console you can then inspect the application state.

**Comment by rodrigotuisla** [comment]
Shouldn't I have a clickPoint and clickFeature on map object?

![image](https://user-images.githubusercontent.com/74065294/98547272-d4c0b980-228f-11eb-9db3-415c93967e46.png)

Thanks.

**Comment by manisandro** [comment]
after clicking on the map, there definitely should be the clickPoint/clickFeature entries.

**Comment by rodrigotuisla** [comment]
Any guess why I don’t have it?

Thanks

**Comment by manisandro** [comment]
Not really, are you using a current version of qwc2? At latest after the `CLICK_ON_MAP` action you should see the entries in the state.

**Comment by rodrigotuisla** [comment]
Yes, I'm using the master branch and I pull the updates today. Any thoughts on what I can do?

Thanks

**Comment by manisandro** [comment]
You'll have to debug this.
