### ISSUE TITLE
Apache rules for printout

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#242]
Hi,
following the documentation about adding these rules to Apache for printout

SetEnvIf Request_URI "^/wms.*/(.+)$" project_name=$1
Header always setifempty Content-Disposition "attachment; filename=%{project_name}.pdf" "expr=%{CONTENT_TYPE} = 'application/pdf'"

apachectl configtest comes up with an error message.

Following
<https://serverfault.com/questions/101948/how-to-send-content-disposition-headers-in-apache-for-files> and
<https://serverfault.com/questions/760160/correct-format-to-eval-in-an-apache-2-4-string-in-the-config-file/760174>
I added an 'e' in 'filename=%{project_name}e.pdf', and Apache accepts the addition.
Can you just update the documentation?
Thanks.

**Comment by manisandro** [comment]
I'm not sure why the "e" in `%{project_name}e.pdf` should matter? What error do you get?

**Comment by mhaelsig** [comment]
Hi,
the error message without this strange 'e' is (I am using Apache 2.4.38):

AH00526: Syntax error on line 77 of /etc/apache2/sites-enabled/prod-rwpl-le-ssl.conf:
Unrecognized header format %.

This is the part from the .conf file, which I copied from the documentation:

76 	SetEnvIf Request_URI "^/wms.*/(.+)$" project_name=$1
77	Header always setifempty Content-Disposition "attachment; filename=%{project_name}.pdf" "expr=%{CONTENT_TYPE} = 'application/pdf'"

Following (but not understanding!) 

https://serverfault.com/questions/760160/correct-format-to-eval-in-an-apache-2-4-string-in-the-config-file/760174

I added the 'e'. Then Apache accepts the configuration, and downloading the .pdf file works. 

Kind regards

Michael Hälsig

P.S. Thanks a lot for this fine solution!

-- 
Dr. Michael Hälsig
Diefenbachstr. 9
81479 München

Tel: +49 89 79 199 563
Mobil: +49 171 333 7558
Am Dienstag, 10. November 2020, 11:20:02 CET schrieb Sandro Mani:

**Comment by manisandro** [comment]
So according to [1], `%{VARNAME}e` means that VARNAME is an environment variable. So you are right @mhaelsig , the e suffix is correct. I'll update the documentation. Thanks for the report!

[1] https://httpd.apache.org/docs/current/mod/mod_headers.html

**Comment by manisandro** [comment]
Fixed in b49e6518b22b9c1c3f05884e67b79342c3c797a4
