### ISSUE TITLE
qwc2-demo-app message print failed

### ISSUE THREAD

**Issue by kahermann** [qgis/qwc2-demo-app#245]
Creating pdf with the original themesConfig.json and config.json of the qwc2-demo-app (for instance with the Uster Theme)
causes the message "print failed"

**Comment by manisandro** [comment]
This is most likely due to CORS. You need to use a browser plugin which bypasses CORS rules.

**Comment by kahermann** [comment]
Hello Sandri,


thanks for your prompt answer.

I use firefox, the "print failed" is caused  by CORS in firefox.

I recommend to mention in the documentation from qwc2-demo-app that problems may possibliy occur with CORS

Also i recommend in themesConfig.json (or a explicit themes.Config.json) to document the references to the themes, layers in the project (world.qgs) in

https://docs.qgis.org/3.16/en/docs/training_manual/qgis_server/wms.html

(the error in the documentation is that in the configuration files for apache and qgis-server there is "qgis.demo" but in the proposed url to call qgisserver there is "qgisplatform.demo")


SG

Karl



<https://docs.qgis.org/3.16/en/docs/training_manual/qgis_server>


________________________________
Von: Sandro Mani <notifications@github.com>
Gesendet: Donnerstag, 26. November 2020 16:47
An: qgis/qwc2-demo-app
Cc: Hermann Karl; Author
Betreff: Re: [qgis/qwc2-demo-app] qwc2-demo-app message print failed (#245)


This is most likely due to CORS. You need to use a browser plugin which bypasses CORS rules.

**Comment by manisandro** [comment]
Hi Karl
There is a corresponding section in the docs [1].

As for your second comment, I'm not sure I understand what you mean, can you explain?

Thanks
Sandro

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#cross-origin-requests

**Comment by kahermann** [comment]
Hi Sandri,

In the qgis documentation section training manual 11. Module QGIS Server there is a tutorial how to set up a working qgis server stack and the service in this howto is named „qgis.demo“
The qgis project file and the data used in this tutorial are the world.qgs and naturalearth.sqlite from QGIS-Training-Data-2.0.
In lesson 11.2 part 11.2.2 GetMap requests there is a sample request which references to a service „qgisplatform.demo“ instead of the configured service „qgis.demo“
In part 11.2.6 GetPrint requests  there is a description to setup a QGIS Web Client (the outdated version) which also references a service „qgisplatform.demo“ instead of the service „qgis.demo“
I know it may be a task of the qgis-documentation but as a starting point it would be nice to have also a description how to setup QWC2 as a client to the service already configured in the tutorial

Greetings

Karl

Von: Sandro Mani <notifications@github.com>
Gesendet: Donnerstag, 26. November 2020 23:49
An: qgis/qwc2-demo-app <qwc2-demo-app@noreply.github.com>
Cc: Hermann Karl <Karl.Hermann@dornbirn.at>; Author <author@noreply.github.com>
Betreff: Re: [qgis/qwc2-demo-app] qwc2-demo-app message print failed (#245)


Hi Karl
There is a corresponding section in the docs [1].

As for your second comment, I'm not sure I understand what you mean, can you explain?

Thanks
Sandro

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#cross-origin-requests

**Comment by manisandro** [comment]
I'll close this, tracking the second part in #127
