### ISSUE TITLE
want to get rid of 'toggle API demo'

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#249]
I have restarted with the version from January 3rd 2021 - hopefully merged all my changes, and my app looks fine, but I cannot get rid of the overlay 'toggle API demo' in the left upper corner. Where is my oversight? 
Thank you.

**Comment by manisandro** [comment]
You can just drop this line https://github.com/qgis/qwc2-demo-app/blob/0ee34ae38c34375640547c0c11b33dbd829157d9/index.html#L54 and you can also delete the `api_examples.js` file.

**Comment by manisandro** [comment]
I've added a note to the box itself: https://github.com/qgis/qwc2-demo-app/commit/e4237f2224f11a48061586abe83342a985832e70
