### ISSUE TITLE
locale de in Firefox

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#251]
In Firefox I can set the language to 'de' only. Then the app searches for /translations/de.json and fails - although there is the fallback locale en-US. 
Browser Console:
*XHR GEThttp://localhost:8081/translations/de.json [HTTP/1.1 404 Not Found 3ms]
Uncaught (in promise) TypeError: defaultLangData is undefined
loadLocale webpack:///./node_modules/qwc2/actions/locale.js?:42*

The applications works, if I duplicate de-DE.json to de.json, or if I set the language in Firefox to de-de. I would expect a more robust behaviour, e.g. to expand single locales - in this example 'de' to 'de-DE'.

**Comment by manisandro** [comment]
As for the `defaultLangData is undefined` error, did you set `defaultLocale` in `appConfig`?

As for dealing with single locales, this won't really work without compiling a list of available locales into the application, as clearly the webapp cannot know which files exist on the server.

**Comment by mhaelsig** [comment]
Hi,
I also changed the defaultLocale to:

"import defaultLocaleData from '../translations/de-DE.json';"

Just to reproduce: in Firefox I can set the locale only to 'de' (or 'en') (see 
screenshot), which is strange from my perspective, by I learned it today. When 
you then start the demo-app, it stops with the error described. 

Kind regards
Michael

P.S. It is really fun to use the app! I am using it for the website 
'radwegplanung-muenchen.de'. There are for sure a lot of undiscovered 
possibilities!
 
-- 
Dr. Michael Hälsig
Diefenbachstr. 9
81479 München

Tel: +49 89 79 199 563
Mobil: +49 171 333 7558
Am Sonntag, 10. Januar 2021, 17:28:24 CET schrieb Sandro Mani:

**Comment by manisandro** [comment]
Looks like the screenshot is missing.

**Comment by manisandro** [comment]
The issue with the fallback locale is fixed in [1].

[1] https://github.com/qgis/qwc2/tree/6208fb99481882b0a90aa8990fcf81019e296242

**Comment by manisandro** [comment]
Thanks for the screenshots. In this case I believe the only proper solution is to duplicate (or symlink) the translation files server-side.

**Comment by manisandro** [comment]
Closing, feel free to reopen if you feel something more needs to be addressed.
