### ISSUE TITLE
change map.clickpoint to map.click 

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#253]
In _qwc2/plugins/MapInfoTooltip.jsx _ in lines 44 and 50
_https://github.com/qgis/qwc2/blob/479b4aa6eecfd50ecf248c9c9224588956f44fcd/plugins/MapInfoTooltip.jsx#L44_ and
_https://github.com/qgis/qwc2/blob/479b4aa6eecfd50ecf248c9c9224588956f44fcd/plugins/MapInfoTooltip.jsx#L50_

_...map.clickpoint_ should be replaced by _map.click_.

**Comment by manisandro** [comment]
Fixed [1], thanks!

[1] https://github.com/qgis/qwc2/commit/e9daf0b9e48b8b3c87705eab06f9ff42768a9360
