### ISSUE TITLE
start extent reverse axis projections problems on proj 2.6.1

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#254]
Tested the latest demo and because of https://github.com/proj4js/proj4js/releases/tag/2.6.1 the start extent is wrong. Until there's time to investigate more, downgrading to 2.6.0 works.

**Comment by manisandro** [comment]
Can you elaborate on this, which start extent is wrong?

**Comment by manisandro** [comment]
Should be fixed by https://github.com/qgis/qwc2/pull/126, thanks @luciman !

**Comment by tudorbarascu** [comment]
It's fixed! Thanks.
