### ISSUE TITLE
Regression introduced in qgis/qwc2@bd46e36

### ISSUE THREAD

**Issue by lpinca** [qgis/qwc2-demo-app#255]
Commit https://github.com/qgis/qwc2/commit/bd46e36719598b8281c476bf7ad289b32f256283 introduced a regression that makes our application crash when issuing a GetFeatureInfo request.

The response in our case is parsed as

```js
{
  type: 'Feature',
  id: '0',
  featurereport: null,
  displayfield: null,
  layername: null,
  layerinfo: null,
  properties: {
    LUNGHEZZA: '123660.20',
    Cod_Sent: 'GAS'
  },
  crs: 'EPSG:3004'
}
```

After that a `TypeError` is thrown because [`geojson.geometry`](https://github.com/dpmcmlxxvi/geojson-bounding-box/blob/v0.2.0/index.js#L72) is not defined.

**Comment by manisandro** [comment]
Thanks for the report, fixed in https://github.com/qgis/qwc2/commit/b7001f9e1dd1919430533bea90759cda9ee37a74
