### ISSUE TITLE
Regression introduced in qgis/qwc2@f600457

### ISSUE THREAD

**Issue by lpinca** [qgis/qwc2-demo-app#258]
Commit https://github.com/qgis/qwc2/commit/f60045710c42cef649d6b3caa6ff84b15803f777 introduced a regression that makes our application crash.

The problem is similar to https://github.com/qgis/qwc2-demo-app/issues/255 and arises because the objects in the [`newFeatures`](https://github.com/qgis/qwc2/blob/1b8c0d387def95994eed64c5928b56c648565d9a/reducers/layers.js#L205) array do not have a `geometry` property.

**Comment by manisandro** [comment]
Thanks for reporting. Looks like this exposed a bug where the bbox of a vectorlayer was not always updated. I've adapted the VectorLayerUtils.computeFeaturesBBox to filter out the features without a geometry [1], which should fix this issue.

[1] https://github.com/qgis/qwc2/commit/c99d0695573b7be54d05cce764cfe53903e455db

**Comment by lpinca** [comment]
Wouldn't https://github.com/qgis/qwc2/commit/c99d0695573b7be54d05cce764cfe53903e455db create a mismatch between features and corresponding bounding boxes if the `geometry` property is set only in some cases?

**Comment by manisandro** [comment]
Uhm not sure I understand your question correctly, but if a feature does not have any geometry, it wouldn't affect the BBOX anyway?

**Comment by lpinca** [comment]
Yes but shouldn't the `features` and `bbox.bounds` arrays have the same length? Assume that there are 3 features and `geometry` is not set only for second element at index 1. `bbox.bounds` will have only 2 elements but the bounds at index 1 correspond to the feature at index 2 and not 1. Does it make sense?

**Comment by manisandro** [comment]
No, bbox.bounds is a [xmin,ymin,xmax,ymax] array containing the bbox of the entire layer:

![image](https://user-images.githubusercontent.com/1298852/107357822-ddb16900-6ad2-11eb-9a73-36e2dbaf2781.png)

**Comment by lpinca** [comment]
Ah ok, thank you.
