### ISSUE TITLE
Blank page with Internet Explorer 11

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#259]
Hi,

when I open the latest QWC2 demo with the Internet Explorer 11 I get only a blank page. The following error is reported in the developer tools console:

```
SCRIPT1053: "const" muss initialisiert sein.
Datei: QWC2App.js, Zeile: 13, Spalte: 122655
```

Is it possible to fix this?

**Comment by manisandro** [comment]
Maybe since fixed, but IE11 is definitely EOL.
