### ISSUE TITLE
layer groups option to switch on/off the visibilitiy (for the underlying layers)

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#26]
Hello,
Is there an option to toggle on/off the visibility of all the underlying layers of a group?

**Comment by manisandro** [comment]
Hi, you can configure the behavior via config.json -> LayerTree -> groupTogglesSublayers

**Comment by tudorbarascu** [comment]
I just noticed that after checking the root of the tree (the project name), unchecking it does nothing.
This is valid only for the root. If I have other groups/subgroups..everything works.

**Comment by manisandro** [comment]
Indeed, this was broken. Fixed in https://github.com/qgis/qwc2/commit/41fb8ffa1cf87b7d1c4d5901593e409fb51e0f26
