### ISSUE TITLE
Switching to inches from feet too soon in imperial scale bar

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#262]
As I zoom in from 1:100 to 1:50, the scale bar text switches from 10 ft to 50 in.  It would be more useful if the scale bar would instead switch from 10 ft to 5 ft then 2 ft then 1 ft as you zoom in.   If the user wishes to zoom in even further, it could then change from 1 ft to 6 in and so on.  We imperialists would rather measure things in feet than inches whenever possible.

**Comment by manisandro** [comment]
This is openlayers behaviour, AFAICS it is not configurable.
