### ISSUE TITLE
Rotate map view on wide (desktop/laptop) screens / default rotation angle

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#264]
Is it possible to set a default rotation angle on desktop and mobile screens?  The rotation is set to -6.8 degrees in my QGIS project but this is not being reflected in the QWC2 web map.

BTW, I discovered that you can use Alt-Shift drag to rotate the map view.

Thanks.

**Comment by manisandro** [comment]
This option is not currently exposed to the client through the WMS GetProjectSettings. One could implement it as a client side config option in themesConfig.json.

**Comment by raynerhoward** [comment]
Where would I stick it in themes.json?  Tried adding the line

"rotation": -6.8,

between "printResolutions" and "sublayers", didn't work

**Comment by manisandro** [comment]
You need to actually implement the support for the setting in the program code

**Comment by danceb** [comment]
Seems like thit is implemented now:
https://qwc-services.github.io/references/qwc2_plugins/#mapplugin

So feel free to close the ticket.
