### ISSUE TITLE
Categories not clickable in qwc2

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#266]
In QGIS, I can use categorized symbology for a layer. Then, each category in this layer can be selected, therefore switched on and off. When I display such a layer with qwc2, this layer is only selectable in total, not the single categories. Only the categories already selected in QGIS are shown in qwc2 - I cannot click on/off other categories. 
Do I miss something to display all categories as selectable in qwc2?
(I can create manually a group of layers by this category - therefore circumvent this issue. But I like the automatism...)
![Screenshot_20210426_082321](https://user-images.githubusercontent.com/10079628/116038129-53a48580-a669-11eb-89f4-47d61d8212e8.png)
![Screenshot_20210426_082715](https://user-images.githubusercontent.com/10079628/116038132-543d1c00-a669-11eb-9e75-98b83aeb5eb0.png)
Thank you for any hint.

**Comment by manisandro** [comment]
This is currently not possible, as the categories are not exposed through WMS GetCapabilities or the QGIS Server WMS GetProjectSettings. The project has to be modified to split the groups into single layers.
