### ISSUE TITLE
Not all layers are shown using additional themes while pdf printing or raster export

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#267]
We are using a QWC2 instance based on the qwc-docker using the qwc-services.  Within the config.json the parameter "AllowAddingOtherThemes" is set to "true", so there is the possibility to load an initial theme and add other themes to the map so the layers of the other themes appear within the layer tree.
When you use this map view for PDF printing or the raster export tool only the layers of the initial theme are printed/exported. All layers which are added in addition do not appear on the output pdf/raster.
Are there any known issues related to this problem? I couldn't find one. I will appretiate any help or ideas, thanks!

![grafik](https://user-images.githubusercontent.com/30999402/116073363-9a59a600-a690-11eb-9a7b-891e007eedf9.png)
(grey boxes because of sensitive data)

**Comment by manisandro** [comment]
You'll need to set `printExternalLayers: true` in the `cfg` block of the `Print` plugin, as layers from other themes are treated as external layers. Support for raster-exporting external layers OTOH is currently not implemented.

**Comment by danceb** [comment]
Ok, thanks for the quick response! I will close this issue now.

**Comment by manisandro** [comment]
Hi @mbernasocchi , do you have

    "qgisServerVersion": 3

in your config.json?

**Comment by mbernasocchi** [comment]
Hey @manisandro thanks for the super quick response. 

no. is that top level in the JSON?

**Comment by manisandro** [comment]
yep, see https://github.com/qgis/qwc2-demo-app/blob/master/static/config.json#L28

**Comment by manisandro** [comment]
Try stepping from here [1] into here [2] to see why those layers aren't added to the print request.

[1] https://github.com/qgis/qwc2/blob/74c5cb578ba64e4015fb4fbc542a2e5ac7207af9/plugins/Print.jsx#L120
[2] https://github.com/qgis/qwc2/blob/74c5cb578ba64e4015fb4fbc542a2e5ac7207af9/utils/LayerUtils.js#L653

**Comment by mbernasocchi** [comment]
@manisandro thanks for the help it was indeed a config.json issue. I had not noticed that config.json had changed location so I was editing an unused file :/
sorry for the noise
