### ISSUE TITLE
Max 100 feature limitation per layer when using Identify Region tool

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#268]
When using the Identify Region tool to draw a polygon around features, there is a 100 feature (record) limitation per layer showing up in the Feature Info window.  It would be a good idea to alert the user to this if the number of features exceeds 100 in any of the layers.  Is there a config setting that allows this number to be increased?  If I draw a box around features using the identify tool in QGIS, it shows (or tries to show) all of the features within the box in the identify results window.

**Comment by manisandro** [comment]
The limit is now configurable [1], but the client cannot really know with certainty whether there are more results than the ones returned.

[1] https://github.com/qgis/qwc2-demo-app/commit/a4bd9570d9121cc8bb63578e5f5ab490849e2cfc
