### ISSUE TITLE
GetFeatureInfo with MapTips

### ISSUE THREAD

**Issue by dkippo** [qgis/qwc2-demo-app#269]
Is there a new per theme configuration to enable mapTips with GetFeatureInfo requests? I have recently upgraded QWC2 and it seems to default to the with_maptip=false parameter.

**Comment by dkippo** [comment]
My old themes work again as previously if I edit 
IdentifyUtils.js
   params: {
      with_maptip:**true**

So feel free to close this issue if it is not an oversight.

**Comment by manisandro** [comment]
You can pass `with_maptip: true` to the config params in config.json if you want the maptip to be part of the GetFeatureInfo response, i.e.:

    "name": "Identify",
    "cfg": {
        "params": {
            "with_maptip": true
        }
    }
