### ISSUE TITLE
Bad link when you click API.js in QWC2_Documentation.md

### ISSUE THREAD

**Issue by raynerhoward** [qgis/qwc2-demo-app#273]
In https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#api-for-external-applications

When you click API.js it shows Page not found:  https://github.com/qgis/qwc2/tree/master/plugins/API.js

Guessing maybe:  https://github.com/qgis/qwc2/blob/master/plugins/API.jsx

**Comment by manisandro** [comment]
Fixed, thanks
