### ISSUE TITLE
Add additional header to "GetMap" Requests

### ISSUE THREAD

**Issue by dmestudent** [qgis/qwc2-demo-app#274]
Hello, 

I am currently implementing Keycloak in a project based on the qwc2 demo app. I need to add my keycloak tokens to the header of the requests requesting the map from the apache qgis server. Unfortunately adding an react axios interceptor does not seem to affect the requests regarding loading the map. Could you point me in the right direction where those requests are build? 

Thanks in advance

**Comment by manisandro** [comment]
You'll need to dig into the openlayers code to see how requests are built, but if you can also pass the token via URL param, for tiled sources you can override the `tileLoadFunction` [1] (i.e. around here [2] for WMS) and alter the URL of the requested image, say
    function olTokenTileLoadFunction(tile, src) {
        ...
        tile.getImage().src = alteredSource;
    }

[1] https://openlayers.org/en/latest/apidoc/module-ol_Tile.html#~LoadFunction
[2] https://github.com/qgis/qwc2/blob/9dfcef2b50f3a12e62dc5c7689b5ffa26b7dea71/components/map/layers/WMSLayer.js#L71
