### ISSUE TITLE
Missing translation for menu entry "Identify Region"

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#275]
The menu entry "Identify Region" is no longer translated after the last rework of the identify plugin. 

![map_and_tools](https://user-images.githubusercontent.com/20335953/119105742-ef81a100-ba1d-11eb-9eef-9428b5b3c66d.png)

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/49f07ead16cd45c2f3e97a1b94edea7835e298a7
