### ISSUE TITLE
ThemeSwitcher auto width

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#28]
Hi,
Depending on how many themes are in the theme switcher, it can have unnecessary large width.
As you can see from the following image, the user has to go all over the screen to get to the theme, which is bad, especially on large screens.
I've made a git patch as a quick way of solving this (look at the bottom of the image)
![theme_issue](https://cloud.githubusercontent.com/assets/11608132/25757064/b8c68cda-31d1-11e7-9e52-9d975a9afe19.png)

```
diff --git a/MapStore2 b/MapStore2
--- a/MapStore2
+++ b/MapStore2
@@ -1 +1 @@
-Subproject commit a8f23d91d6536f6db5774f77068aa02f651302bb
+Subproject commit a8f23d91d6536f6db5774f77068aa02f651302bb-dirty
diff --git a/QWC2Components/components/SideBar.jsx b/QWC2Components/components/SideBar.jsx
index bb371a2..c92a514 100644
--- a/QWC2Components/components/SideBar.jsx
+++ b/QWC2Components/components/SideBar.jsx
@@ -57,7 +57,7 @@ const SideBar = React.createClass({
         let visible = this.props.currentTask === this.props.id;
         let style = {
             width: this.props.width,
-            right: visible ? 0 : 'calc(-' + this.props.width + ' - 8px)',
+            right: visible ? 0 : '-100%',
             zIndex: visible ? 5 : 4
         }
         return (
diff --git a/QWC2Components/plugins/ThemeSwitcher.jsx b/QWC2Components/plugins/ThemeSwitcher.jsx
index 7495e59..589424c 100644
--- a/QWC2Components/plugins/ThemeSwitcher.jsx
+++ b/QWC2Components/plugins/ThemeSwitcher.jsx
@@ -176,7 +176,7 @@ const ThemeSwitcher = React.createClass({
             <input className="themeswitcher-filter" type="text" value={this.props.filter} onChange={this.filterChanged} placeholder={LocaleUtils.getMessageById(this.context.messages, "themeswitcher.filter")}/>
         );
         return (
-            <SideBar id="ThemeSwitcher" width="85%" title="appmenu.items.ThemeSwitcher"
+            <SideBar id="ThemeSwitcher" width="auto" title="appmenu.items.ThemeSwitcher"
                 icon={assetsPath + "/img/themes.svg"} extraTitlebarContent={extraTitlebarContent}>
                 {this.renderThemeGroup(this.state.themes)}
             </SideBar>
```

**Comment by tudorbarascu** [comment]
This cannot be replicated anymore and can be closed.

**Comment by manisandro** [comment]
Actually I think the situation is still the same as when @luciman filed the issue. It should just be a matter of making it configurable how wide the ThemeSwitcher should be.

**Comment by tudorbarascu** [comment]
@manisandro indeed, I had applied the patch with a script. Shouldn't this patch make it into trunk?

**Comment by manisandro** [comment]
Implemented in https://github.com/qgis/qwc2/commit/b76eabcfb4437f50e5f53b229ace0a45dad8c4aa:
Width now defaults to auto, but is configurable.
(The issue with the patch above is that in `right: -100%`, `100%` refers to the parent width, which in this case is the body width, so the slide-in animation looks odd especially for small sidebars, since the sidebar has to slide a very long way - and most of the distance actually being outside the visible area).
