### ISSUE TITLE
Can't see map data with crs epsg 3878

### ISSUE THREAD

**Issue by mittamies** [qgis/qwc2-demo-app#281]
Hi!

Is there limit to use for example epsg 3878 CRS? Project loads to perfect but nothing happend in map canvas. Actually I can't see any map data. If the qgis project is converted to i.e. 3067, the data appears. Is the coordinates exceeded something limits?

Side note: wms from qgis server works well in qgis desktop both cases. Map data format is shapefile and already crs 3878.

Any ideas to debug this issue more?

- Lassi

**Comment by manisandro** [comment]
Have you added the projection definition to config.json?

**Comment by mittamies** [comment]
Thanks for quick reply! Yes, I have following lines in config.json

`    {
      "code": "EPSG:3878",
      "proj": "+proj=tmerc +lat_0=0 +lon_0=24 +k=1 +x_0=24500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
      "label": "GK24"
    }`

**Comment by manisandro** [comment]
Sorry I don't really have any other ideas - I guess you checked the browser console to see if any errors or warnings are displayed.

**Comment by mittamies** [comment]
It was axis orientation which should be different than epsg 3067.

The map works when add +axis=neu parameter to proj value.

Is it correct to set axis orientation to proj config in qwc2? I think that it would be useful to append this to documentation?
