### ISSUE TITLE
Printing/Exporting layers of different map themes

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#282]
Hello there,

May you can help me with the following issue.
We have running a QWC2 within a docker stack using the qwc-services.
Within the QWC2 there is the possibility the organize the layers in different map themes based on different QGIS projects. If the parameter "allowAddingOtherThemes" within the config.json is set to 'true', users can load other themes in addition to the current one to the map.
The issue occurs if you want to print this map now to pdf. The printing works only, if there are only layers from the initial theme in the map. But if I try to print the map with additional layers, I get the following error:

```
<ServiceExceptionReport version="1.3.0">
<ServiceException code="UnknownError">
The server encountered an internal error or misconfiguration and was unable to complete your request.
</ServiceException>
</ServiceExceptionReport>
```

As far as we know, this is not an error in relation to the qwc-print-service. This occurs also using the default print option without the service implemented. Is there anyone with the same issue or having ideas for a solution to fix this?

In addition there is a similar error using the raster-export tool. If you have more then one theme loaded and want to export a raster of the map, only the initial layers appear within the exported image.

Thanks in advance and greetings,
Daniel

**Comment by manisandro** [comment]
I believe this is how QGIS Server behaves if GetPrint is called with no project layers. If you have background layers, by setting a printLayer, you should at least have one project layer included the print layerlist, and printing should work.

**Comment by danceb** [comment]
Hi Sandro,

sorry for misunderstanding. Of course default printing works with defined background layers and at least one project layer.
Our system is'nt public, so I could not share a link to it. I'll try to explane it clearer using screenshots.

If projects layers are loaded on background layers (they are defined as print layers), you can add additional layers from other themes:
![grafik](https://user-images.githubusercontent.com/30999402/126101091-f66013dd-a51d-44be-9841-603e62516d82.png)

If I load layers from the theme "Naturschutz" on top of the default layers for instance, the layer tree looks like this:
![grafik](https://user-images.githubusercontent.com/30999402/126101373-5eacb75b-8a29-4788-8110-7d0a0c03c6c6.png)

If I want to print the map with all of this layers to pdf now, the following error occurs:
![grafik](https://user-images.githubusercontent.com/30999402/126101432-f668ffd3-bfaf-4094-8df1-08756d3677fc.png)

The printing works, of only the initial layers (with background layers defined as print layers) are loaded to the map without the additional layers.

Thanks for your help!

**Comment by manisandro** [comment]
Are you using the qwc-print-service?

**Comment by danceb** [comment]
Yes, we are using the print-service. 
Today I got another information via the qgis-qwc2 mailing list, where someone mentioned, that the issue was fixed by sourcepole (you?) to weeks ago. 
So we will update our qwc2 installation, and I will tell you afterwards, if everything is fine.

**Comment by manisandro** [comment]
This should since be fixed.
