### ISSUE TITLE
layertree on left hand

### ISSUE THREAD

**Issue by mittamies** [qgis/qwc2-demo-app#283]
Hi,

QWC1 has default layout to show layertree on left side of window. Is it easy way to modify app layout in QWC2? If not, this will be feature request. I might be ready to contribute this feature but unsure how to begin develop within this project.

I don't find any issues or post in mailing list related this option.

Thanks,
Lassi

**Comment by manisandro** [comment]
By default it is located to the right - you could tweak it by overriding the respective style declarations for the sidebar in assets/qwc2.css.
