### ISSUE TITLE
thumbnails must not use a full path

### ISSUE THREAD

**Issue by hkfrei** [qgis/qwc2-demo-app#287]
https://github.com/qgis/qwc2-demo-app/blob/f9723851f5a6df63c03f1a418faaa9e1973bb713/themesConfig.json#L294

It can be missleading if in _themesConfig.json_ a path like "_img/mapthumbs/default.jpg_" is used for the default thumbnail. A user can be tempted to only replace the image name and keep the path. But I experienced, that thumbnails do not work with a path, only the image name and the extension must be used.
Therefore I recommend, that every "_img/mapthumbs/default.jpg_" in themesConfig.json  should be replaced by only _**"default.jpg"**_.

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2-demo-app/commit/d072ad6038afea19ef9de4ac0badb3d25df9ead6
