### ISSUE TITLE
Dragging feature info window under Linux Firefox bug

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#29]
Using Firefox ESR (45.9.0) under Linux, if one drags the ``Feature Info`` window, ``user-select:none`` style is not working resulting in all the text being selected, as presented in the following image:

![drag_firefox](https://cloud.githubusercontent.com/assets/3179646/26190273/3dd97e1c-3bb1-11e7-8f90-a0a32b78d8ee.jpg)

Pull request with fix filled upstream https://github.com/bokuweb/react-draggable-custom/pull/4

**Comment by manisandro** [comment]
I've updated to the latest react-rnd which now uses the original react-draggable component, so this should be fixed.

**Comment by tudorbarascu** [comment]
@manisandro That works also :+1:  
Thanks a lot!
