### ISSUE TITLE
reordering layer - skip group at once 

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#290]
The reordering functionality acts unclear if the layertree contains layers groups (configured in qgis desktop). It is fine when layer group is open in layertree but it is not possible skip the group at once when the group is closed. For user it looks like broken feature although it is exactly same behaviour technically.

**Comment by manisandro** [comment]
You could set `preventSplittingGroupsWhenReordering: true` in config.json, this will ensure the entire group is skipped at once (albeit regardless of whether the group is expanded or collapsed).

**Comment by lassitanskanen** [comment]
Thanks, it is good enough.
