### ISSUE TITLE
Add mapcompare plugin to the top toolbar

### ISSUE THREAD

**Issue by vvmruder** [qgis/qwc2-demo-app#293]
I want to add the mapcompare plugin to the top toolbar. I made it to put it there through:
![image](https://user-images.githubusercontent.com/3714179/135280909-1bf92297-1f99-4f1e-aba3-d31c9cd7d0d1.png)

It is there (with the wrong symbol indeed):
![image](https://user-images.githubusercontent.com/3714179/135281261-e0e4bfa6-504b-4bd9-be83-670c793423dc.png)

But when I click on it nothing happens NOR any error output on the console.

I bet there must be a little trick to get this running. What am I missing? Can someone help me out?

Cheers
C

**Comment by manisandro** [comment]
MapCompare is not currently triggered as a task, but it's part of the layers state, so this won't work. You'll need to write a plugin which activates on `state.task.id === "MapCompare"` and sets `state.layers.swipe` when activated.
