### ISSUE TITLE
Using print after Nominatim Search results in blanc site

### ISSUE THREAD

**Issue by Poldy1705** [qgis/qwc2-demo-app#295]
We integrated the SearchProvider Nominatim Search in the QWC2. After we searched a street and a housenumber and start directly after that the Print function, we get a blanc site.

![image](https://user-images.githubusercontent.com/29286915/138044903-dd135bce-bf32-4966-9c6b-4a4e27414670.png)

**Comment by manisandro** [comment]
Cannot reproduce with latest master, feel free to reopen if you can
