### ISSUE TITLE
text/html will not loading after identify feature

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#297]
Hi,

`       else if (result.type === "html") {
            resultbox = (
                <iframe className="identify-result-box" onLoad={ev => this.setIframeContent(ev.target, result.text)} />
            );`

Related to external layers getfeatureinfo requests with html infoformat. When clicking feature on map it will open identifyviewer but not load content. After reload iframe content, it will rendering correctly.

I put some logging inside setIframeContent function and it will not fired before reloading iframe content.

I can't find where issue locate.

**Comment by manisandro** [comment]
Seems to affect chrome. Workaround committed in https://github.com/qgis/qwc2/commit/824afa5c431ad9a5ccd84f5a5955c7a47fdd1a67
