### ISSUE TITLE
bug - cannot close identify window on mobile

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#300]
Hi,
I think that I found bug. I cannot use buttons on topbar of identify window on mobile view. They works well on desktop however.

![image](https://user-images.githubusercontent.com/78619273/141074134-fdc3f513-b6fd-4625-a27b-ebc6bebe0f03.png)

**Comment by manisandro** [comment]
Sigh I keep forgetting that I shouldn't be updating react-rnd above version 10.1.10. Fixed, thanks for reporting!
