### ISSUE TITLE
Feature Request: Attachment PDF viewer popup

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#301]
Is it possible yet or close future to have pdf popup for feature attachments? For example I have polygons that have PDF links in attributes. It would be useful feature to open it to window top of app rather than new browser tab.

**Comment by manisandro** [comment]
Actually this is already possible, I need to update documentation to mention it though. Basically. if you have an attribute with as value a HTML fragment of the form

    <a href="http://www.example.com" target=":iframedialog:example:width=300:height=300:print=true">Example</a>

it will appear as a Link in an inline window:

![image](https://user-images.githubusercontent.com/1298852/141267621-1b7bf09f-eb32-463d-bd8b-4a089b3acdb2.png)


If your link points to a PDF, then, if your browser supports inline-pdf rendering, then the PDF will appear inside that window.

**Comment by manisandro** [comment]
See https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#links-in-identify-results
