### ISSUE TITLE
Resizeable window to right hand

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#302]
How to implement this kind of feature? I would like read identify results on right side.

I managed this with this code but it is not production ready at all. Any tips to do this better?

ResizeableWindow.jsx
```
        } else {
            this.state.geometry = {
                x: window.innerWidth - props.initialWidth - 15,
                y: props.initialY !== null ? props.initialY : Math.max(0, Math.round(0.5 * height)),
                width: props.initialWidth,
                height: height,
                docked: props.initiallyDocked || false
            };

```
I suggest new identify cfg parameter like "side": "right". And after that, it can be move it little bit back towards left side with initialX parameter. (How initialX or Y works?)

**Comment by manisandro** [comment]
You can now set initialX and initialY as props for the Identify component, and when using a negative value for initialX, the value is interpreted as a distance from the right screen edge. You'll hence want something like

        {
          "name": "Identify",
          [...]
          "initialX": -480,
          "initialWidth": 480,
          "initialHeight": 550
        }
