### ISSUE TITLE
Compass is displayed over the menu

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#303]
When the map is rotated, the compass symbol is displayed over the opened menu.

![qwc2_compass_issue](https://user-images.githubusercontent.com/20335953/142889403-43765ff5-ddf1-4a54-892d-f2c0ef58e756.jpg)

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/a2552ba9ae8fa774443612d70fa1a3f8f4b91ab6, thanks
