### ISSUE TITLE
Searchbox is erroring out

### ISSUE THREAD

**Issue by joseffb-mla** [qgis/qwc2-demo-app#304]
I get this error when I type anything into search box. Occurred from newest demo app pulled from this repo today (11-22-21)

I've tried removed search providers and nothing works. The drop down search provider selector is not showing up. Pleas help me figure this out thanks!

Uncaught TypeError: _utils_ConfigUtils__WEBPACK_IMPORTED_MODULE_17__.default.getConfigProp(...) is undefined
    SearchBox webpack://QWC2App/./qwc2/components/SearchBox.jsx?:556
    SearchBox webpack://QWC2App/./qwc2/components/SearchBox.jsx?:515
    React 14
    unstable_runWithPriority webpack://QWC2App/./node_modules/scheduler/cjs/scheduler.development.js?:468
    React 15
    <anonymous> webpack://QWC2App/./js/app.jsx?:19
    jsx http://localhost:8081/dist/App.js:30
    __webpack_require__ http://localhost:8081/dist/App.js:18128
    <anonymous> http://localhost:8081/dist/App.js:19196
    <anonymous> http://localhost:8081/dist/App.js:19198
App.js line 1031 > eval:556:81

**Comment by joseffb-mla** [comment]
I tried this with just vanilla app (no custom config stuff) and same...

**Comment by joseffb-mla** [comment]
Seemed to fix this by adding config-old.json to the static folder. looks like configUtil is explicitly looking for config-old.json instead of config.json.

is that a bug or by design?

**Comment by manisandro** [comment]
I'd only expect this if you have `localConfig=config-old` in the URL.

**Comment by joseffb-mla** [comment]
yea, no config is specified in the url. Was weird that it's hard coded in qwc2/utils/ConfigUtils.js

```        
const urlQuery = url.parse(window.location.href, true).query;
        if (urlQuery.localConfig) {
            configFile = urlQuery.localConfig + '.json';
        }
```

**Comment by manisandro** [comment]
This is a local change you have, not the upstream version [1]

[1] https://github.com/qgis/qwc2/blob/ade338e9dff297468fa5b356bedb79f47cea66d8/utils/ConfigUtils.js#L33

**Comment by joseffb-mla** [comment]
ok, that's great to know. 

I'll re-pull. I pulled from master yesterday. going to just apply this to git weirdness.

Thank you!
