### ISSUE TITLE
identifyutils buildRequest function drops wms params

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#306]
Hi,

There is an issue with external layers wms get feature query builder. buildRequest (in IdentifyUtils.js) function doesn't take all params from themesConfig params block. Such as if I have to use api key for the layer.

![image](https://user-images.githubusercontent.com/78619273/143433850-74d4fa7e-8354-4536-8bd5-23d4b56656aa.png)

I temporary fixed it with adding specific param to params block
`params.authkey = layer.params.authkey`

How about better way to do this?

**Comment by manisandro** [comment]
> I temporary fixed it with adding specific param to params block
> 
>    params.authkey = layer.params.authkey

Where?

**Comment by lassitanskanen** [comment]
`        const params = {
            height: size[0],
            width: size[1],
            feature_count: 10,
            x: Math.round(size[0] * 0.5),
            y: Math.round(size[1] * 0.5),
            i: Math.round(size[0] * 0.5),
            j: Math.round(size[1] * 0.5),
            bbox: bbox.join(","),
            ...options
        };
        params.authkey = layer.params.authkey

        return identifyRequestParams(layer, queryLayers, map.projection, params);`

**Comment by manisandro** [comment]
Ok - a possibility would be to include any additional params in layer.params but filtering LAYERS, OPACITIES, STYLES

**Comment by manisandro** [comment]
Should be fixed by https://github.com/qgis/qwc2/commit/b3b3c7cd43e41068ad944e09f16f0b077ef32247
