### ISSUE TITLE
allow set transparency for group

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#312]
Hi,

Is already possible to set transparency for layer group? It would be very useful feature if have to separate geometry types to sublayers e.g.

![image](https://user-images.githubusercontent.com/78619273/149295907-d731e3e3-c736-4342-9397-dcfdc4531be8.png)

**Comment by manisandro** [comment]
No this is currently not implemented.

**Comment by manisandro** [comment]
Implemented in https://github.com/qgis/qwc2/commit/4018cd139d04e647325e0a960708451984a4d3cd
