### ISSUE TITLE
http://qwc2.sourcepole.ch/catalog.json returns 404

### ISSUE THREAD

**Issue by mbernasocchi** [qgis/qwc2-demo-app#315]
the catalogue in the demo app is not available anymore
https://github.com/qgis/qwc2-demo-app/blob/3bd296887cde1def83470b63646e7388a22ce370/static/config.json#L526

**Comment by manisandro** [comment]
Thanks, fixed https://github.com/qgis/qwc2-demo-app/commit/1561bce0d3d41cef8cddf50ee55fc4eb4be1d827
