### ISSUE TITLE
example for geoadmin searchprovider is missing

### ISSUE THREAD

**Issue by Geomatik-Thalwil** [qgis/qwc2-demo-app#317]
Specifically about the `requiresLayer` key
https://github.com/qgis/qwc2-demo-app/blob/0a774bc7543567e869623932aad92ebd175519b7/js/SearchProviders.js#L362

how is this supposed to be used? I can add an example but the only way I got it to work was by deleting that line :)

**Comment by manisandro** [comment]
The `requiresLayer` key indicates that the search provider is only available if a layer with that name exists in the layertree.
