### ISSUE TITLE
How do I set the map to full screen on load?

### ISSUE THREAD

**Issue by joseffb-mla** [qgis/qwc2-demo-app#318]
Hi!

I've seen the qwc2.requestFullScreen call in the qwc2 object but I haven't been able to get it to initiate a full screen yet.

I'd like the map to load full screen when you load the map. Thanks!

**Comment by manisandro** [comment]
I believe JS will block a scripted attempt to go fullscreen - it has to be triggered by a user action.

**Comment by joseffb-mla** [comment]
I found the same behavior. I had to set the default state in the actual qwc2 component which I really didn't want to touch. it would be nice to be a configurable option in the demo app config.
