### ISSUE TITLE
How/can you do region insets?

### ISSUE THREAD

**Issue by joseffb-mla** [qgis/qwc2-demo-app#322]
How would you go about  doing region insets into the main map? 

i.e. have Hawaii, Alaska, etc at bottom of the map as a smaller/scaled thumbnail and move to that region of the global map when clicked? 

Possible with QWC2 or is this a JS script thing, like the example script?

 If so any one know how to move, via example script js using api, from one part of map to another?

Thank you very much. Good work on demo app btw. :)

**Comment by joseffb-mla** [comment]
Just thinking that we may need a recipe book for using the JS api in external scripts.

**Comment by manisandro** [comment]
Either write a custom QWC2 plugin which displays the thumbnails somewhere and zooms to the respective extent when clicked, or do this in the parent page and use `window.qwc2.zoomToExtent` with the desired extent.

**Comment by joseffb-mla** [comment]
Can you give me a little example of the zoomToExtent as I think that's the approach I'll need to use. 

Is there a doc on how to make a qwc2 specific plugin?

**Comment by manisandro** [comment]
Example: https://github.com/qgis/qwc2-demo-app/blob/master/static/api_examples.js#L57

No there isn't really any doc at the moment, just the existing plugins as examples.

**Comment by manisandro** [comment]
https://github.com/qgis/qwc2/tree/master/plugins

**Comment by joseffb-mla** [comment]
Tyvm. I'll try to contribute back if we build a plugin for this.
