### ISSUE TITLE
tiled : true in themeconfig do not works anymore 

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#323]
Hello,

I allow myself to open an issue because since some times ago I'm now unable to use the mode tiled : true in my themesconfig.json. 
It used to work before then I restart my server and now it do not work at all. If I use tiled : false the layers are shown normally but with tiled : true the layers do not appears, I can query them but nothing is shown. 

I do not have any specific errors in the javascript console that could help me and everything builds fine for production. 

Do not hesitate ton ask me if you need more infos like my themesconfigs files whatsoever.

kind regards.

**Comment by manisandro** [comment]
Try comparing the GetMap requests with tiled=true and tiled=false in the network tab of the web developer tools (which you can open by pressing F12 in most browsers).

**Comment by cazitouni** [comment]
Thanks for your answer. 
I tried with tiled : false the getmap request is made correctly 
![1](https://user-images.githubusercontent.com/92778930/154966897-912e5157-9ef3-4929-b95a-c2ba047eb7df.png)
but with tiled : true there is no getmap request at all.
![2](https://user-images.githubusercontent.com/92778930/154966958-9b9ab45d-3cda-4b97-9601-f7b53fa0a1ae.png)

**Comment by manisandro** [comment]
can you post a diff of two generated themes.json?

**Comment by cazitouni** [comment]
I've tried, the only addition between the two themes is the "tiled : true" line.
Even if I build with tiled : true and change it manually to tiled : false in themes.json it works, but not with tiled : true.
[themes.zip](https://github.com/qgis/qwc2-demo-app/files/8114655/themes.zip)

**Comment by cazitouni** [comment]
Any other idea about this issue  ?
I'm still trying but nothing works.

**Comment by cazitouni** [comment]
Found the issue. It was about declared extent in the qgis project. The qwc-demo-app show the layer in not tiled even if the extent is not declared but in tiled mode the client do not show anything if the extent is not declared in the project.
