### ISSUE TITLE
specifying locale param doesn't work in app url

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#325]
Hi,

Should locale=<locale> parameter work in app url? eg. http://localhost:8080?locale=fr-FR
It should apply translation to French than English.

I have import defaultLocaleData from '../static/translations/en-US.json'; in appConfig.js

There is a mention in the instructions: https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#managing-translations

**Comment by manisandro** [comment]
Documentation was wrong, fixed in https://github.com/qgis/qwc2-demo-app/commit/7d6475008543d21d900d660b43dfadf9b3e7e0e9, thanks for reporting!
