### ISSUE TITLE
Resizeable window is hidden when the browser width is changed

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#327]
Window should respect browser height and width:

![image](https://user-images.githubusercontent.com/78619273/157218419-6b40f986-dba2-42e5-8c5a-a782e4b1d79b.png)

In addition: Should rotation icon be behind resizeable window? I think that it should be.

![image](https://user-images.githubusercontent.com/78619273/157221789-a18d914b-8833-4948-a0c4-a90039197992.png)

**Comment by manisandro** [comment]
> Window should respect browser height and width:

This would need to be addressed in react-rnd.

> In addition: Should rotation icon be behind resizeable window? I think that it should be.

It should, but it's unfortunately not easy to do, as that element is part of the `ol-overlaycontainer-stopevent` container which also contains the scalebar and overview button of the bottom bar, so changing the z-index would move those elements behind the bottombar.
