### ISSUE TITLE
hide url params?

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#329]
Is it already possible to hide url params from app url?

https://qwc2.sourcepole.ch/?locale=fi-FI&l=edit_points%2Cedit_lines%2Cedit_polygons%2Cgeographic_lines%2Ccountry_names%2Cstates_provinces%2Ccountries&bl=bluemarble&t=qwc_demo&c=1000000%2C6000000&s=10000000

replace by
https://qwc2.sourcepole.ch/#
for users.

**Comment by manisandro** [comment]
You can set `"omitUrlParameterUpdates": true` in config.json
