### ISSUE TITLE
Launch a new app in development mode 

### ISSUE THREAD

**Issue by link25** [qgis/qwc2-demo-app#33]
Hi,
I'm trying to create a new app with my own specification, and when i use the command below:
**./node_modules/.bin/webpack-dev-server --config qwc2/MapStore2/web/client/examples/myapp/webpack.config.js --progress --colors --port 8081 --content-base web/client/examples/myapp**
it shows many errors, i think it may be about some missing files in MapStore2 integrated in qwc2 project, or maybe the code was optimised and it exist another command to run it on the right way.
![zeeee](https://cloud.githubusercontent.com/assets/15951124/26351714/ab96f1d4-3fb0-11e7-8a71-fadbb91b511c.JPG)

If you have any idea about this issue please tell me as soon as possible.
Thank you.

**Comment by manisandro** [comment]
So the first strange thing is that it is looking for leaflet, qwc2 should only be using OpenLayers and any code paths using leaflet disabled. How did you clone the repository?

**Comment by link25** [comment]
Hi manisandro,
I just followed the application instruction:   **git clone --recursive https://github.com/qgis/qwc2-demo-app.git**

**Comment by link25** [comment]
No it changed to this: 
![azeae](https://cloud.githubusercontent.com/assets/15951124/26396235/852dcde6-406a-11e7-9d2b-8ac5c4acb60c.JPG)
I just want to create a new MapStore2 application "myapp" inside qwc2 and run it in development mode. What should i do exactly?

**Comment by manisandro** [comment]
Since nobody else hit this I'd say this was an issue with the local development environment. Feel free to reopen if still an issue.
