### ISSUE TITLE
Import from local GeoJson is broken

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#330]
Steps to reproduce.

1. Start the local demo app with yarn start
2. Use GetFeatureInfo and export to GeoJSON
3. Trying to load the exported GeoJSON in the app results in a blank page after pressing the add layer button.

![image](https://user-images.githubusercontent.com/3179646/158786576-2d44cf99-5ae2-4710-b803-314354ee47d1.png)

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/b072183bd3459f37711e46add3082ca20854397f
