### ISSUE TITLE
Map theme and legend is gone while copy/paste url with layers from another theme

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#333]
Hello,
I have to following issue.
If I add layers from another map theme to to current one, the new layers are sorted within a layer group named as the other map theme:

![grafik](https://user-images.githubusercontent.com/30999402/158894535-3262057a-7f3c-4639-a5ca-fd979db1d4e8.png)

While adding the additional layers, this layers and the map theme they came from are added to the map url. 
If I copy this link and paste it in another windows/tab the map is loaded in the same way with the same layers as it should be, but the layer group an legend is gone:

![grafik](https://user-images.githubusercontent.com/30999402/158895158-0336cdfb-2c6b-4b51-b65a-fbfa5a8b1ac6.png)

**Comment by manisandro** [comment]
Which qwc2 submodule revision are you using?

**Comment by danceb** [comment]
At the moment I am using a version from the end of January:
https://github.com/qgis/qwc2/tree/c14ccdfb

Were there some changes relating to this since then?
So I will try it again with a current version.

**Comment by manisandro** [comment]
Yes there have been numerous fixes and improvements related to this, two of the actually just today.

**Comment by manisandro** [comment]
@danceb Should since be fixed, please reopen if issue is still present.
