### ISSUE TITLE
Parameter qgisServerVersion is not documented

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#334]
Although it seems to be clear, a short explanation of the parameter 'qgisServerVersion' in config.json would be helpful: what is the default, what might happen, when there are differences in QGIS client and server version - what are the effects of this parameter?
Thank you!

**Comment by manisandro** [comment]
Done https://github.com/qgis/qwc2-demo-app/commit/025a1c193082d3eb0f83c2d33a46edc8e1e927b9
