### ISSUE TITLE
Correct way of using internal WMTS

### ISSUE THREAD

**Issue by vvmruder** [qgis/qwc2-demo-app#338]
I use the config generator to configure a WebGIS with [qwc-ogc-service](https://github.com/qwc-services/qwc-ogc-service) This way I can route internal layers to be aditionally configured and I do not need to expose my QGIS-Server to the web. However I have also a internal WMTS I want to route throught this construction. In the moment I configure them in my tenantConfig.json as backgroundLayers. This way the Client is directly accessing the WMTS which needs to be exposed to the Web.

What would be the correct QWC way to also route these WMTS through the [qwc-ogc-service](https://github.com/qwc-services/qwc-ogc-service)?

Is there another way I do not see here?

**Comment by manisandro** [comment]
WMTS are currently not handled by qwc-services.

**Comment by vvmruder** [comment]
ok-thank you for the answer. I will try to loop it through a QGIS-Server for the moment.
