### ISSUE TITLE
legendgraphic url bug for external layer

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#339]
Hi,

I have external layers blocks in themesConfig and try to request legendgraphics on UI. It should define LAYERS for GetMap and LAYER for GetLegendGraphic to geoserver.

To make both requests work it have to define legendUrl in themesConfig. I think that this is a bug and we should modify getLegendUrl function in LayerUtils.js? The function use "params" block from themesConfig which produce incorrect url for getLegendGraphic.

With legendUrl which is work:
      {
        "name": "lipas_liikuntapaikat",
        "type": "wms",
        "url": "http://localhost/geoserver/ows"
        "legendUrl": "http://localhost/geoserver/ows?LAYER=lipas_liikuntapaikat",
        "params": {
          "LAYERS": "lipas_liikuntapaikat"
        }
      },

Legendgraphic will not work automatically but it should work also:
      {
        "name": "lipas_liikuntapaikat",
        "type": "wms",
        "url": "http://localhost/geoserver/ows"
        "params": {
          "LAYERS": "lipas_liikuntapaikat"
        }
      },

Version qwc2 @ e717b17

**Comment by manisandro** [comment]
Thanks fixed in https://github.com/qgis/qwc2/commit/1121fc2d3dbc7b35d6f77b51b14beeb608de34d2
