### ISSUE TITLE
Scrolling in "Map & Tools" menu on touch devices

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#341]
With a longer list of entries in the "Map & Tools" menu, for example with the "Map Tools" entry expanded, the scrolling in this list on smaller touch devices is not really usable, because the menu closes automatically when swiping up.

Maybe it is useful to remove that "`onSwipedUp={this.toggleMenu}`" in the [AppMenu.jsx](https://github.com/qgis/qwc2/blob/07abda70db64e9edd17b220321a93f459a7cb89c/components/AppMenu.jsx#L156) file.

**Comment by manisandro** [comment]
Thanks - yes I guess it's easiest to just drop the Swipeable wrapper, done: https://github.com/qgis/qwc2/commit/698af5441907702c6283c6aa00d3e16268f8b335
