### ISSUE TITLE
Issue while printing

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#342]
I got error while printing in version qwc2 @ d4e6048

![image](https://user-images.githubusercontent.com/78619273/164002536-bd7aeb85-fbb3-428f-b8bf-29fb0c625a08.png)

**Comment by manisandro** [comment]
Thanks, since fixed in https://github.com/qgis/qwc2/commit/afb63b10a706e332d1dbc046a538bc4e3e686c07
