### ISSUE TITLE
Avoid excessive WMS parameter updates to reduce load on server does not work as it should

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#343]
https://github.com/qgis/qwc2/commit/d950116a329f88f38377e85aa7c02cbdefe6dd78 does not work as it should
please see the gif
if I revert the commit above it goes well
@manisandro can you take a look?

![example_qwc](https://user-images.githubusercontent.com/11608132/164202238-72660501-8b89-4422-85d5-7f405cc09dc6.gif)

**Comment by manisandro** [comment]
Are you using the default demo theme, and just toggling the layers?

**Comment by luciman** [comment]
Yes the example is on the default demo theme. Also on others themes is the same behavior 
1 case
 If there are no layer toggled, when you'll toggle a layer the map will not update. If you toggle the second layer, the map will update with both. 
2 case
 If there are no layer toggled, when you'll toggle a layer the map will not update. If you will untoggle it the layer will appear for a moment on the map and then disappears
![example](https://user-images.githubusercontent.com/11608132/164205362-bedcea4b-dd62-4ba6-8d3c-add13b6aeaff.gif)

**Comment by luciman** [comment]
if you look at requests on toggle there are no request and on untoggle there are tow requests

![example_qwc_2](https://user-images.githubusercontent.com/11608132/164212664-ed3a4e4d-69bd-4e0c-af38-389c5d6be7cf.gif)

**Comment by manisandro** [comment]
I found the issue, fix coming very soon

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/8592a94d88bd5e78854578f59941d45a96d89b3a

**Comment by luciman** [comment]
Thanks!

**Comment by manisandro** [comment]
Thanks for reporting!
