### ISSUE TITLE
Scrolling the "Map & Tools" menu on touch devices switches also the full screen mode on/off

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#345]
When scrolling a longer list of entries in the "Map & Tools" menu on touch devices, the full screen mode is also switched on/off.

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/87a4c2e5ecf850ccadcb458d7c1ab433db313d03
