### ISSUE TITLE
Current user info

### ISSUE THREAD

**Issue by demtotal** [qgis/qwc2-demo-app#347]
Greetings everyone,

I'm using QWC2 on docker and i'm also using the qwc-db-auth service, i would like to retrieve the username on the client side is that possible ? I found this line of code in qwc2/plugins/Authentication.jsx : `        const username = ConfigUtils.getConfigProp("username");
` that i guess it should retrieve the connected username but it shows me always an empty string! 
Is there's a way to make this happen ?

Thanks in advance,
Have a great day.

**Comment by manisandro** [comment]
`username` in `config.json` (retreived by `ConfigUtils.getConfigProp("username")`) should contain the current username. If not, something is wrong with your qwc-docker setup.
