### ISSUE TITLE
GetMap requests are far bigger than the screen resolution for Retina/Hidpi displays

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#35]
While testing under IOS/Android we noticed the GetMap requests are far bigger than the screen resolution.

You can see this if you do a pinch outer zoom before the next image gets returned.
This affects the mobile experience.
Will try to make a gif.

**Comment by andreasneumann** [comment]
I think this is intended - as you can then pan a bit and already see the surrounding. Probably something that can be tweaked in OpenLayers.

**Comment by tudorbarascu** [comment]
By the looks of it (too lazy to see exactly) the area of the requested image is around 3 times the area of the screen.
Thus, on the same Wifi connection, the experience is noticeably worst than that of a Desktop PC with better resolution.
It seems to be working well only for devices with low resolution or for tiled images.
I think the advantage is too small for the disadvantage.

**Comment by luciman** [comment]
I think is an OpenLayers problem.

For example on my galaxy s7 device on qwc2 I have document.body.offsetWidth = 360 document.body.offsetHeight = 568 and the GetMap request have WIDTH=5764  HEIGHT=9088
which is enormous and makes it very slow.

Also on http://openlayers.org/en/latest/examples/wms-image.html  the map div have width=330 height=400 and the GetMap request have WIDTH=1321  HEIGHT=1418

On desktops the width and the height of the GetMap request are the same as the div

**Comment by tudorbarascu** [comment]
The issue occurs on all HIDPI/Retina screens, whether the client is Mobile or Desktop
