### ISSUE TITLE
changeMeasurementState is not defined

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#350]
Hi,
after upgrading from e883d96 to latest, I get the error: 'changeMeasurementState is not defined' (qwc2App.js 704:3). Reverting back everything works fine.

**Comment by manisandro** [comment]
Can you post a screenshot of the error and steps to reproduce?

**Comment by mhaelsig** [comment]
Hi,
after update to 

93d57f7e Allow dragging time slider cursor 

everything worked fine - calling the localhost:8081 I see in the Firefox 
debugger (screenshot 1).
(The resulting website is 'radwegplanung-muenchen.de')

After update to
445a0780 Pass locale when loading designer form
0bcd3b51 Use dedicated DateInput component in TimeManager

after 'yarn start' calling localhost:8081 I get these messages in the Firefox 
debugger (screenshot 2) - and an empty screen. 

Kind regards - and many thanks for your work

Michael Hälsig

**Comment by manisandro** [comment]
The screenshots didn't make it through

**Comment by manisandro** [comment]
Ups never mind, figured out what happened. Fixed, thanks for the report!
