### ISSUE TITLE
&hc=1 doesn't paint the pin

### ISSUE THREAD

**Issue by claudiadragoste** [qgis/qwc2-demo-app#351]
I go to Share Link, enable  "show pin" and I generate the permalink; When I paste the permalink created and it contains "&hc=1", this has no effect, there is no pin on the map. Is this the expected behavior? 
(by the way, the qwc2 is great!!)

Thank you!

![image](https://user-images.githubusercontent.com/26380648/169255628-5d94a4d7-c0cd-42cb-a747-fc06d8c128e0.png)
![image](https://user-images.githubusercontent.com/26380648/169255804-a327415a-88d6-4af9-bb2b-539459ad6d7c.png)

**Comment by manisandro** [comment]
Do you have the StartupMarker plugin enabled?

**Comment by claudiadragoste** [comment]
Sorry for my stupid question: how can I enable it? (besides having it in AppConfig.js and in config.json)

**Comment by manisandro** [comment]
That's all that's needed actually

**Comment by claudiadragoste** [comment]
Solved!! in config.json, I had "urlPositionFormat": "extent"; changing it for "urlPositionFormat": "centerAndZoom" and it works perfect! It's great!!

**Comment by manisandro** [comment]
Indeed the `c` parameter is required, I forgot about this aspect! I've extended the Share component to ensure `c` is added to the URL if the pin is enabled: https://github.com/qgis/qwc2/commit/e5e28355e1c534748c00048194afc682c2d017fe

**Comment by claudiadragoste** [comment]
Thank you!! That's even better! I'm still wondering how you created the url with 'p' parameter. I couldn't find 5his option in the documentation. I like this compact form: http://qwc2.sourcepole.ch/?k=2ff4415c7&hc=1

**Comment by manisandro** [comment]
There is no standard `p` parameter?

**Comment by claudiadragoste** [comment]
Sorry, sorry, I wabted to say 'k'

**Comment by manisandro** [comment]
`k` is the permalink hash parameter. The share component automatically generates such a key if there is a permalink service active, see [1] and [2].

- [1] https://github.com/qgis/qwc2-demo-app/blob/master/static/config.json#L6
- [2] https://github.com/qwc-services/qwc-permalink-service

**Comment by claudiadragoste** [comment]
Oh, thank you!!
