### ISSUE TITLE
Identify with "mode": "Region" doesn't work 

### ISSUE THREAD

**Issue by claudiadragoste** [qgis/qwc2-demo-app#352]
If I do first "Identify Region", after drawing the polygon, the Identify doesn't work, I got a white window (checking the error with the web developer tool: e.props.click.modifiers is undefined)
If I do first click on the map, Identify works well and then i can do "Identify Region" and also works.

**Comment by manisandro** [comment]
Can you attach a screencast?

**Comment by claudiadragoste** [comment]
Sure

https://user-images.githubusercontent.com/26380648/169381280-48422656-fa8d-479e-a84e-47819ccbd6e0.mp4


https://user-images.githubusercontent.com/26380648/169381343-8375e14b-bbe1-4b74-a1b3-28c20dd0c053.mp4

:

**Comment by claudiadragoste** [comment]
Sure

https://user-images.githubusercontent.com/26380648/169384731-823c2b8e-8c72-4bc0-9cc4-190ea53329e9.mp4


https://user-images.githubusercontent.com/26380648/169384748-99e5fbad-d8d1-47c6-b216-aa51715f9e34.mp4

![image](https://user-images.githubusercontent.com/26380648/169384763-bbddf924-92f3-432d-8f3a-ef0148fdf2b9.png)

**Comment by claudiadragoste** [comment]
Sure
Not working:

https://user-images.githubusercontent.com/26380648/169384885-d4f6fdba-7066-4efe-ad56-bda0f2ffb4bc.mp4

The error:
![image](https://user-images.githubusercontent.com/26380648/169384940-72cd2398-652d-4342-9db9-ca8ebcaeff52.png)

Working:

https://user-images.githubusercontent.com/26380648/169384954-ef5c4da7-2c16-479e-9c19-377212b0d2c0.mp4

**Comment by claudiadragoste** [comment]
By the way, I checked the behavior of Identify Region in the demo web (http://qwc2.sourcepole.ch) and it also fails.

**Comment by manisandro** [comment]
Thanks, fixed https://github.com/qgis/qwc2/commit/5eee62991c2d0772ad175af7a4baf1084e3f6898

**Comment by claudiadragoste** [comment]
Super, thank you
