### ISSUE TITLE
generate getFeatureInfo Form from a json file

### ISSUE THREAD

**Issue by claudiadragoste** [qgis/qwc2-demo-app#359]
Hello,

I saw that I can customize the Attribute Form in the qgis project and then I can see it on the web when I do getFeatureInfo (Identify). My question is: is there a way to generate the form from a json file? The same question for the form in Editing (can I generate the form from a json file?)

**Comment by manisandro** [comment]
What do you mean to generate the form from a json file? If you use the feature-info-service [1], you can create custom feature-info templates, don't know if this satisfies your requirements?

[1] https://github.com/qwc-services/qwc-feature-info-service

**Comment by claudiadragoste** [comment]
Thanks again! i thing I was on the wrong way at the beginning - I arrived to check the jasper-reporting-service instead of feature-info-service. I think that feature-info-service is the solution for what I wanted.
