### ISSUE TITLE
Show image in feature info

### ISSUE THREAD

**Issue by karl-magnus** [qgis/qwc2-demo-app#36]
I want to show an image in the feature info window. The only way I've suceded to do it is to create an virtual attribute in the qgis project like this:
 `'<img src="http://ikarta.kristianstad.se/img/legend/skno/'|| "legend" ||'.PNG" /><a></a>'`
the `<a></a>` is a workaround to pass through the test `if(text.indexOf("</a>") !== -1)` on line 297 in IdentifyViewer.jsx.
Could it be changed to:
`if(text.indexOf("</a>") !== -1 || text.indexOf("<img") !== -1)`
or is there another way to show images?

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/31039fc6f6d2ca5bfc17e184fd787db6568033ac
