### ISSUE TITLE
Do not activate all subgroup layers when activating subgroup

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#360]
When I have a subgroup or nested subgroups, clicking the + marker simply opens the subgroup. But:  especially unexperienced users tend to click the box instead of the + sign, which opens the subgroup, but also *activates* all sublayers and embedded layers in further subgroups. A subgroup might contain conflicting layers, therefore activating all layers at once leads to confusion. 
 
Is there a switch or parameter to prevent activating all sublayers, when a subgroup is activated (clicking the box)?

Thank you for all the great work!

**Comment by manisandro** [comment]
Yes, see [1]

[1] https://github.com/qgis/qwc2-demo-app/blob/e917bfc880a805334827b6aa96260e5c9a612aac/static/config.json#L214
