### ISSUE TITLE
Print issue

### ISSUE THREAD

**Issue by claudiadragoste** [qgis/qwc2-demo-app#361]
Hello,
I wasn't able to find anything that explains how I can manage to add "user_text" textbox, when want to print. And also how can I do to open the pdf that is generated in a new iframe, as it works in https://qwc2.sourcepole.ch/.

**Comment by manisandro** [comment]
See "Print layout labels" in the table[1] and [2] for inline print output.

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#creating-and-publishing-a-qgis-project
[2] https://github.com/qgis/qwc2-demo-app/blob/master/static/config.json#L193

**Comment by claudiadragoste** [comment]
ooooh!! I should have seen it! Sorry! 

Is it possible to modify [1] and write something like 
<td>{LocaleUtils.tr("print."+{label})}</td> 
instead of 
<td>{label}:</td>
and then add manually the translation in the files from the folder static\translations? (I don't know if the syntax of what I wrote is correct, no jsx knowledges)

[1] [https://github.com/qgis/qwc2/blob/eef2d8772483964efc23183187795a99fb06685d/plugins/Print.jsx#L251](url)

**Comment by claudiadragoste** [comment]
No need to answer to this last msg. It's me - that I need some js and jsx. Thank you
