### ISSUE TITLE
Split WMS request by layer

### ISSUE THREAD

**Issue by FirekingD** [qgis/qwc2-demo-app#362]
Hello everyone,

I've noticed that the webclient request different layers with a signle wms query, how can i change it's behavior to to send a wms request seperately for each layer , is this possible through configuration files or should i edit the source code ( Map.jsx or LayerUtils.js ) ?

Thanks in advance,

Have a great day

**Comment by manisandro** [comment]
Forgive me the question, but why would you want to split up the WMS requests?

To answer the question: no this is currently not configurable.

**Comment by FirekingD** [comment]
Hello again,

Splitting WMS requests allows the application to display data quickly when there's layers that loads slowly or in the case of projects with many layers ( 30+ ) i've noticed big performance differences between the two and i could test this manually by creating a blank theme and adding the same layers ( seperately one at a  time ) from another theme. Also using tiled and seperated WMS requests by layers would allow to use server side caching solutions (i guess) .
Should i close the issue ?

Thanks in advance

**Comment by manisandro** [comment]
For pure WMS and measuring the time until the map is fully loaded, I'd expect the performance of split up layers to be worse than combined layers, as you'll multiply the overhead of data transfer + pipeline setup times the number of requests. It is true that the time until something is displayed on the map is likely much shorter with separate requests if there are large layers involved. 

You could experiment with this by tweaking componentDidUpdate of `qwc2/plugins/Map.jsx` by breaking out every sublayer into a separate layer when computing `renderLayers`.

**Comment by FirekingD** [comment]
Ok thanks for your response. I will test it out.

Have a great day.
