### ISSUE TITLE
SearchProviders with their own searchtables

### ISSUE THREAD

**Issue by claudiadragoste** [qgis/qwc2-demo-app#364]
Hello again,
I was thinking to define 2 searchproviders, using the uster example and use them for a theme. Is it possible to define their own searchtables? Right now, if I define the searchtables, they are available for both of the serchproviders. (I don't know if my question makes sense with SearchBox.jsx; as I still use Search.jsx, this would be very helpful for me)

**Comment by manisandro** [comment]
Sorry but I cannot understand the question.

**Comment by claudiadragoste** [comment]
Sure, I will try to be more explicit. Though, maybe I misunderstand the concept af a searchprovider.
So, for a hand, I inform the searchtables in this file (the server has configured with this service):

https://github.com/qgis/QGIS-Web-Client/blob/master/wsgi/search.wsgi#L32

And for another hand I define 2 searchproviders using the "uster" model

https://github.com/qgis/qwc2-demo-app/blob/master/js/SearchProviders.js#L192

If both of them are looking for the same search.wsgi, the tables defined in this file are available for both of the providers. And I don't want this. It seems that I should have 2 different search.wsgi so I could separate the searchtables - I don't know if this is possible or if it is the best solution.

(I enormously appreciate your time dedicated for this kind of doubts that maybe I should know to answer myself)

**Comment by manisandro** [comment]
You can pass a parameter to search.wsgi and handle it to pick the searchtable. But this goes beyond simple questions relating to QWC2.
