### ISSUE TITLE
Labeling of search results

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#365]
Hello,

is there a way to configure the labeling of search results?
Searching for a street looks like this in our system:
![grafik](https://user-images.githubusercontent.com/30999402/172637976-d78b58db-31c3-4049-a60f-2b01a48c7a82.png)

Now I am looking for a way, to get only one label per search result.
We are using the docker-stack with a solr docker image.

Thank you!

**Comment by manisandro** [comment]
Looks like the same label is attached to every vertex of the search geometry. How does the search geometry look like? Can you post the response from the search service containing this geometry?

**Comment by danceb** [comment]
The geometry is a "FeatureCollection" containing a multilinestring. Maybe the issue is related to this?

`{"type": "FeatureCollection", "crs": {"type": "name", "properties": {"name": "EPSG:25832"}}, "features": [{"type": "Feature", "id": 2086, "geometry": {"type": "MultiLineString", "coordinates": [[[681627.115573103, 5645219.62213515], [681626.554694604, 5645220.13860985], [681626.009474006, 5645221.48923319], [681623.773436815, 5645239.5668547]], [[681666.441785714, 5645216.38459972], [681660.178166116, 5645217.97614046], [681628.172779504, 5645218.92968082], [681627.373691534, 5645219.28940746], [681627.115573103, 5645219.62213515]], [[681800.760944399, 5645211.42839444], [681794.894849021, 5645212.80281631], [681743.989923372, 5645212.96736929], [681732.556139453, 5645222.01565477]], [[681714.311602992, 5645215.35022774], [681703.280793085, 5645215.84112346], [681689.390920633, 5645215.96679866], [681666.441785714, 5645216.38459972]], [[681623.773436815, 5645239.5668547], [681619.880749575, 5645239.60353563], [681605.219048839, 5645239.62775222], [681598.330788999, 5645239.71791665], [681582.560063588, 5645239.40676227], [681571.366315302, 5645239.61206936]], [[681571.366315302, 5645239.61206936], [681554.411712655, 5645241.41471911], [681538.50671012, 5645243.47577309], [681521.156911107, 5645246.58802935]], [[681803.236911683, 5645238.43348698], [681786.39931724, 5645238.77957478], [681766.684704657, 5645239.02866172], [681756.032318871, 5645239.11586179], [681738.017738993, 5645239.17385927], [681727.449799786, 5645239.21444866], [681700.30747629, 5645239.42165864], [681667.645015045, 5645239.16412652]], [[682022.191046271, 5645235.53017866], [681988.788303842, 5645235.86136182], [681961.747683656, 5645236.00264755], [681942.319941238, 5645235.69288646]], [[681942.319941238, 5645235.69288646], [681890.225723965, 5645236.84699351], [681803.236911683, 5645238.43348698]], [[681667.645015045, 5645239.16412652], [681639.460641512, 5645239.41903358], [681623.773436815, 5645239.5668547]], [[681936.745987369, 5645212.80561827], [681924.099719342, 5645213.00189464], [681904.052777059, 5645212.89715946], [681800.760944399, 5645211.42839444]]]}, "properties": {}}], "bbox": [681521.156911107, 5645211.42839444, 682022.191046271, 5645246.58802935]}
`

That's the response of the same geometry but in another qwc2 instance using another (own) search, there the response is a multilinestring without the "FeatureCollection" and there it is only one label shown:

`
MULTILINESTRING((681623.773436815 5645239.5668547,681619.880749575 5645239.60353563,681605.219048839 5645239.62775222,681598.330788999 5645239.71791665,681582.560063588 5645239.40676227,681571.366315302 5645239.61206936),(681803.236911683 5645238.43348698,681786.39931724 5645238.77957478,681766.684704657 5645239.02866172,681756.032318871 5645239.11586179,681738.017738993 5645239.17385927,681727.449799786 5645239.21444866,681700.30747629 5645239.42165864,681667.645015045 5645239.16412652),(682022.191046271 5645235.53017866,681988.788303842 5645235.86136182,681961.747683656 5645236.00264755,681942.319941238 5645235.69288646),(681942.319941238 5645235.69288646,681890.225723965 5645236.84699351,681803.236911683 5645238.43348698),(681571.366315302 5645239.61206936,681554.411712655 5645241.41471911,681538.50671012 5645243.47577309,681521.156911107 5645246.58802935),(681666.441785714 5645216.38459972,681660.178166116 5645217.97614046,681628.172779504 5645218.92968082,681627.373691534 5645219.28940746,681627.115573103 5645219.62213515),(681667.645015045 5645239.16412652,681639.460641512 5645239.41903358,681623.773436815 5645239.5668547),(681800.760944399 5645211.42839444,681794.894849021 5645212.80281631,681743.989923372 5645212.96736929,681732.556139453 5645222.01565477),(681714.311602992 5645215.35022774,681703.280793085 5645215.84112346,681689.390920633 5645215.96679866,681666.441785714 5645216.38459972),(681936.745987369 5645212.80561827,681924.099719342 5645213.00189464,681904.052777059 5645212.89715946,681800.760944399 5645211.42839444),(681627.115573103 5645219.62213515,681626.554694604 5645220.13860985,681626.009474006 5645221.48923319,681623.773436815 5645239.5668547))
`

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/8baffa61d806782c8701ddcb4608c90225596f8b
