### ISSUE TITLE
Empty Check Boxes instead of grayed Check Marks

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#366]
Hi,
the QGIS layer structure shows empty check boxes, and only the active layer and the groups containing this layer are check marked (Bild1).
![Bild1](https://user-images.githubusercontent.com/10079628/172653110-b1b49ac8-e391-4230-8079-465247ee46d5.png)
The initial layer structure in qwc2 shows all groups with grayed check marks (Bild2). This seems confusing to the average user - in contrast to the QGIS layer structure.

![Bild2](https://user-images.githubusercontent.com/10079628/172653116-4ab5984e-db5a-4f58-868c-708915708584.png)

Only by opening all groups and subgroups a user can find the active layer (Bild3). Still, inactive groups below are shown with grayed check marks.

![Bild3](https://user-images.githubusercontent.com/10079628/172653121-8e40e3d8-6560-4705-8476-23614df21b16.png)

Is there a way to get the layer structure in qwc2 with empty check boxes similar to the QGIS layer structure? 

These are the layer configuration parameters:

"name": "LayerTree",
          "cfg": {
            "showLegendIcons": true,
            "showRootEntry": false,
            "showQueryableIcon": true,
            "allowMapTips": true,
            "allowCompare": true,
            "allowImport": true,
            "groupTogglesSublayers": false,
            "grayUnchecked": false,
            "layerInfoWindowSize": {"width": 480, "height": 400},
            "bboxDependentLegend": true,
            "scaleDependentLegend": "theme",
            "showToggleAllLayersCheckbox": false

'groupTogglesSublayers' : true
 changed somehow, but has another meaning - which I do not want. 
'grayUnchecked': true
had no visible consequence. 

Thank you!

**Comment by manisandro** [comment]
Are there any active layers below i.e. "Barrieren" in QWC?

**Comment by mhaelsig** [comment]
Hi,
no. All layers below are inactive. There are no more layers below 'Barrieren'. 
The website is <https://radwegplanung-muenchen.de>

Thank you for all your work!
Michael Hälsig

-- 
Dr. Michael Hälsig
Diefenbachstr. 9
81479 München

Tel.: +49 89 79199563
Mob.:+49 171 333 7558
Am Mittwoch, 8. Juni 2022, 17:43:45 CEST schrieb Sandro Mani:

**Comment by manisandro** [comment]
Fixed by https://github.com/qgis/qwc2/commit/e234d9d4a9033430623eef313bd3bfea2070c713
