### ISSUE TITLE
Request Feature Info fails 

### ISSUE THREAD

**Issue by Chris98RUB** [qgis/qwc2-demo-app#368]
Hello people, 

i'm trying to configure the qwc2, but when i like to request the feature info, inside the request window appears the text: "No information available for the selected point". Does somebody know, how to fix this? 

Thanks in advance
Chris

<img width="429" alt="Unbenannt" src="https://user-images.githubusercontent.com/104851011/173424196-98fa075d-2e8d-42f8-ac8a-cd18bbf5647b.PNG">

**Comment by manisandro** [comment]
This looks like a CORS issue: check the browser console (F12) for related messages, see also [1].

HTH
Sandro

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#server-side-configuration

**Comment by Chris98RUB** [comment]
Hello Sandro,

it works with CORS Everywhere.

Thank you 
Chris
