### ISSUE TITLE
MapTips not shown in Mobile

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#369]
Hi,
although I have identical parameters for 'desktop' and 'mobile' in config.json - and also '"mapTips": true,' in themes.json, the menu item 'MapTips' is only shown in the desktop version - see attachments. This is independent of the mobile browser used. 
Are MapTips not possible in 'Mobile' and therefore suppressed?
Thank you for any hints!
Mobile:
![Screenshot_20220619-073950_Edge](https://user-images.githubusercontent.com/10079628/174467606-92d8685e-f070-4386-8a6e-6a2ce60592a8.png)
!
Desktop:
![Screenshot_20220619_073755](https://user-images.githubusercontent.com/10079628/174467620-46ced765-4ee8-499b-acba-e689aa7e3d22.png)

**Comment by manisandro** [comment]
As there is no hover event with touch devices, maptips aren't triggerable on mobile.
