### ISSUE TITLE
Layer title, name and displayField in Feature info

### ISSUE THREAD

**Issue by karl-magnus** [qgis/qwc2-demo-app#37]
Seems that layer title (entered in the metadata tab in layer properties) is never used in the layer info window. DisplayField is only working with the title and shortname set to same as layername or leaved blank.

**Comment by manisandro** [comment]
Old issue, but:
- QWC2 displays the layer name as returned by QGIS Server in the GetFeatureInfo reply
- QGIS Server returns as displayField the field specified in the Vector Layer Properties -> Display Name, if the expression there specified is a simple field, otherwise displayField is empty.
