### ISSUE TITLE
Editing Dataset fails 

### ISSUE THREAD

**Issue by Chris98RUB** [qgis/qwc2-demo-app#370]
Hello people, 

in my configuration of QWC2, i try to set up an editable dataset. If i try to add new data to this dataset by committing in the Editing-Tool, nothing happens. Picking an existing object is also unavailable. I've enabled the editing-tool in "config.json" and "appConfig", set up the "editServiceUrl" with my WMS QGis Server link and also the "editConfig"-part in "themes.json". For editing, i use the default editing interface. 

Does somebody may know the reason why it does not work? 

Thanks in advance 
Chris

**Comment by manisandro** [comment]
Probably due to CORS - did you check the browser console for any messages?

**Comment by Chris98RUB** [comment]
I have activated the CorsE-plugin for Firefox. Requests for feature infos are working.  When i want to add a new dataset, nothing is shown in the browser console and nothing happens. When i want to pick a feature by the editing-Tool there is a message "Uncaught (in promise) TypeError: feature is null".

**Comment by Chris98RUB** [comment]
<img width="1021" alt="Unbenannt" src="https://user-images.githubusercontent.com/104851011/174840596-dc3e83c9-f6f2-4469-a5a7-fc6112f27239.PNG">
It shows this.

**Comment by manisandro** [comment]
This is the browser console, not the network pane

**Comment by Chris98RUB** [comment]
<img width="927" alt="Unbenannt" src="https://user-images.githubusercontent.com/104851011/174847645-e83634c9-58d3-400c-bed4-5143940f562a.PNG">
When i like to pick a point, these are the requests.

**Comment by manisandro** [comment]
These are all requests to the QGIS Server, there appears to be no data service involved

**Comment by Chris98RUB** [comment]
So could it be, that the "editServiceUrl" is wrong?

**Comment by manisandro** [comment]
For editing you need a data service set up, see https://github.com/qwc-services/qwc-data-service for details.

**Comment by manisandro** [comment]
Please look at https://github.com/qwc-services/qwc-docker for a full sample setup.
