### ISSUE TITLE
Feature Info with tabs

### ISSUE THREAD

**Issue by claudiadragoste** [qgis/qwc2-demo-app#373]
Is there any way to configure Feature Info to have tabs, as in the qgis project? Having the service qwc-feature-info-service would solve it? 

What I see in the qgis project:
![image](https://user-images.githubusercontent.com/26380648/180248447-e9094b86-90e5-4b5b-9661-c071bad266b1.png)

What I see on the web side:
![image](https://user-images.githubusercontent.com/26380648/180248958-9c8ecb13-c43a-4239-b595-8e332359d5b4.png)

**Comment by manisandro** [comment]
The FeatureForm plugin will display feature in a form similar to QGIS (autogenerated, Drag and drop or custom forms, as configured in the QGIS layer settings). Do use it as the default identify tool:
- Ensure FeatureForm is enabled as a QWC plugin (similarly to any other plugin)
- In `config.json`, set `"identifyTool": "FeatureForm"` at top-level
- Set up the qwc-data-service if not yet done
- In the qwc-admin gui, create data resources and associated permissions for all layers which should be queryable. The permission can also be read-only if you don't want to allow editing.

**Comment by claudiadragoste** [comment]
As always, thank you very much for your disponibility

**Comment by claudiadragoste** [comment]
as always, tank you very much!
