### ISSUE TITLE
Switch layers visibility strange timing

### ISSUE THREAD

**Issue by vvmruder** [qgis/qwc2-demo-app#374]
I was investing some time to find the reason but was not able to. I experience some strange timing when I switch between two layers in the tree. Since I do not know how to describe it, I shoot a video :)
[layer-switch.webm](https://user-images.githubusercontent.com/3714179/181584939-21b63039-ac65-40a7-83e7-1079e3e117df.webm)

Everytime the new layer is enabled the old one is shown for a short moment. I guess it might be connected to async HTTP stuff?

**Comment by vvmruder** [comment]
I'm still on it. It might be connected. I tried several approaches including wait for [imageloadend](https://openlayers.org/en/latest/apidoc/module-ol_source_Image.ImageSourceEvent.html#event:imageloadend)

but it does not change the behavior.

**Comment by vvmruder** [comment]
To be more specific. If I change the mentioned part to:
```
update: (layer, newOptions, oldOptions) => {
        if (oldOptions && layer && layer.getSource() && layer.getSource().updateParams) {
            let changed = (oldOptions.rev || 0) !== (newOptions.rev || 0);
            const oldParams = wmsToOpenlayersOptions(oldOptions);
            const newParams = wmsToOpenlayersOptions(newOptions);
            if (!changed) {
                changed = Object.keys(newParams).find(key => {
                    newParams[key] !== oldParams[key];
                }) !== null;
            }
            if (changed) {
                const queryParameters = {...newParams,  __t: +new Date()};
                if (layer.get("updateTimeout")) {
                    clearTimeout(layer.get("updateTimeout"));
                }
                layer.setVisible(false);
                layer.set("updateTimeout", setTimeout(() => {
                    layer.setVisible(queryParameters.LAYERS && newOptions.visibility);
                    layer.set("updateTimeout", null);
                }, 5000));
                layer.getSource().updateParams(queryParameters);
                layer.getSource().changed();
                layer.getSource().refresh();
            }
        }
    }
```
It behaves the same. Most strangely it does not do any network requests on the call of `layer.getSource().refresh()` which I can trigger if I do it by hand on the layer. I only starts a request after 5 seconds when `layer.setVisible(queryParameters.LAYERS && newOptions.visibility);` is called.

**Comment by vvmruder** [comment]
If I remove this if it works like expected.

https://github.com/qgis/qwc2/blob/81191f87ed0808ea2034cedffa41f03a3e2e50c3/components/map/OlLayer.jsx#L44-L46

I was not able to see if there are side effects. Everything seems ok. What do you think @manisandro ?

**Comment by manisandro** [comment]
The commit message on that line says `Fix WMS delayed update not triggering redraws if layer visibility changes`.

I think what you are seeing is just the 500ms updateTimeout delay. You can shorten it to say 50ms to see if it makes a difference for you, in case we can make this delay configurable. The overall reason for the timeout is to avoid firing many requests to the QGIS Server in short sequence.

**Comment by vvmruder** [comment]
This is exactly the strange thing. It doesn't matter if I put there 5000ms or 5ms The flicker effect is not changing. It only happens sooner or later. But it happens always the same.

But If I remove the mentioned if statement around the visibility setting of all layer as mentioned above https://github.com/qgis/qwc2/blob/81191f87ed0808ea2034cedffa41f03a3e2e50c3/components/map/OlLayer.jsx#L44-L46
it works without any effects. Is it possible that the settimeout apporach was a leftover from a older OpenLayers version?

**Comment by vvmruder** [comment]
I did a PR to offer a fix: https://github.com/qgis/qwc2/pull/214

**Comment by manisandro** [comment]
Closing as possibly no longer relevant, feel free to reopen if still relevant.
