### ISSUE TITLE
apply OpenLayers className to layer

### ISSUE THREAD

**Issue by vvmruder** [qgis/qwc2-demo-app#376]
As far as I understand the binding to OpenLayers is defined here:
https://github.com/qgis/qwc2/blob/master/components/map/layers/index.js

To change rendering especially related to blend modes e.g. "multiply" it would be really useful to configure the [className](https://github.com/openlayers/openlayers/blob/main/src/ol/layer/Base.js#L31) of a layer. I think this could be done by extending the options of themes.json

A bonus might be to also extend QGIS-Server GetProjectSettings to deliver this information.

1. Any concerns about that?
2. Any hints what parts need special care or if there are pitfalls?

I solved it hardcoded with defining a class in css setting: `mix-blend-mode: multiply;` After that I set all OL WMS-Layers with this class as `className` Result is like in QGIS the multiplied overlay:
![image](https://user-images.githubusercontent.com/3714179/182845450-4bc7ea4e-5e9c-447b-bc5e-2825daab67f4.png)
This gives really nice results without setting opacity :)

**Comment by manisandro** [comment]
Closing as per discussion at FOSS4G
