### ISSUE TITLE
Translate layer's name

### ISSUE THREAD

**Issue by vsgis** [qgis/qwc2-demo-app#380]
Hello everybody,

Is there a way to translate layer's name ?

I try adding a key (i.e layers.layer_name_1) in tsconfig.json --> extra_strings. After running yarn start, the new key (layers --> layer_name_1) is added to all {local}.json files with empty translation. I update the french file to  define the translation text. Then in the themesConfig.json i add the attribute "titleMsgId" to my sublayer (see below)

`{
    "themes":{
        "items":[
            {
                "url":"###",
                "attribution":"###",
                "attributionUrl":"###",
                "subLayers": [
                     {
                         "name": "layer_name_1",
                         "title": "layer_name_1",
                         "titleMsgId":"layers.layer_name_1",
                         "geometryType":"Polygon",
                         "visibility":false,
                         "queryable":false,
                         "displayField":"art",
                         "opacity":255
                     }
                ],
`

But it doesn't work. What is the best solution (if there is one) for translating layers name ?

Thank you and wish you a good day

**Comment by manisandro** [comment]
No this is currently not implemented, resp it would probably be better to handle this via localized qgis projects than attempting to translate everything client-side.

**Comment by vsgis** [comment]
Thank you so much for your fast replay. I believe it's the same for the attribute of the getFeatureInfo request ?

I can see on this url [https://qwc2.sourcepole.ch/api/v1/featureinfo/qwc_demo?service=WMS&version=1.3.0&request=GetFeatureInfo&id=d4b98285-97d1-458e-97d5-ce6d3f961e9f&layers=edit_points,edit_lines,edit_polygons,geographic_lines,country_names,states_provinces,countries&query_layers=edit_points,edit_lines,edit_polygons,geographic_lines,country_names,states_provinces,countries&srs=EPSG:3857&crs=EPSG:3857&info_format=text%2Fxml&with_geometry=true&with_maptip=false&height=101&width=101&feature_count=20&x=51&y=51&i=51&j=51&bbox=1438679.1666666667,6199760.416666666,1492125.0000000002,6253206.25&FI_LINE_TOLERANCE=8&FI_POINT_TOLERANCE=16&FI_POLYGON_TOLERANCE=4&region_feature_count=100](url) that the result do not return all the attributes in an Attribute tag but in a HTMLContent tag. Do you know how to do that qgis server return a HTMLContent for the GetFeatureInfo request ?

Thank you

**Comment by manisandro** [comment]
>  I believe it's the same for the attribute of the getFeatureInfo request?

Yes, if you mean the attribute aliases.

> Do you know how to do that qgis server return a HTMLContent for the GetFeatureInfo request ?

There the qwc-feature-info-service is used, which also allows specifying custom featureinfo display templates.
