### ISSUE TITLE
How do I center to extent defined in qgs file

### ISSUE THREAD

**Issue by ndethi** [qgis/qwc2-demo-app#382]
How do i make ` themesConfig.json` pick the extent defined in the qgs file and have it center the extent instead of centering the entire map, which leaves the `extent` a drift to the right of the viewport?

Tried editing the `config.json` file to no avail? Alternatively where would I pass `$st` parameter on default load of page so it loads the `search result` by default on visiting the client?

**Comment by manisandro** [comment]
The `themesConfig.js` script (or the counterpart in the qwc-config-generator) will read the extent specified in the QGIS project properties if one is set:

![image](https://user-images.githubusercontent.com/1298852/197200113-7402339c-046a-4799-9131-2f43af813bd0.png)

So you can specify your desired extent there.
