### ISSUE TITLE
Wrong layer order in print with external theme

### ISSUE THREAD

**Issue by vvmruder** [qgis/qwc2-demo-app#385]
I do have a strange situation when layers of an external theme are printed with QWC2 (version dd21d2293e05b4e8815f8758c6edbbfcc69e0e70).

All Layers are in correct order in the layer tree. Even when theme and external theme are combined everything works as expected:
[See the instance](https://maps-dev.thalwil.ch/?l=wms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ge_txt%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ug_txt%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23absperrorgan_on_txt%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23rohrleitungsteil%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23muffen%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23station%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23spezialbauwerk%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23siphon%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23hausanschluss%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23absperrorgan_on%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ge%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ug%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23kabel%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23schutzrohr%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_off!%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23absperrorgan_off!%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ug_eigentuemer!%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ge_eigentuemer!%2Chaltestellen%2Cpoi_punkt%2Coeffentliches-wc%2Cparkzonen%2Cbrunnen%2Cparkfeld%2Cparkfelder%2Clfp1!%2Clfp2!%2Clfp3!%2Clfp3_txt!%2Chfp3!%2Chfp3_txt!%2Cgrundstueckpos!%2CGrenzpunkt!%2Choheitsgrenzpunkt!%2Cprojgrundstueckpos!%2Cliegenschaft_projektiert%2Cliegenschaft%2Cv_eo_objektnummerpos!%2Cv_eo_punktelement%2Cv_eo_objektnamepos%2Cv_eo_linienelement_gmaf%2Cv_eo_linienelement_bahn%2Cv_eo_linienelement_alle%2Cv_projgebaeudenummerpos%2Cv_bo_objektnamepos%2Cv_boflaechesymbol%2Cv_gebaeudenummerpos!%2Cv_gebauedenamepos%2Cv_hausnummerpos%2Cgebaeudeeingang%2Cboflaeche_solid%2Cboflaeche%2Cproj_boflaeche%2Cgebaeude%2Ceinzelobjekt%2Cv_eo_flaechenelement_gmaf%2Cboflaeche_dashed%2Cv_lokalisationsnamepos_s%2Cv_lokalisationsnamepos_n%2Cgmdeflaeche&bl=pixelkarte&t=th_ortsplan&c=2685343%2C1238203&s=250)

I fiddled around a little but was not able to find out what goes wrong. So I hope to find help here.

The [image](https://maps-dev.thalwil.ch/ows/th_ortsplan?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=gmdeflaeche%2Cv_lokalisationsnamepos_n%2Cv_lokalisationsnamepos_s%2Cboflaeche_dashed%2Cv_eo_flaechenelement_gmaf%2Ceinzelobjekt%2Cgebaeude%2Cproj_boflaeche%2Cboflaeche%2Cboflaeche_solid%2Cgebaeudeeingang%2Cv_hausnummerpos%2Cv_gebauedenamepos%2Cv_boflaechesymbol%2Cv_bo_objektnamepos%2Cv_projgebaeudenummerpos%2Cv_eo_linienelement_alle%2Cv_eo_linienelement_bahn%2Cv_eo_linienelement_gmaf%2Cv_eo_objektnamepos%2Cv_eo_punktelement%2Cliegenschaft%2Cliegenschaft_projektiert%2Cparkfelder%2Cparkfeld%2Cbrunnen%2Cparkzonen%2Coeffentliches-wc%2Cpoi_punkt%2Chaltestellen&STYLES=%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255&__t=1662013966861&WIDTH=1138&HEIGHT=943&BBOX=2684908.594491864%2C1237931.1674867617%2C2685059.1424085307%2C1238055.9185284283) of the base theme in this example rendered by QGIS Server looks good in terms of layer arrangement. Also the [image](https://maps-dev.thalwil.ch/ows/th_gas?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=schutzrohr%2Ckabel%2Cleitung_on_ug%2Cleitung_on_ge%2Cabsperrorgan_on%2Chausanschluss%2Csiphon%2Cspezialbauwerk%2Cstation%2Cmuffen%2Crohrleitungsteil%2Cabsperrorgan_on_txt%2Cleitung_on_ug_txt%2Cleitung_on_ge_txt&STYLES=%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255&__t=1662013974131&WIDTH=1138&HEIGHT=943&BBOX=2684908.594491864%2C1237931.1674867617%2C2685059.1424085307%2C1238055.9185284283) of the external theme.

The resulting image of combined themes looks good as well:
![image](https://user-images.githubusercontent.com/3714179/193238039-f645abc3-760a-4b27-b894-c7813dd9d196.png)

But using the print of these I get a mixed arrangement of the layers from external theme:
  
![image](https://user-images.githubusercontent.com/3714179/193238408-eea0170c-d419-4246-9d73-6772fa4f1963.png)

To reproduce:

```
curl 'https://maps-dev.thalwil.ch/ows/th_ortsplan?' \
  -H 'authority: maps-dev.thalwil.ch' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,de;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'origin: https://maps-dev.thalwil.ch' \
  -H 'pragma: no-cache' \
  -H $'referer: https://maps-dev.thalwil.ch/?l=wms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ge_txt%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ug_txt%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23absperrorgan_on_txt%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23rohrleitungsteil%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23muffen%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23station%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23spezialbauwerk%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23siphon%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23hausanschluss%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23absperrorgan_on%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ge%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ug%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23kabel%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23schutzrohr%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_off\u0021%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23absperrorgan_off\u0021%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ug_eigentuemer\u0021%2Cwms%3Ahttps%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas%23leitung_on_ge_eigentuemer\u0021%2Chaltestellen%2Cpoi_punkt%2Coeffentliches-wc%2Cparkzonen%2Cbrunnen%2Cparkfeld%2Cparkfelder%2Clfp1\u0021%2Clfp2\u0021%2Clfp3\u0021%2Clfp3_txt\u0021%2Chfp3\u0021%2Chfp3_txt\u0021%2Cgrundstueckpos\u0021%2CGrenzpunkt\u0021%2Choheitsgrenzpunkt\u0021%2Cprojgrundstueckpos\u0021%2Cliegenschaft_projektiert%2Cliegenschaft%2Cv_eo_objektnummerpos\u0021%2Cv_eo_punktelement%2Cv_eo_objektnamepos%2Cv_eo_linienelement_gmaf%2Cv_eo_linienelement_bahn%2Cv_eo_linienelement_alle%2Cv_projgebaeudenummerpos%2Cv_bo_objektnamepos%2Cv_boflaechesymbol%2Cv_gebaeudenummerpos\u0021%2Cv_gebauedenamepos%2Cv_hausnummerpos%2Cgebaeudeeingang%2Cboflaeche_solid%2Cboflaeche%2Cproj_boflaeche%2Cgebaeude%2Ceinzelobjekt%2Cv_eo_flaechenelement_gmaf%2Cboflaeche_dashed%2Cv_lokalisationsnamepos_s%2Cv_lokalisationsnamepos_n%2Cgmdeflaeche&bl=pixelkarte&t=th_ortsplan&c=2684953%2C1237985&s=750' \
  -H 'sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' \
  --data-raw 'TEMPLATE=A3+Querformat&map0%3Ascale=250&DPI=300&map0%3Arotation=0&TITEL=&csrf_token=&map0%3Aextent=2684901.785121467%2C1237952.955775131%2C2685004.285121467%2C1238017.955775131&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&TRANSPARENT=true&SRS=EPSG%3A2056&LAYERS=print_pixelkarte%2Cgmdeflaeche%2Cv_lokalisationsnamepos_n%2Cv_lokalisationsnamepos_s%2Cboflaeche_dashed%2Cv_eo_flaechenelement_gmaf%2Ceinzelobjekt%2Cgebaeude%2Cproj_boflaeche%2Cboflaeche%2Cboflaeche_solid%2Cgebaeudeeingang%2Cv_hausnummerpos%2Cv_gebauedenamepos%2Cv_boflaechesymbol%2Cv_bo_objektnamepos%2Cv_projgebaeudenummerpos%2Cv_eo_linienelement_alle%2Cv_eo_linienelement_bahn%2Cv_eo_linienelement_gmaf%2Cv_eo_objektnamepos%2Cv_eo_punktelement%2Cliegenschaft%2Cliegenschaft_projektiert%2Cparkfelder%2Cparkfeld%2Cbrunnen%2Cparkzonen%2Coeffentliches-wc%2Cpoi_punkt%2Chaltestellen%2CEXTERNAL_WMS%3AN%2CEXTERNAL_WMS%3AM%2CEXTERNAL_WMS%3AL%2CEXTERNAL_WMS%3AK%2CEXTERNAL_WMS%3AJ%2CEXTERNAL_WMS%3AI%2CEXTERNAL_WMS%3AH%2CEXTERNAL_WMS%3AG%2CEXTERNAL_WMS%3AF%2CEXTERNAL_WMS%3AE%2CEXTERNAL_WMS%3AD%2CEXTERNAL_WMS%3AC%2CEXTERNAL_WMS%3AB%2CEXTERNAL_WMS%3AA&OPACITIES=255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255%2C255&COLORS=%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C&A%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&A%3Alayers=schutzrohr&A%3Aformat=image%2Fpng&A%3Acrs=EPSG%3A2056&A%3Astyles=&A%3AdpiMode=7&A%3AcontextualWMSLegend=0&B%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&B%3Alayers=kabel&B%3Aformat=image%2Fpng&B%3Acrs=EPSG%3A2056&B%3Astyles=&B%3AdpiMode=7&B%3AcontextualWMSLegend=0&C%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&C%3Alayers=leitung_on_ug&C%3Aformat=image%2Fpng&C%3Acrs=EPSG%3A2056&C%3Astyles=&C%3AdpiMode=7&C%3AcontextualWMSLegend=0&D%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&D%3Alayers=leitung_on_ge&D%3Aformat=image%2Fpng&D%3Acrs=EPSG%3A2056&D%3Astyles=&D%3AdpiMode=7&D%3AcontextualWMSLegend=0&E%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&E%3Alayers=absperrorgan_on&E%3Aformat=image%2Fpng&E%3Acrs=EPSG%3A2056&E%3Astyles=&E%3AdpiMode=7&E%3AcontextualWMSLegend=0&F%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&F%3Alayers=hausanschluss&F%3Aformat=image%2Fpng&F%3Acrs=EPSG%3A2056&F%3Astyles=&F%3AdpiMode=7&F%3AcontextualWMSLegend=0&G%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&G%3Alayers=siphon&G%3Aformat=image%2Fpng&G%3Acrs=EPSG%3A2056&G%3Astyles=&G%3AdpiMode=7&G%3AcontextualWMSLegend=0&H%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&H%3Alayers=spezialbauwerk&H%3Aformat=image%2Fpng&H%3Acrs=EPSG%3A2056&H%3Astyles=&H%3AdpiMode=7&H%3AcontextualWMSLegend=0&I%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&I%3Alayers=station&I%3Aformat=image%2Fpng&I%3Acrs=EPSG%3A2056&I%3Astyles=&I%3AdpiMode=7&I%3AcontextualWMSLegend=0&J%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&J%3Alayers=muffen&J%3Aformat=image%2Fpng&J%3Acrs=EPSG%3A2056&J%3Astyles=&J%3AdpiMode=7&J%3AcontextualWMSLegend=0&K%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&K%3Alayers=rohrleitungsteil&K%3Aformat=image%2Fpng&K%3Acrs=EPSG%3A2056&K%3Astyles=&K%3AdpiMode=7&K%3AcontextualWMSLegend=0&L%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&L%3Alayers=absperrorgan_on_txt&L%3Aformat=image%2Fpng&L%3Acrs=EPSG%3A2056&L%3Astyles=&L%3AdpiMode=7&L%3AcontextualWMSLegend=0&M%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&M%3Alayers=leitung_on_ug_txt&M%3Aformat=image%2Fpng&M%3Acrs=EPSG%3A2056&M%3Astyles=&M%3AdpiMode=7&M%3AcontextualWMSLegend=0&N%3Aurl=https%3A%2F%2Fmaps-dev.thalwil.ch%2Fows%2Fth_gas&N%3Alayers=leitung_on_ge_txt&N%3Aformat=image%2Fpng&N%3Acrs=EPSG%3A2056&N%3Astyles=&N%3AdpiMode=7&N%3AcontextualWMSLegend=0&CONTENT_DISPOSITION=attachment&map0%3ALAYERS=print_pixelkarte%2Cgmdeflaeche%2Cv_lokalisationsnamepos_n%2Cv_lokalisationsnamepos_s%2Cboflaeche_dashed%2Cv_eo_flaechenelement_gmaf%2Ceinzelobjekt%2Cgebaeude%2Cproj_boflaeche%2Cboflaeche%2Cboflaeche_solid%2Cgebaeudeeingang%2Cv_hausnummerpos%2Cv_gebauedenamepos%2Cv_boflaechesymbol%2Cv_bo_objektnamepos%2Cv_projgebaeudenummerpos%2Cv_eo_linienelement_alle%2Cv_eo_linienelement_bahn%2Cv_eo_linienelement_gmaf%2Cv_eo_objektnamepos%2Cv_eo_punktelement%2Cliegenschaft%2Cliegenschaft_projektiert%2Cparkfelder%2Cparkfeld%2Cbrunnen%2Cparkzonen%2Coeffentliches-wc%2Cpoi_punkt%2Chaltestellen%2CEXTERNAL_WMS%3AN%2CEXTERNAL_WMS%3AM%2CEXTERNAL_WMS%3AL%2CEXTERNAL_WMS%3AK%2CEXTERNAL_WMS%3AJ%2CEXTERNAL_WMS%3AI%2CEXTERNAL_WMS%3AH%2CEXTERNAL_WMS%3AG%2CEXTERNAL_WMS%3AF%2CEXTERNAL_WMS%3AE%2CEXTERNAL_WMS%3AD%2CEXTERNAL_WMS%3AC%2CEXTERNAL_WMS%3AB%2CEXTERNAL_WMS%3AA&map0%3AHIGHLIGHT_GEOM=&map0%3AHIGHLIGHT_SYMBOL=&map0%3AHIGHLIGHT_LABELSTRING=&map0%3AHIGHLIGHT_LABELCOLOR=&map0%3AHIGHLIGHT_LABELBUFFERCOLOR=&map0%3AHIGHLIGHT_LABELBUFFERSIZE=&map0%3AHIGHLIGHT_LABELSIZE=' \
  --compressed
```

The lables and the lines are not in correct order.

Is this something already solved? Or is it a new issue? I was looking into the list of known issues but no one seems to match.

Cheers & THX for helping out
C

**Comment by manisandro** [comment]
From your request, the order passed to the QGIS Server is:

    LAYERS=print_pixelkarte,gmdeflaeche,v_lokalisationsnamepos_n,v_lokalisationsnamepos_s,boflaeche_dashed,v_eo_flaechenelement_gmaf,einzelobjekt,gebaeude,proj_boflaeche,boflaeche,boflaeche_solid,gebaeudeeingang,v_hausnummerpos,v_gebauedenamepos,v_boflaechesymbol,v_bo_objektnamepos,v_projgebaeudenummerpos,v_eo_linienelement_alle,v_eo_linienelement_bahn,v_eo_linienelement_gmaf,v_eo_objektnamepos,v_eo_punktelement,liegenschaft,liegenschaft_projektiert,parkfelder,parkfeld,brunnen,parkzonen,oeffentliches-wc,poi_punkt,haltestellen

Is this correct? What is the order in the LayerTree?

**Comment by manisandro** [comment]
Might also be fixed by https://github.com/qgis/qwc2/commit/75e7a5a7670f30cbc70a7c658fa22386bbe90792 if the layers are in a background layer group.

**Comment by manisandro** [comment]
Closing, please reopen if still an issue.
