### ISSUE TITLE
get full direct link with omitUrlParameterUpdates setting

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#386]
I can't get full link for sharing with omitUrlParameterUpdates setting. Is it possible to generate full link with L url param?

Now I get link with "hc" and "c" parameters eg. http://localhost:8082/?hc=1&c=23687249%2C6324067
I think that it will send permalink service also?

**Comment by lassitanskanen** [comment]
Correct, but url with all params should be generated when sharing link?

**Comment by manisandro** [comment]
Ah now I understand what you mean - actually no, the share component will read location.href, which won't have any URL parameters if you set `omitUrlParameterUpdates` to `true`. So the share component does not make much sense if that setting is active.
