### ISSUE TITLE
Using QGIS server in docker stack for serving ogc services next to the qwc2

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#387]
Hello there,

We are using the docker stack of the qwc services. Beside the qwc2 we have many wms services which are used in other applications. For this we are using an extra installed qgis server.

Now I am looking for the posibility to use the qgis server within the qwc2 doker stack for serving this ogc services, but they should not be shown within the qwc2 map viewer.
My attempt is, to configure all of the content which should be part of the map viewer manually within the tenantConfig.json. In addition I am using the ability of the config generator service to scan a directory with qgis project files and generate the configs based on that automatically. This scanned projects should be the ones, which are accessible as ogc service but should not be part of the qwc2 instance.
To implement that, I think, I have to manage somehow, that only the ogcConfig.json is generated including the scanned files but not the mapViewerConfig.json and featureInfoConfig.json. Is there a way to realize this? Or any other Idea of how to achieve this?
Thanks!

Greetings
Daniel

**Comment by danceb** [comment]
Oh, I didn't know about this parameter. That's what I was looking for!
To create a new config-generator setting the sets `wmsOnly` to true for all of the scanned projects would make it easier of course, but the effort to configure this themes in the tenantConfig.json as well is minimal, so I could do this this way.

Because much of the parameters there are only needed for using in QWC2 it is enough to configure something like
```
        {
          "url": "/ows/qwc_demo",
          "format": "image/png",
          "wmsOnly": true
        }
```

Now using the `wmsOnly` parameter still results in generating a map thumbnail for the QWC2 (which is not needed).
So for preventing this, [Line 501 within the map_viewer_config.py](https://github.com/qwc-services/qwc-config-generator/blob/6d2805e86227e53dd8a42d7ab575d4fb8cef6073/config_generator/map_viewer_config.py#L501) can by changed from
```
if 'thumbnail' in cfg_item:
``` 
to 
```
if 'thumbnail' in cfg_item and not theme_item['wmsOnly']:
```
right? Maybe you can add this? I would not create a pull request for this single change right now, if it's ok.

Thanks!

**Comment by manisandro** [comment]
Done in https://github.com/qwc-services/qwc-config-generator/commit/34b7db269a8fd18d89ef944183cc1e401e3829e0

**Comment by danceb** [comment]
Perfect, thanks!
