### ISSUE TITLE
Possibility for set a custom legend icon in layer tree

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#389]
In Relation to this: https://github.com/qgis/qwc2/pull/217

> Currently not, but should be pretty easy to implement here: https://github.com/qwc-services/qwc-legend-service/blob/master/legend_service.py#L278

So I not feel myself as a great developer at the moment, so sorry for my potential lack of knowledge.

My attempt for this would be to let the function check if there are default images within the directory of `legend_images_path` and take them if there are any.
For this I added/modified these lines here: https://github.com/qwc-services/qwc-legend-service/blob/master/legend_service.py#L310

```
if layer not in legend_images:
    # layer has no custom legend image, so check for default image in legend_images_path
    if type == 'thumbnail' and os.path.isfile(os.path.join(self.legend_images_path, 'thumbnail_default.png')):
        image_path = os.path.join(self.legend_images_path, 'thumbnail_default.png')
    elif type == 'tooltip' and os.path.isfile(os.path.join(self.legend_images_path, 'tooltip_default.png')):
        image_path = os.path.join(self.legend_images_path, 'tooltip_default.png')
    if os.path.isfile(image_path):
        self.logger.debug(
            "Loading legend image '%s' for layer '%s'" %
            (image_path, layer)
        )
        # load image file
        with open(image_path, 'rb') as f:
            image_data = f.read()
    else:
        self.logger.warning(
            "Could not find legend image '%s' for layer '%s'" %
            (image_path, layer)
        )
else:
    return None
```

What I don't like is the code duplicate with the following try-statement, so maybe there is another way.

At the moment I have no idea to test this by myself in my qwc2 stack, so I look up for your opinion on that.

As always, thanks a lot!

**Comment by danceb** [comment]
Meanwhile I had different attempts to get to the expected result, but unfortunately not of them went well. Adding the default image names to the filenames and using only the existing logic would not work, because I have to specify default images for each service. My approach is, that the function should load a default image out of the `legend_images_path` directory and only if it's nothing there it would look for specific files in sub directories for each service.

Here are two of my attempts, maybe I can get a hint, what I am missing. In each case it gets the legend image from the qgis server and ignores the default images placed in the legend image path directory. The attempts using the `type` parameter of the function for trying to find the corresponding default image.

First attempt, instead of https://github.com/qwc-services/qwc-legend-service/blob/master/legend_service.py#L299:

```
try:
    data = open(os.path.join(self.legend_images_path, type + '.png'), 'rb').read()
    if data:
        return data
except:
    for filename in filenames:
        try:
            data = open(os.path.join(self.legend_images_path, service_name, filename), 'rb').read()
            if data or allowempty:
                return data
        except:
            pass
```

second try, instead of https://github.com/qwc-services/qwc-legend-service/blob/master/legend_service.py#L310:

```
if layer not in legend_images:
    try:
        data = open(os.path.join(self.legend_images_path, type + '.png'), 'rb').read()
        if data:
            return data
    except:
        # layer has no custom legend image
        return None
```

Thanks again!

**Comment by manisandro** [comment]
Does https://github.com/qwc-services/qwc-legend-service/pull/14 accomplish what you are looking for?

**Comment by danceb** [comment]
I've got it to work in one of my qwc2 stacks. I've just changed the order the paths are added to the list. With this, it will look for images within the service sub directories first and afterwards for the default images. `allowempty` is only needed for the service layers not for the default images, isn't it?

```
        if type == "thumbnail":
            filenames.append(os.path.join(service_name, layer + "_thumbnail.png"))
        elif type == "tooltip":
            filenames.append(os.path.join(service_name, layer + "_tooltip.png"))
            allowempty = True
        filenames.append(os.path.join(service_name, layer + '.png'))

        if type == "thumbnail":
            filenames.append("default_thumbnail.png")
        elif type == "tooltip":
            filenames.append("default_tooltip.png")
        filenames.append('default.png')

        for filename in filenames:
            try:
                data = open(os.path.join(self.legend_images_path, filename), 'rb').read()
                if data or allowempty:
                    return data
            except:
                pass
```

**Comment by manisandro** [comment]
I've merged the PR with the changes as you suggested above.
