### ISSUE TITLE
Allow disabling of automatic map following when geolocation is active

### ISSUE THREAD

**Issue by mwa** [qgis/qwc2-demo-app#39]
When enabling the location button, the map keeps following the current location and pans back to it after panning manually. Also a new map image must be fetched after every location change.

There should be an option to disable the automatic map following while only updating the current location. This would allow independent manual panning and need less frequent map updates.

**Comment by manisandro** [comment]
Locate is now disabled by default and enabled with a successive click on the locate button:
https://github.com/qgis/qwc2/commit/94eba556b935d843136bdc102cc742e62fe31818
