### ISSUE TITLE
Print  problem with CORS

### ISSUE THREAD

**Issue by theoldman73** [qgis/qwc2-demo-app#394]
Access to XMLHttpRequest at 'http://qwc2.sourcepole.ch/ows/qwc_demo?' from origin 'http://192.168.56.101' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by manisandro** [comment]
See https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#cross-origin-requests
