### ISSUE TITLE
default color scheme is not loaded

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#397]
I could not get a custom color scheme loade by default. I have set up a new color scheme within the `colorschemes.css` file and set the parameter `defaultColorScheme` to the name of the parameter. But the map viewer is always loaded with the default color scheme from the qwc2 app. 
If I am defining the scheme with the `style` url parameter it is loaded correctly, so it is found within the `colorschemes.css` file. But I could not load it by default. Also tried it with the examples "highcontrast" and "dark", it's the same here.
Does this work in your case?

**Comment by manisandro** [comment]
The setting in browser-local-storage is likely overriding the setting, see the last note in [1]. (Not sure if the browser-local-storage thing is a good idea TBH, maybe I'll change it...)

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#color-schemes

**Comment by danceb** [comment]
I think the local storage is a good idea for using the color schemes with the settings plugin. 
But actually I have not activated it because I want to use just the scheme named in `defaultColorScheme` without letting the user to change it. As I have read the documentation, the default scheme is used not matter if the settings plugin is activated or not.
But also without the settings plugin the default scheme is saved within the local storage of the browser. So where is this coming from?

**Comment by manisandro** [comment]
Make sense to only store it in local storage if the settings plugin is enabled, should be addressed in https://github.com/qgis/qwc2/commit/d5aafae8cd35965b2bedab0bd872946e4a23edd6

**Comment by danceb** [comment]
Thanks!
