### ISSUE TITLE
FeatureInfo window should be resizeable

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#4]
Often the content of a feature info responsive is wider or taller than what can be displayed in the standard feature info result window.

Therefore it would be good being able to resize this window.

According to Sandro, this is not trivial. The upstream implementation of the MapStore2 component does not support resizing and the window implementation is quite complex. Either it could be fixed upstream or QWC2 would have its own window object.

**Comment by manisandro** [comment]
Implemented in 422bee1.
