### ISSUE TITLE
Trouble building qwc2-demo-app using "yarn start

### ISSUE THREAD

**Issue by meierrom** [qgis/qwc2-demo-app#405]
Hi folks,

I'm trying to build the current version of qwc2-demo-app using "yarn start".

I'm getting a number of warnings that seem to affect the correct execution in the browser correctly, e.g.

WARNING in ./qwc2/actions/search.js 39:16-23
export 'default' (imported as 'uuid') was not found in 'uuid' (possible exports: NIL, parse, stringify, v1, v3, v4, v5, validate, version)

WARNING in ./node_modules/uuid/dist/esm-browser/v1.js 92:16-31
Can't import the named export 'unsafeStringify' (imported as 'unsafeStringify') from default-exporting module (only default export is available)

How can I fix this?

Kind regards,
Roman

**Comment by manisandro** [comment]
I've never seen this before, have you tried deleting node_modules and running `yarn install`?

**Comment by meierrom** [comment]
Hi,

Thanks Sandro!

I tried that before, but to no avail.

I think this issue is related to node and its uuid package, which appears to be too recent.
Currently I have v9.0.0 installed.

What's the suggested version?

Kind regards,
Roman

**Comment by manisandro** [comment]
So far I've seen no indications of incompatibilities, personally I'm using nodejs-18.12.1 / nodejs-npm-8.19.2

**Comment by meierrom** [comment]
Hi Sandro,

What version of uuid are you using?

You can check that e.g. with "npm list|grep uuid".

Kind regards,
Roman

**Comment by lperozzi** [comment]
Hi all,

I have exactly the same problem as @meierrom. However, when I run `npm list | grep uuid` (in Windows 10 `npm list  | findstr uuid`) I also don't get any output.  
@meierrom did you find a solution meanwhile?

**Comment by meierrom** [comment]
Hi Iperozzi,

Yeah, I did find a solution. Sorry for not reporting this back.

It turned out, that uuid v9.0.0 is too new. The following fixed it for me:

npm install uuid@3.4.0

Kind regards,
Roman

**Comment by manisandro** [comment]
As nothing in qwc2-demo-app/qwc2 requires uuid > 3.4.0, I'd say this is due to a third-party component or custom setup.

**Comment by manisandro** [comment]
FWIW, QWC2 dependencies have been updated and now UUID 8.3.2 is used. See [1] for the changes which were needed to get the build working.

[1] https://github.com/qgis/qwc2-demo-app/blob/master/UpgradeNotes.md#update-to-qwc2-submodule-revision-7a474e3-23012023
