### ISSUE TITLE
themesConfig.json WMS url

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#406]
I'm using the 'qwc2-demo-app' yarn install. I've changed the first url in 'themesConfig.json' then restart qwc2 with 'yarn start', There is now an error:

ERROR: Could not read GetProjectSettings
error Command failed with exit code 1.

[yarn-start.zip](https://github.com/qgis/qwc2-demo-app/files/10277248/yarn-start.zip)

The url I've added is working in QGIS. I suspect that there are dependency elements in other json file somewhere.

**Comment by manisandro** [comment]
`https://ogc.apps.midgard.airbusds-cint.com/apgb/wms` does not appear to be served by QGIS Server?

**Comment by shapley** [comment]
Ahh...It has to be 'QGIS-Server' WMS! Thanks Manisandro

**Comment by manisandro** [comment]
Yes, QWC2 uses proprietary QGIS Server features.
