### ISSUE TITLE
Style problem in QtDesigner component

### ISSUE THREAD

**Issue by smaspons** [qgis/qwc2-demo-app#409]
Hi @manisandro !

I've encountered a bug where the input elements that are disabled/read-only (lineedits, qdateedits, etc.) don't have the proper style applied.

![imagen](https://user-images.githubusercontent.com/78911250/211508485-f540aed9-490b-48bd-ba68-c1719c4477f9.png)

As you can see, the style `input:read-only, textarea:read-only` is ignored because it uses the `input:not([type="checkbox"]):not([type="radio"]):not([type="range"])` style.

I think there is an easy fix, but I don't know enough about CSS, so I leave it up to you...
Thanks!

**Comment by manisandro** [comment]
Thanks for the report, should be fixed by https://github.com/qgis/qwc2/commit/a1040afd0137d914d446d1f3c81f27f53c5b4d08
