### ISSUE TITLE
Layer's display issue

### ISSUE THREAD

**Issue by lperozzi** [qgis/qwc2-demo-app#410]
I'm making some tests with qwc2 using a docker images for the QGIS server.

I added a theme with some test data as described [here](https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#theme-configuration-qgis-projects-and-the-themesconfigjson-file) that has successfully added in the theme list as shown here.

<img src="https://user-images.githubusercontent.com/6198369/212084267-faa67fe6-35a0-44b2-907d-96f11406fa05.png" width="75%" height="75%">

However, in the theme, the selected layer doesn't show up.

<img src="https://user-images.githubusercontent.com/6198369/212085549-b24639cc-62e2-42b9-80c7-9a5a2c6ea9f6.png" width="75%" height="75%">

By importing the layer through WMS (and using exactly the same address used in the `themesConfig.json`), the layers show up. 

<img src="https://user-images.githubusercontent.com/6198369/212086956-80c62f8b-08e3-4b62-8f03-f4fbc2b694d6.png" width="75%" height="75%">

So, I do not think it is a QGIS-server problem rather something wrong in the themesConfig.json which I'm not able to detect. Has someone experienced something similar?

**Comment by manisandro** [comment]
As a first step I'd suggest inspecting the GetMap request via the browser network inspector (F12 -> Network tab).

**Comment by lperozzi** [comment]
Do you mean something like this?

<img src="https://user-images.githubusercontent.com/6198369/212101166-a7d12b2a-7ee5-49b8-b156-6e9608df0566.png" width=75% height=75%>

**Comment by manisandro** [comment]
Yes

**Comment by lperozzi** [comment]
For what I can understand, all seems normal in the GetMap request. I guess the problem is when the WMS address is converted from `themeConfig.json`  to `Config.json`, but I did not find anything strange

**Comment by manisandro** [comment]
If the URL looks correct (you might want to post it here to double check) then you'll need to investigate further on QGIS Server side, perhaps also looking at the QGIS Server logs.

**Comment by lperozzi** [comment]
Hi @manisandro, I've investigated further but without success. The WMS URL is `http://localhost:8380/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=/etc/qgisserver/test_limites.qgs` . The QGIS server is from [this](https://github.com/camptocamp/docker-qgis-server) docker image. Many thanks for your time

**Comment by manisandro** [comment]
Please post the full GetMap URL

**Comment by lperozzi** [comment]
You mean this:
`http://localhost:8380/?MAP=/etc/qgisserver/test_limites.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2463903,1069997,2854871,1301696&SRS=EPSG:2056&WIDTH=665&HEIGHT=551&LAYERS=comuni&FORMAT=image/jpeg

**Comment by lperozzi** [comment]
Hi @manisandro:

- the GetMap URL:
`http://localhost:8380/?SERVICE=WMS&REQUEST=GetCapabilities&map=/etc/qgisserver/comuni.qgs`

-  the `comuni.qgs` (https://we.tl/t-wmkD5CVCAT)
-  and `themeConfig.json`. (https://we.tl/t-2JcXqaw3Ia)

Many thanks for your time

**Comment by lperozzi** [comment]
the url should be:

http://localhost:8380/?SERVICE=WMS&REQUEST=GetMap&map=/etc/qgisserver/comuni.qgs
instead of
http://localhost:8380/?SERVICE=WMS&REQUEST=GetCapabilities&map=/etc/qgisserver/comuni.qgs
