### ISSUE TITLE
Search via fulltext-search-service does not work anymore with new searchprovider configuration

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#413]
I have updated the qwc2 app to the state with the changes on the searchprovider files. But for the search we are using the fulltext-search-service, so this shouldn't be affected with that, right?

But somehow the search does not work anymore with the updated qwc2 app within the stack. The search-api itself works correct, but there is no request on it while typing words into the search field.

So how is the search-service connected to to searchprovider-config and how is it affected by the changes? Any hints are welcome.

Thanks!

**Comment by manisandro** [comment]
So you see no request to `http://localhost:8088/api/v2/search/` or similar when typing in the search field? Can you share your themes.json?

**Comment by danceb** [comment]
exactly, there is no request to the search url. Accessing the search service via the url directly works. Within the qwc-docker-stack I have no themes.json? What else can I share? the tenantConfig.json, or the generated searchConfig.json or mapViewerConfig.json?

**Comment by danceb** [comment]
It hasn't anything to do with the search provider updates. I get it to work in a local environment with the recent qwc2 app, but it does not work in the prod system yet. So the error has to be somewhere in the config. Now I just have to find it ;-)
