### ISSUE TITLE
Feature Info not displaying

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#415]
Hi,
When I click on a feature nothing is displayed. Do I need to activate something I've somehow missed?

![image](https://user-images.githubusercontent.com/7022885/214275422-fd020508-5eee-4b99-870f-c0acf86d06e1.png)

**Comment by manisandro** [comment]
Please check the browser console, possibly it is a CORS issue.

**Comment by shapley** [comment]
Hi... many thanks manisandro,

Installed the Chrome extension 'Moesif Origin & CORS Changer' then activated it on the 'extensions' toolbar.  That did the trick!  Please close call

![image](https://user-images.githubusercontent.com/7022885/214287929-7716155d-87e9-4cfe-889f-b49cf7968c29.png)
