### ISSUE TITLE
Switch themes from URL parameters

### ISSUE THREAD

**Issue by eruizNexus** [qgis/qwc2-demo-app#418]
Hi,

I would like to know if it's posible to switch themes just from changing the url of the project. For example, imagine I have two maps in my QGIS Server, one in the url _https://myserver/0008426511fef6db18638b8f357db7ba_ and other in _https://myserver/29ac6bab2dc9212eb0fd6baccceae538_. I'm working in my local at the moment and I can swtich themes from the graphic interface but I would like to know if you can do it from the url like this (hiding all the other url params):

http://localhost:8081/?t=0008426511fef6db18638b8f357db7ba
http://localhost:8081/?t=29ac6bab2dc9212eb0fd6baccceae538

Thanks!

**Comment by manisandro** [comment]
Yes this should work, the syntax is `<qwc_url>?t=<theme_id>` where `theme_id` is an id of the theme as specified in the `themes.json`.

**Comment by eruizNexus** [comment]
Can I do that but with the id I get from server? In my case with the id 0008426511fef6db18638b8f357db7ba or 29ac6bab2dc9212eb0fd6baccceae538 and not with the autogenerated one?

**Comment by manisandro** [comment]
By default, the autogenerated `id` should match the wms service name, i.e. typically the last portion of the wms URL. In your case, for i.e.

    https://myserver/0008426511fef6db18638b8f357db7ba

the autogenerated `id` should be `0008426511fef6db18638b8f357db7ba`.

**Comment by eruizNexus** [comment]
In my case, in the _themesConfig.json_ file I have the following:

```
{
"themes":{
    "items":[
        {
            "title": "Title",
            "url": "https://myserver/0008426511fef6db18638b8f357db7ba/",
            "default": true
        },
        ...
```

But the _themes.json_ looks like this:

```
{
"themes": {
  "title": "root",
  "subdirs": [],
  "items": [
    {
      "url": "https://myserver/0008426511fef6db18638b8f357db7ba/",
      "id": "459bd030-a6c9-11ed-b50f-e9b59f50110b",
      "name": "Title",
      "title": "Title",
      "description": "",
      ...
```

The autogenerated  id does not match the wms service name. Am I doing something wrong? I would like to have 
`"id": "0008426511fef6db18638b8f357db7ba`

Thanks!

**Comment by manisandro** [comment]
This is because you have a trailing slash in the URL, so the portion after the last slash of the URL is empty, resulting in an empty WMS name and hence fallback to `id=uuid.v1()`.

**Comment by eruizNexus** [comment]
Sorry my fault! 😅 Thanks for the help!

**Comment by manisandro** [comment]
Welcome!
