### ISSUE TITLE
How to make snapping work?

### ISSUE THREAD

**Issue by meierrom** [qgis/qwc2-demo-app#419]
Hi folks,

There's information available on how to enable snapping. It found it here: https://github.com/qgis/qwc2-demo-app/blob/master/doc/src/qwc_configuration.md

It seems that by default snapping isn't set up despite the snapping box appearing in the map window.

I did the following changes to my setup according to the documentation. However, I can't see any changes in the behaviour of editing, redlining or measering.

This is my current configuration according in volumes/config/default/mapViewerConfig.json:

            {
              "name": "Measure",
              "cfg": {
                "showMeasureModeSwitcher": true
                "snapping": true,
                "snappingActive": true
              }
            },
            {
              "name": "Redlining",
              "cfg": {
                  "snapping": true,
                  "snappingActive": true
              }
            },
            {
              "name": "Editing",
              "cfg": {
                  "snapping": true,
                  "snappingActive": true
              }
            },
[...]
        "snapping": {
          "snaplayers": [
            {
              "name": "edit_polygons",
              "min": 100,
              "max": 1000000
            },
            {
              "name": "edit_lines",
              "min": 100,
              "max": 1000000
            },
            {
              "name": "edit_points",
              "min": 100,
              "max": 1000000
            }
          ],
          "featureCount": 500
        },

Any ideas on how to fix this?

Kind regards,
Roman

**Comment by manisandro** [comment]
Check your QGIS project and make sure that geometries are added to the feature info response

![image](https://user-images.githubusercontent.com/1298852/218080911-60c17522-57eb-44a0-80be-ed170f2c9d37.png)

and that the layer you wish to snap to are marked as identifiable:

![image](https://user-images.githubusercontent.com/1298852/218081326-5c619d72-46c5-40a7-ae42-8beb3e77706d.png)

**Comment by meierrom** [comment]
Hi!

I checked the project, which I haven't actually changed. I'm using the default file qwc-docker comes with, which is found here: volumes/qgs-resources/qwc_demo.qgs

![Screenshot_2023-02-10_12-19-56](https://user-images.githubusercontent.com/35899323/218091201-d79e470d-2dca-4f08-a584-a9f802c002ec.png)

Looks fine, right?

Kind regards,
Roman

**Comment by meierrom** [comment]
Hi again,

I must admit, that I don't really know what the snapping feature does.

I checked the demo on http://qwc2.sourcepole.ch and I couldn't figure out a difference between snapping mode being on or off.

Maybe somebody can explain?

Kind regards,
Roman

**Comment by manisandro** [comment]
I've just pushed a fix for the snapping interaction which broke with the OpenLayers 7 upgrade. Also, the snapping control is now not displayed anymore if no snap layers are configured in the current theme. Check if this solves your issues - your configuration should work AFAICS.

**Comment by meierrom** [comment]
Hi Sandro,

Thanks a lot for your fix! I tried to make it work on my end but failed so far.

Let me write down the main steps I took:

git clone --recursive https://github.com/qgis/qwc2-demo-app.git
[...]
yarn run build
[...]
I copied the build to qwc-docker/volumes/qwc2/
[...]
I changed the following config in volumes/config-in/default/tenantConfig.json:

      "name": "mapViewer",
      "generator_config": {
        "qwc2_config": {
          "qwc2_config_file": "/qwc2/config.json",
          "qwc2_index_file": "/qwc2/index.html"
        }
        
I changed the following config in qwc-docker/docker-compose.yml:

  qwc-map-viewer:
#    image: sourcepole/qwc-map-viewer-demo:v2023.01.11
    # Update config.json with:
    # curl -o volumes/config-in/config.json https://github.com/qgis/qwc2-demo-app/raw/v2023.01.11/static/config.json
    # and generate service configuration
    # With custom build added via volume:
    image: sourcepole/qwc-map-viewer-base:v2023.01.11
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/'
    # ports:
    #   - "127.0.0.1:5030:9090"
    volumes:
      - ./pg_service.conf:/srv/pg_service.conf:ro
      - ./volumes/config:/srv/qwc_service/config:ro
      # When using qwc-map-viewer-demo:
      #- ./volumes/qwc2/assets:/qwc2/assets:ro
      # When using own viewer build with qwc-map-viewer-base:
      - ./volumes/qwc2:/qwc2:ro

I updated my service configuration via qwc_admin.
[...]
I added snapping configuration to volumes/config/default/mapViewerConfig.json as mentioned in the first post.

That's about it! Just like you are mentioning in your post, the snapping control is now not displayed anymore. Snapping however still doesn't work for me. I suspect a problem in my configuration.

Any ideas, where things could have gone wrong?

Kind regards,
Roman

**Comment by manisandro** [comment]
If the snapping control is not visible, then there is no snapping configuration for the theme. Check your generated themes.json to see if indeed there is a snapping configuration for your selected theme.

**Comment by meierrom** [comment]
Hi Sandro,

My bad. I put the layer-snapping-configuration outside of the themes configuration (globally) instead of inside the theme. 

Works fine now!

Great feature! Thanks so much!

Kind regards,
Roman
