### ISSUE TITLE
Layer catalog

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#420]
Hi Everyone,

I'm not sure where the 'Layer catalog' is specified? Is it in 'themesConfig.json'? If not is it somewhere else. Documentation isn't clear.  If it's nested in 'themesConfig.json' is it in "items" or "themes"? I also saw somewhere that it was specified in '/static/assets/catalog.json' 
 
{
   "catalog" : [{ }] 
}

**Comment by manisandro** [comment]
It is in the `config.json`:

    {
        "name": "LayerCatalog",
        "cfg": {
          "catalogUrl": "http://qwc2.sourcepole.ch/assets/catalog.json"
        }
      }

**Comment by shapley** [comment]
So I guess my 'catalog.json' is stored in 'assets/catalog.json therefore:-

 {
    "name": "LayerCatalog",
    "cfg": {
      "catalogUrl": "assets/catalog.json"
    }
  }

**Comment by manisandro** [comment]
Yes should work

**Comment by shapley** [comment]
OK... thanks for your fast reply manisandro
