### ISSUE TITLE
Polygon or Feature Highlight

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#422]
Hi,

I've noticed on the first demo you can have features 'highlighted' when clicked. How and where is this feature activated?

![poly-highlight](https://user-images.githubusercontent.com/7022885/219016939-f86d6c60-01fc-4d11-8699-a223cda5e8f9.png)

**Comment by manisandro** [comment]
You need to enable the geometry in the GetFeatureInfo response:

![Uploading image.png…]()
