### ISSUE TITLE
Issue with movable windows in mobile

### ISSUE THREAD

**Issue by smaspons** [qgis/qwc2-demo-app#423]
Hello!

I don't know if it's an issue with the ResizableWindow or the QtDesignerForm, but if a window is movable, in mobile, I can't interact with any widget/button inside it, I can't even close it with the X. The only thing I can do is move it and resize it.

I'm guessing that it detects any input in any part of the window as if it was for moving the window.

Please, let me know if you can reproduce it on your end or if it might be an issue with some component I have.
Thanks!

**Comment by manisandro** [comment]
Thanks for the report, fixed in https://github.com/qgis/qwc2/commit/56775638d77b9ba228ab85659b0ae94a8d89dcc7
