### ISSUE TITLE
Layer attributes search

### ISSUE THREAD

**Issue by lperozzi** [qgis/qwc2-demo-app#425]
Hi,

is there an explicit example that shows how to setup a searchProviders for the attributes of a displayed layer? The objective of this search is to search for object based on their FID number (or other unique attributes). I've read the searchProviders documentation as well checked the `js/SearchProviders.js` and `static/assets/searchProviders.js` but without success.

Many thanks for your help

**Comment by meierrom** [comment]
Hi,

There is an example in qwc_docker, which is doing something very similar. It's the search in facet "ne_10m_admin_0_countries". It's data is stored locally in qwc_postgis.

Unfortunately, it appears to be broken currently. It's usefulness is therefore somehow limited. I was not able to make it work so far.

Kind regards,
Roman

**Comment by lperozzi** [comment]
Hi @meierrom,

Interesting. I tried to play with the example you mentioned, but without success too. I also tried to config a search within a layer in a personal theme, but again, I failed.

It would really be great to make this work, maybe some QWC admin can help us out.

Kind Regards
Lorenzo

**Comment by w0pr** [comment]
I'm almost there, see https://github.com/qgis/qwc2-demo-app/issues/451#issue-1718441605

Inside onSearch function in searchProvider.js, I will do a WMS request to the OGC service (this works already), using the FILTER parameter (this is WMS extension of QGIS server) like described here:
https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#getfeatureinfo
https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#wms-filter

But I'm stuck at navigation/zoom to feature.

**Comment by manisandro** [comment]
I believe the new QGIS Feature Search addresses this requirement: https://qwc-services.github.io/topics/Search/#configuring-the-qgis-feature-search
