### ISSUE TITLE
Printing problem with new measurement function in redlining tool

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#427]
Hi,

first of all, very nice addition that measurements can now also be displayed in the redlining function.

Unfortunately, I have a problem with printing. Printing points, polygons or circles with measurement labels works fine, but for lines the measurement labels not appear in the print. Normal labels works for lines.

I'm not sure if this is a problem in our QWC environment (qwc docker, qwc print service, etc.) or if this is a general problem.

QWC2:
![screenshot_qwc2](https://user-images.githubusercontent.com/20335953/221885541-095cb926-75e2-4d54-82ee-a1a8c3b6ec69.jpg)

PDF-Print:
![screenshot_print](https://user-images.githubusercontent.com/20335953/221885555-21c04f9f-a7e5-4915-95b4-8381e9b71c9b.jpg)

**Comment by manisandro** [comment]
This is an expected limitation I fear as `HIGHLIGHT_LABELSTRING` only accepts one label per feature whereas the linestring has one label per segment. One would need to split the linestring into single segments for printing (which I guess should be doable). The code is in VectorLayerUtils.createPrintHighlighParams.

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/a0c16dffdeba685b61090e4a9d0bdd0415b89acf
