### ISSUE TITLE
logout not shown in menu after user login

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#428]
Hello there,

I am trying to get the user login working. I added the related login entry within the menu and configured an authentication service. Accessing the login page with the menu entry works, just as the user login itself, the access_token is generated.

Nevertheless the menu entry remains as "Login" after user login and not changed to "Logout". And clicking it brings me to the login page again and don't logout the active user.

Accessing `"authServiceUrl" + "logout"` manually (`http://localhost:8080/api/v1/auth/logout` in my local test case) logs the user out as expected.

I have tested it with the db authentification service as well with the ldap service.

Any tipps or ideas where I can digg for this issue?

Thanks!
Daniel

**Comment by manisandro** [comment]
The qwc-map-viewer should replace any `Login` entries with `Logout` if a logged in user is detected, see [1]. Easiest way to debug it would be to edit the file inside the docker container and add some `print` statements as appropriate to understand what is happening.

[1] https://github.com/qwc-services/qwc-map-viewer/blob/c554381e9cd48c54dae063bfd1e5821acb640a03/qwc2_viewer.py#L228

**Comment by danceb** [comment]
Ok, my fault, I tested it with an outdated image (v2023.01.11). It works correctly in the current one v2023.03.14!
