### ISSUE TITLE
Interpreting html tags in attributes in identify result

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#432]
Hi there,

until now, only html link tags in attributes are interpreted as html correctly and I will get a clickable link in the identify window, if I am writing something like `<a href="https://abc.xyz">https://abc.xyz<a/>` within a field of an attribute table.

Is there a chance, to get other html tags like `<p></p>`, `<br />`, `<b></b>`, ... interpreted as well? Now they a treated as text and I get something like `&lt;br /&gt;` instead of a new line. 

Thanks for any suggestions!

**Comment by danceb** [comment]
I have no idea why (there wasn't an update to the qwc2 related to this, right?), but suddenly it works as aspected! Sry for my noise here.

**Comment by lperozzi** [comment]
Many thanks for that. However, I noticed that if the `FeatureForm` Identify Tool, is activated, the link is converted to HTML text and no more clickable (see second image)

<img src="https://user-images.githubusercontent.com/6198369/234875883-63311641-6724-4348-828a-49e16cd31aef.png" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/6198369/234875529-d59c6551-762b-4aa5-ad1d-99f8f62608d3.png" width=50% height=50%>

**Comment by danceb** [comment]
... what is the function of the feature form, isn't it? I think the function of the form is editing the content of the fields (which is the html text) and the function of the feature info window is displaying the content in a user and not editor perspective.
