### ISSUE TITLE
Custom CRS not working

### ISSUE THREAD

**Issue by Abelon38** [qgis/qwc2-demo-app#433]
Hello guys! 

I will need some help! I a trying to use QWC2 with custom CRS "EPSG:3006" without luck. My configuration looks like this:

**_themeConfig.json:_**

"mapCrs": "EPSG:3006",
                        "additionalMouseCrs": [
                            "EPSG:3857"
                        ],
**_config.json under static:_** 
  {
      "code": "EPSG:3006",
      "proj": "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs ",
      "label": "SWEREF99 TM"
    },

My project and layers are in EPSG:3006 and no layes are shown. But If I use "mapCrs": "EPSG:3857", in my themeConfig.json then layers will show up..

How can I do to make it work with "mapCrs": "EPSG:3006" ?

Thanks for your time!

BR/Abel

**Comment by manisandro** [comment]
Check in the network inspector in the Browser Developer Tools (typically open via F12) whether the GetMap request looks correct.

**Comment by pypb** [comment]
@Abelon38 Did you manage to get EPSG:3006 working? I'm facing the same issue.

Adding the following to the projections list:
```
{
  "code": "EPSG:3006",
  "proj": "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs",
  "label": "SWEREF99 TM"
}
```
And then setting EPSG:3006 as mapCrs gives a blank map.
