### ISSUE TITLE
Problem with drawing a new object

### ISSUE THREAD

**Issue by Azures49** [qgis/qwc2-demo-app#435]
It is not possible to draw a new object within the layer. The attribute composition contains all columns, the column formats were taken from the edit_polygon layer in the qwc_demo project. What could be my mistake?
![2023-03-30_11-49-02](https://user-images.githubusercontent.com/125432740/228753217-f90b62a7-52d5-423e-a75f-e659ff6f3817.png)
![image](https://user-images.githubusercontent.com/125432740/228753384-2d9caffa-8ea0-40e6-80b2-cd3ce1ee3992.png)

**Comment by manisandro** [comment]
You probably need to set the field type of `id_0` to hidden in the QGIS layer properties.

**Comment by Azures49** [comment]
![image](https://user-images.githubusercontent.com/125432740/228771823-4f363ece-6b21-4053-a9a1-4235e5a87cef.png)
I set up the attributes as you said, but now this error is displayed

**Comment by Azures49** [comment]
![image](https://user-images.githubusercontent.com/125432740/228776769-04ffee81-5b06-4d84-b289-df1ed24db000.png)
what is can a promlem moment?

**Comment by Azures49** [comment]
![image](https://user-images.githubusercontent.com/125432740/228816713-cd49aa7b-c904-4930-809b-76cd930b52b9.png)
![image](https://user-images.githubusercontent.com/125432740/228816776-d89818b4-f006-4a07-b7c8-26b1f30e1554.png)
![image](https://user-images.githubusercontent.com/125432740/228816885-8aacdc31-a8a4-4368-ab67-f2f7d84286fc.png)
I don't understand why the primary key id_0 is in the data config config in docker, and there is no primary key at all in qgis desktop. When trying to change the id column in the table to id_0, it also outputs an error
