### ISSUE TITLE
Question about the layer loading indicator

### ISSUE THREAD

**Issue by jshirokov-bs** [qgis/qwc2-demo-app#440]
Hi.
I have a little question. 
Every time, when I open a new theme in QWC2 and loading of layers begins, regardless of which layers are activated, loading indicator of all layers appears. Is this a visual bug, or something undocumented?
Thanks!

![image](https://user-images.githubusercontent.com/117968115/231853117-52bbd24e-f5d7-4d58-9d6b-5f62e6562a16.png)

**Comment by manisandro** [comment]
If these layers are part of the same WMS service and you i.e. toggle a sublayer of that WMS, then this is correct, as a new GetMap request is sent and the layers marked as loading while that request is processing.
