### ISSUE TITLE
Tiled mode issues on wms 

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#444]
Hello, 

Since update I encounter an error when I use the tiled mode on some WMS layer.

![image](https://user-images.githubusercontent.com/92778930/235861628-d3f5b8eb-ea4c-46a5-b855-652b68e0754e.png)

It's still working great when I don't use the tiled mode. 

Could this be related to [this commit](https://github.com/qgis/qwc2/commit/c30f2e7b946410a0a94f07dabc829c308b4029ef) ? 

Thanks in advance for your anwser,
Regards, Clément.

**Comment by manisandro** [comment]
Hmm, it looks more like you are missing that particular commit, which replaced the use of the non-existent `imageTile()` function?

**Comment by cazitouni** [comment]
Indeed, I've switched image: sourcepole/qwc-map-viewer-demo:v2023.1-lts to latest in the docker compose config and it's working now. 

Thanks for the quick reply.
