### ISSUE TITLE
termsUrl and viewertitleUrl of BottomBar config are not shown, if configured within "common" section in config.json

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#445]
Both of the mentioned parameters are only shown, when they are configured within the "mobile" or "desktop" section. If I am setting them under "common", the links are not shown within the BottomBar. So somehow they are not merged correctly or something like this?

**Comment by manisandro** [comment]
Can you post your config.json or at least the BottomBar configuration of the common/mobile/desktop sections?

**Comment by danceb** [comment]
Of course!

common:
```
      {
        "name": "BottomBar",
        "cfg": {
          "termsUrl": "mailto:contact@mail.com",
          "viewertitleUrl": "https://example.com",
          "viewertitleUrlTarget": "_blank"
        }
      },

```
mobile:
```
      {
        "name": "BottomBar",
        "cfg": {
          "displayCoordinates": false,
          "displayScales": false
        }
      },
```
desktop:
```
      {
        "name": "BottomBar",
        "cfg": {
          "displayCoordinates": true,
          "displayScales": true
        }
      }
```

**Comment by manisandro** [comment]
Hmm working fine here? What do you mean "are not shown"?

**Comment by danceb** [comment]
Huh, the same here now ... So missconfiguration by myself somehow. Sry.
