### ISSUE TITLE
Few questions about QWC2

### ISSUE THREAD

**Issue by jshirokov-bs** [qgis/qwc2-demo-app#447]
Hello!
I have a few questions about QWC2.
1) Is it possible to configure QGIS Server to interact with GeoServer, not with the database?
2) What is the parameter for determining the order of uploading project files to QWC2? Numbering in the name?
3) Is it possible to set, when opening a project, a transition to a specific object of the project layer? (automatic approach to the object)
4) Are there tools for dynamically updating project files in the scan folder?

Thanks!

**Comment by danceb** [comment]
Hello,
only the second question is related to the qwc2... So I think there are better places to ask/discuss these questions, like https://gis.stackexchange.com/ or the mailing lists, have a look at https://qgis.org/en/site/getinvolved/mailinglists.html. 

To answer 2.:
if you are defining your themes within the themesConfig.json/tenantConfig.json, the themes are generated in the order you are specifying the themes/projects there.
If you are using the qwc-services and the qwc-config-generator service and the approach to detect the project files automatically with `qgis_projects_scan_bas_dir`, then the configuration of the themes should be in the naming order of your files, I think.

**Comment by jshirokov-bs** [comment]
@danceb Thanks!
