### ISSUE TITLE
"No layers found for this map." when importing resources via admin_gui from map resource in /scan folder

### ISSUE THREAD

**Issue by w0pr** [qgis/qwc2-demo-app#448]
When putting a QGIS project file "qwc_demo_TEST.qgs" (which is the renamed qwc_demo.qgs project file) in the /scan folder, the resulting map resource is called "scan/qwc_demo_TEST".
If not renamed to "qwc_demo_TEST", importing resources/layers via admin_gui will result in a 404, since admin_gui will try the following URL:
ERROR in resources_controller: Could not get map details from http://qwc-config-service:9090/maps/scan/qwc_demo_TEST?tenant=default

After renaming the map resource to "qwc_demo_TEST", trying to import layers will result in "No layers found for this map.", although using the same project file without autoconfiguration works.

**Comment by manisandro** [comment]
This should already be fixed in qwc-config-generator-v2023.04.05
