### ISSUE TITLE
QWC2 read WMTS layers published by Internal Server

### ISSUE THREAD

**Issue by sli701** [qgis/qwc2-demo-app#449]
I have a QGIS Project that a WMTS layer.

I have check the GetCapabilities HTTP Request, and the layer is should up on the <Content> tab, which is what I want.

Then, I want to have QWC2 to read that layer.

I have check the themesConfig.json, none of the configuration related to how to add a background layer for Internal WMTS layer.

What is the themesConfig.json to read from that layer?

**Comment by sli701** [comment]
this script does not generate a correct format. I have already used it and tried it out.

**Comment by benoitblanc** [comment]
Should be resolved in https://github.com/qgis/qwc2/commit/924fc49c9a694873f9663a6cd513417b564c0a7e

**Comment by manisandro** [comment]
Closing, feel free to reopen if still relevant (thanks @benoitblanc!)
