### ISSUE TITLE
allow infoformats option from dataurl param

### ISSUE THREAD

**Issue by lassitanskanen** [qgis/qwc2-demo-app#452]
Hi,
There is hardcoded infoformats setting "text/plain" that seems impossible to overwrite with url param in dataurl. Should try json first and then back to text/plain if not correct response from server? Or just allow url params in dataurl.

**Comment by manisandro** [comment]
With recent QWC2 versions you can specify `infoFormat` in the data URL, i.e.

    wms:http://wms.geo.admin.ch?tiled=false&infoFormat=application/geojson#ch.are.bauzonen
