### ISSUE TITLE
GetLegendGraphic

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#454]
I'm having an issue getting a WMS layer to show the legend in Mapview. The url is

https://earthtrack.aber.ac.uk/services/wms/2022
https://earthtrack.aber.ac.uk/services?map=/etc/mapserver/wms2022.map&request=GetMetadata&layer=lw_habb_2022

and GetLegendGraphic:

https://earthtrack.aber.ac.uk/services?map=/etc/mapserver/wms2022.map&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=lw_habb_2022&format=image/png&STYLE=default&

Can you let me know in which 'json' file I can fix the issue. It appears exactly as it should in QGIS project.

N.B. For some reason the attachments have failed to upload.

**Comment by manisandro** [comment]
Hi, I'm afraid you'll have to provide more information regarding the issue you're facing.

**Comment by shapley** [comment]
Hi Manisandro,

If you rest the cursor over the layer tree WMS layer it show the legend heading (lw_habb_2022) only and is missing the remainder of the legend. It works in a QGIS legend as it should. 

![wmslegend](https://github.com/qgis/qwc2-demo-app/assets/7022885/220ca5c0-60c1-49d8-a703-a108d53917af)

![wms-minus-legend](https://github.com/qgis/qwc2-demo-app/assets/7022885/a77e9ab7-beaf-4c3a-b2b5-dcd096a61f09)

**Comment by manisandro** [comment]
Can you post the GetLegendGraphics request URL generated by QWC2 here?

**Comment by shapley** [comment]
Hi Manisandro,

I'm not sure what you mean by 'generated by QWC2' but the 'GetLegendGraphics' url is:

https://earthtrack.aber.ac.uk/services?map=/mapdata/wcs/map/wms2020.map&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=lw_habb_2020&format=image/png&STYLE=default

Thanks

**Comment by shapley** [comment]
Hi Manisandro,

This is what the browser 'Network'tab is showing:

http://qgisserver/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&MAP=%2Fhome%2Fqgis%2Fprojects%2Fworld.qgs&LAYERS=Road_27700%2Cleisure_27700%2Clw_habb_2020%2Ca_and_trunk_roads%2Cbbnpaline&STYLES=%2C%2C%2C%2C&SRS=EPSG%3A27700&CRS=EPSG%3A27700&TILED=false&DPI=96&OPACITIES=255%2C255%2C255%2C255%2C255&__t=1692774648804&WIDTH=1497&HEIGHT=460&BBOX=248742.14060999342%2C206693.16680723187%2C347762.4531099934%2C237120.2501405652

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Maybe this

https://earthtrack.aber.ac.uk/services/wms/2020. On your above query...the URL is a temp QGIS Server I.P (localhost:8081)

**Comment by shapley** [comment]
Hi Manisandro,

It seems that the 'external' wms layers coming from the same source will display the legend in QWC2 but (same layer) will not display through QGIS Server on QWC2.

**Comment by shapley** [comment]
QGIS Server and not a QWC2 issue.

**Comment by danceb** [comment]
Just for anyone, who will land here: The issue is fixed in 3.34.6.

https://github.com/qgis/QGIS/issues/42063
https://github.com/qgis/QGIS/pull/57066
https://github.com/qgis/QGIS/pull/57100
