### ISSUE TITLE
Support for multi styles layers

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#456]
Hello,

Qgis let the user the ability to define multiple styles for a layer and switch between them. 
![image](https://github.com/qgis/qwc2-demo-app/assets/92778930/6c9a8cb7-5b4b-4115-b08a-8c7ec6b6547d)
Wouldn't it be nice to add this feature in QWC ? 

Regards, Clément.

**Comment by manisandro** [comment]
Would for sure be a nice feature, PRs welcome!

**Comment by manisandro** [comment]
Implemented in https://github.com/qgis/qwc2/commit/9faa1bf451e9140b574349ba85c9bd1e3c8ec16e through https://github.com/qgis/qwc2/commit/4bddd5ff2aadd48bbddd6fea76ddeda7704283ca.
