### ISSUE TITLE
intermittent log entries "QNetworkDiskCache::prepare() unable to open temporary file" 

### ISSUE THREAD

**Issue by w0pr** [qgis/qwc2-demo-app#457]
I run sourcepole/qwc-qgis-server:3.28-plugins image from the docker services.

I am getting intermittent "QNetworkDiskCache::prepare() unable to open temporary file", especially when running config-generator.

```qwc-docker-qwc-qgis-server-1              |  QNetworkDiskCache::prepare() unable to open temporary file```

What might be the source of that? Do I need to configure the cache folder somehow? I did **not** specify a host volume for it.

I have set  SERVICE_UID: 1003 & SERVICE_GID: 1003 in docker-compose.yml, is there some permission issue?

**Comment by manisandro** [comment]
Closing in favour of https://github.com/qwc-services/qwc-qgis-server/issues/5
