### ISSUE TITLE
searchProvidersSelector not visible

### ISSUE THREAD

**Issue by beeekey** [qgis/qwc2-demo-app#458]
I am upgrading an old installation and ran into the following issue:

I ran `sourcepole/qwc-map-viewer-base:v2023.05.24` 

and have set
 ```          "searchOptions": {
            "minScaleDenom": 1000,
            "showProviderSelection": true,
            "providerSelectionAllowAll": true,
            "zoomToLayers": false,
            "showProvidersInPlaceholder": false
          }, 
``` 

but the dropdown option button is not visible in my project.

It should look like this: 

![Screenshot 2023-06-05 111133](https://github.com/qgis/qwc2-demo-app/assets/5571334/4b3687de-664a-425d-87f8-531ce0cedb6d)

but looks like this:

![Screenshot 2023-06-05 111345](https://github.com/qgis/qwc2-demo-app/assets/5571334/ee1798e2-6120-473d-b517-bf7c39edb200)

What config do I need to set to have the old version visible

**Comment by manisandro** [comment]
You previously used the `Search` plugin as `TopBarPlugin` search component in [1], whereas the demo builds nowadays used `SearchBox`, which does not provide a provider selection menu. You'll need to build a custom viewer to use the `Search` plugin. Refer to [2].

[1] https://github.com/qgis/qwc2-demo-app/blob/master/js/appConfig.js
[2] https://qwc-services.github.io/configuration/ViewerConfiguration/#building-a-custom-viewer
