### ISSUE TITLE
Bug - Feature Info, Add Layers to current map window can not be closed in the Mobile view

### ISSUE THREAD

**Issue by sli701** [qgis/qwc2-demo-app#459]
![18aedf45-58a0-4d46-9dba-4c6939972323](https://github.com/qgis/qwc2-demo-app/assets/22850666/e6ce965a-5fc7-42e9-9469-6d7c70f71a5b)

**Comment by manisandro** [comment]
Cannot reproduce. Are you using a current version of QWC2?

**Comment by sli701** [comment]
I am testing using iPhone. It works find on end desktop, but not on the mobile. How can I do an upgrade to the QWC2 packages?

**Comment by manisandro** [comment]
Closing, feel free to reopen if still relevant.
