### ISSUE TITLE
qwc2 demo - bounds

### ISSUE THREAD

**Issue by Fudimir** [qgis/qwc2-demo-app#460]
Hello!

I am trying to change the scale of the extent of the demo project so that when I open the site I see not a map of Europe, but a map of a separate city in Austria. However, specifying the extent in the project settings in QGIS does not help. How i can do this?

Thanks!

**Comment by manisandro** [comment]
If you set the advertised extent in QGIS -> Project Properties -> QGIS Server -> WMS and regenerate the theme configuration, this extent should get used as initial extent when loading the theme (unless you have specified a different extent manually in `themesConfig.json`).

**Comment by manisandro** [comment]
Closing, feel free to reopen if questions remain.
