### ISSUE TITLE
wms selection parameters 

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#461]
In Qgis server it is possible to pass a selection:"layername":"elementId" parameter to highlight a feature in the layer.

Could it be a good idea to add the possibility to pass this parameter in the getmap request made by QWC ? 

Otherwise it is necessary to configure the fulltext search service to pass parameter hf hp and/or ht.
It could be usefull to select directly an object without using fulltext search, for example when an URL call is made from another appllication.

**Comment by w0pr** [comment]
> Otherwise it is necessary to configure the fulltext search service to pass parameter hf hp and/or ht. It could be usefull to select directly an object without using fulltext search, for example when an URL call is made from another appllication.

As I read the documentation, it should be possible without using fulltext search by impementing a custom searchProvider using Javascript, which would craft the [filtered WMS request](https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#wms-filter) to QGIS server (using the value of **ht** query parameter).

I tried but hit a another issue [here](https://github.com/qgis/qwc2-demo-app/issues/451#issue-1718441605).

**Comment by cazitouni** [comment]
Hello @w0pr, 

Thanks for your answer. But as I understand Filter parameter will not highlight the elements but only remove other element from the layer. 
Also, a searchProvider will only work for one layer/project if I pass a new parameter within the URL it should work for all layers/projects.
My use case mostly concerns external apps that we use within our structure that needs to make a call via url. 

I actually try some stuff and passing a new parameter called "slc" then using Qgis server Selection parameter actually works quite well
Here is an exemple on the demo app for Switzerland (countries:93)
![t](https://github.com/qgis/qwc2-demo-app/assets/92778930/3464bf3d-03f3-41f8-9331-df273827a2f7)

Do not hesitate if you have any other idea or If I had misunderstood your original message.
Kind regards, Clément.

**Comment by w0pr** [comment]
> Thanks for your answer. But as I understand Filter parameter will not highlight the elements but only remove other element from the layer.

The thing I want as a result from the WMS query is just the feature id and the bounding box if it has been found.

This will be returned from the searchProvider's onSearch() function and the code in SearchBox.jsx will do the highlighting and zooming:
https://github.com/qgis/qwc2/blob/f959d9bd93009dbea5cf381f56a45a7fb0c25c07/components/SearchBox.jsx#L479

>Also, a searchProvider will only work for one layer/project if I pass a new parameter within the URL it should work for all layers/projects. My use case mostly concerns external apps that we use within our structure that needs to make a call via url.

You could configure this searchProvider as defaultSearchProvider:
https://github.com/qwc-services/qwc-config-generator/blob/master/tenantConfig-example.json#L16

> I actually try some stuff and passing a new parameter called "slc" then using Qgis server Selection parameter actually works quite well Here is an exemple on the demo app for Switzerland (countries:93) ![t](https://user-images.githubusercontent.com/92778930/250477179-3464bf3d-03f3-41f8-9331-df273827a2f7.png)

I'll have a look, but as I read the newly improved documentation, it should just work the way I think: https://qwc-services.github.io/topics/Search/

**Comment by cazitouni** [comment]
Qgis search now can do that
