### ISSUE TITLE
Customize Marker style and Measurement style

### ISSUE THREAD

**Issue by ger-benjamin** [qgis/qwc2-demo-app#462]
Hello,
Using qwc2 in a project, I would like to have the possibility to change the measurement style (hard-coded to be red) and the "marker" icon. I've not seen any possibility to do that without overriding the code.

Are you open to receive PR ? I could make one based on the same system as for the defaultFeatureStyle:
https://github.com/qgis/qwc2/blob/8bfcb52b3dfd6d367fa167281f20c9b319721e82/utils/FeatureStyles.js#L26

That mean I would make a PR that: 
 - Add a "markerFeatureStyle" into the config.json to have the possibility to set the marker icon (would be global for every component using this marker icon).
 - Move the measure style into the FeatureStyles file and a "measureFeatureStyle" object into the config.json.

**Comment by manisandro** [comment]
Sounds good to me!

**Comment by ger-benjamin** [comment]
PR are here:
 - https://github.com/qgis/qwc2/pull/247
 - https://github.com/qwc-services/qwc-services.github.io/pull/10

IT's a bit more than expected, the style was less uniformized than expected, so I've modification for marker, redlining, edit, snap and measurement.

**Comment by manisandro** [comment]
PR has been merged
