### ISSUE TITLE
Error when link parameter is to loong

### ISSUE THREAD

**Issue by Areen3** [qgis/qwc2-demo-app#469]
Hi
I have map with about 40 map veiw.
I want to refresh page and have this error:
![image](https://github.com/qgis/qwc2-demo-app/assets/34617740/9280b15d-9283-40da-a2c6-f2830f6d0021)

link is like that:
https://maps.rat-adv.com/?l=zaakceptowane!%2Cautostrady!%2Cw_przygotowaniu!%2Cwszystkie_trasy_podstawowe!%2Cpoziom_autostrad!%2Cwszystkie_trasy_pelny_dostep!%2Cwszystkie_dol_podst!%2Ckoncepcja_dol_podst!%2Cdla_karografa_dol_podst!%2Cdla_zwiadowcy_dol_podst!%2Cgotowa_dol_podst!%2Clokalna_dol_podst!%2Cwszystkie_kuj-pom_podst!%2Ckoncepcja_kuj-pom_podst!%2Cdla_karografa_kuj-pom_podst!%2Cdla_zwiadowcy_kuj-pom_podst!%2Cgotowa_kuj-pom_podst!%2Clokalna_kuj-pom_podst!%2Cwszystkie_lodz_podst!%2Ckoncepcja_lodz_podst!%2Cdla_karografa_lodz_podst!%2Cdla_zwiadowcy_lodz_podst!%2Cgotowa_lodz_podst!%2Clokalna_lodz_podst!%2Cwszystkie_lubelskie_podst!%2Ckoncepcja_lubelskie_podst!%2Cdla_karografa_lubelskie_podst!%2Cdla_zwiadowcy_lubelskie_podst!%2Cgotowa_lubelskie_podst!%2Clokalna_lubelskie_podst!%2Cwszystkie_lub_podst!%2Ckoncepcja_lub_podst!%2Cdla_karografa_lub_podst!%2Cdla_zwiadowcy_lub_podst!%2Cgotowa_lub_podst!%2Clokalna_lub_podst!%2Cwszystkie_mal_podst!%2Ckoncepcja_mal_podst!%2Cdla_karografa_mal_podst!%2Cdla_zwiadowcy_mal_podst!%2Cgotowa_mal_podst!%2Clokalna_mal_podst!%2Cwszystkie_maz_podst!%2Ckoncepcja_maz_podst!%2Cdla_karografa_maz_podst!%2Cdla_zwiadowcy_maz_podst!%2Cgotowa_maz_podst!%2Clokalna_maz_podst!%2Cwszystkie_opol_podst!%2Ckoncepcja_opol_podst!%2Cdla_karografa_opol_podst!%2Cdla_zwiadowcy_opol_podst!%2Cgotowa_opol_podst!%2Clokalna_opol_podst!%2Cwszystkie_podk_podst!%2Ckoncepcja_podk_podst!%2Cdla_karografa_podk_podst!%2Cdla_zwiadowcy_podk_podst!%2Cgotowa_podk_podst!%2Clokalna_podk_podst!%2Cwszystkie_podl_podst!%2Ckoncepcja_podl_podst!%2Cdla_karografa_podl_podst!%2Cdla_zwiadowcy_podl_podst!%2Cgotowa_podl_podst!%2Clokalna_podl_podst!%2Cwszystkie_pom_podst!%2Ckoncepcja_pom_podst!%2Cdla_karografa_pom_podst!%2Cdla_zwiadowcy_pom_podst!%2Cgotowa_pom_podst!%2Clokalna_pom_podst!%2Cwszystkie_slask_podst!%2Ckoncepcja_slask_podst!%2Cdla_karografa_slask_podst!%2Cdla_zwiadowcy_slask_podst!%2Cgotowa_slask_podst!%2Clokalna_slask_podst!%2Cwszystkie_sw_podst!%2Ckoncepcja_sw_podst!%2Cdla_karografa_sw_podst!%2Cdla_zwiadowcy_sw_podst!%2Cgotowa_sw_podst!%2Clokalna_sw_podst!%2Cwszystkie_warmaz_podst!%2Ckoncepcja_warmaz_podst!%2Cdla_karografa_warmaz_podst!%2Cdla_zwiadowcy_warmaz_podst!%2Cgotowa_warmaz_podst!%2Clokalna_warmaz_podst!%2Clokalna_wkp_podst!%2Cwszystkie_wkp_podst!%2Ckoncepcja_wkp_podst!%2Cdla_karografa_wkp_podst!%2Cdla_zwiadowcy_wkp_podst!%2Cgotowa_wkp_podst!%2Clokalna_zachp_podst!%2Cwszystkie_zachp_podst!%2Ckoncepcja_zachp_podst!%2Cdla_karografa_zachp_podst!%2Cdla_zwiadowcy_zachp_podst!%2Cgotowa_zachp_podst!%2Clokalna_pl_podst!%2Cwszystkie_pl_podst!%2Ckoncepcja_pl_podst!%2Cdla_karografa_pl_podst!%2Cdla_zwiadowcy_pl_podst!%2Cgotowa_pl_podst!%2Cwszystkie_dol_full!%2Ckoncepcja_dol_full!%2Cdla_karografa_dol_full!%2Cdla_zwiadowcy_dol_full!%2Cgotowa_dol_full!%2Clokalna_dol_full!%2Cwszystkie_kujpom_full!%2Ckoncepcja_kujpom_full!%2Cdla_karografa_kujpom_full!%2Cdla_zwiadowcy_kujpom_full!%2Cgotowa_kujpom_full!%2Clokalna_kujpom_full!%2Cwszystkie_lodz_full!%2Ckoncepcja_lodz_full!%2Cdla_karografa_lodz_full!%2Cdla_zwiadowcy_lodz_full!%2Cgotowa_lodz_full!%2Clokalna_lodz_full!%2Cwszystkie_lubelskie_full!%2Ckoncepcja_lubelskie_full!%2Cdla_karografa_lubelskie_full!%2Cdla_zwiadowcy_lubelskie_full!%2Cgotowa_lubelskie_full!%2Clokalna_lubelskie_full!%2Cwszystkie_lub_full!%2Ckoncepcja_lub_full!%2Cdla_karografa_lub_full!%2Cdla_zwiadowcy_lub_full!%2Cgotowa_lub_full!%2Clokalna_lub_full!%2Cwszystkie_mal_full!%2Ckoncepcja_mal_full!%2Cdla_karografa_mal_full!%2Cdla_zwiadowcy_mal_full!%2Cgotowa_mal_full!%2Clokalna_mal_full!%2Cwszystkie_maz_full!%2Ckoncepcja_maz_full!%2Cdla_karografa_maz_full!%2Cdla_zwiadowcy_maz_full!%2Cgotowa_maz_full!%2Clokalna_maz_full!%2Cwszystkie_opol_full!%2Ckoncepcja_opol_full!%2Cdla_karografa_opol_full!%2Cdla_zwiadowcy_opol_full!%2Cgotowa_opol_full!%2Clokalna_opol_full!%2Cwszystkie_podk_full!%2Ckoncepcja_podk_full!%2Cdla_karografa_podk_full!%2Cdla_zwiadowcy_podk_full!%2Cgotowa_podk_full!%2Clokalna_podk_full!%2Cwszystkie_podl_full!%2Ckoncepcja_podl_full!%2Cdla_karografa_podl_full!%2Cdla_zwiadowcy_podl_full!%2Cgotowa_podl_full!%2Clokalna_podl_full!%2Cwszystkie_pom_full!%2Ckoncepcja_pom_full!%2Cdla_karografa_pom_full!%2Cdla_zwiadowcy_pom_full!%2Cgotowa_pom_full!%2Clokalna_pom_full!%2Cwszystkie_slask_full!%2Ckoncepcja_slask_full!%2Cdla_karografa_slask_full!%2Cdla_zwiadowcy_slask_full!%2Cgotowa_slask_full!%2Clokalna_slask_full!%2Cwszystkie_sw_full!%2Ckoncepcja_sw_full!%2Cdla_karografa_sw_full!%2Cdla_zwiadowcy_sw_full!%2Cgotowa_sw_full!%2Clokalna_sw_full!%2Cwszystkie_wm-maz_full!%2Ckoncepcja_wm-maz_full!%2Cdla_karografa_wm-maz_full!%2Cdla_zwiadowcy_wm-maz_full!%2Cgotowa_wm-maz_full!%2Clokalna_wm-maz_full!%2Cwszystkie_wlkp_full!%2Ckoncepcja_wlkp_full!%2Cdla_karografa_wlkp_full!%2Cdla_zwiadowcy_wlkp_full!%2Cgotowa_wlkp_full!%2Clokalna_wlkp_full!%2Cwszystkie_zachpom_full!%2Ckoncepcja_zachpom_full!%2Cdla_karografa_zachpom_full!%2Cdla_zwiadowcy_zachpom_full!%2Cgotowa_zachpom_full!%2Clokalna_zachpom_full!%2Cwszystkie_pl_full!%2Ckoncepcja_pl_full!%2Cdla_karografa_pl_full!%2Cdla_zwiadowcy_pl_full!%2Cgotowa_pl_full!%2Clokalna_pl_full!%2Crats_natura2000!%2Crats_obszary_wodno_blotne!%2Crats_parki_krajobrazowe!%2Crats_parki_narodowe%2Crats_pomniki%2Crats_rezerwaty%2Crats_lp_udostepnione!%2Crats_drogi_dolnoslaskie!%2Crats_drogi_kujawsko_pomorskie!%2Crats_drogi_lodzkie!%2Crats_drogi_lubelskie!%2Crats_drogi_lubuskie!%2Crats_drogi_malopolskie!%2Crats_drogi_mazowieckie!%2Crats_drogi_opolskie!%2Crats_drogi_podkarpackie!%2Crats_drogi_podlaskie!%2Crats_drogi_pomorskie!%2Crats_drogi_slaskie!%2Crats_drogi_swietokrzyskie%2Crats_drogi_warminsko_mazurskie!%2Crats_drogi_wielkopolskie!%2Crats_drogi_zachodniopomorskie!%2Crats_inne_dolnoslaskie!%2Crats_inne_kujawsko_pomorskie!%2Crats_inne_lodzkie!%2Crats_inne_lubelskie!%2Crats_inne_lubuskie!%2Crats_inne_malopolskie!%2Crats_inne_mazowieckie!%2Crats_inne_opolskie!%2Crats_inne_podkarpackie!%2Crats_inne_podlaskie!%2Crats_inne_pomorskie!%2Crats_inne_slaskie!%2Crats_inne_swietokrzyskie%2Crats_inne_warminsko_mazurskie!%2Crats_inne_wielkopolskie!%2Crats_inne_zachodniopomorskie!%2Crats_lasy_bialystok!%2Crats_lasy_gdansk!%2Crats_lasy_katowice!%2Crats_lasy_krakow!%2Crats_lasy_krosno!%2Crats_lasy_lodz!%2Crats_lasy_lublin!%2Crats_lasy_olsztyn!%2Crats_lasy_pila!%2Crats_lasy_poznan!%2Crats_lasy_radom%2Crats_lasy_szczecin!%2Crats_lasy_szczecinek!%2Crats_lasy_torun!%2Crats_lasy_warszawa!%2Crats_lasy_wroclaw!%2Crats_lasy_zielona_gora!%2CGoogle%20satelita&bl=mapnik&t=qwc_demo&c=2316069%2C6554950&s=40000

and this link is too big 
Is possible to do something with this error

**Comment by mhaelsig** [comment]
Hi,
first step would be to check the nginx log (following the error message).
Without knowledge of this log, I would propose to set the parameter

_'omitUrlParameterUpdates'_ in config.json to _'true'_.
