### ISSUE TITLE
setting autogen_keyvaltable_datasets to true in tenantConfig.json result in KeyError when generating config for QGS theme/project without /scan prefix

### ISSUE THREAD

**Issue by w0pr** [qgis/qwc2-demo-app#470]
Using sourcepole/qwc-config-generator:v2023.07.24 docker image.

I have an autogenerated edit form for a layer that uses [value relations](https://qwc-services.github.io/topics/Editing/#key-value-relations-value-mappings) in a dropdown widget. I added a geometryless layer to the project and it works fine in desktop QGIS.

In QWC2 however, the dropdowns would not show either the set value or any values to be selected, so I tried setting **autogen_keyvaltable_datasets** to **true**, as noted in https://qwc-services.github.io/topics/Editing/#key-value-relations-value-mappings:

> Note: The relation table needs to be added as a (geometryless) table to the QGIS Project. You also need to set appropriate permissions for the relation table dataset in the QWC admin backend. Alternatively, you can set autogen_keyvaltable_datasetsto true in the config generator configuration, to automatically generate resources and read-only permissions as required.

But setting [autogen_keyvaltable_datasets ](https://qwc-services.github.io/references/qwc-config-generator/#config_autogen_keyvaltable_datasets) to **true** in tenantConfig.json results in KeyError exception ("SW_xxxxxxxxx_Neu_form_dropdown" is the QGS project name):

> Python Exception: 'SW_xxxxxxxxx_Neu_form_dropdown'
> Traceback (most recent call last):
>   File "/srv/qwc_service/./server.py", line 55, in generate_configs
>     generator.write_configs()
>   File "/srv/qwc_service/./config_generator/config_generator.py", line 354, in write_configs
>     self.write_service_config(service_config['name'])
>   File "/srv/qwc_service/./config_generator/config_generator.py", line 387, in write_service_config
>     config = config_handler.config()
>   File "/srv/qwc_service/./config_generator/data_service_config.py", line 44, in config
>     resources['datasets'] = self._datasets(config, session)
>   File "/srv/qwc_service/./config_generator/data_service_config.py", line 168, in _datasets
>     meta = self.themes_reader.layer_metadata(qgs_name, value.get('layername'))
>   File "/srv/qwc_service/./config_generator/theme_reader.py", line 129, in layer_metadata
>     if not self.theme_metadata[service_name]['project']:
> KeyError: 'SW_xxxxxxxxx_Neu_form_dropdown'

**This only happens when a theme is manually configured** (dependent on project in /scan folder).

When deleting this manually configured theme, thereby leaving only "scan/SW_xxxxxxxxx_Neu_form_dropdown", config generation runs without exception.

**Comment by manisandro** [comment]
Can you provide a minimal project incl minimal data to reproduce the issue?

**Comment by manisandro** [comment]
Closing, please reopen if issue still applies with the latest config-generator.
