### ISSUE TITLE
FilterExpression Option of ValueRelation widget of attribute edit form is not used, works in QGIS desktop

### ISSUE THREAD

**Issue by w0pr** [qgis/qwc2-demo-app#471]
I use a ValueRelation widget in the autogenerated attribute form with a table containing all preconfigured values for dropdowns of different attributes, so I need to filter them to those belongimng to the attribute in question.
![image](https://github.com/qgis/qwc2-demo-app/assets/8257055/52dcf912-a3ac-43c9-9563-0a3edf4a873b)

Works fine in QGIS desktop, but QWC2 edit form will load the whole table into the dropdown.

I checked generated config files (especially dataConfig.json), but no trace of filter expression, and no indication in code of config generator or data service of its use.

Is this implemented at all?

I tried using a virtual layer with the filter expression expressed in the SQL query, but this does not seem to work either (maybe I'm making a mistake, but no values are loaded at all).

Do I have to use separate views & layers for the values of each attribute to select from drowdown?

**Comment by manisandro** [comment]
Currently filter expressions are not implemented, you will need to use a view

**Comment by manisandro** [comment]
Initial support for filter expressions has been implemented in [1], currently with a limited number of supported expression verbs [2].

[1] https://github.com/qgis/qwc2/commit/a4efb2bd5a7c78ff3f6bc47494c24457a927d37f
[2] https://github.com/qgis/qwc2/blob/master/utils/expr_grammar/grammar.ne
