### ISSUE TITLE
Do not ask for location on startup

### ISSUE THREAD

**Issue by OndraM** [qgis/qwc2-demo-app#473]
Hi, is it possible to configure QWC2 in a such way, so that it do not asks for user location on startup, but rather only after click to LocateButton?

Current behavior could be a bit obtrusive - you open QWC2 and first thing it does, is to ask you for location permissions... It also might not be the main usecase, for example - you may provide map data only for small locality/city, but the visitors are from around the world. So unless you are actually in the city, it does not make sense to ask for user location as the first thing.

**Comment by manisandro** [comment]
No, but this would indeed be a nice improvement, should merely require some some changes to `OlLocate.js` to delay-construct the `ol.Geolocation` instance only when the user explicitly tries to enable geolocation by clicking on the `LocateButton`.

**Comment by manisandro** [comment]
Done in https://github.com/qgis/qwc2/commit/01a5cd5fa7d4d94018981e1468aa4f43aa6c698f

**Comment by danceb** [comment]
Thanks for this improvement! May you can extend the documentation for the locate plugin naming and explaining the different startup options?
https://qwc-services.github.io/references/qwc2_plugins/#locatebutton
