### ISSUE TITLE
location on apache2 of the 'prod' directory

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#474]
Hi,

I've run 'yarn run prod' but don't know where on an Apache2 server it is meant to be located (Ubuntu 22.04 server). Is it in /var/www/html or /var/www/ or somewhere else?. This post [](https://gis.stackexchange.com/questions/344180/qwc2-first-install ) mentions 'htdocs/root' ? Also... how can it be tested? 

serverIP:port/prod

The documentation isn't clear on 'prod'

**Comment by manisandro** [comment]
It likely is /var/www/html, but this is not really a QWC2 aspect, rather of the webserver configuration which will host qwc2.
