### ISSUE TITLE
The selected theme does not support printing

### ISSUE THREAD

**Issue by beeekey** [qgis/qwc2-demo-app#477]
We are using a QWC2 instance based on the qwc-docker using the qwc-services. 

We have several QGIS projects on this system. But, for some of these I get `The selected theme does not support printing` when clicking on print in the menu, and some just work fine.

![Screenshot 2023-09-01 155210](https://github.com/qgis/qwc2-demo-app/assets/5571334/f57cabdd-3187-4a75-988b-5472cbd955ac)

I have manually compared all QGIS projects and couldn't find any difference. I have recreated the configuration and restarted the servers several times. I have checked, that the layouts are included in the ogc-getProjectSettings.

Does somebody have an idea how to add printing to all Theme/Qgis projects?

**Comment by manisandro** [comment]
Please see https://qwc-services.github.io/topics/Printing/

**Comment by beeekey** [comment]
Yeah, I have read this already several times.

**Comment by manisandro** [comment]
Ultimately the message means that no print layouts are specified in the theme item in themes.json. So make sure that:

- The print layout contains a map element
- The layout appears in the GetProjectSettings output
- The layout is not restricted by permissions set in the admin gui

**Comment by beeekey** [comment]
- The print layout contains a map element 
  -  This is the case
- The layout appears in the GetProjectSettings output
  -  This is the case
- The layout is not restricted by permissions set in the admin gui
  -  It seems there are no restrictions
  
 But, what I could see now, in the themes.json. The themes which not work have no "printUrl", how is this generated?

**Comment by manisandro** [comment]
`printUrl` can be specified in the theme item in `themesConfig.json` to point it to a different location than the base WMS url, but if unspecified, it will use the same url as the base WMS url. So this should not be the issue. Also, the message regarding the theme that does not support printing will only ever appear if there are no print layouts specified for a theme in the `themes.json`, it is not related to `printUrl`. I'm afraid it is pretty hard to give further insight without some debugging effort.

**Comment by manisandro** [comment]
Closing as this is most likely a configuration issue.
