### ISSUE TITLE
backgroundLayers and overview config

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#478]
Hi,

I'm struggling to get 'backgroundLayers' to display including an 'overview'. Can someone give me some advice on setup, e.g what to check for. Here is the backgroundLayer config in 'themesConfig.json' so far but it fails to display any background switcher or overview. I'm obviously missing something. I'm trying to avoid using 'printLayer' and 'group' until I get a least one working successfully.

                "backgroundLayers":[
                      {
                          "name":"Road_27700",
                          "title":"O'S Road Map",
                          "type":"wmts",
                          "url": "https://api.os.uk/maps/raster/v1/wmts?key=VUqinBBHsGPgqoeGHsKwVS429iAfFhGR",
                          "thumbnail":"default.jpg",
                          "overview":false,
                          "params":{"LAYERS":"Road_27700",
                              "STYLES":"default",
                              "VERSION":"1.3.0"
                                   }
                      },
                      {
                          "name":"Leisure_27700",
                          "title":"O'S Leisure Map",
                          "type":"wmts",
                          "url": "https://api.os.uk/maps/raster/v1/wmts?key=VUqinBBHsGPgqoeGHsKwVS429iAfFhGR",
                          "thumbnail":"default.jpg",
                          "overview":true,
                          "params":{"LAYERS":"Leisure_27700",
                              "STYLES":"default",
                              "VERSION":"1.3.0"
                                   }
                      },
                      {
                          "name":"AP-25CM-GB-LATEST",
                          "title":"APGB 25cm Aerial",
                          "type":"wms",
                          "url": "https://ogc.apps.midgard.airbusds-cint.com/apgb/wms?guid=e2ba5ffce0d431863ae5a2441f89f3ad",
                          "thumbnail":"default.jpg",
                          "overview":false,
                          "params":{"LAYERS":"AP-25CM-GB-LATEST",
                              "STYLES":"default",
                              "VERSION":"1.3.0"
                                   }
                      },
                      {
                          "name":"Road_27700",
                          "visibility":true
                      },
                      {
                          "name":"Leisure_27700",
                          "visibility":true
                      },
                      {
                          "name":"AP-25CM-GB-LATEST",
                          "visibility":true
                      }
                ],

**Comment by manisandro** [comment]
I think you are mixing the list of background layer definitions with the list of background layers assigned to a theme item. Please have a look at the sample themesConfig.json: https://github.com/qgis/qwc2-demo-app/blob/master/themesConfig.json

**Comment by shapley** [comment]
I can now see the 'background switcher' but no overview or map. I've added the following code to the layer definition. perhaps "params":{} are missing?

    "backgroundLayers":[
                   {
                          "type":"wmts",
                          "url": "https://api.os.uk/maps/raster/v1/wmts?key=X0X0X0",
                          "title":"O'S Leisure Map",
                          "name":"Leisure_27700",
                          "format":"image/png",
                          "style":"default",
                          "originX":-238375.0,
                          "originY":1376256.0,
                          "projection":"EPSG:27700",
                          "resolutions":[
                              896.0,
                              448.0,
                              224.0,
                              112.0,
                              56.0,
                              28.0,
                              14.0,
                              7.0,
                              3.5,
                              1.75
                          ],
                          "tilesize":[
                              256,
                              256
                          ],
                          "thumbnail":"default.jpg",
                          "tileMatrixPrefix":"18",
                          "tileMatrixSet":"EPSG:27700",
                          "overview":true
                      }],

![backgroundswitcher](https://github.com/qgis/qwc2-demo-app/assets/7022885/35722c9a-2036-42de-86fe-421d5e0e3ccc)

**Comment by shapley** [comment]
Maybe a 'CORS' issue or 'Key=' issue preventing tiles from pulling in browser. Error 401


![key=](https://github.com/qgis/qwc2-demo-app/assets/7022885/1bf17160-8d39-4124-8d16-7c8c96ee2c52)


![error401](https://github.com/qgis/qwc2-demo-app/assets/7022885/62f12938-499c-47f1-84a4-9c484909e424)

**Comment by Skipper-is** [comment]
Looks like your API key isn't passing across your API key when it fetches the request. You could try'/wmts?key=asdasdasdasYOUR KEY&' and see whether it appends the request to that. 
I've noticed that PyQGIS also does some fiddling with the wmts/xyz request URLs if you're adding layers programatically, stripping away arguments from the request URL, so could be an instance of that here.
(Also, maybe regenerate your API key?)

**Comment by shapley** [comment]
Thanks Skipper-is....Seems that was the issue.
