### ISSUE TITLE
Issue on QWC2-demo app - Error while changing tool in Measure Component

### ISSUE THREAD

**Issue by VincentHeau** [qgis/qwc2-demo-app#480]
![image](https://github.com/qgis/qwc2-demo-app/assets/93425160/0d05a4c8-4136-47a5-8de1-1e48f62fb2b2)

The issue is located in the Measure Component. After selecting "lenght", and drawing a segment on the map, an error is raised  if you close the menu or of you select an other option such as "Area", "Bearing" or "Position". As you can see it on the picture the errors are
```
Error: <line> attribute x1: Expected length, "NaN".
Error: <line> attribute x2: Expected length, "NaN".
chartist.js:2076 Error: <path> attribute d: Expected number, "MNaN,62.1LNaN,57.…".
chartist.js:2076 Error: <path> attribute d: Expected number, "MNaN,62.1LNaN,57.…"
```
Thank you for your attention to this matter.
Vincent

**Comment by manisandro** [comment]
Is you QWC2 recent? Can you reproduce it on qwc2.sourcepole.ch?

**Comment by VincentHeau** [comment]
The error is on qwc2.sourcepole.ch as well

![image](https://github.com/qgis/qwc2-demo-app/assets/93425160/2705de31-167e-40ab-b4c1-6ac12ba0af4a)

**Comment by manisandro** [comment]
Thanks, fixed by https://github.com/qgis/qwc2/commit/aba18110edd59db7a4345f885f425003f2bc9551

**Comment by VincentHeau** [comment]
Thank you 😊
