### ISSUE TITLE
Issue while importing WMTS encoded in Key-Value Pair(KVP)

### ISSUE THREAD

**Issue by VincentHeau** [qgis/qwc2-demo-app#481]
I try to use the menu "Import a layer" on last version of qwc2-demo-app (also tested on [qwc2 demo](http://qwc2.sourcepole.ch/))
![image](https://github.com/qgis/qwc2-demo-app/assets/93425160/f8e25de1-1ba7-4d3c-a6a4-fe061fbc6750)

I'm not able to import the layer of WMTS requests encoded in Key-value pair (KVP) system. I may suggest (but I'm not sure) that the problem is located in *ServiceLayerUtils.js* in the **getWMTSLayers method**. To address this, I introduced an 'if' condition in the code I'm developing to check if the *capabilitiesurl* indicates that the request is encoded in Key-Value Pairs (KVP) or not. If it is the case, I include the parameter requestEncoding: 'KVP' in the layerObj. However, I'm uncertain if this is the correct solution. 

The swiss requests work perfectly but they are not encoded in KVP. 
What is weird is that it's not the case with WMS requests. qwc2 works with them.

Here are the WMTS request (from the IGN (France) so you can test it as well. 
⚠️There is a maintenance of the IGN on the 23rd and 24th of September. Test the Getcapabilities requests below before testing them on QWC2. Here is the website where you can find all these requests : {Geoservices IGN] https://geoservices.ign.fr/services-web 

**WMTS examples**
https://wxs.ign.fr/parcellaire/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities
https://wxs.ign.fr/decouverte/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities

**WMS examples**:
https://wxs.ign.fr/essentiels/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

Thank you for your attention to this matter.
Vincent

**Comment by benoitblanc** [comment]
Hi @VincentHeau, I think you can do quite the same thing that I did here : https://github.com/qgis/qwc2/pull/245 to get `format` and `requestEncoding` from WMTS GetCapabilities request.

**Comment by VincentHeau** [comment]
Thank you very much, indeed, this Python script allows generating the JSON object from a WMTS stream, which can then be displayed in the portal. I did draw inspiration from this structure to modify the **getWMTSLayers** (*in ServiceLayerUtils.js*) method in case one would like to add WMTS layers using the layer import functionality.

However, it seems interesting to me to modify this method to deal with the case of KVP-encoded requests.

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/2a5261e4cfb682af62cd15ae39d4fbecdffd9e5b
