### ISSUE TITLE
Constrain extent

### ISSUE THREAD

**Issue by sweco-seiawc** [qgis/qwc2-demo-app#482]
Is it possible to constrain extent in a map?

See https://openlayers.org/en/latest/examples/extent-constrained.html

**Comment by manisandro** [comment]
I've implemented this in https://github.com/qgis/qwc2/commit/d1292751440cdbfec1b49f0719367cb41c9b6f95, se `constrainExtent: true` in `config.json -> plugins -> mapOptions`.

**Comment by danceb** [comment]
Nice feature, thanks! But where can I specify the extent, to which the map should be constrained? I couldn't find this in the configs/documentation.

**Comment by manisandro** [comment]
The extent will be constrained to the project extent resp. the overridden extent in `themesConfig.json`.
