### ISSUE TITLE
Bug with toolbarItemsShortcutPrefix

### ISSUE THREAD

**Issue by smaspons** [qgis/qwc2-demo-app#483]
Hello!

I found out that the toolbar items shortcuts ignore the hidden items via whitelist/blacklist. If I press Alt+Shift+2 it activates the second item that's configured in the config.json, regardless of its visibility on the current theme.

Please let me know if you can't reproduce it on your end or if you need more details.

Thanks!

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/3d893abb4ab9b9935a7f8e33779db5bf72521697
