### ISSUE TITLE
Attribution of background layer(s) not visible

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#487]
Hi,
although 'attribute' and 'attributeUrl' are set, these attributions are not shown, at least when switching the background layer. Even the qwc2-demo-app always shows the attribution 'Demo attribution', although the corresponding themes.json contains specific attributions for e.g. the OSM background layer. 
Here I am lost - I do not like fights with legal ;-)

**Comment by manisandro** [comment]
Can you attach your themes.json?

**Comment by mhaelsig** [comment]
[themesConfig.rwpl.json](https://github.com/qgis/qwc2-demo-app/files/12893104/themesConfig.rwpl.json)

Although the same behaviour can be seen with [qwc2-demo](http://qwc2.sourcepole.ch/  ??

**Comment by manisandro** [comment]
Are you using a current version of QWC2? I cannot reproduce it with master.

**Comment by mhaelsig** [comment]
Yes, I am using the current version.

Looking at the current version of http://qwc2.sourcepole.ch/ in the lower right corner 
![Screenshot_20231017_173707](https://github.com/qgis/qwc2-demo-app/assets/10079628/34cfbaa5-a66b-447b-91ef-baca3c7e1ac6)
I cannot find the OSM attribution, although given as parameter in themesConfig.json:

![Screenshot_20231017_174152](https://github.com/qgis/qwc2-demo-app/assets/10079628/b2aa0c29-800c-4daf-a7ae-4f291e9f9703)
Probably the themes attribution (here: 'Demo attribution') is hiding the background layer attribution. If I omit the themes attribution (in my application), there is also no OSM attribution:
![Screenshot_20231017_175604](https://github.com/qgis/qwc2-demo-app/assets/10079628/ebcd33c9-d8f3-49bf-b505-057db9100c91)
In which situation is the background layer attribution visible?

**Comment by manisandro** [comment]
The OSM attribution is there (although structured slightly differently):

![image](https://github.com/qgis/qwc2-demo-app/assets/1298852/1120e3ca-3174-46f8-be6b-71dfaf1c8597)

**Comment by mhaelsig** [comment]
Thank you for your quick response.
I don't need to know where and how to specify the background layer attribution, but I would like to know, where the qwc2 viewer places this attribution. Therefore, the two screenshots above. The issue is: the end user cannot see this background layer attribution. In the example above: 'OpenStreetMap contributors'.

**Comment by manisandro** [comment]
Sorry I read too fast and though that you were missing the attribution in the generated themes.json. In any event, `qwc2.sourcepole.ch` had `showThemeCopyrightOnly: true` in `config.json` (I've now set it to `false`), you probably have the same setting in your `config.json`.

**Comment by mhaelsig** [comment]
Thank you  😁 - this solved the issue.
