### ISSUE TITLE
From RasterExport to MapExport

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#490]
Hey, I am trying to get into the new plugins. At the moment I am comparing the old RasterExport plugin compared to the new MapExport plugin, which should replace the older one, right?

Within RasterExport no map scales are shown within the panel, altough the config for this is part of the documentation. 
Within MapExport it seems there is no way to disable the scale selection. Is it possible to get this optional with a boolean `allowScale` parameter or something similar?

In my use cases it doesn't make sense to let the user specify  the output scale which can differ from the scale within the map viewer, This will result in an different appearance of the exported image compared to the map viewer. The best thing would be to export the map with the current map extend as it is with the RasterExport plugin.

Thanks!

**Comment by manisandro** [comment]
Implemented in [1]: you can now pass `allowedScales: false` to disable the scale selection and force the current scale.

[1] https://github.com/qgis/qwc2/commit/8d2aad17b1f32cc461b563b12b35db185be04000
