### ISSUE TITLE
Reachability still displaying while routing menu is closed

### ISSUE THREAD

**Issue by VincentHeau** [qgis/qwc2-demo-app#493]
This bug occurs during the computation of a reachability request:

When the menu is open and the reachability polygons are displayed, closing the menu causes the polygons to reappear. This behavior does not occur when processing a simple routing request.
![image](https://github.com/qgis/qwc2-demo-app/assets/93425160/fd437eec-c047-4bf6-9226-e114c6f20c0f)

Thank you for your attention to this matter.
Vincent

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/82586e973b16643f5b974553264388349d112f8c
