### ISSUE TITLE
MapTip : possibility to config display time of MapTip and maximal Layers to diplay in MapTip

### ISSUE THREAD

**Issue by relume** [qgis/qwc2-demo-app#495]
We want to use in the MapTip an clickable URL to an external document (PDF) defined in the QGIS project Layer/Display preferences.

Actually MapTip boxes stay displayed as long the mouse cursor is not moved. In order to point the mouse cursor over the clickable URL displayed in the MapTip box, the mouse cursor has to be moved and thus the MapTip box is cleared/turned off.

In order the clickable URL can be invoked by moving the mouse cursor over the URL the displayed MapTip box has to stay turned on for some time, ideally by a configurable time or until the mouse cursor is moved over a feature without an MapTip. Actually as a very fast workaround we did comment out the in the plugin file `MapTip.jsx` function body of `clearMaptip()`:
```
    clearMaptip = () => {
        /* clearTimeout(this.timeoutId); */
        /* this.timeoutId = null; */
        /* this.props.removeLayer('maptipselection'); */
        /* this.setState({maptips: [], pos: null}); */
    };
```
With this workaround the displayed MapTip box stays displayed until the mouse cursor is moved to an map region (feature) where no MapTip is defined. Of course there would be a better and more versatile solution.

Furthermore it would be "desirable" if the displayed information in the MapTip box could be limited to one entry – stopping a the topmost layer where an MapTip configuration is found for the actual feature pointed by the mouse cursor. We did the following modifications as workarounds to the file `MapTip.jsx`:

```
    static defaultProps = {
        layerFeatureCount: 5,
        /**  adding property "mapTipsItemsMax" where "mapTipsItemsMax:= 0" does not limit, "mapTipsItemsMax:=1" limits the entries to 1 */
        mapTipsItemsMax: 0,
        maxHeight: "15em",
        maxWidth: "20em"
    };
```
In the function body `queryMapTip() ` we added the following condition:

```
    queryMapTip = () => {
    ...
        IdentifyUtils.sendRequest(request, (response) => {
            const mapTips = [];
            /* let mapTipsItemsMax = 1; */
            let mapTipsItemsIndex = 1;
            if (response) {
                const result = IdentifyUtils.parseXmlResponse(response, this.props.map.projection);
                const features = [];
                for (const layerName of request.params.layers.split(",")) {
                    for (const feature of result[layerName] || []) {
                        /**  added conditions ((this.props.mapTipsItemsMax == 0) || (mapTipsItemsIndex <= this.props.mapTipsItemsMax))) */
                        if ((feature.properties.maptip) && ((this.props.mapTipsItemsMax == 0) || (mapTipsItemsIndex <= this.props.mapTipsItemsMax))) {
                            features.push(feature);
                            mapTips.push(feature.properties.maptip);
                            mapTipsItemsIndex = mapTipsItemsIndex + 1;
                        }
                    }
                }
         ...
}
```

**Comment by manisandro** [comment]
I've committed some fixes to the MapTip so that moving the cursor inside the bubble is now possible.

Regarding 

> Furthermore it would be "desirable" if the displayed information in the MapTip box could be limited to one entry – stopping a the topmost layer where an MapTip configuration is found for the actual feature pointed by the mouse cursor.

I'm not sure this would yield a reproducible behaviour, since it will basically be a race which layer delivers the result first.

**Comment by relume** [comment]
- many thanks for the committed fixes. MapTip is now more stable and moving the cursor inside the MapTip bubble is now fine.
- Yes I can understand your concerns about the limitation to the topmost layer. In my app all "relevant" layers have the same attribute data basis (layer duplicates), but every layer shows different attribute information and "thus" for every layer we want to show the same feature info in the MapTip with the clickable Link/URL to an external pdf (for each feature the same (like address, lot, object-id) on all "relevant" layers).
