### ISSUE TITLE
qgis searchProvider | missing parts and/or bugs?

### ISSUE THREAD

**Issue by relume** [qgis/qwc2-demo-app#496]
We configured our qwc2 standalone app (adopted from qwc2-demo-app) in the `themesConfig.json` file analogous as it is documented in the QWC2 documenation for the `qgis` searchProvider:

```
...
"searchProviders":[
 {
	"provider": "qgis",
	"params": {
		"expression": {
			"myLayer": "\"fid\" = '$TEXT$'"
		},
		"title": "<search name>"
	}
 }
],
...
```

The appropriate script code for the `qgis` searchProvider we found in the file `js/SearchProviders.js`

We found the following issues with this script code:

1. for WSM `REQUEST: 'GetFeatureInfo'` parameter the additional parameter `QUERY_LAYERS` is mandatory. As we got an ERROR 404 for QWC2 search-requests without the parameter `QUERY_LAYERS` we added this parameter to the code.
2. the SearchProviders.js code (`IdentifyUtils.parseResponse(response.data, null, 'text/xml', null, searchParams.mapcrs)`) for the `qgis` searchProvider expects search data results in the `text/xml` format. As the search query returned the result in text/plain format and throw a "xml malformed" error we added the query URL parameter `INFO_FORMAT: 'text/xml'`
3. In the browser inspector we can see that with those additions (see below) 1) the search query is ok (reponse code 200) and 2) the resulting search data contains valid xml data for the found feature. But no search results are shown in the search box neither other information is presented nor the specific feature is highlighted. Thus we not know what we may have missed in some config file or if there is an bug?

Our code additions in the file `js/SearchProviders.js`:

```
class QgisSearch {

    static search(text, searchParams, callback, axios) {
        const filter = {...searchParams.cfgParams.expression};
        const values = {TEXT: text};
        const bbox = CoordinatesUtils.reprojectBbox(searchParams.theme.bbox.bounds, searchParams.theme.bbox.crs, searchParams.theme.mapCrs);
        const params = {
            SERVICE: 'WMS',
            VERSION: searchParams.theme.version,
            REQUEST: 'GetFeatureInfo',
/** addition : INFO_FORMAT: 'text/xml' */
            INFO_FORMAT: 'text/xml',
            CRS: searchParams.theme.mapCrs,
            BBOX: bbox.join(","),
            WIDTH: 100,
            HEIGHT: 100,
            LAYERS: [],
/** addition : QUERY_LAYERS: [] */
            QUERY_LAYERS: [],
            FILTER: [],
            WITH_MAPTIP: true,
            WITH_GEOMETRY: true
        };
        Object.keys(filter).forEach(layer => {
            Object.entries(values).forEach(([key, value]) => {
                filter[layer] = filter[layer].replace(`$${key}$`, value.replace("'", "\\'"));
            });
            params.LAYERS.push(layer);
/** addition : params.QUERY_LAYERS.push(layer) */
            params.QUERY_LAYERS.push(layer);
            params.FILTER.push(layer + ":" + filter[layer]);
        });
...

```

Any hint would be very appreciated :-)

P.S. In the QWC2 documentation for the `qgis` searchProvider the examples for the configuration `expression` parameter does mention the `ILIKE` filter operator together with the wildcard character `%`. Unfortunately `ILIKE` is not supported if geopackage is used for layers, thus the `LIKE` filter operator has to be used. Furthermore the wildcard character `%` (`%$TEXT$%` or `$TEXT$%`) can not be passed in the search query URL as the QGIS server reports a Security-Error about allowed and not allowed keywords and special characters.

**Comment by manisandro** [comment]
The issues regarding QUERY_LAYERS and FORMAT have since already been addressed. Regading the highlight, does the identify response contain the feature geometry? Regarding `%`, this worked correctly in my case, which qgis server version do you have?

**Comment by relume** [comment]
- we are using `QGIS Server 3.33.0-Master nightly build (Unbuntu Lunar)`.
- we are using, have adobted from QWC2 version available on 16 october 2023, but I have now seen that `js/SearchProviders.js` has been changed yesterday.
- `%` we get this QGIS Server documented ServiceExceptionReport error:  https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#filter
- yes we get correct search results in the xml response with feature geometry (from Browser Inspector as response to our search value in the QWC2 app search box):

```
<?xml version="1.0" encoding="UTF-8"?>
<GetFeatureInfoResponse>
 <BoundingBox CRS="EPSG:2056" minx="2682870.58" maxx="2682904.182" miny="1263635.516" maxy="1263663.516"/>
 <Layer name="myLayer">
  <Feature id="119">
   <Attribute name="fid" value="119"/>
...  
   <BoundingBox CRS="EPSG:2056" minx="2682870.58" maxx="2682904.182" miny="1263635.516" maxy="1263663.516"/>
   <Attribute name="geometry" value="MultiPolygon (((2682898.126 1263648.296, 2682889.893 1263644.091, 2682890.677 1263642.557, 2682876.89 1263635.516, 2682874.665 1263639.892, 2682874.076 1263641.051, 2682870.58 1263647.92299999, 2682883.975 1263654.764, 2682883.284 1263656.118, 2682897.7 1263663.516, 2682903.918 1263651.813, 2682904.182 1263651.389, 2682898.126 1263648.296)))" type="derived"/>
  </Feature>
 </Layer>
</GetFeatureInfoResponse>
```

**Comment by relume** [comment]
- I updated now to the latest `QGIS Server 3.35.0-Master nightly build (Unbuntu Lunar)`. The issue with the wildcard `%` still persists.

**Comment by relume** [comment]
- I got this morning (2023.11.02) new actual copy from QWC2 qwc2-demo-app and I can confirm that `qgis` SearchProvider now works with the actual `js/SearchProviders.js` file.
- In particular the filter expressions with the wildcard `%` do now work – are accepted by QGIS Server WMS service – as they are now correctly (pre-) encoded to `%25`.
- I found that the `LIKE` filter operator does sometime work as `ILIKE` but this only the case on the first layer in a multi-layer filter expression. But multi-layer filter expression with `LIKE` does work on all layers defined in the filter expression, if the search entry/text is entred correctly case sensitive. As mentioned above `ILIKE` is accepted by the QGIS Server WMS service but does not return any feature results when the layer basis is geopackage. Unfortunately a filter expression as workaround for case insenstive search with `LIKE` as `LOWER("fid") LIKE LOWER('$TEXT$')` is not working, as the QGIS Server WMS service does not allow the word `LOWER`.
- Finally in this morning version of the file `js/SearchProviders.js` I introduced the possibilty to pass a "FEATURE_COUNT" parameter value (featureCount)  from the `themesConfig.json` defined in the `searchProviders` block:

```
{
	"provider": "qgis",
	"params": {
	"expression": {
	"myLayer1": "\"address\" LIKE '%$TEXT$%'",
	"myLayer2": "\"address\" LIKE '%$TEXT$%'"
	},
	"title": "Adressen",
	"featureCount":25
}
```
with this addition in `js/SearchProviders.js`:

```
const params = {
...
            FEATURE_COUNT: searchParams.cfgParams.featureCount
...
```
but today in the meantime the file `js/SearchProviders.js` has been also modified by the owner too :-) with : 

```
...
    feature_count: 100,
...

```

The main advantage to have `featureCount` definded in the `themesConfig.json` is the possibility to define multiple `qgis` SearchProvider blocks and each block can have defined a block specific feature_count value.

**Comment by manisandro** [comment]
Good idea regarding featureCount, I've implemented it.

So as I understand it all QWC2-side issues you encountered are herewith solved?

**Comment by relume** [comment]
- yes QWC2-side search issues are solved - many thanks.
- many thanks also having implemented and documented the `featureCount` parameter.
- many thanks also having implemented and documented the `resultTitle` parameter, appreciating very much - it was my next feature in my "wish list" :-)
- also on my "whish list" would be the possibility to sort returned feature items by a given/defined feature attribute.
- To circumvent the filter case sensitivity limitation with `LIKE` I have "enhanced" the filter `key` replacement function in the files `js/SearchProviders.js` and `qwc2/plugins/FeatureSearch.jsx` with the an optional `key` prefix in order to upper or lower case the corresponding entry value (of course my code addition could be writen more elegant and versatile):

```
...
        Object.keys(filter).forEach(layer => {
            Object.entries(values).forEach(([key, value]) => {
            	filter[layer] = filter[layer].replace(`$${key}#LOW$`, (value.toLowerCase()).replace("'", "\\'"));
                filter[layer] = filter[layer].replace(`$${key}#UPP$`, (value.toUpperCase()).replace("'", "\\'"));
                filter[layer] = filter[layer].replace(`$${key}$`, value.replace("'", "\\'"));
            });
            params.LAYERS.push(layer);
            params.FILTER.push(layer + ":" + filter[layer]);
        });
...
```
thus in the `searchProviders` configuration block in the `themesConfig.json` file the filter value syntax can be configured as this:

```
"provider": "qgis",
"params": {
	"expression": {
	"myLayer1": "\"myfield1\" LIKE '$TEXT$%'",
	"myLayer2": "\"myfield2\" LIKE '$TEXT#UPP$%'",
	"myLayer3": "\"myfield3\" LIKE '$TEXT$LOW%'"
	},
	"title": "Objekt-ID",
	"featureCount":10,
	"resultTitle": "{address}"
}
```
May be this helps also in a non `LIKE` context. But in a `LIKE` it presumes on the QGIS-Server side, that the attribute to be filtered has the same lower- or uppercase notation (a static calculated field, as it seems that virtual fields are served by QGIS-Server but are not filterable - a virtual field definied in the filter does not return any result).
