### ISSUE TITLE
Background layers: No active at start

### ISSUE THREAD

**Issue by Ssalsa** [qgis/qwc2-demo-app#497]
Using the latest build i always get "No background" as default background when opening the map.
I have a couple of background layers that work fine and i can switch between them but setting "visibility": true seems to do nothing.

Same issue using the example map packaged with the app.

**Comment by manisandro** [comment]
Please post your themesConfig.json

**Comment by sweco-seiawc** [comment]
I get this behaviour even with no settings changed after installing as a standard viewer as described in https://qwc-services.github.io/QuickStart/#running-qwc2-as-a-standalone-viewer
So themesconfig.json is same as https://github.com/qgis/qwc2-demo-app/blob/master/themesConfig.json

**Comment by manisandro** [comment]
This was indeed a regression, fixed in https://github.com/qgis/qwc2/commit/31d5d956ac0d88d4982b4b6e2d1eac3c1247dd77. Thanks for reporting!
