### ISSUE TITLE
Changing a theme should not change the map extent

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#5]
In the old QWC a change of theme would retain the current map extent. In QWC2, if one changes the theme, the map extent is changed to the full view of the new theme.

I think the old behaviour of QWC was more intuitive, because often one wants to see the same map extent in different themes.

**Comment by andreasneumann** [comment]
Perhaps, it would have to be checked if the old and new theme geographically overlap, because if the different projects don't geographically overlap, the current behaviour of QWC2 would be fine.

**Comment by tudorbarascu** [comment]
Does it make sense to have this option configurable somehow?

**Comment by manisandro** [comment]
If the map scales change between themes, it won't be possible to preserve the exact same extent. So a possible behaviour would be to preserve the map extent only if the full extent of the previous and next themes intersect and only if the map scales are the same.

**Comment by andreasneumann** [comment]
sounds good to me.

In my scenario (Katnon Zug) I would have the same extent and scales for almost all topics.

**Comment by manisandro** [comment]
Implemented in 994390a.
