### ISSUE TITLE
Interfacing with URL .../?l=xxx does not work 

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#500]
Hi,
after updating from "2023.10.12-master" to "2023.11.08-master" it seems to be that interfacing with URL (../?l=xxx) does not work anymore. How can I help to identify the base issue?

**Comment by manisandro** [comment]
Thanks, this happened due to the incorrect assumption that if `l` is provided, also a valid `t` is provided, but I suppose it is a valid use case to just provide `l` and rely on the default theme configuration.

Fixed in https://github.com/qgis/qwc2/commit/b120474b763f18ebbc5dcd69b65e5149a72e5729.

**Comment by mhaelsig** [comment]
Hi,
thank you - now it works as expected.

Kind regards
Michael Hälsig

-- 
Dr. Michael Hälsig
Diefenbachstr. 9
81479 München

Tel.: +49 89 79199563
Mob.:+49 171 333 7558
Am Montag, 13. November 2023, 11:24:11 CET schrieb Sandro Mani:
