### ISSUE TITLE
defining printLayer using wms resource string does not work

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#502]
I am trying to get rid of the problem, that getPrint with qgis server is pairing the size of labels within the map to the print resolution. Many users struggles with this and I only found different workarounds but no reason why qgis server is doing this.
So the workaround for printing with the qwc2 is to specify a printLayer for the respective backgroundLayer for each theme. While placing and specifing a print layer within the qgis file of a qgis project works correctly, I didn't get it to work using a resource string like mentioned here: https://qwc-services.github.io/topics/Printing/#configuring-print-background-layers.

In my specific case I configured the printLayer as:
```
{
  "name": "stadtplan",
  "printlayer": "wms:https://map.jena.de/mapproxy/wms#Stadtplan300",
  "visibility": true
},
```
The layer `Stadtplan300` is part of my mapproxy, which can be checked here:
https://map.jena.de/mapproxy/wms?VERSION=1.3.0&SERVICE=WMS&REQUEST=GetCapabilities

So is the used syntax with the `#` between the base url and the layer name the right one or is there something else I am missing here? Thanks for any hints!

**Comment by manisandro** [comment]
The syntax looks correct.

Are you using a current version of qwc2?

Do you see any messages in the browser console?

Can you show the POST request body?

**Comment by danceb** [comment]
yes, I have checked out [b120474](https://github.com/qgis/qwc2/commit/b120474b763f18ebbc5dcd69b65e5149a72e5729) in my dev environment. I am testing on the qwc2 app without the print service.
No, there aren't any messages in the browser console related to to print process.
The body of the POST request should be this, right? 
```
"TEMPLATE": "A4+Hochformat",
"map0:scale": "500",
"map0:rotation": "0",
"KARTENTITEL": "",
"csrf_token": "",
"map0:extent": "681885.8,5644961.3,681968.2,5645094.7",
"SERVICE": "WMS",
"VERSION": "1.3.0",
"REQUEST": "GetPrint",
"FORMAT": "pdf",
"TRANSPARENT": "true",
"SRS": "EPSG:25832",
"LAYERS": "EXTERNAL_WMS:A",
"OPACITIES": "255",
"COLORS": "",
"A:url": "https://map.jena.de/mapproxy/wms",
"A:layers": "Stadtplan",
"A:format": "image/png",
"A:crs": "EPSG:25832",
"A:styles": "",
"A:dpiMode": "7",
"A:contextualWMSLegend": "0",
"CONTENT_DISPOSITION": "attachment",
"map0:LAYERS": "EXTERNAL_WMS:A",
"map0:HIGHLIGHT_GEOM": "",
"map0:HIGHLIGHT_SYMBOL": "",
"map0:HIGHLIGHT_LABELSTRING": "",
"map0:HIGHLIGHT_LABELCOLOR": "",
"map0:HIGHLIGHT_LABELBUFFERCOLOR": "",
"map0:HIGHLIGHT_LABELBUFFERSIZE": "",
"map0:HIGHLIGHT_LABELSIZE": "",
"map0:HIGHLIGHT_LABEL_DISTANCE": "",
"DPI": "300"
```
I think `"A:layers": "Stadtplan",` should be `"A:layers": "Stadtplan300",` in my case, but it doesn't ...

**Comment by danceb** [comment]
🤦🤦 I am so sorry for wasting your time ...

Of course the parameter is `printLayer` with capital "L" and not `printlayer` as I wrote it.

No more words, works like a charm.
