### ISSUE TITLE
Wrong save format using inlinePrintOutput on chromium based browsers 

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#504]
Using the inlinePrintOutput function to display the Atlas as a .pdf in the iframe works well, but there's an issue when attempting to save it using Edge/Chrome. It prompts to save it as an xml/json instead of a .pdf.

This functionality performs well on Firefox. Eliminating the targeting to the iframe in the form and opening it in a new tab displays the correct .pdf format when saving. Hence, it doesn't seem to be a content-type problem.

What might be a viable solution to this issue? Perhaps returning the Axios result used for non-inlinePrintOutput to the iframe instead of using the form's target option could be a potential solution. I can look into it eventually

Thank you in advance.
Best regards,
Clément.

**Comment by manisandro** [comment]
This is an annoying (and actually pretty broken) behavior of some browsers, which re-download the PDF when clicking the save button, but they the URL as GET when pressing the save button, meaning the request parameters submitted via POST are lost and hence the QGIS Server will return an invalid request XML. Happy to have any solutions for this...

**Comment by manisandro** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=69677 and https://bugs.chromium.org/p/chromium/issues/detail?id=158957

**Comment by cazitouni** [comment]
@manisandro, I've found something, [ here ](https://github.com/cazitouni/qwc2/blob/master/plugins/Print.jsx), [commit on my branch](https://github.com/qgis/qwc2/compare/master...cazitouni:qwc2:master).
It's working good for downloading the file, only problem is that the file gets a random name, not the project one's.

I don't know if it looks like a good solution but it seems to works on my machine.
I can look more into it.

let me know you opinion, 

Kind regards,
Clément,

**Comment by manisandro** [comment]
Interesting! In my view this solution is already much better than the currently broken behaviour. Happy to accept a PR

**Comment by cazitouni** [comment]
Nice, I'll look a bit more into it tommorow for file name and I make the PR.

I'll let you know.

Thanks.
