### ISSUE TITLE
Printing fails when a layer created by qwc2 is added

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#505]
With the Drawing Tool I created a temporary layer (Redlining.json), which I attach, and wanted to print the resulting map. Print fails with

`<?xml` version="1.0" `encoding="UTF-8"?>`
`<ServiceExceptionReport` version="1.3.0" `xmlns="http://www.opengis.net/ogc">`
`<ServiceException code="Invalid Parameter">HIGHLIGHT_GEOM ('POLYGON ((1273270.06 6131189.07, ...`

Test case: add the attached file with 'Import Layer' to the qwc2 Demo Server <http://qwc2.sourcepole.ch/>. The circles are in the area of Munich, therefore the map should be focused on Munich and display some circles. Then call 'Print'. 

Use Case: People create their own annotations on the map and should be able to print the result. 

[Redlining.json](https://github.com/qgis/qwc2-demo-app/files/13384388/Redlining.json)

**Comment by manisandro** [comment]
This typically happens when a geometry is invalid (self intersections, degenerate lines/polygons, etc). Admittedly it would be nice to show a better error message, resp ideally even report the invalid geometry.

**Comment by mhaelsig** [comment]
Thank you for your quick response!

Apparently, the issue lies not in the printing itself, but rather in the 
geometry. This simple geometry (5 circles) had been generated with the Drawing 
Tool inside the QWC2 Client. Therefore: is there an issue in the geometry 
generator of the Drawing Tool?  

But: the Conformity Test <https://www.itb.ec.europa.eu/json/geojson> shows no 
errors in 'Redlining.json'. The only discrepancy I can see: the coordinates of 
these circles are given in EPGS 3857, and the 'center' coordinates inside 
'circleParams' are given in EPSG 25832. 

The use case is: a user adds with the Drawing Tool some circles etc. and 
prints the resulting map with the QWC2 Print function.
