### ISSUE TITLE
Force refresh after update

### ISSUE THREAD

**Issue by Patatekes** [qgis/qwc2-demo-app#507]
Hello,

Not sure if this is an issue. But i can i imagine more people encounter the same problem.

I regularly update my application, adding new thems/layers/etc, but users dont get to see these new features, since it is saved in their cache.
I've been asking people to delete their cache, but this doesnt really satisfy my need.

It would be beneficial if the cache could automatically be cleared after a new update, or set it to refresh everything after say one week. I've attempted implementing this in the index.html, but unfortunately, I haven't been successful.

Appreciate your assistance in advance.

**Comment by manisandro** [comment]
If you are using a standalone viewer, you need to configure your webserver to add no-cache headers. If you are using qwc-services or qwc-docker, no-cache headers should already be added to the responses.
