### ISSUE TITLE
Background Switcher is not moved while docking a window to bottom

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#512]
If a resizable window like the time manager is docked to to bottom the map buttons (zoom etc.) are moved upwards. Except the background switcher button, which stays behind the docked windows.

**Comment by danceb** [comment]
Edit: Also the Map Copyright should move upwards, too.

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/a196ae6e0bafe6564276667676fcc0d3cacc24f2
