### ISSUE TITLE
Printing and MapExport does not work anymore

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#513]
Since https://github.com/qgis/qwc2/commit/4bddd5ff2aadd48bbddd6fea76ddeda7704283ca Printing and MapExport does not work anymore as I am getting the error
```
layer.params.STYLES is undefined
```

**Comment by manisandro** [comment]
Thanks, should be fixed in https://github.com/qgis/qwc2/commit/c2da7a41364f02f61203ebc23c65b2b288c8bff2
