### ISSUE TITLE
release branch / tag

### ISSUE THREAD

**Issue by davidebz** [qgis/qwc2-demo-app#517]
Hi,

I like to use qwc2-demo-app for creating a stable customized version. Which branch should I use? 2023-lts? Or simply master?

Thanks in advance

Davide

**Comment by manisandro** [comment]
2023-lts is a bugfix only branch, master is the development branch, and shortly there will be a 2024-lts branch.

If waiting up to a year for new features to become available is ok, the lts branch makes sense, if you want them quicker master makes sense.

I'd say while developing (possibly with the need to contribute changes) master can make sense, and as soon as you've reached stability with your custom version, switching to lts makes sense.
