### ISSUE TITLE
Location of 'qgis_mapserv.fcgi' in qwc-docker

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#518]
Hi All,

This is not an issue but I don't know who else to ask. 

I need to put the correct 'url' in 'themesConfig.json' which points to the 'qgis_server.fcgi' executable. I've only ever set this up as a 'Standalone Viewer' in the past using 'yarn' with Apache2. In the qwc-docker version qgis-server is installed in a container 'qwc-docker-qwc-qgis-server' as a plugin. Can you advise how the url would look. e.g. under standalone viewer it looks like this:-

"url": "http://qgisserver/cgi-bin/qgis_mapserv.fcgi?MAP=/home/qgis/projects/myqgisproject.qgs",

which could be tested thus:-

http://qgisserver/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

Many thanks Guys...

**Comment by manisandro** [comment]
That would be 

    http://hostname:port/ows/<projectname>?SERVICE=WMS&REQUEST=...

Look at the requests in the network inspector of a qwc-docker hosted viewer to see some examples.

**Comment by shapley** [comment]
Fantastic...
