### ISSUE TITLE
GetFeatureInfo requests are not compliant

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2-demo-app#52]
I am trying to use qwc2-demo-app together with QGIS Server 2.99/master, and WMS GetFeatureInfo queries don't work. The problem is that qwc2-demo-app sends "ill-formed" GetFeatureInfo requests. QGIS Server 2.18 accepted them, but QGIS Server 2.99/master (in its current form) does not accept them.

The issue is tha GetFeatureInfo requests is that the set of layers in `query_layers` may not be a subset of the set of layers in `layers`. This is for example a GFI request sent by the qwc2.sourcepole.ch application:

```
http://qwc2.sourcepole.ch/wms/wolfsburg/qwc2_demo?service=WMS&version=1.1.1&request=GetFeatureInfo&srs=EPSG:3857&info_format=text%2Fxml&x=51&y=51&exceptions=application%2Fjson&id=Wolfsburg1508484111470&layers=Wolfsburg&query_layers=Beschriftung,Abfallwirtschaft,Bushaltestellen,Hilfsorganisationen&height=101&width=101&bbox=1203546.3855321205,6872708.797678056,1208890.968865454,6878053.38101139&feature_count=10&FI_POINT_TOLERANCE=16&FI_LINE_TOLERANCE=8&FI_POLYGON_TOLERANCE=4
```

In this GFI request `layers` is

```
layers=Wolfsburg
```

while `query_layers` is

```
query_layers=Beschriftung,Abfallwirtschaft,Bushaltestellen,Hilfsorganisationen
```

Although QGIS Server may be changed to be more lenient (while still retaining its OGC conformity), and accept such "ill-formed" requests, I think qwc2-demo-app (or qwc2 or MapStore2) should be fixed to issue "well-formed" requests.

**Comment by manisandro** [comment]
Thanks for reporting! So to get it right, should `layers` be equal to `query_layers`?
FWIW, the request is constructed here: https://github.com/sourcepole/MapStore2/blob/46f2b38cf88b3d84e5916a5ee9dc6fa1ecce0e66/web/client/utils/MapInfoUtils.js#L162

**Comment by elemoine** [comment]
`query_layers` should be the same set of a subset of `layers`.

**Comment by manisandro** [comment]
So if you change [1] to

    layers: queryLayers,

does it work?

[1] https://github.com/sourcepole/MapStore2/blob/46f2b38cf88b3d84e5916a5ee9dc6fa1ecce0e66/web/client/utils/MapInfoUtils.js#L164

**Comment by elemoine** [comment]
I'll try, and I am confident it'll work.

**Comment by manisandro** [comment]
@elemoine Any news on this?

**Comment by elemoine** [comment]
> @elemoine Any news on this?

Not yet. I've been busy on other stuff. I'll test the `layers: queryLayers` change you've proposed and I'll report back.

**Comment by elemoine** [comment]
It works.

I have other issues related to GFI. I have layer names with spaces, and spaces are replaced with `+`'s in the query (e.g. `layers=Sous+collines+ou+avenues&query_layers=Sous+collines+ou+avenues`). Do you have any idea where that may come from?

**Comment by manisandro** [comment]
Thanks for testing!
As for the escaping, I guess it is done by axios itself. The request in `buildIdentifyWMSRequest` is ultimately processed by `getFeatureInfo` [1] which then passes the request params to axios.

[1] https://github.com/sourcepole/MapStore2/blob/qwc2/web/client/actions/mapInfo.js#L95

**Comment by elemoine** [comment]
Why in hell axios changes spaces to `+`'s? Makes no sense to me.

**Comment by manisandro** [comment]
URLs cannot contain spaces. URL encoding normally replaces a space with a plus (+) sign or with %20.

**Comment by elemoine** [comment]
I know that URLs cannot contain spaces. And I thought spaces should always be replaced by %20.

This is the code in axios: https://github.com/axios/axios/blob/b8f6f5049cf3da8126a184b6b270316402b5b374/lib/helpers/buildURL.js#L11.

**Comment by elemoine** [comment]
Going back to `buildIdentifyWMSRequest` are you taking care of fixing it in MapStore2?

**Comment by manisandro** [comment]
Fixed in https://github.com/sourcepole/MapStore2/commit/a814e652f34e1352b17af4ab21e499134f181ddf

**Comment by elemoine** [comment]
Thanks
