### ISSUE TITLE
/data/qwc_demo.qgs

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#520]
Hi,

I'm testing a 'qwc-docker' setup (which is working) but produces an empty map view but won't display the data from 'qwc_demo.qgs'. I've set:-

sudo chown 8983:8983 volumes/solr/data

but get the error

Error:

08:45:07 CRITICAL Server[72]: Error when loading project file '/data/qwc_demo.qgs': Unable to open /data/qwc_demo.qgs                                                     qwc-docker-qwc-qgis-server-1              | 08:45:07 WARNING Server[72]: <?xml version="1.0" encoding="UTF-8"?>                                                                                                       qwc-docker-qwc-qgis-server-1              | <ServerException>Project file error. For OWS services: please provide a SERVICE and a MAP parameter pointing to a valid QGIS project file</ServerException>

**Comment by shapley** [comment]
Just need to check that the 'themesConfig.json' which isn't being loaded on 'demo' start at present only 'qwc_demo.qgs'. Is the 'themesConfig.json' meant to be located in _'qwc-docker/volumes/config-in/default/'_?

**Comment by shapley** [comment]
![logimage](https://github.com/qgis/qwc2-demo-app/assets/7022885/becc5057-fe00-4e2d-b6b9-266a9dbb7894)

**Comment by shapley** [comment]
![logimage2](https://github.com/qgis/qwc2-demo-app/assets/7022885/a6cfec8e-24ee-4911-a789-3529f4b6c229)

**Comment by manisandro** [comment]
This looks like a configuration issue, however please note that the it is more appropriate to ask support questions on the mailing list [1] or use one of the available commercial support options [2]

[1] https://lists.osgeo.org/mailman/listinfo/qgis-qwc2
[2] https://qwc-services.github.io/master/#support
