### ISSUE TITLE
NO GEOMETRY in geojson and all other export from Identify 

### ISSUE THREAD

**Issue by rsrg-zwiama** [qgis/qwc2-demo-app#522]
In the current version of qwc2 the geometry in all exports is missing. I think it's because of changes made in this commits:
https://github.com/qgis/qwc2/commit/d931a409c3825975df9859f637144b50191cebfe
or this one:
https://github.com/qgis/qwc2/commit/ac31b789fd3b8e69374877eb6b5cefc370576e8b

It looks like the `props.exportGeometry` is undefined. I tried by explicit set `"exportGeometry": true` in config.json is still undefined.

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/afc8426dae6ad5a83d7970c94f92b097c959a125

**Comment by rsrg-zwiama** [comment]
thank you!
