### ISSUE TITLE
Not able to create/show categorized layer?

### ISSUE THREAD

**Issue by 9ls1** [qgis/qwc2-demo-app#524]
I'm using qwc-docker generating themes from qwc-admin-gui.
![image](https://github.com/qgis/qwc2-demo-app/assets/10632163/25347387-a8df-4810-8d12-c749c566ddc9)

Despite following the instructions from [Split categorized layers](https://qwc-services.github.io/master/configuration/ThemesConfiguration/#split-categorized-layers) , the layer is not splitted (categorized) in QWC2 as it is in QGIS.

QGIS
![image](https://github.com/qgis/qwc2-demo-app/assets/10632163/4ff793ad-6403-4677-a4c8-a7dc2cc58468)

QWC2
![image](https://github.com/qgis/qwc2-demo-app/assets/10632163/5320d1d2-c55d-486d-9c39-bff6ae8e2258)

split_categorized.py is downloaded and saved in volumes/qgis-server-plugins/split_categorized
![image](https://github.com/qgis/qwc2-demo-app/assets/10632163/ef481e58-8a96-4ca0-8ed5-703aa50845a8)

qwc-qgis-server container is configured:

>   qwc-qgis-server:
>     image: sourcepole/qwc-qgis-server:3.28-plugins
>     # ports:
>     #   - "127.0.0.1:8001:80"
>     volumes:
>       - ./volumes/qgs-resources:/data:ro
>       - ./pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
>       - ./volumes/qgis-server-plugins/split_categorized:/usr/share/qgis/python/plugins/split_categorized:ro

The layer has a variable convert_categorized_layer true.
![image](https://github.com/qgis/qwc2-demo-app/assets/10632163/7738344b-f798-4297-8dc2-181353778bd1)

Then I successfully generate themes configuration.
However, the layer is not splitted (see images above).

Any idea where I go wrong?

**Comment by manisandro** [comment]
If you enable INFO logging in qgis server:
```
  qwc-qgis-server:
    environment:
      QGIS_SERVER_LOG_LEVEL: 0
```
do you see in the `qwc-qgis-server-log` the following log entry?

    qwc-qgis-server_1              | 09:05:19 INFO Server[73]: Server plugin split_categorized loaded!

**Comment by 9ls1** [comment]
@manisandro Thanks, I enabled INFO-logging, but I'm not able to find/see qwc-qgis-server-log? However, I have located /var/lib/docker/containers and had a look in the qwc-qgis-server container (xxxx-json.log, finding the contianer id xxxx with `sudo docker ps`), and can't find any string containing 'split'. Not a good sign, I assume.

**Comment by 9ls1** [comment]
@manisandro Thanks for the command making log-retrieving much easier. However, no sign of split in the log 
[log_qgis_server_20240207_01.txt](https://github.com/qgis/qwc2-demo-app/files/14193943/log_qgis_server_20240207_01.txt)

**Comment by 9ls1** [comment]
@manisandro Yes, I have tried several things like restarting docker, stopping docker and starting docker, recreating the server container, but without any luck in seeing "Server plugin split_categorized loaded!" nor splitted layers in QWC2. The split_categorized.py is placed in /xxx/xxx/qwc-docker**/volumes/qgis-server-plugins/split_categorized** corresponding to the instructions:
...
volumes:
- ./volumes/qgis-server-plugins/split_categorized:/usr/share/qgis/python/plugins/split_categorized:ro
...
Not sure how else to mount the plugin.

**Comment by manisandro** [comment]
Last idea would be to `docker-compose exec qwc-qgis-server bash` and then check within the docker container that the plugin files are indeed there as expected and readable.

**Comment by jonathanrizzi** [comment]
Hello,

I am in the same situation. Plugin is installed, with all updated to the latest version as of July 15. The plugin is visible and readable from inside docker but it seems that is not loaded from the logfile. What addictional control can be done to find the issue?

Thank you!

**Comment by manisandro** [comment]
If you enter the container (`docker compose exec qwc-qgis-server bash`), can you read the plugin file? I.e.

    cat /usr/share/qgis/python/plugins/split_categorized/split_categorized.py

**Comment by jonathanrizzi** [comment]
Hello,

Yes, I can read the file doing that command. The .qgs file with categories and the shapefile are copied into the directory "volumes/qgs-resources/scan". I tried also in the directory "volumes/config-in/default/qgis_projects" but in both the layer is not split.

Thank you.

**Comment by manisandro** [comment]
(The location `volumes/config-in/default/qgis_projects` is obsolete and should not be used anymore.)

Can you post the qgis server container logs?

Have you set `convert_categorized_layer=true` in the project variables?

**Comment by jonathanrizzi** [comment]
Hello.

Here the log. The variable is set.

[log_20240717_01.txt](https://github.com/user-attachments/files/16262964/log_20240717_01.txt)

Thank you.

**Comment by manisandro** [comment]
As the ClearCapabilities plugin is loaded

    qwc-docker-qwc-qgis-server-1  | 10:43:05 INFO Server[72]: Server plugin ClearCapabilities loaded!

the only other thing I can think of at distance is to compare the structure of the clear_capabilities plugin folder with the one of the split_categorized and see if there is any difference which stands out.

**Comment by jonathanrizzi** [comment]
Hi,

I noticed that and I had compared the files. It is exactly the same structure and files (except the name of the main py file), and same permissions. In the file system they are in different folder, but in docker they appear under same directory ans two separate folders, together with some other plugins directories. However no trace of the split categorized plugin in the log.

Thank you again.

**Comment by manisandro** [comment]
Short of setting up a custom qgis server container which runs as root and debugging the qgis server startup with `strace` I'm afraid I don't have any additional ideas at distance.

**Comment by manisandro** [comment]
I've managed to track this down on an affected system: it is a conflict between the split_categorized and the clear_capabilities plugins. I'll investigate further.

**Comment by jonathanrizzi** [comment]
Hello, thanks for the update. Looking forward for further information.

**Comment by manisandro** [comment]
This should be fixed by simply adjusting the plugin execution priority [1]. Closing, feel free to reopen if issues persist.

[1] https://github.com/qwc-services/qwc-qgis-server-plugins/commit/125ae32bd2011ff96e3b4cf4ef90dcaf68d53af5

**Comment by jonathanrizzi** [comment]
Hello,

We downloaded the newer version of the pluging, run everything again, and we see the menu like in the figure for the layer who should have the legend splitted, but nothing change when switching between the two options.

Is that correct? Are we doing something wrong?

Thank you.

![image](https://github.com/user-attachments/assets/2a174ace-e36c-46d9-a4d1-c80b23f3eff6)

**Comment by manisandro** [comment]
This use-case (i.e. switching to a categorized style) is currently not implemented.
