### ISSUE TITLE
Change width of Layer Tree

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#530]
Is it possible to change the default width of the Layer tree? Probably I am blind...

In fact it is possible by moving the left boundary of the layer tree with the mouse. But casual users do not see this possibility. 

Background: some layers have long names, starting with the same pattern, which cannot be shortened. So it seems to be that there are layers with identical names.

**Comment by manisandro** [comment]
Hi

Yes that would be the `width` prop [1]

[1] https://qwc-services.github.io/master/references/qwc2_plugins/#layertree

**Comment by mhaelsig** [comment]
thanks - this was my hope that there is a screw...

Viele Grüße
Michael Hälsig
