### ISSUE TITLE
edithing themesconfig.json

### ISSUE THREAD

**Issue by Mrpolit** [qgis/qwc2-demo-app#532]
Hi,wanted to report a problem about loading a qgis project , so when i add my .qgs file url to themesConfigs.json it works without error but when i run project as development and select my added theme it shows nothing  and when i was looking at network requests i found out that requested STYLE was not correct , so i just commented part of the qwc2 code that was responsible for assigning STYLE and it worked!!!!

files i have changed:
qwc2-demo-app/qwc2/scripts/themesConfig.js line 209 to 212

**Comment by manisandro** [comment]
What GetMap request did QWC2 generate with the style? (You can inspect the network traffic in the browser via F12 -> Network)

**Comment by manisandro** [comment]
Can you copy the URL of the request that produces the 500 response?

**Comment by Mrpolit** [comment]
i know following question is not relevant to this issue but i wanted to know if i make a Persian json language can i give it to you so you can add it to the supported languages?
currently i am working on it you can visit my modified version in 45.156.184.164/3000/prod

**Comment by Mrpolit** [comment]
> Can you copy the URL of the request that produces the 500 response?

this is one of the in correct requests 
 http://45.156.184.164:3000/cgi-bin/qgis_mapserv.fcgi?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image%2Fpng&STYLES=name%2Cname%2C&TRANSPARENT=true&MAP=%2Fhome%2Fqgis%2Fprojects%2Ftutorial%2Fworld.qgs&LAYERS=countries_shapeburst%2Ccountries%2Cairports&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=false&OPACITIES=255%2C255%2C255&__t=1710253758965&FILTER=&WIDTH=817&HEIGHT=775&BBOX=-1616313%2C3592582.4166666674%2C3787801.583333333%2C8718884.5

**Comment by manisandro** [comment]
Thanks, this is fixed in https://github.com/qgis/qwc2/commit/22bd8fe97a942110b44b4d1a5f4570bdf1c823ff. 

Regarding Persian, sure feel free to submit a PR with the translation file. Thanks!
