### ISSUE TITLE
The "coordinates" search provider doesn't work correctly

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2-demo-app#54]
I've noticed two problems with the "coordinates" search provider:

1. It doesn't work with negative values. For example no results are displayed/suggested when typing `-3`.
1. It displays three results when typing "30": "3, 0 (EPSG:3857)", "3°E, 0°N" et "0°E, 3°N". Instead it should wait for a separator (coma or space) before making suggestions.

**Comment by manisandro** [comment]
Indeed, the regex for matching the coordinates was not good enough... Fixed, thanks for reporting!

**Comment by elemoine** [comment]
Thanks!
