### ISSUE TITLE
Questions regarding MapFilter

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#543]
Hello I got a ew questions regarding the new mapfilter plugins. 

First, using the related config in my tenantconfig theme I got an error 
```
  "predefinedFilters": {
                "id": "quartier",
                "title": "Quartier",
                "titlemsgid": "quartier",
                "filter": {
                  "quartier": ["nom_commune", "=", "quartier_choix"]
                },
                "fields": {
                  "id": "quartier_choix",
                  "title": "Choix du quartier",
                  "titlemsgid": "quartier_choix",
                  "defaultValue": "Neuhof - Meinau",
                  "inputConfig": {"type": "select", "options": [{"Neuhof - Meinau": "Neuhof - Meinau", "Neudorf": "Neudorf"}]}
                }
              }
```

This is the related error when opening the theme

```
TypeError: (e.predefinedFilters || []).filter is not a function
    at Object.createThemeLayer (ThemeUtils.js:136:64)
    at et (theme.js:51:35)
    at theme.js:231:13
    at redux-thunk.mjs:5:14
    at n.<computed> [as setCurrentTheme] (react-redux.mjs:352:47)
    at StandardApp.jsx:152:36
    at b (PermaLinkUtils.js:134:9)
    at StandardApp.jsx:100:13
```

Probably I've done something wrong within the config but can't figure what, also I would like to know the correct way to reference the field variable within the filter expresion should I just use "field_id" or is it something special like "$TEXT$" used in the Qgis search plugin ? 

Thansk in advance for your answer and also for the implementation of this nice feature.
Kind regards, Clément.

**Comment by manisandro** [comment]
Apologies, there was a mistake in the documentation: predefinedFilters should be an array - fixed now. Regarding the placeholder values, it is `$field_id`. I've also improved the documentation in this regard.

**Comment by cazitouni** [comment]
Thanks it now works great. 
Also I would have another question regarding the geometry filter. 

When applying the circle, shouldn't all the ellement outside be filtered 

![circle](https://github.com/qgis/qwc2-demo-app/assets/92778930/5f4aece3-9234-4afb-97ab-47a1662f5919)

It doesnt seems to do much and no error is returned in the console. 
I use the docker version if that's matter. 

Also i've tested temporal dimension and it worked great. 

Thansk for your answers .

**Comment by manisandro** [comment]
Do you see a FILTER_GEOM in the GetMap request? Is the layer a Postgis layer? Do you have the `filter_geom` QGIS server plugin enabled?

**Comment by cazitouni** [comment]
Ok it's a geopackage that's why, sorry for the dumb question. 

I'll close the ticket since everything's fine then. 

Thanks again for the quick answers !
