### ISSUE TITLE
Adding an ArcGIS Rest WFS

### ISSUE THREAD

**Issue by mapperfr** [qgis/qwc2-demo-app#549]
Hi, 

I tried to add the following ArcGIS REST service (so-called WFS) as a temporary layer through the QWC2 layer control: https://services3.arcgis.com/zy1UGXGNCAGm516O/arcgis/rest/services/survey123_91a097126e68419fae62d315873d8048_results/FeatureServer

As I suspected, it doesn't work as it's not a standard WFS. 

Is there a way to import this kind of service yet, or a workaround? 

Is it on the roadmap to implement ArcGIS REST service support? 

We're in the middle of a cartographic platform migration from an ESRI infrastructure towards a QGIS infrastructure. The ability to import such ESRI "WFS" layers is quite critical to the project. Any feedback or suggestion would be much appreciated!

Best regards,

Jeremy

**Comment by manisandro** [comment]
There is currently no support for importing ArcGIS services in QWC2, though it should not be too hard as basic OpenLayers support exists.

**Comment by manisandro** [comment]
Duplicate https://github.com/qgis/qwc2-demo-app/issues/349
