### ISSUE TITLE
No geometries in GetFeatureInfo queries with QGIS 3

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2-demo-app#55]
With QGIS 3 `WITH_GEOMETRY=true` needs to be in the query params for geometries to be returned in GFI responses.

I just did a quick test and adding `with_geometry: 'true'` to the [Identify WMS request](https://github.com/sourcepole/MapStore2/blob/a814e652f34e1352b17af4ab21e499134f181ddf/web/client/utils/MapInfoUtils.js#L162-L179) works as expected. But I am not sure this is the right place for fixing this.

**Comment by manisandro** [comment]
In QGIS 2.x you can control this behaviour in`Project Properties -> OWS Server -> WMS Capabilities -> Add geometry to feature response`. In QGIS 3, that option is in `Project Properties -> QGIS Server -> WMS Capabilities`. Does `WITH_GEOMETRY` need to be specified regardless?

**Comment by elemoine** [comment]
Setting `Add geometry to feature response` has no effect in QGIS 3. It should be removed, which is the topic for a separate issue on QGIS.

**Comment by andreasneumann** [comment]
@manisandro - your colleague Marco knows everything about this change ;-) he implemented it so that Desktop GIS is not bothered by a long list of coordinates.

Web-GIS clients need to change and add the WITH_GEOMETRY and WITH_MAPTIP (for mouse over display of map tips).

**Comment by elemoine** [comment]
Any news on it? Should I create a PR that adds with_geometry?

**Comment by manisandro** [comment]
@elemoine I'll discuss it with my colleague tomorrow.

**Comment by elemoine** [comment]
Thanks a lot.

**Comment by manisandro** [comment]
`with_geometry: true, with_maptip: true` added in https://github.com/sourcepole/MapStore2/commit/581b0af5af2cca3c2837278480fe36cd184e01f5. The project still needs to have `Add geometry to feature response` selected, the idea is that the project instructs the server whether the geometries should exposed if the client requests them, and the client on his part needs to decide whether it actually wants to receive the geometries.

**Comment by elemoine** [comment]
Understood. Thanks.
