### ISSUE TITLE
Crash in identifyViewer.jsx

### ISSUE THREAD

**Issue by mhaelsig** [qgis/qwc2-demo-app#554]
Probably by changes since the version of 2024-03-27 I get a crash:

qwc2 actual copy: `https://test.radwegplanung-muenchen.de/?l=L5`, click left on any route. The error message is attached: 
[ErrorMessage.txt](https://github.com/qgis/qwc2-demo-app/files/15178350/ErrorMessage.txt)

The same happens, when I implant my themesConfig.json and config.json into the demo-app. 

qwc2 version 2024-03-27: `https://maps.radwegplanung-muenchen.de/?l=L5`, click left on any route. Details of this route are shown in the standard form.

I am using the standard/standalone viewer. 

My first thought was to point to a typo in identifyViewer.jsx line 780 (_..exportes_ instead of _..exporters_), but this is not the reason (same 'typo' in api.jsx). 

Any hints? Thank you.

**Comment by manisandro** [comment]
Thanks, should be fixed in https://github.com/qgis/qwc2/commit/14edf406f9d193d77bb74e4313c13c084578ded0
