### ISSUE TITLE
Time manager crashes when enable a temporal layer

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#555]
When I open the time manager without a visible temporal layer, the normal message "No temporal layers are visible in the map." appears. Then when I enable a temporal layer while the time manager  is open, the QWC2 crashes.

When I enable the temporal layer first and open the time manager afterwards, it works without any problems.

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/42d0a56327444ac1f6e00946b3081a69b1eaad5a
