### ISSUE TITLE
Layer tree plugin: allowMapTips vs. mapTipsEnabled

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#561]
What is the difference between these two parameters?
https://github.com/qgis/qwc2-demo-app/blob/master/static/config.json#L237
https://github.com/qgis/qwc2-demo-app/blob/master/static/config.json#L238

Within the doc only `allowMapTips` is mentioned.

**Comment by manisandro** [comment]
The first one is whether mapTips can be enabled, the second one is whether they are enabled by default.
