### ISSUE TITLE
MapViewer Search - $TEXT$ replaced only once in GetFeatureInfo request

### ISSUE THREAD

**Issue by naub1n** [qgis/qwc2-demo-app#562]
hi,

I try to use filters in search box with logical operator:
```
{
    "params": {
        "expression": {
            "my_layer": "\"code\" ILIKE '%$TEXT$%' OR \"name\" ILIKE '%$TEXT$%'"
        },
        "resultTitle": "{code}:{nom}",
        "title": "AllInOne Search"
    },
    "provider": "qgis"
}
```

but when I write "Blaise" in searchbox, only the first `$TEXT$` variable is replaced in GetFeatureInfo request:

`https://geo-dev.lesagencesdeleau.eu/dsiun/api/v1/featureinfo/scan/Cyclope/recherche?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&CRS=EPSG:3857&WIDTH=100&HEIGHT=100&LAYERS=my_layer&FILTER=my_layer:"code"+ILIKE+'%Blaise%'+OR+"name"+ILIKE+'%$TEXT$%'&WITH_MAPTIP=false&WITH_GEOMETRY=true&feature_count=100&info_format=text/xml&QUERY_LAYERS=my_layer`

Docker images used :
- qwc-feature-info-service:v2024.04.24
- qwc-map-viewer-demo:v2024.05.16

**Comment by manisandro** [comment]
Thanks, fixed in [1] and [2]

- [1] https://github.com/qgis/qwc2/commit/097abdecff557ffe88c935d4fdf293b24d3f1953
- [2] https://github.com/qgis/qwc2-demo-app/commit/07391db10da9a152fb709d94302d8cf3c86dcfbc

**Comment by naub1n** [comment]
Wouah Thx !!!
I try it on the next docker image release!
