### ISSUE TITLE
Layer does not exist or is not permitted while printing, if another theme is added to the current map via search box

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#563]
The printing fails, if you are using the search box to search for a specific theme and add this to the current map via the plus symbol next to the search result and try to get a map print afterwards. In such case, the printing windows shows an service exception error like `Layer "XYZ" does not exist or is not permitted`.
The printing works, if the other theme is added to the current map via the theme switcher and not via the search box.

This issue could be reproduced with the demo app at http://qwc2.sourcepole.ch/ as well.

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qgis/qwc2/commit/a26d305578fe55eac1d122d477908a54549ce78b
