### ISSUE TITLE
GetMap timeout too short

### ISSUE THREAD

**Issue by naub1n** [qgis/qwc2-demo-app#564]
Hi,

My config generator can't generate new config file because it get a timeout on GetMap task.

I try to manually do the GetMap and request during 20secondes.

It's possible to get an environment variable instead static value ?

[Line code with timeout=10](https://github.com/qwc-services/qwc-config-generator/blob/5ee248331be0e1e6ca6f686a5cb958bdec4bbbe3/src/config_generator/map_viewer_config.py#L606)

**Config Generator error :**
![image](https://github.com/qgis/qwc2-demo-app/assets/8344600/aebaab18-7303-4201-906c-73d9b53847b4)

**Manual GetMap:**
![image](https://github.com/qgis/qwc2-demo-app/assets/8344600/789756be-1b49-4258-b7d3-e71e351b297b)

Thx

**Comment by manisandro** [comment]
This is only the thumbnail which will not be generated, the rest of the configuration should succeed regardless. Anyway, I'm happy to accept a PR making the timeout configurable.

**Comment by naub1n** [comment]
My config don't succeed, timeout is the only one error.

I use version `v2024.06.14` of config generator service

![image](https://github.com/qgis/qwc2-demo-app/assets/8344600/6fbd3b77-1396-4e26-86f2-aed37ecab014)

I look with Oslandia for a PR :wink:

**Comment by manisandro** [comment]
I've demoted the thumbnail generation errors to warnings so that the should not be faal anymore: https://github.com/qwc-services/qwc-config-generator/commit/577717bda170f2e033cf130e6a26fbb35207d364
