### ISSUE TITLE
The Featureinfo Window Close button is hidden by the QWC2 header.

### ISSUE THREAD

**Issue by hdus** [qgis/qwc2-demo-app#568]
When a featureinfo window is opened, the header of the window is covered by the header of the QWC2, see image. As a result, the featureinfo window can no longer be closed.

QWC2-Map-Viewer: latest-2024-lts

![grafik](https://github.com/user-attachments/assets/f870e958-42a9-453c-b6da-5a2a629874f5)

**Comment by manisandro** [comment]
Since fixed
