### ISSUE TITLE
Print Plugin: Extra button for export if inlinePrintOutput is true 

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#572]
This is more a feature request than an issue.

It would be nice, to get an extra button within the PrintOutputWindow below the iframe for explit saving the rendered result to disk. Of course you could do this with the save button of the browsers pdf viewer or "right click - save as" for other output formats.  But actually I had some cases from users where they didn't get the point to save the print result on disk. This would be a more comfortable way to achive this. The button could be named with "Export result" or somethin like that.

**Comment by manisandro** [comment]
Done in https://github.com/qgis/qwc2/commit/77d2bc194bb328109678471f1117ec7cf829eb1f

**Comment by danceb** [comment]
As a very small improvemt I would recommend to add the css
```css
font-size: large;
```
to the save symbol as it is used with the other smybols in the topbar of the print output window.

Side note: All of the icons have a dimension of 24x24 px, but are slightly different sized as the width/height within most of the SVG files are not used completely and transparent space is left. Would it be a task to match the icon sizes that the 24 px are used in the best way?
