### ISSUE TITLE
News popup is shown again after new deployment

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#573]
Each time, when I am updating the application and doing a `docker-compose down` and `up` the news popup is shown again nevertheless the parameter `newsRev` didn't changed. Is there a new cookie generation initiated or where does this come from? 
Is there a possibility to keep the same user cookie with new app deployments as the news itself didn't changed?

**Comment by manisandro** [comment]
This should not be related to down/up. Try comparing the state of the browser cookie store when this happens.

**Comment by danceb** [comment]
ok, I recognized that the news cookie has a lifetime of only two weeks. So the cookie is deleted after this and the news popup is shown again, even if there is no update on the `newsRev` parameter, right?
I recomment to extent this to a much bigger time period (one year?) as there isn't going on so much within just two weeks, that the news have to be shown again.

**Comment by manisandro** [comment]
Right, done https://github.com/qgis/qwc2/commit/2e0fc18ed83d9c0ab80c96b510f16018303fd9c4
