### ISSUE TITLE
Unable to Locate ConfigProvider.js in New Version of QWC2

### ISSUE THREAD

**Issue by Patatekes** [qgis/qwc2-demo-app#574]
Hi,

In the previous version of QWC2, I used to define my background layers in **qwc2/utils/ConfigProvider.js**. However, after upgrading to the new version, I can't seem to find this file or identify where I should now define my background layers.

Could you please guide me on how and where to set up background layers in the current version?

Thanks in advance for your assistance.

Best regards,
Johannes

**Comment by manisandro** [comment]
Please use a `xyz` background layer instead, see [1].

[1] https://qwc-services.github.io/master/configuration/ThemesConfiguration/#background-layers

**Comment by Patatekes** [comment]
Thanks for the quick response.
Its working now.
