### ISSUE TITLE
MapSelection Instead of changeSelection 

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#579]
Hello @manisandro, 

In this commit you removed the selection reducer https://github.com/qgis/qwc2/commit/c7610ebc345a01d3444513aa2756949233c41aa4. 

I have develloped a module for french cadastre using https://github.com/sourcepole/qwc2-extra/blob/master/plugins/PlotInfoTool.jsx as an inspiration. But now with the removal of changeselection I'm kinda stuck because I didn't really understand how the new components work compared to the former one and could use a little help. 

Because just replacing the former function with a new component using the same parameters in "activated()" doesn't seem to be near enough. 

I've tried to look at https://github.com/qgis/qwc2/commit/ad4c3e6124e693bf68b4f963bb73aae09f49c68e?diff=unified&w=1#, but it's still a bit confusig to me. 

Could you guide me a little on that ? 

Thanks a lot,
Kind regards, Clément.

**Comment by manisandro** [comment]
In a nutshell it should be sufficient to render the `MapSelection` component along these lines:

```
            <MapSelection
                active={selectionActive}
                geomType={selGeomType}
                geometry={this.state.selectionGeom}
                geometryChanged={(geom) => this.setState({selectionGeom: geom})}
                styleOptions={this.props.highlightStyle} />
```

and you will obtain your selection geometry in `this.state.selectionGeom`.

I'd need to know more about where you are stuck to help further.

**Comment by cazitouni** [comment]
@manisandro  thanks for the answer

I started from this 

```
    activated = () => {
        const assetsPath = ConfigUtils.getAssetsPath();
        this.props.changeSelectionState({geomType: 'Point', style: 'default', styleOptions: {
            fillColor: [0, 0, 0, 0],
            strokeColor: [0, 0, 0, 0]
        }, cursor: 'url("' + assetsPath + '/img/plot-info-marker.png") 12 12, default'});
    };
```

To this 

```
    activated = () => {
        const assetsPath = ConfigUtils.getAssetsPath();
        const cursorPath = 'url("' + assetsPath + '/img/plot-info-marker.png") 12 12, default';
        <MapSelection
            active={selectionActive}
            geomType={selGeomType}
            geometry={this.state.selectionGeom}
            cursor = {cursorPath}
            geometryChanged={(geom) => this.setState({selectionGeom: geom})}
            styleOptions={this.props.highlightStyle} />
    };
```

But previously When i cliked on the plugin button on the menu i got a selection cursor then after selection some logic got triggered. 

Now I got nothing, or with the code you linked I got an error because selectionActive isn't defined, But I do not understand where i'm supose to define it. What I would want is to select the geometry(Point XY in this case) to pass the request to my plot api.

**Comment by manisandro** [comment]
You need to render the `MapSelection` component in your `render()` function, and control whether it is active through the `active` prop of the  `MapSelection` component. I.e. you'd write
```
activated = () => {
    this.setState({selectionActive: true})
}
render() {
    return [
        ...,
        <MapSelection
            key="MapSelection"
            active={this.state.selectionActive}
            geomType={selGeomType}
            geometry={this.state.selectionGeom}
            cursor = {cursorPath}
            geometryChanged={(geom) => this.setState({selectionGeom: geom})}
            styleOptions={this.props.highlightStyle} />
    ];
}
```

**Comment by cazitouni** [comment]
@manisandro Thanks for the quick answer I now do understand. 
Have to modify the render a little bit to render either the windows or the mapselect but it works like this 

```
    render() {
        return (
            <>
                {this.state.plotInfo && this.state.plotInfo.features.length > 0 ? (
                    <ResizeableWindow
                        icon="plot_info"
                        initialHeight={this.props.windowSize.height}
                        initialWidth={this.props.windowSize.width}
                        initialX={0}
                        initialY={0}
                        onClose={() => this.props.setCurrentTask(null)}
                        scrollable={true}
                        title="appmenu.items.PlotInfoTool"
                    >
                        {this.renderBody()}
                    </ResizeableWindow>
                ) : this.state.selectionActive ? (
                    <MapSelection
                        active={this.state.selectionActive}
                        geomType={'Point'}
                        geometry={this.state.selectionGeom}
                        cursor={`url("${ConfigUtils.getAssetsPath()}/img/plot-info-marker.png") 12 12, default`}
                        geometryChanged={(geom) => this.setState({selectionGeom: geom})}
                        styleOptions={{fillColor: [0, 0, 0, 0], strokeColor: [0, 0, 0, 0]}}
                    />
                ) : null}
            </>
        );
    }
```

Thanks again !
