### ISSUE TITLE
dealing with theme url while loading themes from database

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#580]
I want to change my theme configuration to load all of the themes from database instead of local files [1]. 
Besides the services for the map viewer I am using other services which are not used in the map viewer by setting the parameter `"wmsOnly": true` (which I am missing in the documentation?).

As the data source is mapped within the service url, all urls look different now. For instance the ows service urls 
```
https://my_qwc.com/ows/service_abc
https://my_qwc.com/ows/service_xyz
```
become
```
https://my_qwc.com/ows/pg/schema_name/service_abc
https://my_qwc.com/ows/pg/schema_name/service_xyz
```
As I want to change this in an established application, this isn't really an option for me. I couldn't change all urls at the client side.

So my attempt is, that the projects are stored at database but are available at `https://my_qwc.com/ows/service_abc` as before.

I have tried to achieve this using rewrite rules in the nginx configuration, for instance:
```
    location /ows {
        rewrite ^/ows/(.*)$ /ows/pg/qwc_config/$1 break;
        proxy_pass http://qwc-ogc-service:9090;
    }
```
If this is working, I have to do this for all services with url access like legend, featureinfo, ...

Using rewrite rules the direct access like 
```
https://my_qwc.com/ows/service_abc?REQUEST=GetMap[...]
```
is working as expected. But within the map viewer it still tries to load the service with 
```
https://my_qwc.com/ows/pg/schema_name/service_abc?REQUEST=GetMap[...]
```
which fails now.

So do you have any thoughts how to overcome this issue? How can I get the (nginx) configuration work, that both, the direct access and the map viewer, will use `https://my_qwc.com/ows/service_abc` for the resolving the service url?

[1] https://qwc-services.github.io/master/configuration/ThemesConfiguration/#storing-projects-in-database

**Comment by manisandro** [comment]
I'd grep through the `config-in` and `config` folders to see if any traces of `/pg/schema_name` remain.

**Comment by danceb** [comment]
Within the themesConfig I have to specify the urls like `ows/pg/schema_name/service`, as the config generator requests `http://qwc-qgis-server/ows/pg/schema_name/service`, regardless what I have specified within the `nginx.conf`. So `/pg/schema_name/` is written in all the files in the `config` folder aswell. 
With the rewrite rules and `/ows/service` in the themesConfig the config generation fails.

Or should the config generator requests the capabilities etc. at `/ows/service`, if the nginx config is set the right way?

**Comment by manisandro** [comment]
Yes indeed the config generator relies on the syntax to decide whether it is reading a filebased or db-based project. You'd either need to change [1], or perhaps easier leave the `pg` prefix and just handle the legacy urls in `nginx.conf` in addition to the new `pg` urls so that the old URLs stay valid - I believe this could work, but needs to be tested.

[1] https://github.com/qwc-services/qwc-config-generator/blob/master/src/config_generator/qgs_reader.py#L51

**Comment by danceb** [comment]
Ok, I've got it to work with:
```
    location /ows {
        rewrite ^/ows(/pg/qwc_config)?/(.*)$ /ows/pg/qwc_config/$2 break;
        proxy_pass http://qwc-ogc-service:9090;
    }
```

Another thing which is a bit related to this:
The MapExport [1] and Print [2][3] plugins take the theme name as filename for export. As `name` is generated from the url and not passed as parameter from themesConfig, the files are saved as "pg_schemaname_themename". May you change this, that the parameter ìd`, is used instead? As `id` is generated but can be provided within the themesConfig aswell, this fits better I think. 

[1] https://github.com/qgis/qwc2/blob/master/plugins/MapExport.jsx#L173
[2] https://github.com/qgis/qwc2/blob/master/plugins/Print.jsx#L511
[3] https://github.com/qgis/qwc2/blob/master/plugins/Print.jsx#L628
