### ISSUE TITLE
Editing features: Error in relationship

### ISSUE THREAD

**Issue by rsrg-zwiama** [qgis/qwc2-demo-app#582]
When editing a layer, that has a relationship to another table defined in qgis project, the corresponding features are not shown in the editing dialog. The get request for the relationship values is sent and response looks good. Adding features is not possible and results in following error: 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'concat')
    at AttributeForm.jsx:234:83
    at EditingUtils.js:133:9
```
This error occured, after update from  qwc2 lts 2023 to 2024 (master). 
In this version, the features are shown, but trying to edit results in following error:
```
AttributeForm.jsx:206 Uncaught TypeError: Cannot set properties of undefined (setting '__status__')
    at Object.addRelationRecord (AttributeForm.jsx:206:23)
    at t.addRelationRecord (QtDesignerForm.jsx:617:20)
    at onClick (QtDesignerForm.jsx:609:152)
    at Object.Ne (react-dom.production.min.js:54:317)
    at Ge (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Lr (react-dom.production.min.js:105:68)
    at Or (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at cc (react-dom.production.min.js:273:42)
EditingUtils.js:133 Uncaught (in promise) TypeError: o is not a function
    at EditingUtils.js:133:9
```

**Comment by manisandro** [comment]
Are you using a qwc-data-service version compatible with the used qwc-map-viewer? See [1]

[1] https://qwc-services.github.io/master/release_notes/QWC2UpgradeNotes/#update-to-qwc2-submodule-revision-3e1763a-15052024

**Comment by rsrg-zwiama** [comment]
I think so. For local testing, I use docker compose with new versions of data service and config service (acutally, I updated all of them to the lts 2024: 
```
  qwc-data-service:
    image: sourcepole/qwc-data-service:v2024.4-lts
...
  qwc-config-service:
    image: sourcepole/qwc-config-generator:v2024.5-lts
```

**Comment by manisandro** [comment]
What about the map-viewer-service?

**Comment by rsrg-zwiama** [comment]
I build my own. It is based on the the demo app. I tried different versions of the qwc2 submodule. All ending in different errors. In the dockerimage i use ` QWC_MAP_VIEWER_VERSION='v2024.16-lts' `and mount my qwc build to  /qwc2

**Comment by manisandro** [comment]
You are likely building your own app from the master branch (and not the 2024-lts branch). In this case, you'll need a qwc-data-service from the master branch => try with `qwc-data-service:v2024.07.04`

**Comment by rsrg-zwiama** [comment]
>  building your own app from the master branch (and not the 2024-lts branch)
master of qwc2 or demo-app?
Is there an impact to this, when i use:
```
  qwc-feature-info-service:
    image: sourcepole/qwc-feature-info-service:v2024.08.28
```

**Comment by manisandro** [comment]
Both qwc2-demo-app and qwc2 submodule have master and lts branches.

Regarding the feature-info-service no there should not be any incompatibilities.

**Comment by rsrg-zwiama** [comment]
>  => try with qwc-data-service:v2024.07.04

using not the lts data service solves my issue! Thank you!
