### ISSUE TITLE
Measure plugin uses mapCrs projection insted of displayCrs leading to distorted results

### ISSUE THREAD

**Issue by longerCZE** [qgis/qwc2-demo-app#583]
I have a problem with Measure plugin which uses displayCrs as target projection to convert two points to it and calculate distance between them. It seems that this value is designed to be set by BottomBar plugin which happens but it doesn't affect variable which is used in Measure plugin. As far I can understand it seems that the Measure plugin is loaded with mapCrs value and it allways wins in logic around selectors/displaycrs.js before displayCrs.

As a result, all the measurements on Mercator projection map are distorted depending on distance from equator including on QWC demo page.

I was also not able to find solution how to specifically set defalut displayCrs for BottomBar plugin. I have Mercator and WGS84 projections defined in config and it allways sets the Mercator one when app loads, maybe because of the lower ESPG id.

Difference between measurements of one building side in QGIS and QWC demo is attached below.

![Screenshot from 2024-09-27 16-49-49](https://github.com/user-attachments/assets/6023a145-0402-4809-9de4-25e845f6f6cb)

![Screenshot from 2024-09-26 23-41-44](https://github.com/user-attachments/assets/c55b7c49-80ee-4aac-939c-d4716aea437c)

**Comment by manisandro** [comment]
Hi, possibly you are looking for the `geodesicMeasurements` option in `config.json` [1], since you are measuring on the ellipsoid in QGIS?

[1] https://qwc-services.github.io/master/configuration/ViewerConfiguration/#global-settings

**Comment by longerCZE** [comment]
Okay, that was easy fix I have been looking for many hours. Thanks a lot!
