### ISSUE TITLE
Feature count and layer selection in identifyViewer

### ISSUE THREAD

**Issue by cazitouni** [qgis/qwc2-demo-app#593]
Hi @manisandro,

Based on user feedback, it seems that adding the ability to select results by layer in the identify panel, along with showing a count of features selected (per layer), would be a valuable enhancement.

To implement this, I’m considering modifying the IdentifyViewer component. Would this approach will be the correct one? Additionally, would you find this feature valuable if I were to submit a pull request to the public repository?

Looking forward to your thoughts!

This is a WIP screenshot for example
![image](https://github.com/user-attachments/assets/9366b8d2-337b-4ad0-9a50-a0bd07e9257b)

Let me know ! 
Thanks, Clément.

**Comment by manisandro** [comment]
Hi Clément, yes this looks like a nice enhancement, thanks!
