### ISSUE TITLE
Rounding numbers during numerical input in the redlining function

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#594]
If I draw a rectangle in the redlining function and then set for example the width to a decimal number in the numeric input window, the value in the input field is rounded. But when I measure the width of the rectangle with the measurement functions, the original decimal number was used for the creation of the rectangle geometry. The export to GeoJSON and the measurement in QGIS also result in the decimal number.

In this example, I created a 1000.5 m x 1000 m rectangle. The input field for the width was automatically rounded to 1001 m. However, the measurement of the width in the map results in 1000.5 m. The coordinate system was EPSG:25832 and the config parameter geodesicMeasurements was false.

![rounding_numbers_during_numerical_input ](https://github.com/user-attachments/assets/2cf9cb3c-659e-4a06-a69a-c81fa8e959aa)

**Comment by manisandro** [comment]
So it would be sufficient to round the numerical input values to say two decimals like the measurements, right?

**Comment by stamogis** [comment]
Yes, I think that should be sufficient

**Comment by manisandro** [comment]
I've implemented some changes here:

- There is now a global `measurementPrecision` setting you can set in `config.json` at top-level
- Still in `config.json`, for each entry in `projections` you can specify `precision` to decide with how many digits the respective coordinates should be shown in the map, i.e.

    "projections": [
      {
        "code": "EPSG:2056",
        "proj": "+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs",
        "label": "CH1903+ / LV95",
        "precision": 2
      }
    ]

The NumericInput widget and elsewhere will now honour these settings.
