### ISSUE TITLE
Can not able to access more than one layer from the QGIS server

### ISSUE THREAD

**Issue by Deba088** [qgis/qwc2-demo-app#596]
Description: I have a QGIS server where I have hosted a QGIS project which is having 2 layers in it.

Steps performed:
1. I have used the QGIS web client along with QGIS demo app.
2. Updated the themeConfig.json file and added URL of my server.
3. Run npm start.

Expectations: QGIS web client should show both the layers.
Reality: QGIS web client is showing one layer only.

**Comment by manisandro** [comment]
Check the QGIS Server logs for any indications regarding failures to read data sources etc. Do both layers appear in the WMS capabilities?

**Comment by Deba088** [comment]
Hello, thanks for your reply.
In the server WMS capabilities I can see both the layers available and server is able to serve both the layers through http requests.
The themes.json file that is getting generated during npm build process also has information for both the layers, but in the web-ui I am able to see one layer only.

**Comment by manisandro** [comment]
Can you attach the themes.json?

**Comment by Deba088** [comment]
[themes.json](https://github.com/user-attachments/files/18196151/themes.json)

Here is the themes.json for your reference.

**Comment by manisandro** [comment]
I see both layers listed in the layertree and in the GetMap requests, AFAICS the webclient processes the theme correctly. Check the GetMap request in the Network Inspector and verify that it is plausible for your project, and make sure you don't i.e. have any scaled dependent visibility configured in the project.

**Comment by Deba088** [comment]
Hi, I have checked the network tab inspector, it is calling only one layer and not both layers, also there is no scale dependent visibility configured for the project. Also I am able to see only one layer in the layer details of web-ui.

**Comment by manisandro** [comment]
This also when starting the webclient in a new browser tab (i.e. not refreshing a previous tab)?

**Comment by Deba088** [comment]
Hi, thanks for your suggestion. I have triggered it from the new browser tab and suddenly some magic happened 😅 (May be it refreshed the cache) and I am able to see both the layers.
Many many thanks for your valuable time.

**Comment by manisandro** [comment]
You probably deleted the layer in your previous session. The URL stores the viewer state, including the layers. So refreshing that page simply restored the viewer state with only one layer.

**Comment by Deba088** [comment]
Ah, that also might be possible. Thanks for the info.
