### ISSUE TITLE
Feature Info: allow suppressing of emtpy attribute values

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#6]
QWC 1 had a global option to suppress attribute values if they are empty, so generating lower list in cases where tables contain many empty values.

It should be discussed at the upcoming coordination meeting how we handle this in the future, e.g. a global option with a way to override per project and per layer?

**Comment by manisandro** [comment]
Both are doable, either globally in config.json "skipEmptyFeatureAttributes" or similarly per theme in themesConfig.json. Preferences?

**Comment by andreasneumann** [comment]
I like the mechanism of a global option in config.json with the option to overwrite it on the project level in themesConfig.json, if defined there. This would be very flexible.

**Comment by manisandro** [comment]
In that case I'd rather have the global option also in themesConfig.json, similar to defaultScales etc.

**Comment by andreasneumann** [comment]
fine with me.

**Comment by manisandro** [comment]
Should "NULL" also count as empty, or just an actual empty string?

**Comment by andreasneumann** [comment]
I think NULL should also count as empty.

**Comment by manisandro** [comment]
Implemented in qgis/qwc2@bfc9be9
