### ISSUE TITLE
IE doesn't work with latest code

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#61]
The error can only pe encountered in IE, (Edge, Chrome, firefox etc. do work.

The error is ``SCRIPT1003: expected ':'``

**Comment by manisandro** [comment]
Groan. I'll need to check...

**Comment by manisandro** [comment]
@tudorbarascu Appears to work fine with the latest code. Can you confirm?

**Comment by tudorbarascu** [comment]
Nope, it doesn't work. Internet Explorer 11.98. Tested on Windows 7 and 10.

**Comment by manisandro** [comment]
Mhh I just tested now a deployed version, and indeed it does not work (but development mode appears tow ork). Needless to say that the error message is very unhelpful...

**Comment by manisandro** [comment]
Looks like the babel transpiler was stumbling on a variable which was missing the scope declaration, fixed in https://github.com/qgis/qwc2/commit/257f39e578944e219ef0d2ad8d343e8f0634eba1.

**Comment by tudorbarascu** [comment]
Thanks a lot!
