### ISSUE TITLE
WMS Version standardize

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#65]
Now we have for themes the defaultWMSVersion, for GetFeatureInfo it's uses version 1.1.1, for RasterExport - GetMap is 1.3.0 and for GetPrint  it's uses 1.3 (which is not correct and the behavior is from 1.1.1)

I think it will be good if there will be a parameter for each theme and use the same wms version everywhere.

The problem occurs when a projection with reverse axis is used.
Also make a function to check if there is 1.3.0 used for correct the bbox for 'neu' axies projection from requests of RasterExport, GetPrint and GetFeatureInfo

Moreover, shouldn't all the requests to the QGIS Server be 1.3.0?

**Comment by manisandro** [comment]
Good point, we should just use the theme version everywhere.

**Comment by manisandro** [comment]
Done in https://github.com/qgis/qwc2/commit/fa78ca97223f9e2d84f78d2824f9b20ae67b9ed4
