### ISSUE TITLE
Using ES modules instead of require

### ISSUE THREAD

**Issue by luizaugustocs** [qgis/qwc2-demo-app#66]
I would like to know if you have already planned to start using the ES2015 import syntax instead of the AMD require syntax.

**Comment by manisandro** [comment]
No specific plans currently, but should be easy to do semi-automatically with some smart regex.

**Comment by luizaugustocs** [comment]
Ok, thanks. 
I'll do it and send a pull request then.

**Comment by manisandro** [comment]
cool, thanks

**Comment by manisandro** [comment]
This is now done.
