### ISSUE TITLE
QGIS Server 3 printing

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#69]
I noticed that the new **Layout manager** in QGIS Server 3 doesn't yet advertise the layouts, see
https://issues.qgis.org/issues/17747

I tested QWC2 with QGIS Server 3 and the layouts in the old **Composer manager** work but the GetPrint request bbox must be reversed now according to the axis. Basically, the requests for QGIS 3 are different than for QGIS 2.

It seems that qwc2 will need to have the option to switch between QGIS Servers versions.
Has anyone tested this? Any thoughts?

**Comment by andreasneumann** [comment]
or QGIS server must be fixed.

If there is no good reason from QGIS server to change its behaviour between versions 2 and 3 they should fix it.
