### ISSUE TITLE
Support for high-dpi WMS requests

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#7]
The OpenLayer 3 based ol3mobile viewer from Sourcepole supports high-dpi WMS support for displays with higher-dpi than standard. OpenLayers 3 supports them as well, and so does QGIS server.

QWC2 should also support high-dpi display, e.g. for mobile devices.

See also https://github.com/sourcepole/ol3-mobile-viewer/commit/8837f048d8c4aa6db111f796a85f1fd2a94dd2aa
and https://github.com/sourcepole/ol3-mobile-viewer/search?utf8=%E2%9C%93&q=dpi

or ask Matthias ;-)

I'll create a separate ticket for WMTS - as this requires more research and can be treated separately.

**Comment by pka** [comment]
Openlayers 3 example: http://openlayers.org/en/latest/examples/wmts-hidpi.html

**Comment by manisandro** [comment]
Fixed in sourcepole/MapStore2@84110e3
