### ISSUE TITLE
Attribute table is limited to 2000 rows when try to filter

### ISSUE THREAD

**Issue by plodelie** [qgis/qwc2-demo-app#71]
I have layer with 5289 points; they are village centroids / Bulgaria.
The project is at http://gis.plodelie.com/gisapp/Project_tamplate

QWC2 shows them correctly on map.
Problem exists when I open attribute table in order to find an attribute/row.
In this case rows are limited to 2000.
It is like filter which cuts first 2000 names ordered/indexed by attribute name (village names in my case).
There are indications about:
Indication 1: After layer name it is written "(2000)". 
Indication 2: Names starting with letter "K" and bellow are rejected.
Indication 3: Number of pages - there are 100 pages with 20 rows each

My questions are:
1. Can I increase limit for attribute rows possible for searching?
2. How can I find and show village by its name in layer with 5000+ rows? (Village layer is correctly displayed by QWC2)

Project URL: http://gis.plodelie.com/gisapp/Project_tamplate

Thank you in advance,
Dimitar

**Comment by manisandro** [comment]
http://gis.plodelie.com/gisapp/Project_tamplate does not appear to be QWC2?

**Comment by plodelie** [comment]
Sorry, my mistake...
I thought that QWC2 and Extended QGIS Web client are the same.
Now I see they are different applications.

Sorry again...
