### ISSUE TITLE
linux chrome & firefox - production build - click event.x event.y are undefined

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#75]
In production build the click event.x and event.y 
https://github.com/qgis/qwc2/blob/master/MapStore2Components/components/map/openlayers/Map.jsx#L100
https://github.com/qgis/qwc2/blob/master/MapStore2Components/components/map/openlayers/Map.jsx#L113

are undefined.
In development it works fine but in prod no (tested on Debian chrome and on Firefox, on Windows works fine).
@manisandro Do you have any idea?  Can you test it, please? Do you think it will be ok if event.x and event.y will become event.clientX and event.client.Y

Thank you!

**Comment by manisandro** [comment]
Actually I think it is better to use clientX and clientY in any case, done in bc6de50eabd4aefa5dc5e45844f40678cbd8afb0, thanks for reporting.
