### ISSUE TITLE
Help for installing

### ISSUE THREAD

**Issue by news24lor** [qgis/qwc2-demo-app#77]
I have an error during the installation.
After 'yarn start' command the modules are built but not all, at the end I have this error:
<pre>
ERROR in ./qwc2/QWC2Components/plugins/Redlining.jsx
Module not found: Error: Can't resolve 'react-color' in '/Applications/MAMP/htdocs/qwc2/qwc2/QWC2Components/plugins'
 @ ./qwc2/QWC2Components/plugins/Redlining.jsx 20:15-37
 @ ./js/appConfig.js
 @ ./js/app.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./js/app
</pre>
The module 'react-color' is not present. Should I install it with npm?

An help thanks

**Comment by manisandro** [comment]
Is your qwc2 submodule up-to-date? Redlining.jsx shouldn't require react-color anymore.

**Comment by news24lor** [comment]
I've last qwc2 from github.
I have installed react-color with
yarn add react-color
After I have reinstalled qwc2 and the error is gone. Now it's work.
So react-color is required.
Thanks again

**Comment by manisandro** [comment]
Ah maybe you have the obsolete Draw plugin active? Or what does

    $ grep -r react-color qwc2/

give?

**Comment by news24lor** [comment]
I have this result:
<pre>
<code>
$ qwc2//QWC2Components/plugins/Draw.jsx:const {TwitterPicker} = require('react-color');
$ qwc2//QWC2Components/plugins/Redlining.jsx:const {TwitterPicker} = require('react-color');
</code>
</pre>
react-color is required...

**Comment by manisandro** [comment]
So you don't have the latest qwc2 submodule version, i.e. look at [1] , there is no `require('react-color');`

[1] https://github.com/qgis/qwc2/blob/b50513a557965efeeaaae038257ea9828405e8fe/QWC2Components/plugins/Redlining.jsx
