### ISSUE TITLE
Redlining print and raster export

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#78]
Redlining lines are not visible on print and raster export.
Points stroke-width is always 1  on print and raster export.

I don't know if it is a qwc2 issue or qgis server issue.
For me the qwc2 request seems to be ok.
I tried on qgis server 2.8 and 3.0 and it is the same problem.

**Comment by manisandro** [comment]
2.8 or 2.18?
I'm regularly testing with 2.18, where it works fine.

**Comment by luciman** [comment]
2.18 sorry

**Comment by manisandro** [comment]
Can you attach the project which you are using, and a sample request?

**Comment by luciman** [comment]
also on http://qwc2.sourcepole.ch/wms/wolfsburg/qwc2_demo the demo theme from qwc2-demo app the stroke-width of point is always 1

it's true on this the lines are visible
I think just on 3.0 the lines are not visible, I have to reinstall 2.18 and retest

![screen](https://user-images.githubusercontent.com/11608132/36256894-7b35dae8-125d-11e8-89ca-a026f1d2608b.png)
[qwc2_demo print.pdf](https://github.com/qgis/qwc2-demo-app/files/1727627/qwc2_demo.print.pdf)

**Comment by manisandro** [comment]
Ah yes true about the stroke width of points. Lines seem to work though.

**Comment by luciman** [comment]
Yes on 2.18 the lines works, just on 3 they not working
The point stroke-width not working on both

**Comment by manisandro** [comment]
Yeah looking at the point stroke width, though odd because the SDL QWC2 generates is basically identical to the SDL QGIS generates.

**Comment by manisandro** [comment]
And about the lines: it might be worth comparing the SLDs from QGIS 3 with those of QWC2

**Comment by manisandro** [comment]
So the point stroke width is also a QGIS bug: if you export a point layer style to SDL and re-import it, the stroke width is lost.

**Comment by manisandro** [comment]
These are QGIS issues.
