### ISSUE TITLE
Discussion: should feature highlight with more than one hit highlight all returned geometries?

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#8]
When a feature info returns one unique result, the concerned feature is immediately highlighted in the map. When more than one hit is returned, no element is highlighted.

It should be discussed whether all hits should be highlighted first, until another feature info request is made or an individual feature is chosen in the feature info result window.

To be discussed at the next coordination meeting.

**Comment by manisandro** [comment]
There is a WFS-based "area"-identify which can be used to query multiple geometries. Lemgo has financed a QGIS server 3.0 extension to allow WMS-based GetFeatureInfo queries using a polygon geometry instead of a point as hit-test.

**Comment by andreasneumann** [comment]
I don't fully understand how your comment relates to the issue. In both cases - with point-identify and polygon-intersect identify we have the issue that we have more than one hit.

I think in both cases all features that were hit should be highlighted.

But yes - the polygon hit-test is a welcome addition - but has the same problems as described.

Or do you mean that the highlight issue is solved with the polygon-hit test extension)

**Comment by manisandro** [comment]
Ah I misread the problem, it is not about which features are actually returned but whether all returned features are highlighted in the map immediately. This is already implemented in qgis/qwc2@4f0f96df0246d2930f7c3f8161eab5fa0ae2625c, see screenshot:
![screen](https://cloud.githubusercontent.com/assets/1298852/23658089/7a7f838c-0341-11e7-9f88-8f0a8e14969a.jpg)

**Comment by andreasneumann** [comment]
Yes - exactly. looks good then. Thanks!
