### ISSUE TITLE
Elevation information display with no decimals

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#82]
Hi, just tested the elevation display and it's working great.
Is there a reason why the elevation display is rounded to 0 out of the box?
It would be nice it it were configurable or at least round with 1 decimal as to leave space for high precision projects.
Thoughts?

**Comment by manisandro** [comment]
Sure, fine for me. Suppose a simple configuration prop should do.

**Comment by manisandro** [comment]
Adressed by @luciman
