### ISSUE TITLE
The editing select option should select the first value by default

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#87]
In the select option combobox the first value is  displayed but in the backround it's not selected and on submit the value is null.
Also, what do you think about turning:
```
         "constraints": {
                    "values": ["ETH", "UNI"]
                }
```
into something like
```
       "constraints": [
          {
            text: 'ETH',
            value: 'ETH'
          },
          {
            text: 'UNI',
            value: 'UNI'
          }
        ]
      }
```

**Comment by manisandro** [comment]
Sorry for the late reply, missed the ticket. Should null value should now be fixed, and separate value / labels is also implemented.

**Comment by luciman** [comment]
Thank you!
