### ISSUE TITLE
delete the *contents* of prod when running yarn prod

### ISSUE THREAD

**Issue by uniquestring** [qgis/qwc2-demo-app#90]
Before I come to my problem, I want to ask if there is a reason for putting parts of the build commands into the [qwc2 components repo](https://github.com/qgis/qwc2/blob/master/scripts/package-commands.sh).

I think this script should be in the qwc2-demo-app repo, because it uses commands and paths that are specific to this project.

---

My problem has todo with the script from the other repo that I mentioned, but since it's related to the building process, I guess the right place for my issue is here.

I'm referring to [this line](https://github.com/qgis/qwc2/blob/7543ebd5fe52d10e4362ec55b776fe654ff42bda/scripts/package-commands.sh#L18). Could we delete the **contents** of `prod` rather than `prod` itself when running `yarn run prod`?

This would help making this project more docker friendly. For development/configuration I'm mounting the `prod` directory from one container into another. The problem is, that you can't delete the mounted directory. Changing `rm -rf prod` to something like `rm -rf prod/*` should work the same and would fix my issue.

**Comment by manisandro** [comment]
The goal is to put as much as possible into the common `qwc2` submodule to reduce the number of file a user might need to manually update when updating the submodule. The build commands in most cases won't be application specific, but if someone has specific commands, he can just update the `package.json` and modify the commands as necessary.

Yes in any case deleting the contents should work just as well, I've changed it. Thanks for the suggestion.
