### ISSUE TITLE
preserveExtentOnThemeSwitch doesn't work anymore

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#91]
Just noticed the ``preserveExtentOnThemeSwitch`` doesn't seem to function anymore when set to true.

**Comment by manisandro** [comment]
Indeed, fixed in https://github.com/qgis/qwc2/commit/63bf72e45bc54e0a68635d9886059c058e81fd49, thanks!

**Comment by tudorbarascu** [comment]
Thank you!
