### ISSUE TITLE
Provide a configuration to switch tiling of the map on or off.

### ISSUE THREAD

**Issue by bstroebl** [qgis/qwc2-demo-app#94]
Currently tiling is always on.
I would prefer to have no tiles for the following reasons:
- Performance: Requesting many small maps for a large screen is slower than one large map
- Labelling: Labels get cut or doubled in adjacent tiles
So having tiling on or off should be configurable.
I added `"tiled": false` at every possible location in themesConfig.json but to no avail

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/d9a3e00bf3e456e701720a31fb87e7eb3cb0ce5c

**Comment by bstroebl** [comment]
Hi Mani,
thanks for fixing this, however it seems that by default tiling is off now, which might break existing installations.
