### ISSUE TITLE
Compare top layer breaks the layertree

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#98]
How to reproduce.
1. Activate ``Compare top layer``
2. Activate or deactivate the ``Root Group`` that contains the top layer breaks the layer tree
![problem](https://user-images.githubusercontent.com/3179646/40602205-654c5952-6260-11e8-9ca0-52908fd86d4b.gif)

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/b969fcf611dcb8558a33197046666faba4d5535f
