### ISSUE TITLE
Google as search provider

### ISSUE THREAD

**Issue by pierloca** [qgis/qwc2-demo-app#99]
Hi, do you think it could be possible to use google as search provider?
I'm not able to find how, is anyone so kindly to help me? I have the api from google that i use in a postgresql database to get the xml and convert lan-lon in points, but i have no idea how to use it inside SearchProviders.js.
I tried to study the example, but my skills are not so good to understand it

**Comment by manisandro** [comment]
The API is documented here:

https://developers.google.com/places/web-service/search

You'll need to write a function which calls i.e.

https://maps.googleapis.com/maps/api/place/textsearch/json?query=<text>&key=<API_KEY>

and constructs from the response JSON a result array as [documented in SearchProviders.js](https://github.com/qgis/qwc2-demo-app/blob/master/js/SearchProviders.js#L35). Look at the geoAdminLocationSearch search example.

**Comment by pierloca** [comment]
Thanks for your help Sandro, but it's too difficult for me, i feel it's easy if you know the language, but I'm not a programmer, I tried to study the example, i tried to change some strings, but it doesn't work. The example is good but it's specific for that server and i don't know what I can delete or change. For the moment I giveup.
